### ISSUE TITLE
Open-XML-SDK on Linux

### ISSUE THREAD

**Issue by HowardRubin** [OfficeDev/Open-XML-SDK#100]
Now that Microsoft has bought Xamarin, when will there be a way to output OOXML on Linux? The mono migration analyzer reports 34 problems with the Open-Xml-Sdk (see below)

I need to know because I'm on a team that maintains our application that outputs ooxml. I'd ask on OpenXMLDeveloper.org, but that website has been decommissioned, and Eric White has been pulled from the project.

libopc looks like a good solution to some problems but is unlikely to help us. Its OPC module looks like a good replacement for the System.IO.Packaging module we're using. But we have 3500 lines of working C# code that calls the DocumentFormat.OpenXML module that would need to be rewritten.

We'd like to leverage our investment in using the Open-Xml-Sdk and port it to Linux, probably with mono.

So to clarify my question,
1. Does Microsoft have any plans to add the API calls that the mono migration analyzer reports as problems?
2.How can I contact the developers responsible for the Open-Xml-SDK and those for mono?
- Howard Rubin

![deleteme](https://cloud.githubusercontent.com/assets/20303087/16589912/8a27be46-4292-11e6-8ec0-6908df2d7135.png)

**Comment by Numpsy** [comment]
Are you sure that the report from MoMa is correct? Last time I tried it, it seemed to be somewhat out of date with the actual state of Mono.

I've been building the SDK with Mono on OSX and it builds fine, though there are a load of failures in the unit tests (getting better now though). I haven't tried it on Linux for a while, but I don't think the implemented libs should be behind OSX?

**Comment by xrkolovos** [comment]
#72 #65 #95 #96
many people wait this

**Comment by twsouthwick** [comment]
This is being tracked by #111

**Comment by HowardRubin** [comment]
[#111](https://github.com/OfficeDev/Open-XML-SDK/issues/111) Add support .NET Standard is closed. What is the status of this issue #100

**Comment by twsouthwick** [comment]
As long as you are using a platform that supports .NET Standard 1.3, you should be able to consume this library. Please open a specific issue if you are not able to.

@tomjebo Are we going to close these issue requests? There are number of related ones that are expected to be fixed with .NET Standard support

**Comment by HowardRubin** [comment]
The original issue of this thread was a request for "a way to output OOXML on Linux" so no further issue should need to be opened because that specific question has not yet been fully answered.
What Linux platforms are known to support .NET Standard 1.3, and is mono the way to do it?

**Comment by twsouthwick** [comment]
.NET Standard is supported on newer versions of Mono which support some varieties of Linux. .NET Core also supports .NET Standard 1.3 and is available for some varieties of Linux. The original issue is beyond the scope of this specific project and a bit misleading - nothing in this project is specific to an OS, but is rather dependent on where our dependencies are available. If you are not aware of .NET Standard, please take a look at the [documentation](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) that explains what it is and how it affects libraries.

> is mono the way to do it?

This question can't be fully answered here as it depends on your specific use case. Mono supports some things that .NET Core does not and .NET Core supports some things the Mono does not. Those are the two options for Linux at the moment.

**Comment by HowardRubin** [comment]
I'm hearing that the minimum I need for full support of Open-XML-SDK is .NET Standard 1.3. Is that right? And if not here, where would be appropriate to ask about .NET Standard 1.3 support for Linux?

**Comment by twsouthwick** [comment]
Yes - this library supports .NET Standard 1.3 and .NET 4.5. .NET Core supports it on Linux, but as for Mono, you'll need to look at the Mono site for their support of .NET Standard. Mono can run some libraries built for .NET 4.5, but I believe historically WindowsBase.dll has been a problem, which the .NET Standard 1.3 version should alleviate.

I would recommend adding the MyGet feed described in the readme and installing the package that way to your project and trying it out. If possible, upgrade to the latest Mono as well. If it doesn't work, please open an issue with the versions of the various components (Mono, OS, etc) and we can help with that. If it does work, please let us know that as well.

**Comment by HowardRubin** [comment]
Got it. So nobody has tested these 2 Microsoft technologies (Open-XML-SDK and mono) together on Linux.

**Comment by twsouthwick** [comment]
I haven't tried it on Mono and Linux yet (not sure if anyone else has). I have a service that uses it on .NET Core and it works fine. We definitely should create a list or matrix of known supported configurations. I've created issue #168 to track this - let's continue the conversation there.

**Comment by xrkolovos** [comment]
HowardRubin, i think you should first go and read about the .NET Standards.

https://docs.microsoft.com/en-us/dotnet/articles/standard/library
https://github.com/dotnet/standard/blob/master/docs/faq.md

**Comment by Numpsy** [comment]
I gave it a very brief test on Linux/Mono some time ago while preparing for some Mac work, with results similar to on the Mac (lots of test failures due to path separator/case sensitivity issues, a variety of bugs in Monos ZipArchive handling).
Those should have been sorted now, but I haven't tried the latest code with Monos owm system.io.packaging so I don't know if there will be more problems there. I'l have a look if i get some tmie for it.

**Comment by tomjebo** [comment]
@Numpsy I just built both projects on Ubuntu and they built fine. Tests still were failing due to paths as you observed. I'm investigating.

**Comment by twsouthwick** [comment]
As OpenXML now supports .NET Standard which is supported by .NET Core on various distros of Linux, I'm going to close this issue. If you have a specific issue you are encountering, please create an issue for that.
