### ISSUE TITLE
Make XmlPath constructors public

### ISSUE THREAD

**Issue by rmboggs** [OfficeDev/Open-XML-SDK#1004]
This is request to make the 2 constructors of [XmlPath](https://github.com/OfficeDev/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml/XmlPath.cs) public instead of internal.  I'm trying to work on a way of quickly locating a particular OpenXmlPart/OpenXmlElement within a document and XmlPath looks like it is the way to go but in its current state, it's limited to processes internal to the assembly.  Is there any reason that would prevent this change?  I would like to avoid reinventing the wheel if possible.

**Comment by ThomasBarnekow** [comment]
@rmboggs, I'd say either of the following needs to be public:

1. The two internal factory methods or
2. The two internal factory methods and the two constructors.

I would not see why they can't be made public. @twsouthwick already said he'd be interested in making certain internal APIs public.

**Comment by rmboggs** [comment]
So, what I am after here is a way to reliably serialize and deserialize a complete path to an OpenXmlPart and/or an OpenXmlElement in a given document.  The serialization piece would be needed to setup the path to look for in a document while deserialization would be to return the actual object.  My thinking was that since the [XmlPath](https://github.com/OfficeDev/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml/XmlPath.cs) is already in here and in use for validation purposes, this would be a better starting point for serialization rather than recreate the wheel.  I know that I will need to write a way to actually locate the object with that information but I would need to do this anyway regardless of the path I take.  From my perspective, changing the XmlPath constructors to be public instead of internal would make this process easier.  In regard to the internal factory methods, if they help with creating the full path, I can look into using those as well.

I'm open to alternatives at this point but like I said before, why recreate the wheel.

**Comment by twsouthwick** [comment]
I'm fine making those constructors public. @rmboggs happy to take a PR for that!

**Comment by rmboggs** [comment]
I can do that.  Standby.

**Comment by rmboggs** [comment]
Pull request: [1013](https://github.com/OfficeDev/Open-XML-SDK/pull/1013)

**Comment by rmboggs** [comment]
Thanks for pulling in the request.
