### ISSUE TITLE
GenerateCode Functionality

### ISSUE THREAD

**Issue by ph1ll** [OfficeDev/Open-XML-SDK#101]
I am currently trying to port this to NetStandard for use in .NET Core projects and am having difficulty replacing BinaryFormatter (not available in .NET Core) due to missing the functionality to regenerate the serialised schemas using a .NET Core supported serialisation method:
- O12SchemaConstraintDatas.bin
- O14SchemaConstraintDatas.bin
- O15SchemaConstraintDatas.bin

Best I can tell, these are created using the `SdbBuilder` tool in the makefiles, however from looking at the makefiles it is clear that the generation code is missing. 

@EricWhiteDev are you able to provide any insight into this?

**Comment by tomjebo** [comment]
@ph1ll please sync or clone again, we have completed work on .Net Standard and the serialization code. This should be covered by #111.
