### ISSUE TITLE
Installing Productivity tool MSI issue

### ISSUE THREAD

**Issue by krishnav0** [OfficeDev/Open-XML-SDK#1012]
I am not able install Productivity tool with MSI as I am not finding SDK 2.5 installer.  Installer is failing with below message. Any suggestions to install tool?

To Install the open XML SDK 2.5 Productivity tool for Microsoft Office, you need to first install Open XML SDK 2.5 for Microsoft Office from MSDN
![image](https://user-images.githubusercontent.com/89851102/131509077-9c9b2a72-86e5-4026-bcd9-0a29009a4422.png)

**Comment by ThomasBarnekow** [comment]
Have a look at the following URL (Google is your friend):

https://docs.microsoft.com/en-us/answers/questions/466445/where-can-i-download-open-xml-sdk-25-productivity.html

@tomjebo, would it make sense to also provide a link to the SDK v2.5 itself, if that is required for installing the Productivity Tools?

**Comment by krishnav0** [comment]
Thanks. I found using bing :) once after create the issue. 

https://web.archive.org/web/20190116000204/https://www.microsoft.com/en-us/download/details.aspx?id=30425
