### ISSUE TITLE
OpenXML doesn't retrieve correct display formatted data

### ISSUE THREAD

**Issue by Tirupatisriharsha** [OfficeDev/Open-XML-SDK#1017]
**Description**
File Type : XLSX
We have data in one cell like, 1.1, 2.1, 2.3. While we reading cell value with OpenXML, we getting like 1.100000001, 2.10000001, 2.23999999.

**Information**

- .NET Target: (ie .NET Framework)
- DocumentFormat.OpenXml Version: (ie 2.13.1)

**Repro**

**Observed**

 1.1, 2.1, 2.3 Reading cell value as 1.100000001, 2.10000001, 2.23999999.

**Expected**

1.1, 2.1, 2.3 It should read cell value as 1.1, 2.1, 2.3

**Comment by ThomasBarnekow** [comment]
Could you please provide both the code and the data (e.g., an Excel workbook or the Open XML markup for the relevant part) that would allow us to reproduce the issue?

**Comment by Tirupatisriharsha** [comment]
When Datatype is null, we handled like below. Then it is working fine.
if (double.TryParse(_cell.InnerText, out double oaData)) return oaData;
