### ISSUE TITLE
Conflicts with OpenXmlPowerTools and LINQ implementation

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#1026]
There is (hopefully) one last issue to be addressed if you put the `OpenXmlLinqExtensions` class and the namespace-related classes (e.g., `W`, `W10`, `W14`) in the same assembly and, as it stands at the moment, same namespace. Consider the following simplified example:

### Example

First, the `DocumentFormat.OpenXml.Linq` namespace contains the extension methods provided by the feature:

```csharp
// DocumentFormat.OpenXml.Linq: OpenXmlLinqExtensions.cs

using DocumentFormat.OpenXml.Packaging;

namespace DocumentFormat.OpenXml.Linq
{
    public static class OpenXmlLinqExtensions
    {
        public static XElement? GetXElement(this OpenXmlPart part)
            => part.GetPartRootXElementFeature().Root;

        public static void SetXElement(this OpenXmlPart part, XElement element)
            => part.GetPartRootXElementFeature().Root = element;
    }
}
```

Second, the `DocumentFormat.OpenXml.Linq` namespace contains the generated namespace-related classes (I've removed all comments to keep it short):

```csharp
// DocumentFormat.OpenXml.Linq: W.g.cs

namespace DocumentFormat.OpenXml.Linq
{
    public static class W
    {
        public static readonly XNamespace w = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
        public static readonly XName abstractNum = w + "p";
    }
}
```

Third, the `OpenXmlPowerTools` namespace contains extension methods (similar but not identical to the ones provided by this PR), many namespace-related classes, and a lot of useful functionality (not shown in the example).

```csharp
// OpenXmlPowerTools: PtOpenXmlUtil.cs

using DocumentFormat.OpenXml.Linq;
using DocumentFormat.OpenXml.Packaging;

namespace OpenXmlPowerTools
{
    // The following class contains the extension methods that could be changed to use the new API.
    public static class PtOpenXmlExtensions
    {
        public static XDocument GetXDocument(this OpenXmlPart part)
        {
            // Leverage new Linq feature provided by DocumentFormat.OpenXml.Linq library.
            return new XDocument(new XDeclaration("1.0", "UTF-8", "yes"), part.GetXElement());
        }

        public static void PutXDocument(this OpenXmlPart part, XDocument document)
        {
            // Leverage new Linq feature provided by DocumentFormat.OpenXml.Linq library.
            part.SetXElement(document.Root);
        }
    }

    // This is one example of a namespace-related class that already exists in the OpenXmlPowerTools library.
    public static class W
    {
        public static readonly XNamespace w = "http://schemas.openxmlformats.org/wordprocessingml/2006/main";
        public static readonly XName abstractNum = w + "p";
    }
}
```

Fourth, when using both libraries from your own project, you'd do something like this:

```csharp
// My own project

using DocumentFormat.OpenXml.Linq;
using DocumentFormat.OpenXml.Packaging;
using OpenXmlPowerTools;

namespace MyOwnNamespace
{
    public static class MyOwnClass
    {
        public static void MyOwnMethod(MainDocumentPart part)
        {
            // Get the root element, using the extension method existing in the DocumentFormat.OpenXml.Linq namespace.
            // You might have used part.GetXDocument().Root before, but you now want to use the new feature.
            // There is no issue because the same name does not exist in the OpenXmlPowerTools namespace.
            var document = part.GetXElement();

            // Assume you are using some other feature provided by the OpenXmlPowerTools, which is why
            // you've imported the namespace OpenXmlPowerTools.

            // Do something else for which you need one or more of the namespace-related classes.
            // If we are not specifically including it from either namespace, this is where we'll get a CS0104:
            // 'W' is an ambiguous reference between 'DocumentFormat.OpenXml.Linq.W' and 'OpenXmlPowerTools.W'.
            // The solution here is to say either:
            // using W = DocumentFormat.OpenXml.Linq.W; or
            // using W = OpenXmlPowerTools.W;
            var paragraphs = document.Descendants(W.p);
        }
    }
}
```

### Discussion

The example above shows a situation where developers might want to use the feature (and its API) but not (yet) the namespace-related classes. While the feature provides additional functionality or behavior, the namespace-related classes don't add value immediately, unless you require names that are not provided by the Open XML PowerTools.

If they've used the Open XML PowerTools, using just the API is not possible without explicitly declaring which namespace-related class they want to use. 

I understand that you do not want to add the API to the `OpenXmlPart`, which would immediately solve this problem, so we need to find another way to avoid the naming conflict.

### Solution

To be able to separately opt-in to:

1. the feature with the extension methods as its API (`OpenXmlLinqExtensions` etc.) and
2. the namespace-related classes (e.g., `W`),

we should put both (1) and (2) into separate namespaces. For example:

1. `DocumentFormat.OpenXml.Linq` for the feature etc. and
2. `DocumentFormat.OpenXml.Linq.Names` for the namespace-related classes.

Any other sensible combination or names would work as well.

What are your thoughts?

_Originally posted by @ThomasBarnekow in https://github.com/OfficeDev/Open-XML-SDK/issues/1021#issuecomment-920207165_

**Comment by twsouthwick** [comment]
This is reasonable. How about `DocumentFormat.OpenXml.Linq.XNames`?

**Comment by ThomasBarnekow** [comment]
@twsouthwick, can we do the following?

1. `DocumentFormat.OpenXml.Packaging` (same namespace as for `OpenXmlPart`) for the feature with the extension methods as its API (`OpenXmlLinqExtensions` etc.) and
2. `DocumentFormat.OpenXml.Linq` for the generated namespace-related classes (e.g., `W`)?

By referencing the `DocumentFormat.OpenXml.Linq` NuGet package, you'd automatically have access to the extension methods (e.g., `GetXElement(this OpenXmlPart part)`) as soon as you are using the `DocumentFormat.OpenXml.Packaging` namespace to access the `OpenXmlPart` class. You'd have to explicitly opt-in to the generated namespace-related classes (e.g., `W`) by using the `DocumentFormat.OpenXml.Linq` namespace.

This way, we don't need two additional namespaces and we'd make using the extension methods very straightforward. 

You could think about this as a two-step opt-in. The first step is to reference an assembly. This might provide additional features in the established namespaces. The second step is to use an additional namespace (e.g., `DocumentFormat.OpenXml.Linq`) for stuff that should be in a separate namespace, e.g., to avoid naming conflicts.

**Comment by twsouthwick** [comment]
That sounds reasonable as well. Are able to make those changes?

**Comment by ThomasBarnekow** [comment]
Yes, I can make those changes.
