### ISSUE TITLE
Productivity Tool usability

### ISSUE THREAD

**Issue by HowardRubin** [OfficeDev/Open-XML-SDK#103]
The [Open XML SDK 2.5 Productivity Tool](https://www.microsoft.com/en-us/download/details.aspx?id=30425) does some amazing things for me, but it would be even better if there could be some way to automatically fill in the Browse Files to Compare dialog box, such as with the last files opened.

**What** I tried:
1. Google search for: Open XML SDK Productivity Tool command line
2. I used the [Spy++](https://msdn.microsoft.com/en-us/library/dd460756.aspx?f=255&MSPPError=-2147217396) program that comes with Visual Studio. It only recognizes the dialog box, not the dialog box controls.
3. I wrote the below program to find the dialog using EnumWindows(). I can find the dialog and move the control focus by sending it tab characters, but EnumChildWindows() doesn't find the dialog controls, and sending keystrokes to the dialog doesn't fill in the dialog controls.

Howard Rubin

```
BOOL CALLBACK EnumWindowsProc(HWND hwnd, LPARAM lParam);

int _tmain(int argc, _TCHAR* argv[]) {
    EnumWindows(EnumWindowsProc, NULL);
    return 0;
}

using namespace std;

BOOL CALLBACK EnumChildProc(HWND hwnd, LPARAM lParam) {
    wcout << hwnd << std::endl;
    return TRUE;
}

BOOL CALLBACK EnumWindowsProc(HWND hwnd, LPARAM lParam) {
    wchar_t title[1000];
    GetWindowText(hwnd, title, sizeof(title)-1);
    if (!wcscmp(L"Browse Files to Compare", title)) {
            wcout << "Window title: " << title << endl;
        EnumChildWindows(hwnd, EnumChildProc, NULL);

        for (int i = 0; i < 2; ++i) {
            SendMessage(hwnd, WM_KEYDOWN, VK_TAB, 0);
            SendMessage(hwnd, WM_KEYUP, VK_TAB, 0);
        }
        //SendMessage(hwnd, WM_CLOSE, NULL, NULL);
    }
    return TRUE;
}
```

**Comment by tomjebo** [comment]
@HowardRubin thank you for the suggestion and the code sample, but the Productivity Tool is not currently part of this repository. If you don't mind, please post your suggestion here:
[https://social.msdn.microsoft.com/Forums/office/en-us/home?forum=oxmlsdk](url)
