### ISSUE TITLE
Why is auxHint namespace (Auxiliary XML Document 2003) not mapped with strong names?

### ISSUE THREAD

**Issue by arlm** [OfficeDev/Open-XML-SDK#105]
Is there a reason, other than that these elements have no effect and are not processed by Word, for not mapping `http://schemas.microsoft.com/office/word/2003/auxHint` namespce into strong names?

We do have a pretty nice description of them here:
- [Auxiliary XML Document 2003 Introduction [Word 2003 XML Reference]](https://msdn.microsoft.com/en-us/library/aa175186%28v=office.11%29.aspx?f=255&mspperror=-2147217396)
- [Auxiliary XML Document 2003 Namespace Elements [Word 2003 XML Reference]](https://msdn.microsoft.com/en-us/library/aa175174%28v=office.11%29.aspx?f=255&MSPPError=-2147217396)
- [Auxiliary XML Document 2003 Namespace Types [Word 2003 XML Reference]](https://msdn.microsoft.com/en-us/library/aa175211%28v=office.11%29.aspx?f=255&MSPPError=-2147217396)

**Comment by tomjebo** [comment]
@arlm The OpenXML SDK doesn't support the 2003 Office XML format which is not ISO 29500/ECMA 376 standard.

**Comment by arlm** [comment]
Ok, understood. Thanks.
