### ISSUE TITLE
Install Open XML SDK in a Ubuntu server

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/Open-XML-SDK#106]
I am trying to install Open XML SDK in my Nginx & Ubuntu server.

By following its readme page and [this video](https://www.youtube.com/watch?v=zfSeqzMOXiQ&list=LL_WrYcTnXlz5Rjj9ZNwpWEA&index=1), I have installed git and mono in the server, cloned the code.

Then I did "make -f Makefile-Linux-Mono build" in the folder and got the following error:

"make: Makefile-Linux-Mono: No such file or directory
make: **\* No rule to make target `Makefile-Linux-Mono'.  Stop."

Indeed, there is even no "makefile" in the folder.

Does anyone know how to solve this?

**Comment by Numpsy** [comment]
try using build.open-xml-sdk.sh instead of make?

**Comment by chengtie** [comment]
Thanks for your reply...

Indeed, I should have tried build.open-xml-sdk.sh.

I tried to run it in the server, but it gives an error: http://pastebin.com/y3p3UDKy

Do you have any idea?

Cheers

Tie

**Comment by twsouthwick** [comment]
The project has switched to using the latest .NET tooling and provides a MyGet feed to download precompiled binaries targeting .NET Standard 1.3 and .NET Framework 4.5 (with more to come). Please see the README for details. Please reopen or create a new issue if you have trouble using the package.
