### ISSUE TITLE
new CellValue(bool) generates invalid XML

### ISSUE THREAD

**Issue by stevehansen** [OfficeDev/Open-XML-SDK#1070]
**Description**

The introduced new CellValue(bool) uses the wrong serialization causing Excel to fail to load the file.

**Information**

- .NET Target: all
- DocumentFormat.OpenXml Version: since 2.12-ish (https://github.com/OfficeDev/Open-XML-SDK/pull/782)

**Repro**

```csharp
Debug.Assert(new CellValue(true).InnerText == "true");
``` 

**Observed**

Spec expects the boolean values to be "true" or "false" but the code is using bool.ToString() which returns "True" or "False".

https://github.com/OfficeDev/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml/Spreadsheet/CellValue.cs#L42

**Expected**

Per .NET remarks for the boolean.ToString:

This method returns the constants "True" or "False".

Note that XML is case-sensitive, and that the XML specification recognizes "true" and "false" as the valid set of Boolean values. If the string returned by the ToString() method is to be written to an XML file, its String.ToLowerInvariant method should be called first to convert it to lowercase.

**Comment by stevehansen** [comment]
The validator uses the .NET bool.TryParse which allows both "True" and "true" so isn't exactly correct.
CellTests is using the string "true" and "false" directly and didn't use the new constructor.
SpreadsheetCellTests has no tests for boolean.

**Comment by twsouthwick** [comment]
@tomjebo can you verify this from the spec side? I'm good taking a fix for this, just want to verify the spec

**Comment by twsouthwick** [comment]
@tomjebo I merged this in. Please let me know if there's any issue with the spec.

**Comment by tomjebo** [comment]
@twsouthwick @stevehansen thanks for getting this in. Our implementer notes and 29500 are not explicit on the case.
MS-OI29500 2.1.659 says: 

```If the cell contains a Boolean, the value shall be 1 to specify true and 0 to specify false.```

The W3C spec has this: 

```3.2.2 boolean
[Definition:]  boolean has the ·value space· required to support the mathematical concept of binary-valued logic: {true, false}.

3.2.2.1 Lexical representation
An instance of a datatype that is defined as ·boolean· can have the following legal literals {true, false, 1, 0}.

3.2.2.2 Canonical representation
The canonical representation for boolean is the set of literals {true, false}.

3.2.2.3 Constraining facets
boolean has the following ·constraining facets·:

pattern
whiteSpace
```

Note the "legal literals". 
And Excel does balk at "True" and "False" so IMO this fix is warranted.
