### ISSUE TITLE
No symbols package on nuget.org for v2.14.0

### ISSUE THREAD

**Issue by andrewmolyneux** [OfficeDev/Open-XML-SDK#1074]
Ref #639 - this seems to have regressed because there is no option on nuget.org to download symbols for version 2.14.0.

**Comment by twsouthwick** [comment]
Thanks for the heads up! I'll take a look at that

**Comment by twsouthwick** [comment]
I updated our release to push the symbols (`*.nupkg` doesn't catch `.snupkg` files :)). It's now pushed. I'm closing this, but please reopen if for some reason it doesn't work for you.
