### ISSUE TITLE
ZipPackage _containerStream isn't closed when a exception is thrown in the ZipArchive constructor

### ISSUE THREAD

**Issue by tutkowskim** [OfficeDev/Open-XML-SDK#108]
If an exception is thrown in the ZipArchive constructor inside of ZipPackage(string path, FileMode packageFileMode, FileAccess packageFileAccess, FileShare share), which can happen if the specified file is not a archive or the disk is completely out of space, the _containerStream isn't disposed.

I was able to fix it by adding the call `_containerStream.Dispose();` in the following catch block.

**Comment by tarunchopra** [comment]
I reviewed the code and believe that it's appropriate to replace zipArchive.Dispose() call with Dispose(true); as it will handle other cleanups too. Hope that's fine. 

I'll work on check-in the code.

**Comment by tarunchopra** [comment]
We have addressed this issue in #112 which removed our custom System.IO.Packaging. If you still any issue with System.IO.Packaging, please open an issue at following link: https://github.com/dotnet/corefx
