### ISSUE TITLE
.NET 5 problems

### ISSUE THREAD

**Issue by mtugnoli** [OfficeDev/Open-XML-SDK#1130]
Try to new WebApp .Core with .NET 5
this error occour ...

_Project DocumentFormat.OpenXml is not compatible with net5.0 (.NETCoreApp,Version=v5.0)_

**Comment by twsouthwick** [comment]
Can you share how you are incorporating the SDK? It provides a .NET Standard 2.0 target that is compatible with .NET 5.0.
