### ISSUE TITLE
Price Reading From xlsx file

### ISSUE THREAD

**Issue by caglarsarikaya** [OfficeDev/Open-XML-SDK#1143]
# Before submitting an issue, please fill this out

Is this a:
- [x] Issue with the OpenXml library
- [x] Question on library usage

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

---------------- Remove this line and above before posting ----------------

**Description**

I am uploading some products in excel, There are only two columns one is name other is price. I have read rows from excel as you suggested, also I added a method reading with cell index because when a cell is null, it was sliding. 

I keep the inner text from the cell if the cell has a datatype

`    
string value = cell?.InnerText;

case CellValues.SharedString:
               value = stringTablePart.SharedStringTable.ChildElements[Int32.Parse(value)].InnerText?.Trim();
               break;

return value;
`
 I get the value like that, everything is ok except price. It changes the signs. firstly removes all dots, then replaces the comma to dot 
ex1. value from excel 1.200.000,50 -> reads like 12000000.5

so dot and comma comes from culture number seperator settings, culture and cultureUI and current thread culture and ui set as tr-TR because tr culture has . for group seperator and comma for decimal seperator. 

Why is this excel reading like that?

**Information**

- .NET Target: (.Net 5)
- DocumentFormat.OpenXml Version: (ie 2.13.0)

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
``` 

**Observed**

value saved in excel 1.500,70
read like 1500.7

**Expected**

it should read the same as how is written. Because the convert working with culture settings, this is a string value and I will parse this to decimal. (1500.7) this is converted as (15007) because . is group separetor.

Please add your expected behavior here.

**Comment by ThomasBarnekow** [comment]
Did you have a look at what is actually stored in the Excel sheet? If you do that, you will notice that `1.500,70` is not what gets written. This is only what Excel _displays_ based on your cell formatting. What is actually written and stored is what you get from the Open XML SDK.

It also seems that you are parsing decimal values using a specific locale (like the one used in Germany, for example). However, the values are stored in Excel using the "InvariantCulture", which uses the period (`.`) as the decimal separator, while your chosen culture uses the comma (`,`) as the decimal separator.

**Comment by caglarsarikaya** [comment]
Hi, thanks for the advice I wrote the values into the cell, I copied this row 5 times, and I changed each of the formatting styles, like a number, price, text, general, etc. I tried all formatting styles. The actual value is 1.500,70 just changed the format styles but it didn't change anything, I tried also invariant culture, there is no setting when opening the file to giving culture, but I set all threads and system culture and culture before reading the excel, but still same.

**Comment by ThomasBarnekow** [comment]
Please share the following:

- The Open XML markup that shows what is stored in the SpreadsheetDocument
- The C# code that shows how you read that Open XML and produce the formatted number

You need to understand that the Open XML SDK just gives you access to the raw data stored in the various XML files that together form a document (e.g., Workbook). So, you will be able to see a raw floating-point number in the invariant culture (e.g., `1500.7`). You will also see the format specifications that might have been entered in Excel. However, the SDK does not perform any formatting for you. Instead, you would have to read the raw number and the format specifications, interpret the format specifications and format the number accordingly if you need that.

**Comment by caglarsarikaya** [comment]
I completely agree with you, I was looking convert method on the first attempt but I saw the convert method works truly when converting string to decimal. I saw the string value is not the same as in the excel value.

```
SpreadsheetDocument spreadSheetDocument = SpreadsheetDocument.Open(path, false); //opening excel file
DataTable dt = new DataTable(); // dt for columns and rows

IEnumerable<Sheet> sheets = spreadSheetDocument.WorkbookPart.Workbook.GetFirstChild<Sheets>().Elements<Sheet>();
string relationshipId = sheets.First().Id.Value;
WorksheetPart worksheetPart = (WorksheetPart)spreadSheetDocument.WorkbookPart.GetPartById(relationshipId);
Worksheet workSheet = worksheetPart.Worksheet;
SheetData sheetData = workSheet.GetFirstChild<SheetData>();
IEnumerable<Row> rows = sheetData.Descendants<Row>();

foreach (Cell cell in rows.ElementAt(0)) // creating colums in datatable
{ 
  DataColumn col = new DataColumn(GetCellValue(spreadSheetDocument, cell));
  dt.Columns.Add(col);
}

foreach (var row in rows) // creating rows at datatable
{
    DataRow tempRow = dt.NewRow();
    for (int i = 0; i < row.ChildElements.Count; i++)
    {
        Cell cell = row.Descendants<Cell>().ElementAt(i);
        int index = CellReferenceToIndex(cell);
        var val = GetCellValue(spreadSheetDocument, cell);
        tempRow[index] = val;  // the value was changed here, in the excel cell 1.200,55 but here I dont how, it turned this 1200.55
    }

    if (tempRow.ItemArray.All(x => x is DBNull || string.IsNullOrWhiteSpace(x as string)))    //row is fully empty, it will not add
        continue;
    dt.Rows.Add(tempRow);
}

dt.Rows.RemoveAt(0); //...i am taking out the first row of excel from first row datatable, because its column names







//my helper methods are here for reading the data from the cell, I used that method because when a cell is empty, it was slide cells to the left

private int CellReferenceToIndex(Cell cell)
{
    int index = -1;
    string reference = cell.CellReference.ToString().ToUpper();
    foreach (char ch in reference)
    {
        if (Char.IsLetter(ch))
        {
            int value = (int)ch - (int)'A';
            index = (index + 1) * 26 + value; //if the columns at excel bigger than last letter of alphabet
        }
        else
            return index;
    }
    return index;
}

private string GetCellValue(SpreadsheetDocument document, Cell cell)
{
    try
    {
        SharedStringTablePart stringTablePart = document.WorkbookPart.SharedStringTablePart;
        string value = cell?.InnerText;

        if (cell.DataType != null && value != null)
        {

            switch (cell.DataType.Value)
            {
                case CellValues.SharedString:
                    value = stringTablePart.SharedStringTable.ChildElements[Int32.Parse(value)].InnerText?.Trim();
                    break;

                case CellValues.Number:
                    value = stringTablePart.SharedStringTable.ChildElements[Int32.Parse(value)].InnerText?.Trim();
                    break;

                case CellValues.Boolean:
                    switch (value)
                    {
                        case "0":
                            value = "FALSE";
                            break;
                        default:
                            value = "TRUE";
                            break;
                    }
                    break;

                    //case CellValues.Date:
                    //    break;

                    //case CellValues.String:
                    //    break;
            }
            return value;

        }
        else
        {
            return value?.Trim();
        }
    }
    catch (Exception ex)
    {
        var m = "Excel cell did not read. GetCellValue";
        throw new Exception(m, ex);

    }
}


```

**Comment by caglarsarikaya** [comment]
I changed the invariant culture before read the excel, didnt work, so more researched, I changed invariant culture also current thread culture also with them cultureui,

**Comment by ThomasBarnekow** [comment]
@caglarsarikaya, you clearly have a usage problem that is much better addressed at stackoverflow.com. There is no issue with the SDK, for which an issue should be opened.

I did not look at all of your code, but what jumps at me is that you are trying to read numbers from the `SharedStringTable`. Thus, before you even go to stackoverflow.com, please answer my questions above (in particular regarding the Open XML markup) and provide that information in your stackoverflow.com question. You would not store numbers in the `SharedStringTable` and it looks like you are trying to store formatted numbers as strings. This is not how it works. Number formatting is a **display** issue, not a **storage** thing.

I also suggest that you manually create an Excel workbook with the expected content to see the Open XML markup produced by Excel. Before jumping into any code, you should also look at the Open XML markup, e.g., using the [Open XML Productivity Tool](https://github.com/OfficeDev/Open-XML-SDK/releases/tag/v2.5) or any other tool that lets you view the markup. If you don't fully understand the Open XML markup, you cannot use the Open XML SDK successfully.

**Comment by ThomasBarnekow** [comment]
@caglarsarikaya, I forgot to mention [ClosedXML](https://github.com/ClosedXML/ClosedXML), which is an open-source library that would make it much easier for you to work with Excel workbooks.

**Comment by caglarsarikaya** [comment]
Okay but I tried all formatting types in excel, I created rows with all kinds of formatting types with the 1.200,55 value and all of the formatting types did not change the read data :/ but okay thanks, you said it's not an issue, maybe I missed something. I am closing this now, thanks for your time
