### ISSUE TITLE
write error

### ISSUE THREAD

**Issue by pulmuone** [OfficeDev/Open-XML-SDK#1145]
# Before submitting an issue, please fill this out

Is this a:
- [v] Issue with the OpenXml library
- [ ] Question on library usage

---------------- Remove this line and above before posting ----------------

**Description**
Error Message :

System.ArgumentException: '', hexadecimal value 0x1D, is an invalid character.

DocumentFormat.OpenXml Version 2.16.0

Xamarin

**Comment by tomjebo** [comment]
@pulmuone Can you provide repo code that demonstrates the issue and a stack trace?  Does this also occur when not using Xamarin?

**Comment by ThomasBarnekow** [comment]
@tomjebo, it looks like @pulmuone lost interest in this issue, so we should close it.
