### ISSUE TITLE
New cell value API is not working as expected

### ISSUE THREAD

**Issue by Gurudeep007kumar** [OfficeDev/Open-XML-SDK#1146]
**Description**

Incorrect cell value written in excel when open xml api are used

**Information**

- When open xml API are used to write cell value, particular string is not updated as it is.
- It is C# code

**Repro**

1. assign excel cell value with following string using Open XML
"Test_xfeed_Test"

**Observed**

Cell content found to be - "TestﻭTest" instead of "Test_xfeed_Test"
_xfeed_ is replaced with ﻭ

**Expected**

Cell content should be as is

**Comment by ThomasBarnekow** [comment]
Could you please provide a minimal repro?

**Comment by Gurudeep007kumar** [comment]
Hi Thomas,

Please follow below steps and let me know whether you can reproduce

1. Copy the lines from step [2] and call below function by passing full file path in place of "Path of empty excel file"
  WriteRandomValuesSAX(@"Path of empty excel file", 10, 10);

Example : WriteRandomValuesSAX(@"C:\Users\Test.xlsx", 10, 10);

This function writes 10 rows and 10 columns with cell values as "Test_xfeed_Test" but in the excel it is coming as TestﻭTest

2. --------------Code to copy and Paste--------------------------------------------------
Private static WorksheetPart InsertWorksheet(WorkbookPart workbookPart,string Name)
        {
            // Add a new worksheet part to the workbook.
            WorksheetPart newWorksheetPart = workbookPart.AddNewPart<WorksheetPart>();
            newWorksheetPart.Worksheet = new Worksheet(new SheetData());
            newWorksheetPart.Worksheet.Save();

            Sheets sheets = workbookPart.Workbook.GetFirstChild<Sheets>();
            string relationshipId = workbookPart.GetIdOfPart(newWorksheetPart);

            // Get a unique ID for the new sheet.
            uint sheetId = 1;
            if (sheets.Elements<Sheet>().Count() > 0)
            {
                sheetId = sheets.Elements<Sheet>().Select(s => s.SheetId.Value).Max() + 1;
            }

            string sheetName =Name;

            // Append the new worksheet and associate it with the workbook.
            Sheet sheet = new Sheet() { Id = relationshipId, SheetId = sheetId, Name = sheetName };
            sheets.Append(sheet);
            workbookPart.Workbook.Save();

            return newWorksheetPart;
        }
        public static void GenerateStylesheet(Stylesheet stylesheet,ref UInt32Value styleIndex)
        {
            Border s = new Border(
                        
                        new LeftBorder(new Color() { Auto = true }) { Style = BorderStyleValues.Medium },
                        new RightBorder(new Color() { Auto = true }) { Style = BorderStyleValues.Medium },
                        new TopBorder(new Color() { Auto = true }) { Style = BorderStyleValues.Medium },
                        new BottomBorder(new Color() { Auto = true }) { Style = BorderStyleValues.Medium },
                        new DiagonalBorder());

            
            CellFormat cd = new CellFormat { BorderId = stylesheet.Borders.Count, ApplyBorder = true };
       
            stylesheet.Borders.Append(s);
            stylesheet.CellFormats.Append(cd);
            stylesheet.Save();

            styleIndex=stylesheet.CellFormats.Count;
        }


        static void WriteRandomValuesSAX(string filename, int numRows, int numCols) 
        {
            SpreadsheetDocument mdoc=null;
            try
            {
              
                using (mdoc = SpreadsheetDocument.Open(filename, true))
                {
                    WorkbookPart objWrk = mdoc.WorkbookPart;
                    UInt32Value StyleIndex = 0;             
                    GenerateStylesheet(objWrk.WorkbookStylesPart.Stylesheet,ref StyleIndex);
                   

                    for (int i = 0; i < 10; i++)
                    {
                        WorksheetPart baseWorkSheet = InsertWorksheet(objWrk, "Test -" + i.ToString());

                        string baseRomSheetId = objWrk.GetIdOfPart(baseWorkSheet);          
                        WorksheetPart replacementWorksheet = objWrk.AddNewPart<WorksheetPart>();
                        string replacementWorksheetId = objWrk.GetIdOfPart(replacementWorksheet);

                        OpenXmlReader xmlReader = OpenXmlReader.Create(baseWorkSheet);
                        OpenXmlWriter xmlWriter = OpenXmlWriter.Create(replacementWorksheet);

                        while (xmlReader.Read())
                        {
                            if (xmlReader.ElementType == typeof(SheetData))
                            {
                                if (xmlReader.IsEndElement) continue;
                                xmlWriter.WriteStartElement(new SheetData());
                                xmlWriter.WriteStartElement(new Row());
                                xmlWriter.WriteEndElement();
                                for (int row = 2; row < numRows; row++)
                                {

                                    xmlWriter.WriteStartElement(new Row());
                                    for (int col = 1; col < numCols; col++)
                                    {
                                        Cell c = new Cell() { DataType = CellValues.String, CellReference = GetColumnName(col) + row.ToString(),StyleIndex= StyleIndex };
                                       
                                        CellValue v = new CellValue("Test_xfeed_Test");
                                        c.Append(v);
                                        
                                        xmlWriter.WriteElement(c);
                                    }
                                    xmlWriter.WriteEndElement();
                                }
                                xmlWriter.WriteEndElement();
                            }
                            else
                            {
                                if (xmlReader.IsStartElement)
                                {
                                    xmlWriter.WriteStartElement(xmlReader);
                                }
                                else if (xmlReader.IsEndElement)
                                {
                                    xmlWriter.WriteEndElement();
                                }
                            }
                        }
               

                        xmlReader.Close();
                        xmlWriter.Close();
                        Sheet sheet = objWrk.Workbook.Descendants<Sheet>().Where(s => s.Id.Value.Equals(baseRomSheetId)).First();
                        sheet.Id.Value = replacementWorksheetId;
                        objWrk.DeletePart(baseWorkSheet);

                    }

                    mdoc.Dispose();
                }
            }
            catch (Exception ex)
            {

            }
            finally 
            {
                if (mdoc != null)
                {
                    mdoc.Dispose();
                }
            }
            
        }

        private static string GetColumnName(int columnIndex)
        {
            int dividend = columnIndex;
            string columnName = String.Empty;
            int modifier;

            while (dividend > 0)
            {
                modifier = (dividend - 1) % 26;
                columnName = Convert.ToChar(65 + modifier).ToString() + columnName;
                dividend = (int)((dividend - modifier) / 26);
            }

            return columnName;
        }

    }
}

**Comment by Gurudeep007kumar** [comment]
thanks Thomas for the suggestion.
I am using xml reader and writer to boost performance. This is totally business requirement. Please neglect this part.

The point i am talking is, these three line
 Cell c = new Cell() { DataType = CellValues.String, CellReference = GetColumnName(col) + row.ToString(),StyleIndex= StyleIndex };
                                
 CellValue v = new CellValue("Test_xfeed_Test");
c.Append(v);
  
When input string contains, "xfeed" word, it is automatically gets decoded in utf 16. 
Unicode Character “ﻭ” (U+FEED)

Can you please suggest how should it be handled. Request you to please replicate once and let me know your thoughts

**Comment by Gurudeep007kumar** [comment]
Just a add on, If string contents any UTF-16 unicodes , it is automatically decoded when writing instead of preserving as it is

**Comment by Gurudeep007kumar** [comment]
@ThomasBarnekow 
Followed your suggestion, verifyed manually and found that, for UTF-16 unicode like _xHHHH_ pattern in a string are automatically decoded when cellValue is used. 
Strange thing is if we add prefix "_x005F" to UTF-16 then string are written correct

Example : 
Not working as expected                                                  Writing cell value as "Test_xfeed_Test"
CellValue v = new CellValue("Test_xfeed_Test");  ---->      CellValue v = new CellValue("Test_x005F_xfeed_Test");

Can you please suggest, is there a different way to handle UTF-16 codes in string ?

**Comment by Gurudeep007kumar** [comment]
@tomjebo @twsouthwick 
Please lend your expertise on this issue

**Comment by ThomasBarnekow** [comment]
@Gurudeep007kumar, it seems that there is no other way than to escape that string `_xfeed`.

I created a blank Excel workbook, entered `Test_xfeed_Test` in a cell and found that Excel represents that as follows in the **SharedStringTablePart** (and not in the **WorksheetPart**, as I already said above):

```xml
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="1" uniqueCount="1">
  <si>
    <t>Test_x005F_xfeed_Test</t>
  </si>
</sst>
```

I did not look at the standard, but I can only guess that the pattern `_xHHHH` (note the prefix `_x`) is documented there as the way to represent Unicode characters contained in Rich Text. Since the Open XML SDK does not provide any abstractions, it is generally your job as an Open XML developer to make sure you represent strings correctly, e.g., by properly escaping or unescaping them.

If you wanted to represent the Unicode character "ﻭ", you'd have to write `"_xfeed"` or `"_xFEED"` (not `"_XFEED"`). If you want to represent `_xfeed` (or `_xFEED`) as part of your string, you must escape it.

**Comment by Gurudeep007kumar** [comment]
@ThomasBarnekow 
Thank you for your suggestion. 
Currently  escaping _xHHHH_ pattern using _x005F.

**Comment by AnorZaken** [comment]
The relevant standard is here:
https://learn.microsoft.com/en-us/openspecs/office_standards/ms-oi29500/d34ae755-c53f-4a44-a363-c6dd3ee018a4

Relevant part:

> c.   The standard allows Xstring to encode underscores using _x005f_.
> 
> In Excel, Xstrings may only contain the escape sequence _x005f_ when escaping the lead underscore from a string in the form _xHHHH_.

So basically because the original string "`Test_xfeed_Test`" has a (middle) part that matches the "`_xHHHH_`" escape pattern for unicode escapes, Excel solves this by escaping the _leading_ underscore of that part.

In other words the part that deceptively looks like an escape: "`_xfeed_`" is escaped as "`_x005F_xfeed_`" where "`_x005F_`" simply is the actual escape for underscore.

Note the complicating part of the spec: "only ... when escaping lead underscores [of unicode escapes]".
Meaning that the naive approach of just escaping all underscores in a body of text is **not** allowed.
