### ISSUE TITLE
OpenXML nuget package x64 release build error

### ISSUE THREAD

**Issue by debasrbd** [OfficeDev/Open-XML-SDK#1148]
am using OpenXML nuget package (v2.10.0) for my UWP project

though **"x64 Debug build" is OK**

I am getting **build error** during **"x64 Release Build"** with OpenXML nuget package

Is their any solution for this problem?
```
....PATH....\microsoft.net.native.compiler\2.2.10-rel-29722-00\tools\Microsoft.NetNative.targets(805,5): error : Type 'System.Xml.XmlDocumentXPathExtensions' from assembly 'System.Xml.XPath.XmlDocument' was not included in compilation, but was referenced in method 'HtmlWeb.GetCacheHeader(Uri, string, string)'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release. [  ....PATH.... ]
          ....PATH....\microsoft.net.native.compiler\2.2.10-rel-29722-00\tools\Microsoft.NetNative.targets(805,5): error : Type 'System.Xml.XmlDocumentXPathExtensions' from assembly 'System.Xml.XPath.XmlDocument' was not included in compilation, but was referenced in method 'HtmlWeb.GetCacheHeader(Uri, string, string)'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release. [  ....PATH....]
          ....PATH....\microsoft.net.native.compiler\2.2.10-rel-29722-00\tools\Microsoft.NetNative.targets(805,5): error : Method 'HtmlWeb.GetCacheHeader(Uri, string, string)' will always throw an exception due to the missing method 'XmlDocumentXPathExtensions.SelectSingleNode(XmlNode, string)' in assembly 'System.Xml.XPath.XmlDocument'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release. [  ....PATH....]
          ....PATH....\microsoft.net.native.compiler\2.2.10-rel-29722-00\tools\Microsoft.NetNative.targets(805,5): error : Method 'HtmlWeb.GetCacheHeader(Uri, string, string)' will always throw an exception due to the missing method 'XmlDocumentXPathExtensions.SelectSingleNode(XmlNode, string)' in assembly 'System.Xml.XPath.XmlDocument'. There may have been a missing assembly, or a dependency on a more recent Windows SDK release. [ ....PATH.... ]
          ....PATH....\microsoft.net.native.compiler\2.2.10-rel-29722-00\tools\Microsoft.NetNative.targets(805,5): error : ILT0005: ' ....PATH....\runtime.win10-x64.microsoft.net.native.compiler\2.2.10-rel-29722-00\tools\x64\ilc\Tools\nutc_driver.exe
```

**Comment by debasrbd** [comment]
upgrade to v2.16.0 shows same error

**Comment by ThomasBarnekow** [comment]
Hi @debasrbd, could you provide the information that you would need when asked to help solve the issue? For example, can't see how this is related to the Open XML SDK at all. The error message talks about the type `System.Xml.XmlDocumentXPathExtensions`, which was referenced in the method `HtmlWeb.GetCacheHeader(Uri, string, string)`. That method is not part of the Open XML SDK. 

Another question is why you need to do an x64 build rather than building for "any" platform.

**Comment by debasrbd** [comment]
we have some native lib dependency which support only x64 for now
so we need to use this x64 build

**Comment by ThomasBarnekow** [comment]
@debasrbd, how about `HtmlWeb.GetCacheHeader(Uri, string, string)`, which references the type `System.Xml.XmlDocumentXPathExtensions`? Where is that used in your codebase?

If you did a search in this repo, you'd see that the Open XML SDK does not have a dependency on the `System.Xml.XPath.XmlDocument` NuGet package, which contains the `System.Xml.XmlDocumentXPathExtensions` type. You will also not find any occurrence of `HtmlWeb` or `GetCacheHeader`.

Thus, I'd say this is not related to the Open XML SDK. You'd have to provide a repro that clearly demonstrates that it is related to the Open XML SDK.

**Comment by ThomasBarnekow** [comment]
@debasrbd, can we close this issue? Did you find the "culprit"?

**Comment by twsouthwick** [comment]
@debasrbd I'm going to close this issue as @ThomasBarnekow's analysis appears to indicate this is not an issue with the SDK. We do not produce those APIs.
