### ISSUE TITLE
This repository: Some build job seems stuck

### ISSUE THREAD

**Issue by m-gallesio** [OfficeDev/Open-XML-SDK#1153]
This has been running / pending for 20+ days, is it normal?
https://github.com/OfficeDev/Open-XML-SDK/runs/6361756954

**Comment by tomjebo** [comment]
Thanks for pointing this out. There are some other issues with our backend build (blocking the other PRs) that we're straightening out which is why I didn't check this build. It actually was pending permission on the signing phase. I gave it permission and will check again on it.

**Comment by tomjebo** [comment]
Looks like it succeeded. Thanks again @m-gallesio
