### ISSUE TITLE
 OpenXML does not allow special character such as &, ", >, < in hyperlink, it can throw exception when get worksheet instance

### ISSUE THREAD

**Issue by ttnnphuoc** [OfficeDev/Open-XML-SDK#1179]
# Before submitting an issue, please fill this out

Is this a:
- [x] Issue with the OpenXml library
- [x] Question on library usage

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

**Description**

 OpenXML does not allow special character such as &, ", >, < in hyperlink, it can throw exception when get worksheet instance

**Observed**

 OpenXML does not allow special character such as &, ", >, < in hyperlink, it can throw exception when get worksheet instance

**Expected**
Allow  special character such

**Comment by twsouthwick** [comment]
This is a known issue due to the `System.Uri` class itself (see https://github.com/OfficeDev/Open-XML-SDK#known-issues). That links provides a mechanism to "sanitize" the document before reading it. It's not ideal, but the best option at this point.

**Comment by twsouthwick** [comment]
This has become much easier in v3.0 - see #1322. Docs to follow on how to use
