### ISSUE TITLE
A paragraph is inside a run

### ISSUE THREAD

**Issue by TimYi** [OfficeDev/Open-XML-SDK#119]
I paste pictures into word document. And the pictures can't be recognized by OpenXml SDK.
Inside my docx file, I found some abnormal structure:
```
<w:r>
<w:p xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">
<w:r>
<w:drawing>
<wp:anchor distT="0" distB="0" distL="114300" distR="114300" simplePos="0" relativeHeight="251658240" behindDoc="0" locked="0" layoutInCell="1" allowOverlap="1">
<wp:simplePos x="0" y="0"/>
<wp:positionH relativeFrom="column">
<wp:align>center</wp:align>
</wp:positionH>
<wp:positionV relativeFrom="paragraph">
<wp:posOffset>2540</wp:posOffset>
</wp:positionV>
<wp:extent cx="5352176" cy="1837188"/>
<wp:wrapTopAndBottom/>
<wp:docPr id="9" name="media/GIUACAFYtDB.png"/>
<a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
<a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
<pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
<pic:nvPicPr>
<pic:cNvPr id="0" name="media/GIUACAFYtDB.png"/>
<pic:cNvPicPr/>
</pic:nvPicPr>
<pic:blipFill>
<a:blip r:embed="rId9"/>
<a:stretch>
<a:fillRect/>
</a:stretch>
</pic:blipFill>
<pic:spPr>
<a:xfrm>
<a:off x="0" y="0"/>
<a:ext cx="5352176" cy="1837188"/>
</a:xfrm>
<a:prstGeom prst="rect"/>
</pic:spPr>
</pic:pic>
</a:graphicData>
</a:graphic>
</wp:anchor>
</w:drawing>
</w:r>
</w:p>
</w:r>
```
A paragraph with picture is inside a run. Can I read the picture using OpenXml SDK in such condition?

**Comment by tarunchopra** [comment]
Hello TimYi: I'll have a look and get back !

**Comment by tarunchopra** [comment]
Hello TimYi:

I replaced content of the document.xml with the one you pasted but it didn't work well. Can you please share your .docx file to verify\troubleshoot the behavior you are observing?

Thx.

**Comment by TimYi** [comment]
Hello tarunchopra, 
This is the file：
[click the link will directly download the docx file.](http://note.youdao.com/yws/api/personal/file/WEB5942ab3d548536b63a88b9aaf090136d?method=download&inline=true&shareKey=6a90d6a90221699e3103c567379e2380)
In this file, the pictures are all in embed paragraph(a paragraph in a run). Display of this file is correct by Microsoft Office.

**Comment by Will-Gregg** [comment]
Hello TimYi:

Thank you for posting your .docx that exhibits the behavior you are seeing. We will do some research and reply back with the results of our investigation.

**Comment by Will-Gregg** [comment]
Hello TimY:

Since your document is corrupted accessing the contained pictures is difficult. The easiest solution is to fix-up the errors in the document. You can easily do that by opening your document in Word 2016 and then saving the document from Word 2016 as a Strict OpenXML document addresses those issues.

If you are unable to correct the document corruption and need to access the images you can do so by using an System.IO.Package instance and then iterating over each of the contained parts. The images are parts with the ContentType of "image/png". Once you have the specific part you can get a stream of the part to access the image.

For example:
```
            System.IO.Packaging.Package package = Package.Open(fileName);
            foreach (PackagePart part in package.GetParts())
            {
                if (part.ContentType == @"image/png")
                {
                    System.IO.StreamReader partStream = new System.IO.StreamReader(part.GetStream());
               }
```
I hope that helps.
