### ISSUE TITLE
EMF file stream does not convert properly

### ISSUE THREAD

**Issue by SanaWaseem** [OfficeDev/Open-XML-SDK#1214]
I have a word document that has an EMF image file in it. I have to read that image file and save it in the system. Following is the code that I am using:

```csharp
  var lstImages = selectedImage.Descendants < DocumentFormat.OpenXml.Drawing.Pictures.Picture > ();

  if (lstImages != null && lstImages.Any())
  {
    foreach(var image in lstImages)
   {
      string imageFileName = image.NonVisualPictureProperties?.NonVisualDrawingProperties?.Name;
      string blip = image.BlipFill.Blip.Embed.Value;
      ImagePart img = (ImagePart) wordDoc.MainDocumentPart.GetPartById(blip);
      GetExtension(ref fileName, imageFileName, img);
      string binaryDateTime = _dateTimeHelper.GetDateTimeUtcNow().ToBinary().ToString();

      var stream = img.GetStream();
      var byteStream = new byte[stream.Length];
      int length = (int) stream.Length;
      stream.Read(byteStream, 0, length);
      stream.Dispose();
      var uploadPath = "D://ImageFile//"

      if (!_directoryManager.Exists(uploadPath)) {
        _directoryManager.CreateDirectory(uploadPath);
      }

      fileName = string.Concat(binaryDateTime, "_", fileName);

      string completePath = string.Concat(uploadPath, fileName);

      using(var fileStream = new FileStream(completePath, FileMode.OpenOrCreate)) {

        // Write bytestream to disk
        fileStream.Write(byteStream, 0, length);
        fileStream.Close();
      }
    }
  }
```
The saved file when being open says the file is damaged. Can you guide what is it that I am doing wrong or is there an easier way to save or convert EMF file as png?

**Comment by mikeebowen** [comment]
Hi @SanaWaseem ,

The SDK does not save files itself, that's up to the implementation, so I recommend posting this to [stackoverflow](https://stackoverflow.com). 

That said it might be simpler to use the [Stream.CopyTo](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.copyto?view=net-7.0) method instead of creating a byte array. Something like this:

```csharp
using (var fileStream = new FileStream(completePath, FileMode.OpenOrCreate))
{
    stream.Seek(0, SeekOrigin.Begin);
    stream.CopyTo(fileStream);
    fileStream.Close();
}
```

**Comment by Asbjoedt** [comment]
Hi

I am implementing a similar thing that saves embedded images as TIFF.
My implementation uses the Magick.Net nuget package to convert image to new file format.
Here's link to github:
https://github.com/dlemstra/Magick.NET

I suggest you add the same package to perform your conversion from .emf to .png before saving the stream to a file.

Feel free to reclose this issue, I just wanted to add my experiences.
