### ISSUE TITLE
Bug with Open XML SDK

### ISSUE THREAD

**Issue by Th3AnG3L** [OfficeDev/Open-XML-SDK#1219]
Hello i'm having an issue..
I download from nuget latest version 2.18.0
and on my pc program that i build on vb.net works fine..
But i put the program on another computer and where it uses the library shows error:

System.IO.FileLoadException: Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17'

How to solve this issue?
Why it reads 2.7.2.0 when i have installed 2.18.0 ??

**Comment by tomjebo** [comment]
@Th3AnG3L,
I think that's actually why. ClosedXML, if you have a dependency on that, has a dependency on DocumentFormat.OpenXml. ClosedXML used 2.7.2 until (I think) June of this year.

**Comment by twsouthwick** [comment]
This is a common issue on .NET Framework, but does not exist on .NET Core.

ClosedXML is referencing v2.7.2.0 on the version you had installed. However, you installed a higher version. By default, .NET Framework will not automatically load the referenced version and then it will see you don't have that version (2.7.2) but a different one (2.18). 

You need what's called a "binding redirect" to tell it that it's ok to load that. However, as @tomjebo pointed out, ClosedXML has updated to a later version, so updating that should work as well (although you may now see it wants 2.16.0 and not 2.18.0 so you'll still need a binding redirect).

Visual Studio usually tried to help - check any warnings in your build output and see the docs here: https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection.
