### ISSUE TITLE
Bug with Open XML SDK: It doesn't recognize SlideMaster part after v2.9.0

### ISSUE THREAD

**Issue by FullStackEngN** [OfficeDev/Open-XML-SDK#1225]
**Describe the bug**
Customer is using OpenXML SDK read PPTX file, they found the GetPartById() method didn't return SlideMaster type for a special file.
They did more investigation then found SDK didn't recognize SlideMaster correctly if there is slideLayout1.xml in the “\ppt\_rels\presentation.xml.rels" file. 
We understand slideLayout1.xml should not appear here, but the SDK can recognize it correctly before v2.9.0
As XML is very open structure, so it seems like we should still read the SlideMaster type as v2.8.

**Screenshots**
![image](https://user-images.githubusercontent.com/41477903/201304280-8036e062-ea45-475c-9cd9-fdc4b4cebc19.png)
![image](https://user-images.githubusercontent.com/41477903/201304371-42b884d4-cf4d-4359-8a0a-2064ff4614e5.png)

**To Reproduce**
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.

1. Use the repro file, it's private, so could not share in the issue, will contact to issue owner directly later.
2. Use following code read the file.
`        
string presentationFile = "C:\\temp\\repro.pptx";

        // Open the presentation as read-only.
        using (PresentationDocument presentationDocument = PresentationDocument.Open(presentationFile, false))
        {
            var tempPart = presentationDocument.PresentationPart.GetPartById("rId2");
            Console.WriteLine(tempPart.GetType());
        }
`

**Observed behavior**
The code returns "ExtendedPart" type.

**Expected behavior**
It should returns "SlideMasterPart"

**Desktop (please complete the following information):**
 - OS: Windows
 - Office version 16.0.15726.20202
 - .NET Target: (.NET Core)
 - DocumentFormat.OpenXml Version: (e.g. 2.18.0)

**Additional context**

**Comment by yuhungchun** [comment]
HI @FullStackEngN 

Thank you for reporting this issue. We will triage this issue shortly. It might be related to [(https://github.com/OfficeDev/Open-XML-SDK/issues/1225)] that was reported few months back.

**Comment by adamshakhabov** [comment]
@FullStackEngN, it would be good if could share your presentation file with a minimum structure for repro.

I've checked on new empty presentation and it works:

```c#
using var pres = PresentationDocument.Open("some.pptx", false);
var part = pres.PresentationPart!.GetPartById("rId1");

Console.WriteLine(part.GetType().Name);
```

Output:
```
SlideMasterPart
```

File:

![image](https://user-images.githubusercontent.com/5969304/202788551-94c78076-4e74-4883-bbe5-eb182749bd26.png)

.NET Target: .NET 6
DocumentFormat.OpenXml Version: 2.18.0

**Comment by hunyu** [comment]
Hi @FullStackEngN,

Two questions - do we know which version of Open XML SDK was used to create the PPTX in question?
Could you also try creating PPTX with the latest Open XML SDK https://github.com/OfficeDev/Open-XML-SDK/pull/1234 to see if the issue is resolved?

Hung-Chun Yu
Microsoft Open Specifications Support

**Comment by FullStackEngN** [comment]
@hunyu , we and customer don't know how the PPTX file was created.

The scenario is customer developed an application which allow their users choose PPTX file and their application will try to parse the PPTX file, Customer's application worked well on OpenXML SDK v2.7.2. When they upgrade the SDK to v2.18, then users started reported issue the application doesn't work, they did investigate and found the PPTX file provided by their users are not well format, The root cause is the SliderMaster was not correctly recognized. So, they submitted the issue and would like a fix in the SDK that bypass the not-well formatted PPTX file. 

I will ask customer to test the issue #1234 and share feedback, Thanks.

**Comment by FullStackEngN** [comment]
@hunyu @adamshakhabov Customer tested the latest code but still encountered issue.

Customer mentioned a possible fix, could you give your advice?
If adding the new "relationship.RelationshipType" check equal slideLayout or not, then the SDK can recognize their end users' PPTX file successfully?

`
 internal void LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart? sourcePart, RelationshipCollection relationshipCollection, Dictionary<Uri, OpenXmlPart> loadedParts)
        {
            foreach (var relationship in relationshipCollection)
            {
                // Fix bug https://github.com/OfficeDev/Open-XML-SDK/issues/1205
                if (relationship.RelationshipType == @"http://schemas.microsoft.com/office/2006/relationships/recovered")
                {
                    continue;
                }



               **if (sourcePart is PresentationPart
                    && relationship.RelationshipType == @"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout")
                {
                    continue;
                }**
`

**Comment by yuhungchun** [comment]
That will be awesome. Thank youSent from my iPhoneOn Nov 20, 2022, at 11:56 PM, FullStackEngN ***@***.***> wrote:﻿
@hunyu @adamshakhabov Customer tested the latest code but still encountered issue.
Customer mentioned a possible fix, could you give your advice?
If adding the new "relationship.RelationshipType" check equal slideLayout or not, then the SDK can recognize their end users' PPTX file successfully?
`
internal void LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart? sourcePart, RelationshipCollection relationshipCollection, Dictionary<Uri, OpenXmlPart> loadedParts)
{
foreach (var relationship in relationshipCollection)
{
// Fix bug #1205
if (relationship.RelationshipType == @"http://schemas.microsoft.com/office/2006/relationships/recovered")
{
continue;
}
           **if (sourcePart is PresentationPart
                && relationship.RelationshipType == @"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout")
            {
                continue;
            }**

`

**Comment by hunyu** [comment]
> @hunyu @adamshakhabov Customer tested the latest code but still encountered issue.
> 
> Customer mentioned a possible fix, could you give your advice? If adding the new "relationship.RelationshipType" check equal slideLayout or not, then the SDK can recognize their end users' PPTX file successfully?
> 
> ` internal void LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart? sourcePart, RelationshipCollection relationshipCollection, Dictionary<Uri, OpenXmlPart> loadedParts) { foreach (var relationship in relationshipCollection) { // Fix bug #1205 if (relationship.RelationshipType == @"http://schemas.microsoft.com/office/2006/relationships/recovered") { continue; }
> 
> ```
>            **if (sourcePart is PresentationPart
>                 && relationship.RelationshipType == @"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout")
>             {
>                 continue;
>             }**
> ```
> 
> `

**Comment by FullStackEngN** [comment]
@hunyu Thanks, customer did test locally and confirmed the new "relationship.RelationshipType" check works for them, so they would like OpenXML team consider it and may add it to next release then they can upgrade to next version SDK.

**Comment by FullStackEngN** [comment]
@hunyu May I have an update for this issue? Will customer have the fix in next OpenXML SDK version? Thanks.

**Comment by hunyu** [comment]
@FullStackEngN

Next OpenXML SDK version will not have this fix. Our team won't be able to work on it until after next OpenXML SDK is released.
