### ISSUE TITLE
Different part name between Excel and Open-XML-SDK

### ISSUE THREAD

**Issue by HowardRubin** [OfficeDev/Open-XML-SDK#123]
When I call the function `WorksheetPart.AddNewPart<DrawingsPart>`, the result part filename is /xl/drawings/drawing.xml, which is different from what Excel 2013 names it (/xl/drawings/drawing1.xml). Note the "1". This wouldn't matter, **except** that the Open XML SDK 2.5 Productivity Tool for Microsoft Office won't compare DrawingsPart s created the two different ways.

What's causing this is that line 7719 of DocumentFormat.OpenXml\src\GeneratedCode\package.cs returns the TargetNameConstant which lacks the "1":
`    internal const System.String TargetNameConstant =@"drawing";`

I need to control the name of the DrawingsPart so the Productivity Tool can generate Open-XML-SDK code for me to use in my program. Can you help me? If this requires a change to the Productivity Tool, I have other ideas for enhancements too.

Howard Rubin

**Comment by HowardRubin** [comment]
There's a similar issue for part `/xl/worksheets/sheet1.xml` on lines 9891 & 9897 of the same package.cs file:
`    internal const System.String TargetNameConstant =@"sheet";`

**Comment by Josh-Curry** [comment]
Hi Howard, I just submitted a PR to address this problem. Please let me know if you run into any other issues related to this. Thanks.

**Comment by HowardRubin** [comment]
/word/theme/theme1.xml has the same missing "1" issue on line 16663 of src/GeneratedCode/package.cs

**Comment by HowardRubin** [comment]
Hi Josh,

 

Thanks for letting me know. /word/theme/theme1.xml has the same missing "1" issue on line 16663 of src/GeneratedCode/package.cs

 

Howard Rubin

**Comment by Josh-Curry** [comment]
I was aware of that one as well. After reviewing the ISO/IEC 29500-1 standard, 39 of the contentTypes will now have a number appended to the name even if there is only a single instance of that type in the package. This addresses all 3 package/file types and should match the behavior of Word, Excel, and PowerPoint.
