### ISSUE TITLE
Merge .NET Standard changes to Office2016 branch

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#126]

**Comment by ph1ll** [comment]
Are there any plans for an official nuget package to go with this? #2

**Comment by twsouthwick** [comment]
I'm working with the team to set up a signing service via AppVeyor and the .NET Foundation to get some CI/CD builds (hopefully of both vNext and Office2016 branches).

**Comment by tomjebo** [comment]
We will likely be including the Office2016 branch changes in the coming months. I've merged them privately and tests are passing. This is in our plans.
