### ISSUE TITLE
Confusing exception when file cannot be found

### ISSUE THREAD

**Issue by JustinMinnaar** [OfficeDev/Open-XML-SDK#128]
I have a large document that opens fine and edits without issue under Microsoft Word 2016. It contains 67 pages, and some images and tables. When trying to open this document using the OpenXml libraries, I receive the following exception. Any suggestions?

An exception of type 'DocumentFormat.OpenXml.Packaging.OpenXmlPackageException' occurred in DocumentFormat.OpenXml.dll but was not handled in user code

Additional information: The specified package is invalid. The main part is missing.

**Comment by tarunchopra** [comment]
@JustinMinnaar : 

Please share the WORD document so that we can debug the issue AND openxml test code that you are using to reproduce the issue.

Thx

**Comment by JustinMinnaar** [comment]
Regret that the document is a confidential document and I cannot send it to you. I'll try create a dummy document tomorrow to reproduce the issue. Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [OfficeDev/Open-XML-SDK] Can't open valid Word document (#128)From: "TarunChopra[MSFT]" To: OfficeDev/Open-XML-SDK CC: Justin Minnaar ,Mention @JustinMinnaar :
Please share the WORD document so that we can debug the issue AND openxml test code that you are using to reproduce the issue.
Thx

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OfficeDev/Open-XML-SDK","title":"OfficeDev/Open-XML-SDK","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OfficeDev/Open-XML-SDK"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tarunchopra in #128: @JustinMinnaar : \r\n\r\nPlease share the WORD document so that we can debug the issue AND openxml test code that you are using to reproduce the issue.\r\n\r\nThx"}],"action":{"name":"View Issue","url":"https://github.com/OfficeDev/Open-XML-SDK/issues/128#issuecomment-263623935"}}}

**Comment by tarunchopra** [comment]
Sure, we will wait for the artifacts. Thanks.

**Comment by JustinMinnaar** [comment]
Hi. My apologies, I've determined that this error actually means that the file is not found. I deleted everything out of the file and it still raised the error, until I realized that the file was not being copied into the debug folder.
  
 Perhaps it would be worth raising the FileNotFoundException instead?
  
 Kindest regards,
  
 Justin Minnaar
  
  
  

----------------------------------------

**Comment by tarunchopra** [comment]
@JustinMinnaar : Yes, you are correct and I'm able to verify\reproduce the issue. I'll add a validation check for File.Exists at all the entry points.

**Comment by JustinMinnaar** [comment]
Great. As I was unable to Edit and Continue during debugging, I ended up wrapping the functions I needed to extract the data into my own classes. This also made it easier to write unit tests for the functions I needed. Thanks for providing me with a clean method of extending Word. It's really useful. Justin Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [OfficeDev/Open-XML-SDK] Can't open valid Word document (#128)From: "TarunChopra[MSFT]" To: OfficeDev/Open-XML-SDK CC: Justin Minnaar ,Mention @JustinMinnaar : Yes, you are correct and I'm able to verify\reproduce the issue. I'll add a validation check for File.Exists at all the entry points.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OfficeDev/Open-XML-SDK","title":"OfficeDev/Open-XML-SDK","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OfficeDev/Open-XML-SDK"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tarunchopra in #128: @JustinMinnaar : Yes, you are correct and I'm able to verify\\reproduce the issue. I'll add a validation check for File.Exists at all the entry points."}],"action":{"name":"View Issue","url":"https://github.com/OfficeDev/Open-XML-SDK/issues/128#issuecomment-263931120"}}}

**Comment by twsouthwick** [comment]
@tarunchopra are you still planning on doing this?

**Comment by twsouthwick** [comment]
@JustinMinnaar Can you share the code that you are using to open the package? I'm interested which overload you are using that causes the package to fail to load. A small repro will ensure we are addressing the right issue for you (and then find if it's a pattern for other overloads)

**Comment by JustinMinnaar** [comment]
Hello @twsouthwick . I've not worked on this project for almost a year now. It was a confidential project at a client. I regret I can't recall anymore what exactly the issue was at the time.

**Comment by twsouthwick** [comment]
Ok. I think I found the location.

https://github.com/OfficeDev/Open-XML-SDK/blob/138977da97202c440ea647a86622bdcbccefa567/DocumentFormat.OpenXml/src/Framework/OpenXmlPackage.cs#L314-L35

@tarunchopra Are you going to submit a PR for this? It is a breaking change, but probably a good one. We'll want to document it, though.
