### ISSUE TITLE
How I can detect "filled markers" list item ?

### ISSUE THREAD

**Issue by vitalylukyanenko** [OfficeDev/Open-XML-SDK#129]
Hi,  
I need detect TextBody/Paragraphs with markers. All markers type has a mark "CharacterBullet" or "NoBullet", but one of these hasn't any mark.

Here is a slide with TextBody which contains undetected markers:
![1](https://cloud.githubusercontent.com/assets/23737443/20787636/886ba5b4-b7df-11e6-9270-334fbf61399f.png)

How I can detect theirs ?

**Comment by tarunchopra** [comment]
@vitalylukyanenko : Can you please share your .pptx file and tell us as to which textbody\para does not have a marker ?

**Comment by vitalylukyanenko** [comment]
@tarunchopra : Thank you. Here is a .ppts file with my issue


[Test.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/747480/Test.pptx)

**Comment by tarunchopra** [comment]
@vitalylukyanenko : So if I understand correctly, you want to detect following para using SDK?

One - There is no any marks, but it’s a bullet point
Two – There is no any marks, but it’s a bullet point

Thx

**Comment by vitalylukyanenko** [comment]
@tarunchopra yes, you're right.

**Comment by twsouthwick** [comment]
@vitalylukyanenko This does not seem to be a bug in the library itself but rather a question. I'm closing this issue and recommend that you open it as a question on StackOverflow
