### ISSUE TITLE
Add a strong name key

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#134]
This is to track adding the strong name signing back, not to start a discussion on whether or not there should be one. Hopefully we can add one that will mitigate the known dev issues of strong names (ie local builds) following guidance the [CoreFX team](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md) is using.

**Comment by tomjebo** [comment]
I'm working on this and should have it in the build soon. Thanks.

**Comment by tomjebo** [comment]
Done.
