### ISSUE TITLE
Excel row height behaves unexpectedly on high-dpi machines

### ISSUE THREAD

**Issue by mjrousos** [OfficeDev/Open-XML-SDK#137]
Setting spreadsheet row height appears to be affected by high-dpi scaling even though the height is not set in terms of pixels.

As an example, setting `Row.Height` to 15 creates a spreadsheet with a row of only 7.5 height (20 pixels) on a machine with DPI scaling set to 200% (192). 

edit - I should specify this is with the 2.5.0 package available on NuGet. I haven't tried with more recent builds.

**Comment by tarunchopra** [comment]
@mjrousos : 

I created the attached file with default height of 15 by executing test case  G002() to reproduce the issue using **Latest Code** (DPI was 100%). 

After creating the file, I increased the DPI to 175% and verified the Row Height (Home->Cell->Format->Row Height option in excel) and excel still reports it as 15.

Can you please verify enclosed file once and let me know if you still see the issue or If I missed anything?

[3467c253-9281-4875-8310-5d654780dfe6.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/685615/3467c253-9281-4875-8310-5d654780dfe6.xlsx)


Thanks.

**Comment by DaniusLabs** [comment]
I was able to reproduce this with package id="DocumentFormat.OpenXml" version="2.10.1" targetFramework="net472" />

**Comment by zengjilong** [comment]
@tarunchopra You should create a new sheet and set the row height in the new sheet, and you can reproduce this problem
DocumentFormat.OpenXml 2.19.0

**Comment by zengjilong** [comment]
> @mjrousos :
> 
> I created the attached file with default height of 15 by executing test case G002() to reproduce the issue using **Latest Code** (DPI was 100%).
> 
> After creating the file, I increased the DPI to 175% and verified the Row Height (Home->Cell->Format->Row Height option in excel) and excel still reports it as 15.
> 
> Can you please verify enclosed file once and let me know if you still see the issue or If I missed anything?
> 
> [3467c253-9281-4875-8310-5d654780dfe6.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/685615/3467c253-9281-4875-8310-5d654780dfe6.xlsx)
> 
> Thanks.

Although the row height value in the file is set correctly, when viewed using Microsoft Office, it is not displayed according to the set value.
[learnOpenXml.xlsx](https://github.com/user-attachments/files/16107484/learnOpenXml.xlsx)
For example, although the above file is set to 100, when opened through office, you can see that the row height is only 66.666. After saving, the value becomes 66.666.

**Comment by zengjilong** [comment]
I understand, the above phenomenon is because the sheetViews tab does not exist in the sheet I created.
