### ISSUE TITLE
Issue with Generating Powerpoint document in Memory Stream. The file is corrupted

### ISSUE THREAD

**Issue by mohammad234** [OfficeDev/Open-XML-SDK#138]
Hello Expert,

I am facing issue with generating powerpoint, when working with Memory Stream. The generated powerpoint is corrupted.

below Code:
I am also attaching the sample. Any help will be highly appreciated.
MemoryStream templateStream = null;

            using (Stream stream = File.Open(@"D:\Project\Open XML SDK\Template.pptx", FileMode.Open, FileAccess.Read))
            {
                templateStream = new MemoryStream((int)stream.Length);
                stream.Copy(templateStream);
                templateStream.Position = 0L;

                using (PresentationDocument myPres = PresentationDocument.Open(templateStream, true))
                {

                    var presPart = myPres.PresentationPart;
                    var slideIdList = presPart.Presentation.SlideIdList;

                    var list = slideIdList.ChildElements
                                .Cast<SlideId>()
                                .Select(x => presPart.GetPartById(x.RelationshipId))
                                .Cast<SlidePart>();

                    var tableSlidePart = list.Last();

                    //Use the first slide as a template just for cloning
                    var newtableSlidePart = CloneSlidePart(presPart, tableSlidePart, true);
                    var slideCreated = true;
                    var current = newtableSlidePart;
                    for (var i = 1; i <= 3; i++)
                    {
                        if (!slideCreated)
                        {
                            var newTablePartForNewCoveragePlan = CloneSlidePart(presPart, tableSlidePart, true);
                            current = newTablePartForNewCoveragePlan;
                            slideCreated = true;
                        }

                        SetPlaceholder(current, i);
                        SetNotes(current);

                        GenerateTable(current, presPart, tableSlidePart, i);
                        current.Slide.Save();
                        slideCreated = false;
                    }

                    myPres.PresentationPart.Presentation.Save();

                    //delete the first slide that we used just for cloning
                    //Get slide id to delete
                    var slideIdToDelete = slideIdList.ChildElements[0] as SlideId;

                    // Get the relationship ID of the slide.
                    string slideRelId = slideIdToDelete.RelationshipId;

                    // Remove the slide from the slide list.
                    slideIdList.RemoveChild(slideIdToDelete);

                    // Save the modified presentation.
                    presPart.Presentation.Save();

                    // Get the slide part for the specified slide.
                    var slidePart = presPart.GetPartById(slideRelId) as SlidePart;

                    // Remove the slide part.
                    presPart.DeletePart(slidePart);

                    File.WriteAllBytes(@"D:\Project\Open XML SDK\Output.pptx", templateStream.ToArray());
   }

[ExportPPT.zip](https://github.com/OfficeDev/Open-XML-SDK/files/661429/ExportPPT.zip)
           

[Template.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/661425/Template.pptx)

**Comment by tarunchopra** [comment]
Hello mohammad234 : I'll look into it.

**Comment by tarunchopra** [comment]
I made some modifications in your code and able to generate the output file w/o any issue. Can you please review below modified solution?

[ExportPPT.zip](https://github.com/OfficeDev/Open-XML-SDK/files/683874/ExportPPT.zip)

In addition, there is any existing test case - CanCreatePresentationFromTemplate() that you can refer to leverage existing functions to generate power point file from the template.

**Comment by shubhjack** [comment]
@tarunchopra can you help me tweak my api too, For me I'm also unable to save stream as file at the end. 

```
        [HttpGet]
        [Route("[action]")]
        public IActionResult RemoveEmptySection(IFormFile file)
        {
            int count = 0;
            using (Stream stream = new MemoryStream(ConvertToStream(file)))
            {
                using (PresentationDocument presentationDocument = PresentationDocument.Open(stream, true))
                {
                    var sectionList = presentationDocument.PresentationPart!.Presentation.PresentationExtensionList?.Descendants<SectionList>().First();

                    List<Section> emptySectionList = new List<Section>();

                    // Remove empty sections
                    foreach (Section section in sectionList)
                    {
                        var isEmptySection = section.SectionSlideIdList.Count() == 0 ? true : false;

                        if (isEmptySection)
                        {
                            emptySectionList.Add(section);
                            count++;
                        }
                    }

                    foreach (var item in emptySectionList)
                    {
                        sectionList.RemoveChild(item);
                    }
                    presentationDocument.PresentationPart.Presentation.Save();

                   /* some code to save the file */
                }                
            }
            return Ok($"{count} empty sections deleted");
        }
```
