### ISSUE TITLE
Can't find any package in myget feed V3

### ISSUE THREAD

**Issue by xrkolovos** [OfficeDev/Open-XML-SDK#139]
I can't find any package in myget feed V3 with vs 2015. I also checked Include Prerelease packages.

**Comment by tomjebo** [comment]
I'm looking into this. It should be mostly in place but there were some issues with signing.

**Comment by tomjebo** [comment]
Actually, it was saying the pkg we build was corrupt:
"Error publishing package. NuGet server returned 400: Invalid or corrupt NuGet package detected. A local file header is corrupt."
We're investigating.

**Comment by tomjebo** [comment]
@xrkolovos There is now a manually built latest version nuget package available on myget feed. Note that this is not currently strong named and there may be other minor details to polish but the package is available, working and up to the latest commits. Let us know if you find any issues.
