### ISSUE TITLE
Adding dates to cells is not easily discoverable

### ISSUE THREAD

**Issue by thyams** [OfficeDev/Open-XML-SDK#142]
Using the following example to determine cell value:

        private static CellValues GetDataType( object DataColumn )
        {
            CellValues cvs = new CellValues();

            if( DataColumn is int || DataColumn is short || DataColumn is long ||
                DataColumn is float || DataColumn is double || DataColumn is uint ||
                DataColumn is ulong || DataColumn is ushort || DataColumn is decimal)
            {
                cvs = CellValues.Number;
            }
            else if (DataColumn is DateTime)
            {
                cvs = CellValues.Date;
            }
            else
            {
                cvs = CellValues.String;
            }

            return cvs;
        }

Any time I use CellValues.Date spreadsheet needs repair. Everything displays correctly but ideally I would like it not to need repairing on opening.

Allowing DateTime to fall into the CellValues.String also works.

I don't know if it's a bug or not, so I am just asking if it's a valid cell value.

**Comment by twsouthwick** [comment]
@thyams Which platform are you running on? ie .NET Framework, UWP, .NET Core, etc

**Comment by thyams** [comment]
NetCore, CI

**Comment by twsouthwick** [comment]
Do you see the repro if you compile against .NET Framework?

**Comment by thyams** [comment]
I will try tomorrow.

**Comment by tomjebo** [comment]
Please disregard that last reference from #131. It was a mistake.

**Comment by twsouthwick** [comment]
@thyams Were you able to repro it on .NET Framework?

**Comment by blakepell** [comment]
I have this same issue compiled against net461.  I'm temporarily writing strings, anytime I use CellValues.Date and put a date into it it corrupts the spreadsheet.  I set the cell's DataType to CellValues.Date and then the CellValue to a new CellValue with the date passed in as a string to the constructor of CellValue (perhaps it needs a specific format on the date?.. as opposed to whatever DateTime.Now.Date.ToString() might spit out?).

**Comment by twsouthwick** [comment]
@blakepell You need to call ToString() with the appropriate format string to generate an ISO 861 compliant string. Calling `DateTime.Now.Date.ToString("s", CultureInfo.InvariantCulture)` should get you what you want.

This seems like a common thing someone would want to do, so I think we should add an overload to `CellValue` that takes a `DateTime`.

**Comment by 1Jesper1** [comment]
How to create a DateTime column and add dates to an Excel 2013 file?  @twsouthwick

**Comment by tomjebo** [comment]
@1Jesper1 If you're reporting a problem with the SDK, this is a good place. How to type questions should be posted on stackoverflow. A search like this may help:
[StackOverflow #openxml-sdk datetime](https://stackoverflow.com/search?q=%5Bopenxml-sdk%5D+datetime)

**Comment by DartWelder** [comment]
Try to set CellValues to Number.

**Comment by nagindotnet9** [comment]
I am facing another Issue, I want to set only date in Cell with Date datatype but there is no reference available.
If we specify formatted string then it is no more date.

Anyone can help in that ?
