### ISSUE TITLE
Add constructor overload to validator that determines file format version instead of defaulting to 2007

### ISSUE THREAD

**Issue by tomjebo** [OfficeDev/Open-XML-SDK#143]
From #8 this is a request for fixing and improving default handling for validator ctor.

"The constructor of the validator requires me to specify against which fileformat (2007/2010/2013) to validate. How can I determine the file format of an existing document? If that's possible, why doesn't the default constructor of the validator do so, instead of defaulting to 2007?"

**Comment by twsouthwick** [comment]
I don't believe this is possible. Is there anything in the OpenXML schema that gives this information? @tomjebo  @EricWhiteDev
