### ISSUE TITLE
Export to excel error

### ISSUE THREAD

**Issue by fadenmad** [OfficeDev/Open-XML-SDK#145]
Hello.
I got data from database, created excel file and wrote that data into one sheet.
But, when i tried to open that file, i got error "missing ';'".
I unzipped excel file and in file sheet.xml i found that some Unicode symbols are incorrect wrote. For example, "&#43E&#41A;&#438". After first unicode symbol ';' is missing.

**Comment by Josh-Curry** [comment]
Hi fadenmad, can you verify that the data you get from the database is valid? I would imagine that the SDK doesn't modify the string when it writes it to the file.

Can you reproduce the problem by hardcoding the string or another way that you can share with us? If yes, can you please share a code snippet that reproduces the problem?

Thanks.

**Comment by fadenmad** [comment]
This is test project: https://drive.google.com/open?id=0B02wP-j_WJ1fZ3FpbWVIM0FDV3M (zip-archive)
This is excel file from export: 
[example.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/715842/example.xlsx)

**Comment by Josh-Curry** [comment]
Thanks. I'll take a look at it.

**Comment by Josh-Curry** [comment]
Hi fadenmad, is the problem semi-random? I've run the project several times but each time the file it creates is valid. Is there a trick to it?

I tried opening the example.xlsx that you provided and it fails to open for me as well, but trying to open and parse the 436MB sheet.xml file is more than a little cumbersome. Is it possible for you to reproduce the problem with the counter set to something smaller such as 10?

**Comment by fadenmad** [comment]
I reduced columns and rows count from 1000 to 25. Error still appeare.
[test.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/723508/test.xlsx)

**Comment by Josh-Curry** [comment]
Hi fadenmad, I see that the new file you posted still has a problem with it. But I am still not able to reproduce the issue with the sample application you sent.

I took a closer look at the actual data in the sample file versus what the sample application produces and I can see that the data is completely different. Is that still being pulled from the database? I can also see that the xml is formatted differently, which tells me that the files are likely being produced by different applications. 

Unless the sample application can produce a working repro I will not be able to debug the issue. Have you verified that the problem isn't with the data that is coming from the database?

**Comment by fadenmad** [comment]
Hello. Data that exports to Excel is not from database (i can't send you our database data). I reproduced the problem by hardcoding as you ask. I create the new test application with similar export method. Problem is not from database output or other. It's appear when I use Open XML for export to Excel. I tried to run application on other computers with similar soft (almost identical, for, example, MS Office and .NET Framework was installed from one distributive on all computers) and i got this problem on 50% workstations.

**Comment by Josh-Curry** [comment]
I tried to test it on a few other machines but I wasn't able to reproduce the problem. It could be something specific to the client or environment as well.

I also noticed that you are using an older version of the DocumentFormat.OpenXML.dll. It looks like you are using the official 2.5 version that is several years old at this point. There have been significant changes to the SDK since that release. I think it would be worth it to test your scenario with the latest build. Can you try that and let me know if it makes any difference?

Thanks.

**Comment by fadenmad** [comment]
The latest version is require .Net Framework 4.5. I need a .dll for .Net Framework 4.0.

**Comment by fadenmad** [comment]
Can you give me advice, how can i use the latest version of OpenXML dll library on .NET Framework 4.0 ?
.NET Framework updating is currently impossible.

**Comment by Josh-Curry** [comment]
Hi fadenmad, we don't have any plans at this time to make the SDK compatible with the 4.0 framework. However, I did some initial investigation into what this might take. If you modify the project.json file to change the framework version from net45 to net40, remove the netstandard1.3 option, and then try to build the project there is only a small handful of errors that don't seem like they would be too difficult to 'fix'. 

I would encourage you to create a fork of the vNext branch and try that yourself. If you are able to get that working, please submit a pull request and we'll review it for possible inclusion in the main project.
