### ISSUE TITLE
Update-Version.ps1 script fails to update version

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#152]
@tomjebo 

After a recent change (6fb08bcc133bd7b291badcd8669b3392bcb21dc2), the [`build\Update-Version.ps1`](https://github.com/OfficeDev/Open-XML-SDK/blob/vNext/build/Update-Version.ps1) script no longer works. This was searching for the `3.0.0-*` string to find/replace in the project.json files and now it won't find it.

**Comment by tomjebo** [comment]
Thanks, I'll remove that since I changed the version in the json to 2.7.0.

**Comment by twsouthwick** [comment]
If you remove it, then the versioning won't be done by GitVersion. With GitVersion, CI builds get a version based off the previous tag (ie, 2.7.0-vnext003, where 003 is the number of commits since 2.7.0); if you remove it, then you have to manually change the version each time and it will break the automation.

**Comment by tomjebo** [comment]
I'm fixing it. Sorry. I'll also change the 3.0.0 placeholder to 0.0.1 so it's more obvious this is a placeholder.

**Comment by tomjebo** [comment]
fixed.
