### ISSUE TITLE
Visual Studio does not find tests

### ISSUE THREAD

**Issue by jpgeiger6789** [OfficeDev/Open-XML-SDK#154]
When I clone this to my computer (Windows 7) and open the project in in Visual Studio 2015, visual studio is unable to find any tests in the Test Explorer.  I have to run the tests using a command line utility.  I am not sure if this is an issue with my computer/Visual Studio installation or an issue with the SDK, but Visual Studio is finding the Open XML Power Tools tests.

**Comment by Will-Gregg** [comment]
@jpgeiger6789 the v2.7 label or PR #155 has changes that should address the issue you are seeing. Please sync your repro with those changes.

**Comment by jpgeiger6789** [comment]
The project is configured to use .NET core version 1.0.  I have .NET core version 1.1 installed.  I can't even find an installer (after a short google search) for version 1.0.  Is there an easy way to fix this?
