### ISSUE TITLE
Validator incorrectly reports MaxExclusive contraint errors

### ISSUE THREAD

**Issue by Themanwithoutaplan** [OfficeDev/Open-XML-SDK#16]
Not sure whether this is part of the project or not. The validator in the Productivity Tool routinely reports pageMargin attributes as errors "t has an invalid value of '0.75'. The MaxExclusive constraint failed. The value must be less than 49"

**Comment by Themanwithoutaplan** [comment]
This also applies to MaxInclusive constraints.

**Comment by ThomasBarnekow** [comment]
This is addressed in #50.

**Comment by EricWhiteDev** [comment]
We are creating a new milestone, 4.0, in which we will systematically correct the validation functionality.

**Comment by ThomasBarnekow** [comment]
Again, this is fixed in PR #50.
