### ISSUE TITLE
Trouble with Import-Module, no System.IO.Packaging.dll

### ISSUE THREAD

**Issue by 3bm** [OfficeDev/Open-XML-SDK#163]
Trying to Import-Module Open-Xml-PowerTools returns this error

> Add-Type : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\Users\macer\Docu
ments\WindowsPowerShell\Modules\Open-Xml-Sdk\DocumentFormat.OpenXml\bin\debug\System.IO.Packaging.dll' because it does
not exist."
At C:\Users\macer\Documents\WindowsPowerShell\Modules\Open-Xml-PowerTools\AddTypes.ps1:69 char:16 
> + ... -Type -Path "$PSScriptRoot\..\Open-Xml-Sdk\DocumentFormat.OpenXml\bin ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : WriteError: (:) [Add-Type], ParameterBindingException
>     + FullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.AddTypeCommand
> 

"DocumentFormat.OpenXml.dll" can't be found either but is in a net45 and netstandard1.3 folder

**Comment by twsouthwick** [comment]
@3bm Where are you getting the `Open-Xml-PowerTools`? Are you building it yourself or downloading it from the PSGallery? This looks to be an issue with the module and not the Open-XML-SDK library. Here's the repo for that: https://github.com/OfficeDev/Open-Xml-PowerTools.

**Comment by 3bm** [comment]
@twsouthwick I cloned the PowerTools from the repo.

**Comment by twsouthwick** [comment]
I'm not familiar with that project, so I would suggest you raise an issue there. I'll check around to see if I can find who owns it. As a work around, try downloading the package from the MyGet feed and referencing that (you'll want the net45 version of it)

**Comment by 3bm** [comment]
Oops, might have used the wrong branch, switched to the master branch on both projects and have no issues anymore.

**Comment by twsouthwick** [comment]
That makes sense, then. This project has a lot of divergence from develop vs master and looks like that project has an expectation about the project structure that has since changed. I've created an issue there for it to just pull in the library this project generates instead of expecting the repo side-by-side so others won't be blocked by this. Thanks!
