### ISSUE TITLE
Opening generated Xlsx in numbers (iOS) doesn't work.

### ISSUE THREAD

**Issue by joelharkes** [OfficeDev/Open-XML-SDK#167]
Using the following code, i generate an xlsx document. which i can open in Excel 2016 but when i open it in Numbers (iOS) i see the worksheet name, but i don't see any data in the sheet. (its just blank, I don't even see cells).

When i open in excell => save => open in Numbers (iOS) it does open.

Biggest changes that happen after saving in Excel:

* Styles.xml is filled with default styling (it was empty)
* xl/theme/theme1.xml is added
* docProps/app.xml is added
* docProps/core.xml is added
* xl/workhseet/sheet.xml is renamed to => xl/worksheet/sheet1.xml
* some rels are added for docprops.

Code: 
```
///Stream is mem stream written into output stream.
using (var ssd = SpreadsheetDocument.Create(stream, SpreadsheetDocumentType.Workbook))
{ 
    ssd.AddWorkbookPart();
    ssd.WorkbookPart.Workbook = new Workbook();
    ssd.WorkbookPart.Workbook.Save();
    var sharedStringTablePart = ssd.WorkbookPart.AddNewPart<SharedStringTablePart>();
    sharedStringTablePart.SharedStringTable = new SharedStringTable();
    sharedStringTablePart.SharedStringTable.Save();
    ssd.WorkbookPart.Workbook.Sheets = new Sheets();
    ssd.WorkbookPart.Workbook.Save();
    var workbookStylesPart = ssd.WorkbookPart.AddNewPart<WorkbookStylesPart>();
    workbookStylesPart.Stylesheet = new Stylesheet();
    workbookStylesPart.Stylesheet.Save();
    var worksheetPart = ssd.WorkbookPart.AddNewPart<WorksheetPart>();
    worksheetPart.Worksheet = new Worksheet(new SheetData()) {};
    worksheetPart.Worksheet.Save();
    var sheets = ssd.WorkbookPart.Workbook.GetFirstChild<Sheets>();
    var sheet = new Sheet
    {
        Id = ssd.WorkbookPart.GetIdOfPart(worksheetPart),
        SheetId = (uint) (ssd.WorkbookPart.Workbook.Sheets.Count() + 1),
        Name = "translations"
    };
    sheets.Append(sheet);
    ssd.WorkbookPart.Workbook.Save();
    var wbPart = ssd.WorkbookPart;
    worksheetPart = wbPart.WorksheetParts.First();
    var sheetdata = worksheetPart.Worksheet.GetFirstChild<SheetData>();
    var headerColumns = new[] {"ResourceKey", "Value", "LocaleId", "GroupName"};
    var r = new Row();
    Cell cell;
    uint rowIndexer = 1;
    var columnIndexer = 1;
    r.RowIndex = rowIndexer;
    foreach (string t in headerColumns)
    {
        var i  = InsertSharedStringItem(t, sharedStringTablePart);
        cell = new Cell
        {
            CellReference = ColumnName(columnIndexer) + rowIndexer,
            DataType = CellValues.SharedString,
            CellValue = new CellValue(i.ToString())
        };
        r.AppendChild(cell);

        columnIndexer++;
    }
    sheetdata.Append(r);
    worksheetPart.Worksheet.Save();
    wbPart.Workbook.Save();

    ssd.Close();
}
```

**Comment by joelharkes** [comment]
anyone knows a way to fix this? ive been searching the internet but didnt find anything

**Comment by twsouthwick** [comment]
Which version of the library are you using?

**Comment by joelharkes** [comment]
I used version 2.7.0.
I saw 2.7.1 was just released. But it looked like not much changed?

(Btw I tried to get the myget feed to work, but I couldn't so I just uploaded it myself to nuget, I'm wondering why you guys aren't?).

**Comment by joelharkes** [comment]
I had been trying to debug by removing saves and not using shared string library. But that wouldn't work.

**Comment by twsouthwick** [comment]
What are you compiling against? 2.7.1 fixed a validation bug when on .NET Framework and a packaging issue.

As for NuGet, there are processes we have to go through to get it uploaded to NuGet and are figuring that out. Which package are you supporting? We would like to consolidate to just one to limit confusion. What problem were you getting with myget? If you used 2.7.0 from myget, then saw issues, it's because we intentionally delisted it due to a packaging error we found with it.

**Comment by joelharkes** [comment]
My package (with credits to you guys, ofc). Its a direct build of the 2.7.0 release: https://www.nuget.org/packages/Joelharkes.DocumentFormat.OpenXml/

We are using dotnet core 1.1.0 sdk with project json.

**Comment by joelharkes** [comment]
I'll try 2.7.1 and come back to you.

**Comment by Josh-Curry** [comment]
I just tested this with the latest build from the repo, not the nuget package, and Numbers for iPad is able to open and convert the file without any issues. Interestingly though, Numbers on iPhone doesn't even try to convert the file. I don't think it should matter, but I'm using the .NET 4.5 dll.

**Comment by joelharkes** [comment]
@twsouthwick  2.7.1 Still has the issue.

Running on latest iOS (Siera 10.12.3) and numbers 4.0.5 (4052).
and dotnet core app1.1.

**Comment by Josh-Curry** [comment]
@joelharkes I believe that is MacOS, not iOS.

**Comment by joelharkes** [comment]
Ah yes, sorry, i'm not really into the apple scene, my colleague tests it for me. 

but i had another colleague try and for him it also didnt work on macOS

**Comment by joelharkes** [comment]
@Josh-Curry  where you able to reproduce it as well?

**Comment by twsouthwick** [comment]
This has been fixed with https://github.com/OfficeDev/Open-XML-SDK/pull/267. Please reopen if you still see it
