### ISSUE TITLE
para.Descendants<OfficeMath>().Count() return 0

### ISSUE THREAD

**Issue by GuanRainy** [OfficeDev/Open-XML-SDK#173]
when I call the "para.Descendants<OfficeMath>().Count()"(para is a Paragraph class instance), it return 0, but the para instance contain the "m:oMath" label, What is the problem ? thansks!
the para instance contents as follows:

- <m:oMathPara xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math">
- <m:oMath>
- <m:sSup>
- <m:sSupPr>
- <m:ctrlPr>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" w:eastAsia="Cambria Math" /> 
  </w:rPr>
  </m:ctrlPr>
  </m:sSupPr>
- <m:e>
- <m:d>
- <m:dPr>
- <m:ctrlPr>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" w:eastAsia="Cambria Math" /> 
  </w:rPr>
  </m:ctrlPr>
  </m:dPr>
- <m:e>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" w:eastAsia="Cambria Math" /> 
  </w:rPr>
  <m:t>x+a</m:t> 
  </m:r>
  </m:e>
  </m:d>
  </m:e>
- <m:sup>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" w:eastAsia="Cambria Math" /> 
  </w:rPr>
  <m:t>n</m:t> 
  </m:r>
  </m:sup>
  </m:sSup>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" /> 
  </w:rPr>
  <m:t>=</m:t> 
  </m:r>
- <m:nary>
- <m:naryPr>
  <m:chr m:val="∑" /> 
  <m:grow m:val="1" /> 
- <m:ctrlPr>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" w:eastAsia="Cambria Math" /> 
  </w:rPr>
  </m:ctrlPr>
  </m:naryPr>
- <m:sub>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" /> 
  </w:rPr>
  <m:t>k=0</m:t> 
  </m:r>
  </m:sub>
- <m:sup>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" /> 
  </w:rPr>
  <m:t>n</m:t> 
  </m:r>
  </m:sup>
- <m:e>
- <m:d>
- <m:dPr>
- <m:ctrlPr>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" w:eastAsia="Cambria Math" /> 
  </w:rPr>
  </m:ctrlPr>
  </m:dPr>
- <m:e>
- <m:f>
- <m:fPr>
  <m:type m:val="noBar" /> 
- <m:ctrlPr>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" w:eastAsia="Cambria Math" /> 
  </w:rPr>
  </m:ctrlPr>
  </m:fPr>
- <m:num>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" /> 
  </w:rPr>
  <m:t>n</m:t> 
  </m:r>
  </m:num>
- <m:den>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" /> 
  </w:rPr>
  <m:t>k</m:t> 
  </m:r>
  </m:den>
  </m:f>
  </m:e>
  </m:d>
- <m:sSup>
- <m:sSupPr>
- <m:ctrlPr>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" w:eastAsia="Cambria Math" /> 
  </w:rPr>
  </m:ctrlPr>
  </m:sSupPr>
- <m:e>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" /> 
  </w:rPr>
  <m:t>a</m:t> 
  </m:r>
  </m:e>
- <m:sup>
- <m:r>
- <w:rPr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:rFonts w:ascii="Cambria Math" w:hAnsi="Cambria Math" /> 
  </w:rPr>
  <m:t>n-k</m:t> 
  </m:r>
  </m:sup>
  </m:sSup>
  </m:e>
  </m:nary>
  </m:oMath>
  </m:oMathPara>

**Comment by tomjebo** [comment]
@GuanRainy can you share the code you use to get to this point?

**Comment by tomjebo** [comment]
This works for me, perhaps you need to get past the initial `<p>`:
`            using (WordprocessingDocument package = WordprocessingDocument.Open(@"..\..\..\..\equation.docx", true))
            {
                // Assign a reference to the existing document body.
                Body body = package.MainDocumentPart.Document.Body;
                DocumentFormat.OpenXml.Wordprocessing.Paragraph para = body.GetFirstChild<DocumentFormat.OpenXml.Wordprocessing.Paragraph>();
                DocumentFormat.OpenXml.Math.Paragraph opara = para.GetFirstChild<DocumentFormat.OpenXml.Math.Paragraph>();
                int count = para.Descendants().Count();
                Console.WriteLine("Paragraphs in the body: {0}", count);
            }

`

**Comment by GuanRainy** [comment]
@tomjebo Thank you very much for your ! Your answer helped me solve the problem.
My OfficeMath should belong to the "DocumentFormat.OpenXml.Math.OfficeMath" type, and I mistakenly think that it is "DocumentFormat.OpenXml.Wordprocessing.OfficeMath", 
`para.Descendants<DocumentFormat.OpenXml.Wordprocessing.OfficeMath>.Count()` return 0.

My word2010 sample document has two OfficeMath formulas, they are "Inline" and "Display" type, where "Inline" type formula in the "DocumentFormat.OpenXml.Wordprocessing.Paragraph" instance of the "Run" region, and " Display "type formula in the" DocumentFormat.OpenXml.Math.Paragraph "instance, and" DocumentFormat.OpenXml.Math.Paragraph "in the" DocumentFormat.OpenXml.Wordprocessing.Paragraph "region.

**Comment by tomjebo** [comment]
@GuanRainy glad you figured it out.
