### ISSUE TITLE
Usage of branches unclear

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#177]
It's been a while since I made my last contribution and I see that a lot is going on right now, which is good. However, when I looked at the repo, I asked myself what I should actually use if I wanted to upgrade to the latest stable revision. I couldn't see a clear logic as to how branches are used, at least compared to how we intended to use master and vNext at the time vNext was introduced.

I actually proposed to add the vNext branch at the time. This was inspired by the libgit2sharp project. The vNext branch was meant to be the place for adding new features that would not yet be part of the official release. However, now it seems that the latest releases are all on vNext and master is very much behind. On the other hand, there was a recent merge into master that is not in vNext.

I've also just had a look at the libgit2sharp project to see where they are right now. My impression is that those guys have stopped using the vNext branch, possibly with a view to continuous integration. It seems they merge feature branches directly into master.

**Comment by tomjebo** [comment]
The merge is done so master is up to date now.

**Comment by ThomasBarnekow** [comment]
Thanks!
