### ISSUE TITLE
I can't download OpenXml Packges,how can I Dot

### ISSUE THREAD

**Issue by qinmeigui** [OfficeDev/Open-XML-SDK#179]

**Comment by qinmeigui** [comment]
[image](https://cloud.githubusercontent.com/assets/24547755/23987444/957bb24e-0a64-11e7-9688-f1b7e1ecc2d7.png)

**Comment by tarunchopra** [comment]
@qinmeigui : I'm pretty confident that you have downloaded wrong package; this package is hosted on myget and not on nugget. As taylor suggested; follow 'The Latest Builds' section in readme (https://github.com/OfficeDev/Open-XML-SDK#how-to-install-the-nuget-package) to get correct package.

**Comment by twsouthwick** [comment]
@qinmeigui Since the directions are on the README and there are other issues with examples, I'm going to close this. Please reopen with more details if you feel your issue has not been addressed.
