### ISSUE TITLE
Update the Readme.md to correctly reference VS 2015 

### ISSUE THREAD

**Issue by tomjebo** [OfficeDev/Open-XML-SDK#189]
Currently, Build Instructions says:

...
To build the Open XML SDK:

Clone the repo at https://github.com/OfficeDev/Open-XML-SDK
Open the solution using Visual Studio 2015. Community Edition of VS2015 works just fine.

That last line should say 2017, as we now have a requirement for 2017.

**Comment by tarunchopra** [comment]
This table too needs an update:

Table 1: The latest builds are available via a MyGet feed
Client
Feed URL
NuGet V3 (Visual Studio 2015+)
https://dotnet.myget.org/F/open-xml-sdk/api/v3/index.json

NuGet V2 (Visual Studio 2012+)
https://dotnet.myget.org/F/open-xml-sdk/api/v2

**Comment by tomjebo** [comment]
@tarunchopra I think for using the library it's ok
