### ISSUE TITLE
Build using Powershell-Script fails

### ISSUE THREAD

**Issue by michivo** [OfficeDev/Open-XML-SDK#19]
Building using the Powershell-script BldSdk.ps1 fails on my system with Nmake error u1095 (expanded command line too long).
System: Windows Server 2008 R2, Visual Studio Express 2012 for Windows Desktop

**Comment by tarunchopra** [comment]
@michivo: We are closing this issue as BldSdk.ps1 PS script is no longer a part of present code base.
