### ISSUE TITLE
Official Nuget package for .NET Core

### ISSUE THREAD

**Issue by Doff3n** [OfficeDev/Open-XML-SDK#191]
Do you have a roadmap on .NET Core support and are you planning to put .NET Core packages on Nuget anytime soon? Our conclusion is that #184 is awaiting to be merged before packages are released to Nuget.

The myget feeds work great for us so far, creating docx documents programatically

**Comment by twsouthwick** [comment]
.NET Core support has been available since November (see #111) and #184 is already merged. What's the specific need for NuGet support if MyGet is already working for you? We are working on getting a NuGet release, but someone has already taken the name and we're trying to get ahold of the publisher to take it over with official releases.

**Comment by robertmuehsig** [comment]
MyGet Feeds have the notion of "pre-release" stuff. I',m also waiting for an official NuGet release, because I want to avoid to manage custom feeds inside our dev-environment, especially if you provide a real NuGet.org hosted package it would be confusing and would require some "migration" work.

**Comment by twsouthwick** [comment]
We're working on getting the NuGet feed, but the MyGet feed is not prerelease (although it does contain some prerelease versions). @robertmuehsig have you tried just adding a NuGet.config file and adding the myget endpoint there? It's very lightweight and I haven't had any issues doing that for any of my projects. Are there other considerations you have in managing custom feeds?

**Comment by robertmuehsig** [comment]
@twsouthwick - I'm aware of the NuGet.config, but I try to avoid to point to "alpha" (or beta) channels. Most OSS projects I know use MyGet as "Alpha" channels and push to NuGet.org regularly as soon as it is stable enough. 
But to be clear: A MyGet feed is a good step in the right direction - currently we have tons of other work to do, so we can wait a little longer for the NuGet.org release ;)

**Comment by Bitmapped** [comment]
I'd like to see a NuGet feed as well. I have a NuGet package (OfficeFileProperties) that depends on OpenXML. Requiring users of my package to configure a MyGet package as well is unnecessarily messy.

**Comment by Will-Gregg** [comment]
We will be updating the readme shortly. But in the mean-time, interim builds are published to the MyGet feed and official releases are published to the NuGet feed: [https://www.nuget.org/packages/DocumentFormat.OpenXml/](url).

**Comment by Bitmapped** [comment]
Thank you for updating the NuGet feed.

**Comment by CZEMacLeod** [comment]
Yay for publishing to the NuGet feed
However, the (currently) published 'official release' version has the issue with the assembly version number (#200) and also has a different public key token - this means that anyone depending on the old package will have major headaches if someone updates to the newer package, or depends on 1 package that references 2.5.0 and another that references 2.7.x or higher.

**Comment by twsouthwick** [comment]
@CZEMacLeod 

- The version is fixed and will be available in the next release. @tomjebo can comment on when that might be
- Unfortunately, the key had to change as the previous key was not one we could make available publicly. In order to move the project to OSS and therefore have community involvement the decision was made to switch the key to one we could make public. Sorry for the difficulties this makes (I know from experience that this is very frustrating), but it won't need to change again.

**Comment by twsouthwick** [comment]
I'm going to close this as the releases are now available on NuGet.

**Comment by xrkolovos** [comment]
good job @twsouthwick

**Comment by CZEMacLeod** [comment]
@twsouthwick I was wondering about this signing key change bit - EF6 has been moved to opensource but has kept the original key. To allow using custom builds they have a delay sign and key bypass mechanism but keeping 'curated' releases with the original key.
[https://github.com/aspnet/EntityFramework6/wiki/Building-the-Runtime](https://github.com/aspnet/EntityFramework6/wiki/Building-the-Runtime)
`build /t:EnableSkipStrongNames`

> ** SkipStrongNames is required because the assemblies that are produced by building the open source code base are delay signed. Because the assemblies aren’t signed with the actual certificate we need to disable strong name verification for them. Delay signing ensures that the assemblies have the same strong name that they will have when signed with the Microsoft certificate and released on NuGet. Having the same strong name ensures products that build on top of Entity Framework (such as MVC Scaffolding) will work with open source builds.

**Comment by twsouthwick** [comment]
I started an internal thread to look into that option last week. With build, most of the team was busy, but hopefully we can get some traction on it this week.

Sent from my Windows 10 phone
