### ISSUE TITLE
Add print option to file templates.

### ISSUE THREAD

**Issue by wacked7c1a** [OfficeDev/Open-XML-SDK#193]
Doh.  I forgot to add an option to Word File Templates to print.  This could be a thing.  Totally I should do this tomorrow.  That may or may not be a thing you could do with OpenXML, but with automation it could work.

**Comment by twsouthwick** [comment]
I'm not clear on what you are asking. Are you seeing an issue with the SDK or are you requesting a feature?

**Comment by wacked7c1a** [comment]
I'm very sorry.  I had multiple GIT tabs open and I added something to your Issue Tracker that was intended for my own.

**Comment by twsouthwick** [comment]
:) No worries!
