### ISSUE TITLE
NuGet package for 2.7

### ISSUE THREAD

**Issue by jmhmaine** [OfficeDev/Open-XML-SDK#194]
What is the NuGet package for version 2.7.1? I only see the following listed:
https://www.nuget.org/packages/OpenXMLSDK-MOT/

This is at version 2.6.1.

**Comment by ThomasBarnekow** [comment]
@jmhmaine, please have a look at the [README](https://github.com/OfficeDev/Open-XML-SDK) (as shown on the main page of this repo). You will find links to **myget.org**, where the NuGet packages are hosted (i.e., not on **nuget.org**). If you are looking for version 2.7.1, you will end up [here](https://dotnet.myget.org/feed/open-xml-sdk/package/nuget/DocumentFormat.OpenXml/2.7.1).

**Comment by jmhmaine** [comment]
Thank you for the quick response @ThomasBarnekow. 
Is the new location of OpenXMLSDK-MOT that was on NuGet, or a different fork? 

Josh.

**Comment by ThomasBarnekow** [comment]
@jmhmaine, I don't know what "OpenXMLSDK-MOT that was on NuGet" is and I don't know anything about the package author's affiliation.

> Is this the new location of OpenXMLSDK-MOT that was on NuGet, or a different fork?

"This" is the official location of the Open XML SDK and nothing else. To my knowledge, the project never released a NuGet package on nuget.org but only on myget.org. Because a NuGet package was in high demand before this project released it on myget.org, other authors published packages based on this repo, i.e., either directly or indirectly based on a fork.

**Comment by jmhmaine** [comment]
Thank you for the clarification @ThomasBarnekow. I'm beginning to think that the OpenXMLSDK-MOT on NuGet was only added because it is a dependency for other packages, such as the one I'm using which is OpenXml Power Tools ( https://www.nuget.org/packages/OpenXmlPowerTools/ ). The issue I see is that this never gets updated from the official project, which appears to be yours. I also see the other dependency System.Management.Automation ( https://www.nuget.org/packages/System.Management.Automation/ ) is many versions behind the official current version.

I'll follow-up with the Eric White, the Author of the NuGet packages. Thank you.

**Comment by ThomasBarnekow** [comment]
While @EricWhiteDev is the author of the Open XML PowerTools and also maintained the Open XML SDK for a while, to my knowledge he did not author NuGet packages for these projects. This also led other people to author those NuGet packages that you can find on nuget.org.

You didn't actually need those NuGet packages in the past. You could have built those libraries from source. While the NuGet packages are certainly more convenient, if they are not the official ones and possibly not updated in a regular fashion, you don't really know what you get.

If you are primarily interested in the Open XML PowerTools, those now also use the NuGet packages published on myget.org. I even issued a pull request which updates the PowerTools to the latest one (albeit a CI build, if that is important for you to understand).

**Comment by jmhmaine** [comment]
@ThomasBarnekow, that makes sense. It seems the ideal would be to have the dependency reference the official Open XML SDK from the Repo.  I'm not sure if NuGet supports linking to another repo for dependencies, I haven't seen it before. Likely Open XML PowerTools would need to be hosted on MyGet and for the dependency to work. This assumes that MyGet supports the same dependency referencing that NuGet uses.

The only issue with MyGet hosting is that Visual Studio out of the box just references NuGet, so the average developer would need to setup the link to the MyGet repo. Not hard to do, just an extra step and it is much simpler than downloading source and compiling, if all you're interested in is the compiled library.

**Comment by twsouthwick** [comment]
When NuGet is finding packages, it doesn't care which feed an item is on; it will search all the feeds and then add them to your project. We've been working on adding a package to NuGet.org, but the ID is already taken, so we've been trying to figure out our next steps. Please see issue #191 for more details.

I'm going to close this as it's a duplicate ask for #191. Please feel free to comment there or reopen if you feel it is not a duplicate.
