### ISSUE TITLE
Standardize on style for code base

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#197]
Style feels inconsistent in the code base (or at least not what I'm used to). In either case, it would be good to define a set of conventions for what styles are, and then use StyleCop (I find the analyzers to work well) and editor config to enforce some of these (which is available in VS2017 and other editors as well).

I generally recommend projects follow the style used by CoreFX (https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md), but we can tweak it for this project if people have strong opinions one way or another.

Thoughts?

/cc @tomjebo @ThomasBarnekow 

Here's a list of analyzers I'm planning on turning on (subject to change). The text following the ID is what will trigger the analyzer. For details, look up the documentation at https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/Master/documentation

 ## Maintainability

- [x] **SA1119** A C# statement contains parenthesis which are unnecessary and should be removed.
- [x] **SA1400** The access modifier for a C# element has not been explicitly defined.
- [x] **SA1402** A C# code file contains more than one unique type.
- [x] **SA1403** A C# code file contains more than one namespace.
- [x] **SA1404** A Code Analysis SuppressMessage attribute does not include a justification.
- [ ] ~~**SA1405** A call to Debug.Assert in C# code does not include a descriptive message.~~
- [x] **SA1406** A call to Debug.Fail in C# code does not include a descriptive message.
- [x] **SA1410** A call to a C# anonymous method does not contain any method parameters, yet the statement still includes parenthesis.
- [x] **SA1411** An attribute declaration does not contain any parameters, yet it still includes parenthesis.
- [x] **SA1412** The encoding of the file is not UTF-8 with byte order mark.
- [x] **SA1413** A multi-line initializer should use a comma on the last item.

## Readability

- [x] **SA1100** A call to a member from an inherited class begins with base., and the local class does not contain an override or implementation of the member.
- [x] **SA1106** The C# code contains an extra semicolon.
- [x] **SA1107** The C# code contains more than one statement on a single line.
- [x] **SA1108** A C# statement contains a comment between the declaration of the statement and the opening brace of the statement. 
- [x] **SA1113** A comma between two parameters in a call to a C# method or indexer, or in the declaration of a method or indexer, is not placed on the same line as the previous parameter.
- [x] **SA1115** A parameter within a C# method or indexer call or declaration does not begin on the same line as the previous parameter, or on the next line.
- [x] **SA1116** The parameters to a C# method or indexer call or declaration span across multiple lines, but the first parameter does not start on the line after the opening bracket.
- [x] **SA1120** The C# comment does not contain any comment text.
- [x] **SA1121** The code uses one of the basic C# types, but does not use the built-in alias for the type.
- [x] **SA1122** The C# code includes an empty string, written as "".
- [x] **SA1125** The Nullable type has been defined not using the C# shorthand.
- [x] **SA1127** A generic constraint on a type or method declaration is on the same line as the declaration, within a C# code file.
- [x] **SA1129** A value type was constructed using the syntax new T().
- [x] **SA1130** An anonymous method was declared using the form delegate (parameters) { }, when a lambda expression would provide equivalent behavior with the syntax (parameters) => { }.
- [x] **SA1131** A comparison was made between a variable and a literal or constant value, and the variable appeared on the right-hand side of the expression.
- [x] **SA1132** Two or more fields were declared in the same field declaration syntax.
- [x] **SA1133** Two or more attributes appeared within the same set of square brackets.
- [x] **SA1134** An attribute is placed on the same line of code as another attribute or element. 
- [x] **SA1136** Multiple enum values are placed on the same line of code.
- [x] **SA1137** Two sibling elements which each start on their own line have different levels of indentation.
- [x] **SA1139** Use literal suffix notation instead of casting.

## Layout rules

- [ ] ~~**SA1500** BracesForMultiLineStatementsMustNotShareLine	The opening or closing brace within a C# statement, element, or expression is not placed on its own line.~~
- [x] **SA1501** StatementMustNotBeOnSingleLine	A C# statement containing opening and closing braces is written completely on a single line.
- [x] **SA1502** ElementMustNotBeOnSingleLine	A C# element containing opening and closing braces is written completely on a single line.
- [x] **SA1503** BracesMustNotBeOmitted	The opening and closing braces for a C# statement have been omitted.
- [x] **SA1504** AllAccessorsMustBeSingleLineOrMultiLine	Within a C# property, indexer or event, at least one of the child accessors is written on a single line, and at least one of the child accessors is written across multiple lines.
- [x] **SA1505** OpeningBracesMustNotBeFollowedByBlankLine	An opening brace within a C# element, statement, or expression is followed by a blank line.
- [x] **SA1506** ElementDocumentationHeadersMustNotBeFollowedByBlankLine	An element documentation header above a C# element is followed by a blank line.
- [x] **SA1507** CodeMustNotContainMultipleBlankLinesInARow	The C# code contains multiple blank lines in a row.
- [x] **SA1508** ClosingBracesMustNotBePrecededByBlankLine	A closing brace within a C# element, statement, or expression is preceded by a blank line.
- [x] **SA1509** OpeningBracesMustNotBePrecededByBlankLine	An opening brace within a C# element, statement, or expression is preceded by a blank line.
- [x] **SA1510** ChainedStatementBlocksMustNotBePrecededByBlankLine	Chained C# statements are separated by a blank line.
- [x] **SA1511** WhileDoFooterMustNotBePrecededByBlankLine	The while footer at the bottom of a do-while statement is separated from the statement by a blank line.
- [x] **SA1512** SingleLineCommentsMustNotBeFollowedByBlankLine	A single-line comment within C# code is followed by a blank line.
- [x] **SA1513** ClosingBraceMustBeFollowedByBlankLine	A closing brace within a C# element, statement, or expression is not followed by a blank line.
- [x] **SA1514** ElementDocumentationHeaderMustBePrecededByBlankLine	An element documentation header above a C# element is not preceded by a blank line.
- [x] **SA1515** SingleLineCommentMustBePrecededByBlankLine	A single-line comment within C# code is not preceded by a blank line.
- [x] **SA1516** ElementsMustBeSeparatedByBlankLine	Adjacent C# elements are not separated by a blank line.
- [x] **SA1517** CodeMustNotContainBlankLinesAtStartOfFile	The code file has blank lines at the start.
- [x] **SA1518** UseLineEndingsCorrectlyAtEndOfFile	The line endings at the end of a file do not match the settings for the project.
- [x] **SA1519** BracesMustNotBeOmittedFromMultiLineChildStatement	The opening and closing braces for a multi-line C# statement have been omitted.
- [x] **SA1520** UseBracesConsistently	The opening and closing braces of a chained if/else if/else construct were included for some clauses, but omitted for others.

**Comment by ThomasBarnekow** [comment]
@twsouthwick and @tomjebo, this sounds good. I am fine with those CoreFX guidelines.

I am using ReSharper to maintain consistency of code style and some of my style settings are thus based on ReSharper defaults. Those settings and preferences are still very close to the CoreFX style. However, I do a few minor things differently. I am highlighting those below to get your thoughts.

Commenting on the list on the page referenced by @twsouthwick above, in item 3 the rule is to "prefix instance fields with `_`, static fields with `s_` and thread static fields with `t_`". I just don't do use the `s_` and `t_` prefixes, probably because I don't need the distinction in what I am doing. For `static readonly` fields, I also use PascalCase, which is the ReSharper default I believe.

Secondly, I would format the following example from the first example file slightly differently.
```
    public ObservableLinkedList(IEnumerable<T> items)
    {
        if (items == null)
            throw new ArgumentNullException(nameof(items));

        foreach (T item in items)
        {
            AddLast(item);
        }
    }
```
While requiring braces after `for`, `foreach` etc. is totally fine by me, in those simple cases I would typically write:
```
    public ObservableLinkedList(IEnumerable<T> items)
    {
        if (items == null) throw new ArgumentNullException(nameof(items));

        foreach (T item in items)
            AddLast(item);
    }
```
Also note the if statement on just one line. Where I check multiple parameters for null, for example, the top of the method would look like this, if all if statements nicely fit on one line:
```
    public void DoSomething(string first, string second, string third)
    {
        if (first == null) throw new ArgumentNullException(nameof(first));
        if (second == null) throw new ArgumentNullException(nameof(second));
        if (third == null) throw new ArgumentNullException(nameof(third));

        ...
    }
```
I have come to find that more readable than the following:
```
    public void DoSomething(string first, string second, string third)
    {
        if (first == null)
            throw new ArgumentNullException(nameof(first));
        if (second == null)
            throw new ArgumentNullException(nameof(second));
        if (third == null)
            throw new ArgumentNullException(nameof(third));

        ...
    }
```
In general, where a simple if statement nicely fits in one line, I recently started putting it on one line rather than two. But in all cases, I keep lines of code that are close together consistent in layout. For example, in a series of if statements where you would put one of them on two lines, I'd put all of them in two lines.

Again, the proposed guidelines are fine by me as they are and would lead to a big improvement if those were applied consistently. The things I do differently are just a matter of personal taste. As a side note, I have done a good deal of reading on typography for my application, so I do see a lot of value in a consistent look and feel.

**Comment by twsouthwick** [comment]
I've added StyleCop to the code base and slowly started turning on a few whitespace normalizers. I'll keep this open to discuss any desired rules to be turned on (tracking in the original post). The thing I want to see out of these changes is not any specific style (those come in and out of fashion), but I do want to see consistency applied. These analyzers should help with that.

**Comment by ThomasBarnekow** [comment]
@twsouthwick No problem. And I don't feel strongly about the points I made above. If there are good rules that are widely adopted, I would be totally fine with those.

**Comment by twsouthwick** [comment]
These have all been enabled. Any further changes will be tracked by new issues.
