### ISSUE TITLE
Provide an official nuget package

### ISSUE THREAD

**Issue by davidanthoff** [OfficeDev/Open-XML-SDK#2]

**Comment by sgutkin** [comment]
If you cannot distribute binaries why not distribute *.csproj that allow for multi targeted builds?  and perhaps a post build operation to setup the Nuget package.   If you don't know what you're doing you'll burn half a day putting it altogether.  Perhaps you could even distribute a shell of a  xxx.nupkg  file to help folks.

**Comment by EricWhiteDev** [comment]
@sgutkin Unfortunately, in this area, I don't know what I'm doing, so prob will take a bit more than half a day!  :-)  Do you have any interest in putting together a post build operation to setup the Nuget package?  If you start with the vNext branch of Open-Xml-Sdk, and put together a pull request, I'll attend to it as soon as you submit it.  Then, when we have the Nuget package, I think that it is a small task to post the package, isn't it?

If you are open to doing this, would you kindly consider doing the same for Open-Xml-PowerTools?  It would be really super to have both projects on Nuget, and to have them updated on a regular basis.

Would it make sense to have a separate solution / project to put together the Nuget package?  Then, when we have a new release that we want to push to Nuget, it would be a simple process of building with this solution, and then uploading the Nuget package.

As I said, I am unfamiliar with all of the details of publishing via Nuget, so not clear about the best practices with this.  You certainly know better than me.  :-)

**Comment by gabisandor** [comment]
I managed to create a NuGet feed for my personal fork of this project using the steps described here: http://weblogs.asp.net/bsimser/automatically-publishing-nuget-packages-from-github. It seems to work fine, it's uploaded here: https://www.nuget.org/packages/GabiS.OpenXmlSdk/ (please don't use it, it's just for NuGet testing purposes, nothing official).

I can make a pull request with my changes, but they only include some updates in the build scripts and the .nuspec file needed for NuGet packaging. The rest of the steps will have to be performed by the original author and owner of the Open XML SDK GitHub repo (i assume Eric White), but they are quite well explained in the previous link. Let me know what you think.

**Comment by sergey-tihon** [comment]
I probably can help with it. 

It should be pretty simply if you are open to add dependency on [FAKE](http://fsharp.github.io/FAKE/) (I will use it to script build steps for Open-XML-SDK).

[Lots of OSS projects](http://fsharp.github.io/FAKE/users.html) already use FAKE and love it.

Release process can be as simple as run `build Release` in you console. We popularize this approach in [ProjectScaffold](https://github.com/fsprojects/ProjectScaffold).

@EricWhiteDev, your thought?

**Comment by gabisandor** [comment]
If this ever materializes officially, i would highly appreciate if all the assemblies published in the NuGet package were signed.

**Comment by anantu** [comment]
Isn't this "OpenXMLSDK-MOT" package official? It's by Microsoft Open Technologies Inc.

**Comment by accidentaldeveloper** [comment]
Can you please confirm whether the mentioned Nuget package is "official? It gives some appearances of being official, but I'm not confident that it is.

https://www.nuget.org/packages/OpenXMLSDK-MOT/

**Comment by EricWhiteDev** [comment]
Not official, but I have connected with Ranji Venkatesh, he is volunteering to keep them up to date.

**Comment by robertmuehsig** [comment]
This is official enough for me ;) - thanks! :+1:

**Comment by george-polevoy** [comment]
Unfortunately the mentioned above is not quite official enough for my company just yet, so we are building it locally for now, but would definitely switch to an official version as it's available.

Any movement in this direction yet?

**Comment by george-polevoy** [comment]
@EricWhiteDev
I am working on the nuspec files to contribute for the DocumentFormat and PowerTools. What is the version top up mechanism you are using?

I'm building vNext  515cbde73c03f330819f288bf8549057da4c1a0a
The version in the AssemblyInfo.cs is: 2.6.0.0

**Comment by EricWhiteDev** [comment]
@george-polevoy I didn't do the work to create that Nuget package.  I don't know what the best top up mechanism is.  I am happy to hear/take your recommendation.  If you put this together, then can we include it in the repo, in such a way that when we create a new release, we can easily update the NuGet package?

**Comment by george-polevoy** [comment]
@EricWhiteDev 
I discovered a dependency on System.IO.Packaging.
It seems it should go into another package.
Is it the original code base for System.IO.Packaging, or it's just a copy? Should we create a nuget package for it, or source it from somewhere else?

**Comment by sergey-tihon** [comment]
@george-polevoy I think the source code of `System.IO.Packaging` should be in another repo with separate release cycle and NuGet package

**Comment by kfertitta** [comment]
I'm glad to see the work going on here with the NuGet package development but wondering if as part of this we will address the issue with strong-naming these assemblies.  I've spent quite a bit of time charging down the same path as #60 with the exact same results.  I've also investigating using ILMerge to work around the issue, but it has trouble specifically with the case of resources referring to type names (which occurs in the schema validation areas of these assemblies, and likely elsewhere).

So, without strong-naming, I seem totally stymied and unable to use these wonderful tools.  How is it that other devs that also need to invoke these tools from their own strongly-named assembly are able to get past this?

**Comment by robertmuehsig** [comment]
I would strongly recommand you to stop the strong-naming stuff, because it is basically useless for most use cases, but I don't want to start a new discussion on "pro/contra strong-naming", because there are tons of discussions on this topic out there. (e.g. [here](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md))

**Comment by kfertitta** [comment]
Yeah, don't want to start that discussion either, as I'm very familiar with all of the arguments -- most of them simply ignore reality in one sense or the other.  The v2.5 SDK was strongly named, so I suspect v3.0 will eventually be if it's to be part of the framework.  As such, is that going to cause a problem for you in your app to the extent you'll continue to build and deploy from the GitHub repo?  I'm guessing "no", and that commercial apps will want to use the official bits.  So, if it's not going to cause a problem for folks when released, why not strong name them now and enable a whole class of other users to work with these bits now?  Not strong naming seems to unnecessarily exclude those ("useless" - I think you called them) use cases, while providing no real benefit to the (presumably "useful") use cases that don't need them.

**Comment by robertmuehsig** [comment]
Currently we use a very unofficial NuGet package (http://www.nuget.org/packages/DocumentFormat.OpenXml/) for our commercial app, but other companies have other rules, so a first step would be a NuGet package build from this repo.

**Comment by kfertitta** [comment]
Hi Robert,

Thanks for the reply.  Indeed, getting a NuGet package together, even if it's just for our own private use, is the right way to go.  The difficulty is in building the source with a string name.  There are some binary resources used for some of the schema validation stuff that seem to have assembly references in them, and those assembly references will not resolve when you build the repo with your own private key.  I'm assuming you guys didn't strongly name, or did you somehow get around the resource assembly reference stuff?

**Comment by robertmuehsig** [comment]
Nope, we started some years ago and tried to strong name our stuff, but then we took dependencies on other libraries (mostly OSS) - first we cloned the code and signed it with our own cert, but it was pretty complicated and the whole strong naming discussion lead us to our current "don't use strong naming at all"-policy.

**Comment by kfertitta** [comment]
Gotcha.  Yeah, you can do that if you control the whole stack.  Sadly, for our current application, we don't.  Have to comply with some official specs that require use of the GAC, policy file versioning, etc.  So, we have to deal with strong names.  For now, I'm having to fallback to v2.5 to get any of our codegen working, but I'll want to be using the HtmlConverter, which relies on the newer stuff.  So, I'm gonna be totally stuck at that point.  Perhaps an official v3.0 release will be out soon?

**Comment by gabisandor** [comment]
Hi everyone.

Just as a reminder for anyone wanting to grab the code and sign the assemblies themselves, with their own key, this is achievable but first you have to change line 305 in SimpleTypes.cs from FormatterAssemblyStyle.Full to FormatterAssemblyStyle.**Simple**. See https://github.com/OfficeDev/Open-XML-SDK/issues/60 for more details.

**Comment by kfertitta** [comment]
Ah, yes, I missed that Update 2 portion.  This is definitely in the bit of code that was causing an issue (hopefully the last).  I'll give that a try.  As the OP points out, however, a signed NuGet package really would enable more folks to work with the tooling more easily.  Thanks again for your assistance here.

**Comment by robertmuehsig** [comment]
@EricWhiteDev @sergey-tihon @george-polevoy The [current NuGet package](https://www.nuget.org/packages/OpenXMLSDK-MOT/) ships with System.IO.Packaging.

As far as I know, the System.IO.Packaging stuff will end up in the .NET Core FX - so in the future there will be a seperate package, right?
In the mean time, we could build a NuGet package, which contains the System.IO.Packaging dll and the OpenXml dll, right?

**Comment by sergey-tihon** [comment]
NuGet package creation was automated in #82 (without signing)

**Comment by george-polevoy** [comment]
@EricWhiteDev @robertmuehsig 

I'm proposing movement to a separate repo for System.IO.Packaging and making it a nuget package, as @sergey-tihon suggests.

Please have a look at the experimental
https://github.com/george-polevoy/System.IO.Packaging - a repository split for SIP
https://github.com/george-polevoy/Open-XML-SDK (would issue a pull request if the above adopted officially)

The repository split is accomplished with a single git branch filtering command and then adding a new solution for System.IO.Packaging.

When a .NET Core FX package is ready, this additional repository could be dropped for the good.

The build process is set up entirely in appveyor web UI.
This way the repositories are clean from the build process stuff which is good for those forking your opensource repositories. It requires just the solution and a .nuspec file in the repository.

Following are the nuget feed sources of the temporary appveyor project:
https://ci.appveyor.com/nuget/system-io-packaging-9b35uvcur80a
https://ci.appveyor.com/nuget/open-xml-sdk-j15tlagy3kof

You can try to add those as nuget package sources and run:
Install-Package Open-XML-SDK -Version 2.6.1-alphaAAA2 -Pre

It's just a preliminary work, a finished setup would include pushing the packages to the nuget.org feed.
Another approach would be just downloading from appveyor artefacts and uploading to nuget.org manually, which is not a big deal.

To initiate an appveyor build with the proposed process is as follows:
push a new branch according to a semver 1.0.0 spec:
For example:
release/v2.6.1-alpha - for a prerelease
release/v2.6.1 - for a production release.
The resulting package would have the versions:
v2.6.1-alpha{build}
v2.6.1.{build}
See also:
http://semver.org/spec/v1.0.0.html

This allows for both pre-release and release versioning.
Let me know if this approach is good enough for you. I can hand over all the details.

**Comment by george-polevoy** [comment]
@EricWhiteDev @robertmuehsig @sergey-tihon 
I have summarized what I'm proposing in [Publishing a .NET project with Appveyor and NuGet](http://few-lines-of-code.blogspot.com/2016/03/publishing-net-project-with-appveyor.html) on my [Few Lines of Code](http://few-lines-of-code.blogspot.com) blog.

**Comment by avishnyakov** [comment]
+1, 2.6 not in the NuGet, only source code in the release, seriously?

**Comment by TsengSR** [comment]
Yes, please please please add nuget packages to official nuget feeds!

**Comment by lostincomputer** [comment]
+1 Our company has a policy of only using signed libraries so it would be really great if Microsoft releases an official Nuget package where the libraries are signed.

**Comment by tomjebo** [comment]
@lostincomputer Yes, we are currently working on that. Thanks for the feedback!

**Comment by twsouthwick** [comment]
@lostincomputer By signed are you referring to authenticode signed or strong name signed? Authenticode provides security benefits, while strong name doesn't. Currently, the story for strong name signing is still being worked out.

**Comment by lostincomputer** [comment]
@twsouthwick strong-named assembly

**Comment by twsouthwick** [comment]
@lostincomputer That is known (see #134) and we are working to figure that out.

**Comment by tomjebo** [comment]
The package is being built and currently available on myget feed (see the readme). The strong naming is being tracked by #134. Closing.
