### ISSUE TITLE
DLL Version Number in Nuget packages does not match package

### ISSUE THREAD

**Issue by CZEMacLeod** [OfficeDev/Open-XML-SDK#200]
I would have expected the AssemblyVersion for the released nuget package V2.7.1 to be 2.7.1.0 but it is 0.0.1.0
I see there are build scripts that should set this, but the packages pushed to myget all seem to have the 'hardcoded' value of either 2.6.0.0 or 0.0.1.0.
```
DocumentFormat.OpenXml, Version=0.0.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17
DocumentFormat.OpenXml, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null
```

**Comment by twsouthwick** [comment]
Good catch! This should be fixed ASAP
