### ISSUE TITLE
Wrong AssemblyVersion

### ISSUE THREAD

**Issue by TeaDrivenDev** [OfficeDev/Open-XML-SDK#202]
The AssemblyVersion attribute is not set correctly in the NuGet package for version 2.7.1; it is set to 0.1.0.0, which is a bit odd when setting binding redirects from an older version with a correct version.

**Comment by CZEMacLeod** [comment]
I think this has already been addressed in issue #200 that I raised and was fixed with #201.
Although I think this build has a different key from the one published previously on nuget.org as V2.5.0 so you can't use binding redirects for that version.

**Comment by twsouthwick** [comment]
Yes sorry for the version - it was working at some point but we apparently didn't check when we actually released it since the NuGet version was correct. I'm closing this issue as it has been fixed.
