### ISSUE TITLE
Issue with listnumber track changes

### ISSUE THREAD

**Issue by ManoharRT** [OfficeDev/Open-XML-SDK#203]
Hello,

I have turned on the track changes(Revisions) option in word and made some changes and found all the track changes were being tracked and found all track changes in the openxml content. but i am not seeing the deleted listnum value in openxml content and the listnum values are continued from the next paragraph. so how can I track/get the deleted listnum value in openXml.

For example- If I delete 2 list number after turning on track changes, now list number 3 becomes 2 and so I am not able to get the deleted value 2 in second paragraph.
       

1.        Test Paragraph1
2.        Test Paragraph2
3.        Test Paragraph3

I am curently using OPenxmlPowerTools to process the word document.

Thanks 

Manohar

**Comment by tarunchopra** [comment]
Please post this to : https://github.com/OfficeDev/Open-Xml-PowerTools/issues to get traction.
