### ISSUE TITLE
Could not load file or assembly DocumentFormat.OpenXml

### ISSUE THREAD

**Issue by gilbertovalente1976** [OfficeDev/Open-XML-SDK#206]
Hi,

I update the openxml to the last version (2.7.1 via Nuget), and my project stop work.

Error:
"An exception of type 'System.IO.FileLoadException' occurred in portal.dll but was not handled in user code.

Could not load the file or assembly 'DocumentFormat.OpenXml, Version = 2.5.5631.0, Culture = neutral, PublicKeyToken = 31bf3856ad364e35' or one of its dependencies. The definition of the localized assembly manifest does not match the assembly reference. (Exception from HRESULT: 0x80131040)"

Cumps.
Gilberto Valente

**Comment by FindAirin** [comment]
When I download the DLL via Nuget manager, the version is 0.0.1.0.

**Comment by gilbertovalente1976** [comment]
It's strange. In the references properties the dll "Description" is Open XML Format SDK 2.7 but the Version is 0.0.1.0
You have the same issue???

Cumps.
Gilberto Valente

**Comment by CZEMacLeod** [comment]
See comments in #200, #201 and #202
Also be careful as the public key token has changed so binding redirects won't work and you cannot mix packages dependant on 2.5 with code dependant on 2.7+

**Comment by tomjebo** [comment]
@gilbertovalente1976 @CZEMacLeod you're right these are fixed #200, @201, and @202. Since these are breaking changes we will tag a new release.

**Comment by Djblois** [comment]
Hi, I was wondering how we can fix this for now? or do you have a new version coming out? I cannot run my project.

**Comment by daggmano** [comment]
Please release an update to NuGet ASAP as this is a critical issue.  I understand the issue has been resolved but a release is required to fully resolve.

**Comment by tomjebo** [comment]
@gilbertovalente1976 we're pushing the package to nuget.org today.

**Comment by tomjebo** [comment]
@daggmano the version fix is in the 2.7.2 nuget.org package  [https://www.nuget.org/packages/DocumentFormat.OpenXml](url).

**Comment by AKrasheninnikov** [comment]
Hi all, 

Now getting the following strange issue. 2.7.2 is installed by ClosedXML 0.94.2, but something tries to load 2.9.1.

'Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.9.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

FileLoadException: Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by hDrummer** [comment]
> 
> 
> Hi all,
> 
> Now getting the following strange issue. 2.7.2 is installed by ClosedXML 0.94.2, but something tries to load 2.9.1.
> 
> 'Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.9.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
> 
> FileLoadException: Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

The same problem.
How to fix it?

**Comment by hDrummer** [comment]
Ok, the way to fix this issue lies in correcting the app.config file.

Change this section to:
<assemblyIdentity name="DocumentFormat.OpenXml" publicKeyToken="8fb06cb64d019a17" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-**2.7.2.0**" newVersion="**2.7.2.0**" />
      </dependentAssembly>

**Comment by AKrasheninnikov** [comment]
That's right. In our case there was a design limitation as well for the consumer's application domain, it could not use the adjacent dll.config at all, all binding redirect instructions had to be loaded from a different location's config file.

**Comment by Th3AnG3L** [comment]
with last version has same result when i run the app on another computer...

**Comment by twsouthwick** [comment]
If you can't set the binding redirect for some reason, you can hook into `AppDomain.ResolveAssembly` event and load it that way. Thankfully, this is a non-issue on core, but still a thing for version differences on framework.

**Comment by evlo** [comment]
> with last version has same result when i run the app on another computer...
with older version it is ok?

**Comment by evlo** [comment]
it is looking for Version=2**.8.1**.0
but the version is 2 **18**

wtf?

**Comment by twsouthwick** [comment]
@evlo  Have you tried the fixes discussed in the issue? Please give more context and open a new issue instead of commenting on an old (and closed) issue.

As @hDrummer said above,

> Ok, the way to fix this issue lies in correcting the app.config file.
> 
> Change this section to:
> 
> ```
> <assemblyIdentity name="DocumentFormat.OpenXml" publicKeyToken="8fb06cb64d019a17" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-2.7.2.0" newVersion="2.7.2.0" />
>       </dependentAssembly>
> ```
> 
> Don't forget to check publicKeyToken value.

That `newVersion` field should be updated to whatever version you are actually shipping (i.e. the version you have in the output).

@evlo

> with older version it is ok?

Not sure what you mean by this, but the project follows [Semantic Versioning](https://semver.org/) so you can use a later version of 2.x, but not an earlier one than any of your dependencies.
