### ISSUE TITLE
Can't load any of the csproj's files from this solution after cloning it 

### ISSUE THREAD

**Issue by joviledog** [OfficeDev/Open-XML-SDK#207]
I got the following errors trying to open the sln after cloning the project.

C:\Users\Andy\Source\Repos\Open-XML-SDK\DocumentFormat.OpenXml\DocumentFormat.OpenXml.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Andy\Source\Repos\Open-XML-SDK\DocumentFormat.OpenXml\DocumentFormat.OpenXml.csproj

C:\Users\Andy\Source\Repos\Open-XML-SDK\DocumentFormat.OpenXml.Tests\DocumentFormat.OpenXml.Tests.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Andy\Source\Repos\Open-XML-SDK\DocumentFormat.OpenXml.Tests\DocumentFormat.OpenXml.Tests.csproj

C:\Users\Andy\Source\Repos\Open-XML-SDK\BinaryFormatConverter\BinaryFormatConverter.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Users\Andy\Source\Repos\Open-XML-SDK\BinaryFormatConverter\BinaryFormatConverter.csproj

**Comment by tarunchopra** [comment]
Are you opening it with VS 2017?

**Comment by joviledog** [comment]
No, just using VS 2015

**Comment by ThomasBarnekow** [comment]
VS 2015 is no longer supported. While the README.md does not say that directly, the build instructions say that you must open the project with one of the tools that support the latest formats. This includes VS 2017 and other tools, but not VS 2015.

You can use the NuGet package if you don't need to build from source, though.

**Comment by twsouthwick** [comment]
This is by design and is documented in the README that you need VS2017 to build. If you feel the docs don't explain it well enough, please reopen and submit a PR!
