### ISSUE TITLE
File version probably not correct

### ISSUE THREAD

**Issue by JoGillis** [OfficeDev/Open-XML-SDK#208]
When using the 2.7.1 nugget package we get a dll with product version 2.7.1, but the file version is 0.0.1.0, which is way lower than  the file version of the dll in the 2.5 sdk released by Microsoft. This may break some update mechanisms.

**Comment by CZEMacLeod** [comment]
See #200, #201, #202 for discussion on this.

**Comment by twsouthwick** [comment]
This is fixed now and uploaded to NuGet.org. May take a little bit of time for it to show up.

**Comment by twsouthwick** [comment]
btw - you'll want the 2.7.2 release to get the fix
