### ISSUE TITLE
how to get ChartData from an existed ChartPart

### ISSUE THREAD

**Issue by khspace** [OfficeDev/Open-XML-SDK#209]
Can I get ChartData from an existed ChartPart?

**Comment by ThomasBarnekow** [comment]
@khspace, GitHub issues are not the right way to ask how-to questions. Please post this to stackoverflow.com.

**Comment by twsouthwick** [comment]
@khspace As @ThomasBarnekow stated, this tracker is for product issues. Please ask your question on stackoverflow
