### ISSUE TITLE
Convert openxml document to xps, pdf,images and html format

### ISSUE THREAD

**Issue by mojtabakaviani** [OfficeDev/Open-XML-SDK#21]
please add capability to openxml document that allow convert pages to other format such as xps, pdf, png, jpg, and html. maybe not convert to pdf but I think images, xps and html format not limitation.

**Comment by softboy99** [comment]
we need it also without using automating the Office client

**Comment by Vijay-Nirmal** [comment]
Using office interop in server environment is very bad idea since it create new word instance for every request. Depend upon load this will become costly operation.

**Comment by softboy99** [comment]
> Using office interop in server environment is very bad idea since it create new word instance for every request. Depend upon load this will become costly operation.

agree,+1

**Comment by softboy99** [comment]
Hi,
Microsoft is also doesn't suggest using office interop in server side but doesn't give solution.
https://support.microsoft.com/en-us/topic/considerations-for-server-side-automation-of-office-48bcfe93-8a89-47f1-0bce-017433ad79e2.
In the above link,

>

Most server-side Automation tasks involve document creation or editing. Office 2007 supports new Open XML file formats that let developers create, edit, read, **and transform file** content on the server side. These file formats use the System.IO.Package.IO namespace in the Microsoft .NET 3.x Framework to edit Office files without using the Office client applications themselves. This is the recommended and supported method for handling changes to Office files from a service.

There is "transform file content" in the above article. The Open XML file formats are a public standard. The PDF file format is also a public standard. There're also iText library to read/write PDF.  So it is so strange, Why this feature is missing?

**Comment by tomjebo** [comment]
@softboy99, thanks for posting here. PDF conversion as well as others is a much heaver feature and as was stated at the beginning of this thread, considered out of scope. The "transform file content" mentioned in the article is a broad phrase that covers a lot of ground. A server side implementation that consumes the Open XML SDK can also consume additional libraries to accomplish this.

**Comment by softboy99** [comment]
Hi，@EricWhiteDev， it‘s turn out to your Powerbility of  [Open-XML-PowerTools](https://github.com/OpenXmlDev/Open-Xml-PowerTools).

**Comment by Snailya** [comment]
Same needs for converting a openxml document into pdf, images or html

**Comment by pugwonk** [comment]
Folks, this is like going onto an Unreal Engine forum and saying a good feature for the platform would be Fortnite...
