### ISSUE TITLE
DocumentFormat.OpenXml on NuGet.org

### ISSUE THREAD

**Issue by JaredShaver** [OfficeDev/Open-XML-SDK#210]
It looks like the DocumentFormat.OpenXml package is now on NuGet.org.  The readme could be updated with the instructions for using the package there instead of the MyGet feed workaround.

**Comment by tomap** [comment]
Link to the nuget: https://www.nuget.org/packages/DocumentFormat.OpenXml/ :)

**Comment by twsouthwick** [comment]
Good point!

**Comment by tomjebo** [comment]
@JaredShaver @tomap take a look at the [README.md](https://github.com/OfficeDev/Open-XML-SDK/blob/vNext/README.md)
