### ISSUE TITLE
VBA Range.xml and place to Opendocumentxml

### ISSUE THREAD

**Issue by nithinshiriya** [OfficeDev/Open-XML-SDK#211]
We have an application that collects part of data using VBA  range,.xml. 

Now, I want to place that XML string into another document using DocumentFormat.OpenXml. 

Any idea how can I do that.

Thanks,
Nitheen

**Comment by twsouthwick** [comment]
@nithinshiriya Yes it is possible. Please ask your question on StackOverflow as this tracker is meant for product issues.
