### ISSUE TITLE
New packages?

### ISSUE THREAD

**Issue by EatonZ** [OfficeDev/Open-XML-SDK#216]
Hello, upgrading via NuGet from 2.7.1 to 2.7.2 is wanting to install 2 new packages. What is the purpose of these assemblies? I try to keep my application slim and don't want these if they aren't required.
![1](https://user-images.githubusercontent.com/3020941/27249624-fd7ec522-52e7-11e7-9128-688eb689e1d7.png)

**Comment by tomjebo** [comment]
@EatonZ you should refer to [readme section on System.IO.Packaging](https://github.com/OfficeDev/Open-XML-SDK#windowsbase-or-systemiopackaging). We do need this to resolve some issues.

**Comment by EatonZ** [comment]
I see - thank you.
