### ISSUE TITLE
What is the status of OpenXmlPackage.Save?

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-XML-SDK#217]
The power tools reference `OpenXmlPackage.Save`. I've gotten a Nuget build that has it uncommented with different logic. I'm not sure where that is coming from.

**Comment by ThomasBarnekow** [comment]
@daniel-white, Could you be a little more specific? Which part (class, method) of the PowerTools reference the `OpenXmlPackage.Save()` method and which NuGet build of what has it uncommented with different logic?

I first contributed the save-and-clone functionality in January 2015 (see 06fa235) and the OpenXmlPackage class still has my Save() method (with later enhancements):
```
        /// <summary>
        /// Saves the contents of all parts and relationships that are contained
        /// in the OpenXml package, if FileOpenAccess is ReadWrite.
        /// </summary>
        public void Save()
        {
            ThrowIfObjectDisposed();
            if (FileOpenAccess == FileAccess.ReadWrite)
            {
                lock (_saveAndCloneLock)
                {
                    SavePartContents();
                    // TODO: Revisit.
                    // Package.Flush();
                }
            }
        }
```
However, I also just found a few lines of code in which a previous `Save()` method was commented out. That is likely the source of the confusion and those commented-out lines should be removed.

That current `Save()` method works just fine in production code (and I might have even written the part of the PowerTools that references that method).

**Comment by daniel-white** [comment]
Thanks @ThomasBarnekow. I must have had a bad version referenced somewhere in the powertools. My CTRL+F foo must have been lacking. I pointed the PowerTools vNext at the SDK's 2.7.2 and it seems to be working. The powertools needs help IMO w/ referencing *this* project.
