### ISSUE TITLE
ExtendedFilePropertiesPart.Properties.Pages.Text returns incorrect value

### ISSUE THREAD

**Issue by JernejJerin** [OfficeDev/Open-XML-SDK#22]
I am using the following code to open WordprocessingDocument from MemoryStream and then get the page size of the document, but it always returns the value 1, which is incorrect as the document contains 11 pages.

```cs
using (WordprocessingDocument myDoc = WordprocessingDocument.Open(reportDocumentStream, false))
{
    pages = int.Parse(myDoc.ExtendedFilePropertiesPart.Properties.Pages.Text);
}
```

**Comment by EricWhiteDev** [comment]
That value is not guaranteed to be correct.  In fact, it often will be incorrect.  This is one of the issues with Open XML - determining pagination is a big job.  (This is true for other document formats, including ODF, not just XML.)  Currently, Microsoft's advice is that if you need exact pagination information, you should automate Word.
