### ISSUE TITLE
Extracted excel file does not open!

### ISSUE THREAD

**Issue by ejapuk** [OfficeDev/Open-XML-SDK#220]
Using OpenXML to find embedded files and exporting them to the working directory. I followed the example given [in msdn example](https://code.msdn.microsoft.com/CSOfficeDocumentFileExtract-e5afce86/sourcecode?fileId=65214&pathId=1944795283). excerpt of the code given below.
`private void ReadWriteStream(Stream readStream, Stream writeStream)
{ 
    int Length = 256; 
        Byte[] buffer = new Byte[Length]; 
        int bytesRead = readStream.Read(buffer, 0, Length); 
        // write the required bytes 
        while (bytesRead > 0) 
        { 
            writeStream.Write(buffer, 0, bytesRead); 
            bytesRead = readStream.Read(buffer, 0, Length); 
        } 
        readStream.Close(); 
        writeStream.Close(); 
    }` 
The file got created. The Bytes of the original and the file that got extracted differ by few Bytes. The extracted file is not getting opened in the excel application. Neither does it throw any errors. When i try the same with macro enabled excel, i'm able to open the VBA developer and it shows the macro and the sheets are present in the VBA developer. But the sheets are not shown open in the excel application. Is there any byte offset required?

edit:
This issue is present only when the document has track changes turned on and the document object was inserted after the enabling the track changes option. Accepting the changes also does not work. However the objects inserted prior to turning on the track changes option get extracted without any data corruption.

**Comment by tomjebo** [comment]
@ejapuk this appears to be more of a straight Office Open XML packaging question vs the OpenXML SDK which isn't involved in what you're doing. I did a quick test using the same code from that sample (which is very simple) and it does very cleanly extract the embedding parts and write them to a file. There's nothing wrong with this code. One problem you may be having which I also noticed, is that the following is set in the .xlsx embedded in my test .docx file:

`    <bookViews>
        <workbookView visibility="hidden" xWindow="0" yWindow="0" windowWidth="21570" windowHeight="8925" activeTab="1" xr2:uid="{0C2F8079-B5BF-4D38-AC07-582BEFCE3483}"/>
    </bookViews>`

Notice that visibility is set to "hidden". I believe this is Word behaviour for an embedding. I changed this value to "visible" and the worksheet properly displayed in Excel after extraction.
I don't know if that's what you're hitting but possibly this is it.

**Comment by ejapuk** [comment]
Thank you @tomjebo. After extracting the excel file I replaced the value of visibility from "hidden" to null during run time using open xml sdk itself. Now the extracted file has the sheets visible. Thanks for the tip.
