### ISSUE TITLE
How to generate a Table of Contents (TOC)

### ISSUE THREAD

**Issue by sanathjs** [OfficeDev/Open-XML-SDK#223]
As per MSDN forum link below i get to know that still there is no way in generating a Table of Contents as per sdk 2.0 but is it updated in 2.7 can we generate TOC in 2.7 i couldn't find it.

https://social.msdn.microsoft.com/Forums/office/en-US/19032efe-80af-4a16-b954-1f5a6d2f2236/open-xml-sdk-v2-faq-part-1?forum=oxmlsdk#x_Q7

**Comment by robertmuehsig** [comment]
I guess not, because you need a "renderer" for this kind of stuff. There are some libraries (e.g. from SyncFusion, but you need a license for that) that may help you.

**Comment by tomjebo** [comment]
@sanathjs per the link you provided, probably your best option would be to use Word automation in conjunction with Open XML SDK to accomplish this. In case you haven't seen it yet, Eric's blog and video here should help: 
[http://ericwhite.com/blog/2011/08/22/fourth-and-final-screen-cast-in-series-on-addingupdating-the-toc-in-openxml-wordprocessingml-documents/](url)
