### ISSUE TITLE
Open sourcing the Productivity Tool?

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-XML-SDK#225]
Would it be possible to get the Productivity Tool open sourced? There's plenty of things I would love to improve it.

**Comment by twsouthwick** [comment]
Are you referring to [Open XML Package Editor Power Tool for VS](https://github.com/OfficeDev/Open-XML-Package-Editor-Power-Tool-for-Visual-Studio) or [OpenXML Power Tools](https://github.com/OfficeDev/Open-Xml-PowerTools)? Both of those are open source

**Comment by daniel-white** [comment]
Neither of those. This is the one
![image](https://user-images.githubusercontent.com/735269/29471396-df7cfe06-841d-11e7-9e27-d118d8f41f45.png)

**Comment by twsouthwick** [comment]
Ah - @tomjebo would know more about that.

**Comment by tomjebo** [comment]
@daniel-white currently we don't have any plans for open sourcing that tool but thanks for the suggestion. We will consider it.

**Comment by glenn-slayden** [comment]
I'd like to add my vote for open-sourcing the **Document Editor** executable from the **_"Open XML SDK v2.5 Productivity Tool for Office"_**.

Until such time as such is possible, is [this](https://www.microsoft.com/en-us/download/details.aspx?id=30425) the latest available binary version? Having date 11/20/2012, it seems quite old.

**Comment by andreykhr** [comment]
And my vote too. I wana port that tool to OS X. Or may be u do that job?. After dotnet core i think it not too hard. UI part is quite simple (may be WEB?).

two votes from me)))

**Comment by rmboggs** [comment]
FYI - I got tired of waiting and started working on a new class library project that would provide the same features as the productivity tool. It's still very early in development but I was able to "codify" a simple Excel workbook in both C# and VB.NET. Having trouble with PowerPoint files at the moment. I will try to create a new github repo for this project within the next couple of weeks if anyone is interested.

**Comment by rmboggs** [comment]
Next couple of weeks?  I meant a couple of years. 

If there is still interest in this, I finally have working code that will generate source code for openxml based documents.  It is still considered alpha status but I've been able to recreate documents using the generated code without errors so it's definitely working.

Project is here for those who want to check it out. [Serialize.OpenXml.CodeGen](https://github.com/rmboggs/Serialize.OpenXml.CodeGen).
