### ISSUE TITLE
NullReferenceException when setting PackageProperties entry on .NET Standard 2.0

### ISSUE THREAD

**Issue by igitur** [OfficeDev/Open-XML-SDK#235]
I'm working on building a .NET Standard 2.0 version of [ClosedXML](http://github.com/ClosedXML/ClosedXML)

I'm experiencing a `System.NullReferenceException` exception with the following piece of code when I run it against `netcoreapp2.0`. When I run it against `net452` or `net461`, I don't experience the exception. 

In all cases I reference `DocumentFormat.OpenXml` version `2.7.2`.
For `net461` and `netcoreapp2.0` I reference `System.IO.Packaging` version `4.4.0`. For `net452` I reference `WindowsBase`.

```c#
using (var document = SpreadsheetDocument.Open ("test.xlsx", true)) 
{
    document.PackageProperties.Creator = null;
}
```
The stack trace is:
```
Failed   SetPackagePropertiesEntryToNullWithOpenXml
Error Message:
 System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at System.IO.Packaging.PartBasedPackageProperties.SerializeDirtyProperties()
   at System.IO.Packaging.PartBasedPackageProperties.Flush()
   at System.IO.Packaging.Package.System.IDisposable.Dispose()
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose(Boolean disposing)
   at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Dispose()
   at ClosedXML_Tests.OpenXMLTests.SetPackagePropertiesEntryToNullWithOpenXml() in C:\dev\ClosedXML\ClosedXML_Tests\OpenXMLTests.cs:line 17
```

The exception occurs when setting any of the `PackageProperties` entries except:
`.Created`, `.Modified` and `.LastModifiedBy`.

I don't think the issue is related to the specific .xlsx file. I experience the exception for any file, but I attach the file anyway.
[test.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/1236364/test.xlsx)

**Comment by kenleese** [comment]
@igitur a workaround: when attempting to delete a property (by setting its value to null) first ensure the property exists.
`if (author == null) document.PackageProperties.Creator = "";`
`document.PackageProperties.Creator = author;`

**Comment by igitur** [comment]
@kenleese Thanks, the workaround works. Never thought to try that myself.

**Comment by twsouthwick** [comment]
I'm going to close this issue on the OpenXML side. I've submitted a fix to CoreFx for the issue @kenleese found and progress can be tracked there. I'm glad there was an easy work around!
