### ISSUE TITLE
It convert math formulas, SmartArt, or DrawingML drawings to image.Is it feasible?

### ISSUE THREAD

**Issue by iopzxc** [OfficeDev/Open-XML-SDK#237]
hi , I want It convert math formulas, SmartArt, or DrawingML drawings to image . Is it feasible?
When using it to convert to HTML

**Comment by twsouthwick** [comment]
This library does not provide that functionality. I believe you should look at the [OpenXmlPower tools](https://github.com/OfficeDev/Open-Xml-PowerTools)
