### ISSUE TITLE
How to generate unique paraid in word openxml?

### ISSUE THREAD

**Issue by arun-newgen** [OfficeDev/Open-XML-SDK#245]
<w:p w14:paraId="09868DD9" w14:textId="434C9D2D" w:rsidR="00A65BB5" w:rsidRPr="003D4286" w:rsidRDefault="00DD267D" w:rsidP="00DD267D">
            <w:pPr>
                <w:pStyle w:val="prelimhead"/>
            </w:pPr>
            <w:bookmarkStart w:id="0" w:name="_Toc4"/>
            <w:r w:rsidRPr="003D4286">
                <w:t>Author’s Note</w:t>
            </w:r>
            <w:bookmarkStart w:id="1" w:name="_GoBack"/>
            <w:bookmarkEnd w:id="0"/>
            <w:bookmarkEnd w:id="1"/>
        </w:p>

**Comment by tomjebo** [comment]
@arun-newgen The SDK doesn't have a specific function for this but any implementation adding a paragraph that has this attribute can simply generate the unique id per this [MS-OI29500] note:

2.6.2.3 paraId
Target namespace: http://schemas.microsoft.com/office/word/2010/wordml
An ST_LongHexNumber (as specified by [ISO/IEC29500-1:2012] section 17.18.50) attribute that
specifies an identifier for a paragraph that is **unique within the document part** (as specified by
[ISO/IEC29500-1:2012] section 11.3), with the exception that it need not be unique across the
choices or fallback of an Alternate Content block (as specified by [ISO/IEC29500-1:2012] section
17.17.3). **Values MUST be greater than 0 and less than 0x80000000.** See section 2.2.4 for how this
attribute integrates with ISO/IEC-29500-1.
The following W3C XML Schema ([XMLSCHEMA1] section 2.1) fragment specifies the contents of this
attribute.
<xsd:attribute name="paraId" type="w:ST_LongHexNumber"/>
See section 5.1 for the full W3C XML Schema ([XMLSCHEMA1] section 2.1).

**Comment by twsouthwick** [comment]
@arun-newgen This appears to be answered. If not, please reopen.
