### ISSUE TITLE
On Excel, Table fields lose formulas and format

### ISSUE THREAD

**Issue by andrecalil** [OfficeDev/Open-XML-SDK#250]
Hey there,

We noticed that if you have an Excel spreadsheet with a table and some of its columns have calculated or formatted values, these properties (either the formula or the format) will be lost on the table definition if the file is loaded using OpenXML.

This was initially noticed on ClosedXML, a library that relies on OpenXML for all the heavy lifting. Further details can be found on [this issue](https://github.com/ClosedXML/ClosedXML/issues/513).

I cloned ClosedXML repo and got the source code. When debugging, I noticed that, in a given moment, it would call OpenXML to parse all the file to objects. This is the line where it happens:

```
using (var dSpreadsheet = SpreadsheetDocument.Open(fileName, true))
                LoadSpreadsheetDocument(dSpreadsheet);
```

After that, if you peek into the table definitions that were loaded, you'll see that the formula and formats have been lost.

To be clear, this is what I'm referring to:
**\xl\tables\table1,xml**
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" id="1" name="Tabela1" displayName="Tabela1" ref="B2:F3" totalsRowShown="0">
	<autoFilter ref="B2:F3"/>
	<tableColumns count="5">
		<tableColumn id="1" name="colum1"/>
		<tableColumn id="2" name="colum2"/>
		<tableColumn id="3" name="colum3" dataCellStyle="Vírgula"/> <!-- THIS -->
		<tableColumn id="4" name="colum4"/>
		<tableColumn id="5" name="colum5"><calculatedColumnFormula>Tabela1[colum4]+Tabela1[colum3]+Tabela1[colum2]+Tabela1[colum1]</calculatedColumnFormula></tableColumn> <!-- AND THIS -->
	</tableColumns>
	<tableStyleInfo name="TableStyleMedium2" showFirstColumn="0" showLastColumn="0" showRowStripes="1" showColumnStripes="0"/>
</table>
```
This can be found if you rename XLSX to ZIP and go sniffing into it. Those parts get lost on OpenXML.

I can try and get into this on my own, if you'd like. Any direction on where to get started would be much appreciated.

**Comment by tarunchopra** [comment]
@andrecalil : I've used following code and it's able to persist the spreadsheet formatting . 

_Note - I've tested this with openxmlsdk ONLY and have not looked into the internals of closexml._

            using (var packageDocument = SpreadsheetDocument.CreateFromTemplate(@"Template.Example.xlsx"))
            {
                var part = packageDocument.WorkbookPart;
                var root = part.Workbook;

                 packageDocument.SaveAs(@"Template.Example.copy.xlsx").Close();

                // We are fine if we have not run into an exception.
                Assert.True(true);
            }

**Comment by andrecalil** [comment]
Thanks for looking into this, @tarunchopra .
ClosedXML uses the method `Open`. Perhaps there's some different in the internals of OpenXML between `CreateFromTemplate` and `Open`?

**Comment by tarunchopra** [comment]
@andrecalil : Can you please repro the issue with openxmlsdk (removing closexml) ? I assume that the formatting is disturbed in LoadSpreadsheetDocument function; but this function is exposed by closexml and not openxmlsdk. If you can get us a repro; purely with openxmlsdk; we will be able to help.

**Comment by andrecalil** [comment]
So I tried this:

```
[Fact]
public void X009_XlsxCreation_KeepTableProperties()
{
	using (var packageDocument = SpreadsheetDocument.Open(@"F:\calil.xlsx", true))
	{
		var part = packageDocument.WorkbookPart;
		var root = part.Workbook;

		packageDocument.SaveAs(@"F:\calil.copy.xlsx").Close();

		// We are fine if we have not run into an exception.
		Assert.True(true);
	}
}
```
And, er... it worked. I mean, the formula on the table is kept, so that adding a new line replicates it.

I'll keep looking into ClosedXML. I'll close this issue for now.

Thanks mate!

**Comment by igitur** [comment]
@tarunchopra I'm the maintainer of ClosedXML. If you see any queries about files generated by ClosedXML, I suggest the first think you ask is whether this has been logged on ClosedXML's page and whether the maintainer (i.e. me) is certain that it is an OpenXML bug. Chances are likely it will be a ClosedXML bug.

**Comment by tarunchopra** [comment]
@igtur: Thanks. OP mentioned that the issue is an already existing issue @ ClosedXML - https://github.com/ClosedXML/ClosedXML/issues/513; hence there was no reason for me to ask. 

I'll leave it up to OP to follow up on ClosedXML repro. From our side; we need purely openxmlsdk code to investigate that it's our issue.
