### ISSUE TITLE
Query: Can create xlsx preview inside web application using Open-XML

### ISSUE THREAD

**Issue by amitpandeyjss** [OfficeDev/Open-XML-SDK#251]
Hi,
After did lots of search in forum and related links on Open-XML unable to found any relevant answer on my query, so asking here...

__Can we show Preview of an **Excel spreadsheet (XLSX)** using the OpenXML inside web application (website) on web browser?__

-I don't want to use any COM object or MS-Excel libraries (as these software not install in system/computer).
-Here I am, not talking about read/write or any manipulation on **Excel spreadsheet**, just want to show preview the sheet inside browser (web application) .

If **YES,** then please suggest right path to do so...
If **NO**, then is any alternative utils available by Microsoft to do this in web browser?

-Thanks in Advance!

**Comment by twsouthwick** [comment]
This library is designed for programmatically manipulating the document. The https://github.com/OfficeDev/Open-Xml-PowerTools might be a better bet if you want to show a document; it has some utilities to convert to HTML.

**Comment by tomjebo** [comment]
@amitpandeyjss as @twsouthwick said, the SDK is about manipulating the markup (XML) making up the document package. Having said that, one thing that comes to mind would be to embed the spreadsheet in another document (like Word), perhaps using Word automation services (Eric's [blog here ](http://ericwhite.com/blog/2011/08/22/fourth-and-final-screen-cast-in-series-on-addingupdating-the-toc-in-openxml-wordprocessingml-documents/)discusses Word automation services) and then pull out the presentation cache to render on your page. The embedded xlsx worksheet would be referenced in the document.xml part in this markup: 

`<o:OLEObject Type="Embed" ProgID="Excel.Sheet.12" ShapeID="_x0000_i1025" DrawAspect="Content" ObjectID="_1570459982" r:id="rId7"/>`

and the rId7 relationship in the word\_rels\document.xml.rels:

`<Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/package" Target="embeddings/Microsoft_Excel_Worksheet.xlsx"/>`

but you would want the cached imaged for this (from document.xml part): 

`<v:shape id="_x0000_i1025" type="#_x0000_t75" style="width:103.5pt;height:59.25pt" o:ole="">
                        <v:imagedata r:id="rId6" o:title=""/>
                    </v:shape>`

and the rId6 relationship points to the cached image in document.xml.rels:

`<Relationship Id="rId6" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image1.emf"/>`

Eric's blog shows how to extract embedding parts and this can be a starting point:
[http://ericwhite.com/blog/updating-data-for-an-embedded-chart-in-an-open-xml-wordprocessingml-document/](url)

**Comment by twsouthwick** [comment]
@amitpandeyjss This question seems to be answered, so I'm closing this issue. Please reopen if you feel like it isn't fully answered.
