### ISSUE TITLE
"High fidelity conversion of DOCX => HTML/CSS and HTML/CSS => DOCX."

### ISSUE THREAD

**Issue by nicolascaorsi** [OfficeDev/Open-XML-SDK#257]
The Readme file mentions that is possible to convert docx to HTML, but I didn't find any example or documentation explaining how to do it. Can anyone provide an example? I have only found using https://github.com/OfficeDev/Open-Xml-PowerTools, but due to some restrictions, I can't use this library.

Thanks.

**Comment by twsouthwick** [comment]
I believe you need to use the power tools for that. Some of the README is a holdover from when the powertools where in the same repo. @tomjebo we should reword the README so it is targeted solely for the OpenXml library.

> due to some restrictions, I can't use this library

@nicolascaorsi What are the restrictions that make it so you can't use the library?

**Comment by nicolascaorsi** [comment]
@twsouthwick Thanks for answering. I need to run it on Xamarin Android project, the SDK is compatible, but PowerTools isn't. There is any port of it?

**Comment by twsouthwick** [comment]
It's in progress, but nothing available ATM. I'd suggest following over there to see what needs to be done.
