### ISSUE TITLE
Explicit call to Save() does nothing when AutoSave is set to false

### ISSUE THREAD

**Issue by kamilzzz** [OfficeDev/Open-XML-SDK#262]
In current implementation explicitly calling Save() from OpenXmlPackage does nothing when AutoSave option is set to false.
It's because Save() calls SavePartContents() which checks if AutoSave is enabled.

This makes sense when SavePartContents() is called from Dispose() method, because we shouldn't save automatically during disposal when this flag is set to false, but shouldn't explicit call to Save() actually save package regardless of AutoSave state?

**Comment by twsouthwick** [comment]
Thanks for reporting this!

**Comment by encrypt0r** [comment]
@twsouthwick What exactly is Save() supposed to do? I mean only saving the document (with autosave enabled) produces a corrupted package. Is there any way to save the document without having to close it?

**Comment by twsouthwick** [comment]
@encrypt0r  This seems like it would be a different issue (corruption versus a no-op). Can you open an issue with a repro?

**Comment by encrypt0r** [comment]
@twsouthwick actually after more testing it doesn't save at all (AutoSave enabled). The corruption was due to some other reasons. [I have setup a repo](https://github.com/encrypt0r/OpenXmlDemo) That shows the problem. After calling Workbook.Save() and SpreadsheetDocument.Save() the stream is still empty. Have I missed something?

**Comment by twsouthwick** [comment]
@encrypt0r I'll take a look. Can you open a new issue for this?

**Comment by twsouthwick** [comment]
@encrypt0r This has been enabled in the latest CI build available here: https://dotnet.myget.org/gallery/open-xml-sdk. You'll want to upgrade to at least `2.7.3-vnext0051`

**Comment by twsouthwick** [comment]
@kamilzzz This is released now as stable and you should be able to upgrade to 2.8.1 to get it
