### ISSUE TITLE
how to remove Shared Formula in an Excel using OpenXML

### ISSUE THREAD

**Issue by KPVPAPARAO** [OfficeDev/Open-XML-SDK#273]
I am trying to remove all the formulas those exist in an Excel file. 
I was successful in doing that when excel doesn't contain shared formulas however if an excel contains shared formulas in it. 
post running my program excel file corrupts. 
any pointers on resolving this issue is highly appreciated.

**Comment by KPVPAPARAO** [comment]
[Input-test.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/1416904/Input-test.xlsx)
an example input file which contain shared formula in it

**Comment by twsouthwick** [comment]
@KPVPAPARAO In order to help, we need to see the code that you have tried using. If this is a question, please refer to StackOverflow. However, it appears that you are getting a corrupted file so it may be a bug. In either case, we need to see what you are doing.

**Comment by twsouthwick** [comment]
@KPVPAPARAO I'm going to close this issue. Please reopen if you feel like this is a bug. If so, please supply a working repro.
