### ISSUE TITLE
Documentation is inconsistant

### ISSUE THREAD

**Issue by Itaros** [OfficeDev/Open-XML-SDK#305]
https://github.com/OfficeDev/Open-XML-SDK/blob/ae8b0003830232b70a6518afe6acbe0ea02fe978/DocumentFormat.OpenXml/src/Framework/OpenXmlCompositeElement.cs#L166-L186

Why it says 'sets' if it doesn't?

**Comment by twsouthwick** [comment]
Good catch! There are a number of places the documentation is wrong unfortunately :( PRs are welcomed and encouraged to correct these mistakes. I've been correcting them as I see them, but it's a large project!
