### ISSUE TITLE
Each XML part of the generated documents has a BOM prefix

### ISSUE THREAD

**Issue by elkinmilen** [OfficeDev/Open-XML-SDK#309]
**Description**

Cannot generate document without BOM sequence prefix on every part of the document.
Some viewers throw an error and do not open the document because of this. When first opened and saved with MS Excel the BOM sequences for each part gets removed.

**Information**

- .NET Target: any
- DocumentFormat.OpenXml Version: (ie 2.7.2)

**Repro**

Generate basic Excel document. Change the extension of the generated document to ZIP. Open the ZIP archive. Open an XML file inside into a HEX editor of choice. 

**Observed**

The file contents start with EF BB BF (or BOM) and you cannot avoid that.

**Expected**

No BOM sequence or a setting in the API to omit it.

![bom](https://user-images.githubusercontent.com/6715076/33540348-618a1ef6-d8d3-11e7-87d6-4ca2ef3a4a43.png)

**Comment by twsouthwick** [comment]
Thanks for letting us know! In the future, for a repro, providing code would make it much easier to diagnose the problem. I'll take a look and see if this is sufficient.

**Comment by twsouthwick** [comment]
I've repro'd it:

```csharp
[Fact]
public void PartsShouldBeEncodedWithUTF8WithoutBOM()
{
    using (var ms = new MemoryStream())
    {
        using (var package = SpreadsheetDocument.Create(ms, DocumentFormat.OpenXml.SpreadsheetDocumentType.Workbook))
        {
            var wb = package.AddWorkbookPart();

            wb.Workbook = new Workbook();
        }

        using (var package = Package.Open(ms))
        {
            var part = package.GetPart(new Uri("/xl/workbook.xml", UriKind.Relative));

            using (var stream = part.GetStream())
            using (var reader = new StreamReader(stream))
            {
                reader.Read();

                var encoding = Assert.IsType<UTF8Encoding>(reader.CurrentEncoding);
                Assert.Empty(encoding.GetPreamble());
            }
        }
    }
}
```

@tomjebo Is there anything in the spec that specifies that parts must be written in a specific encoding? Changing to output UTF8 w/o the BOM is easy enough, but I want to make sure this is ok in terms of the spec.

We'll probably want to find all places where the an `XmlWriter` is created and ensure we update all those. We may want to look at consolidating the `XmlWriter` instances if possible.
