### ISSUE TITLE
Inquiry: code generation method

### ISSUE THREAD

**Issue by dodyg** [OfficeDev/Open-XML-SDK#310]
What kind of tool are you guys using to generate the classes (https://github.com/OfficeDev/Open-XML-SDK/tree/vNext/DocumentFormat.OpenXml/src/GeneratedCode)? 

I am trying to implement an Open NDC protocol C# client (http://www.iata.org/whatwedo/airline-distribution/ndc/Pages/schema-download2.aspx)

**Comment by twsouthwick** [comment]
These are generated by some custom generators (a path I would not recommend if you're starting with a new project). Have you explored the `xsd.exe` tool?

**Comment by dodyg** [comment]
XSD has not been updated since .NET 2.0. I ended up with https://github.com/mganss/XmlSchemaClassGenerator.

**Comment by twsouthwick** [comment]
Ah - I hadn't realized it was so out of date (I haven't used it for a while). Glad you found a replacement!
