### ISSUE TITLE
Generated xml namespace for xmlMaps.xml

### ISSUE THREAD

**Issue by Sbou** [OfficeDev/Open-XML-SDK#32]
Hi,

I try to add an XmlMapping part in an Excel file butI've got an issue.

I use CustomXmlMappingsPart and MapInfo Objects and the generated file is fine. But when I open Excel file the XML Mapping window is empty.

I compare a file created with Excel and mine created by code and the difference is in xmlMaps.xml file.

The file created by Excel starts with this lines :
`<MapInfo xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" SelectionNamespaces="">
	<Schema ID="Schema1">`

and the file created by code :
`<?xml version="1.0" encoding="utf-8"?>
<x:MapInfo SelectionNamespaces="" xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
       <x:Schema ID="Schema1">`

The main difference is the namespace prefix.

If I remove this prefix and repackages Excel file, it works.

Why this prefix is used and how to remove it ?

Thanks,

**Comment by EricWhiteDev** [comment]
What did you use to serialize the XML?  Why is the prefix getting
introduced?

**Comment by Sbou** [comment]
This is the code I use :
`CustomXmlMappingsPart part = workbookPart.AddNewPart<CustomXmlMappingsPart>(GetNextIdPart(workbookPart.Parts));

            var mapInfo1 = new MapInfo(){ SelectionNamespaces = "" };

            Schema schema1 = new Schema(){ Id = "Schema1" };

            var xsd = new XmlDocument();
            xsd.Load(XSDfile);

            OpenXmlUnknownElement openXmlUnknownElement1 = OpenXmlUnknownElement.CreateOpenXmlUnknownElement(xsd.LastChild.OuterXml);

            schema1.Append(openXmlUnknownElement1);

            Map map1 = new Map(){ ID = (UInt32Value)1U, Name = "Root_Map", RootElement = "Root", SchemaId = "Schema1", ShowImportExportErrors = true, AutoFit = true, AppendData = false, PreserveAutoFilterState = true, PreserveFormat = false };

            mapInfo1.Append(schema1);
            mapInfo1.Append(map1);

            part.MapInfo = mapInfo1;

            mapInfo1.Save();
`

The 'x' prefix is coded in MapInfo class.

**Comment by EricWhiteDev** [comment]
Can you please post the spreadsheet that won't load?  (Either here or in the forums at OpenXmlDeveloper.org)

**Comment by Sbou** [comment]
This is the generated file.

[Excel file](http://we.tl/KgvaXaf716)

Thanks

**Comment by EricWhiteDev** [comment]
Can you kindly attach it to a post on GitHub or on OpenXmlDeveloper.org?
That link wants to download cookies and whatnot.

**Comment by Sbou** [comment]
OK,

I created a post on OpenXmlDeveloper
[Post](http://openxmldeveloper.org/discussions/development_tools/f/38/p/8288/164107.aspx#164107)

**Comment by EricWhiteDev** [comment]
This issue was discussed and closed at the above link.
