### ISSUE TITLE
DocumentFormat.OpenXml.Spreadsheet.Map boolean conversion

### ISSUE THREAD

**Issue by Sbou** [OfficeDev/Open-XML-SDK#33]
Hi,

I try to use DocumentFormat.OpenXml.Spreadsheet.Map in CustomXmlMappingsPart but generated attributes values for booleans is not interpreted by Excel.

With OpenXml SDK :
`<Map ID="1" Name="Root_Map" RootElement="Root" SchemaID="Schema1" ShowImportExportValidationErrors="1" AutoFit="1" Append="0" PreserveSortAFLayout="1" PreserveFormat="1" />`

With Excel :
`<Map ID="1" Name="Root_Map" RootElement="Root" SchemaID="Schema1" ShowImportExportValidationErrors="true" AutoFit="true" Append="false" PreserveSortAFLayout="true" PreserveFormat="true" />`

Why this difference ?

Thanks

**Comment by EricWhiteDev** [comment]
Both are valid per the standard.  A producer can produce either form of markup, their choice, and it still will be a conforming document.  Probably it was written that way because it was cleaner to code, or something.

**Comment by Sbou** [comment]
It is perhaps valid for the standard but Excel doesn't recognize it.

**Comment by EricWhiteDev** [comment]
What are you using for writing the markup?  The Open XML SDK?  I have a document with a map in it.  I changed the markup to look like this:
    <Map ID="2"
         Name="Data_Map"
         RootElement="Data"
         SchemaID="Schema1"
         ShowImportExportValidationErrors="0"
         AutoFit="1"
         Append="0"
         PreserveSortAFLayout="1"
         PreserveFormat="1"/>
Excel opened the document without any issues, and the Open XML SDK productivity tool validated that markup.

I suspect that there is another issue.  Excel, more than Word or PowerPoint, is fussy about the markup that you write.  If you order elements incorrectly, or for instance, if cells in a row are not in the right order, Excel will complain and not open the XLSX.

"0" and "false" (and "1" and "true") are interchangeable for boolean values, and this code is very general, and used throughout the Office suite, as well as the SDK.

Can you provide more information?  Perhaps you can post the question in the forums at OpenXmlDeveloper.org - that is where I hang out and answer questions.  :-)
