### ISSUE TITLE
Ignoring the namespace leads to validation errors.

### ISSUE THREAD

**Issue by Themanwithoutaplan** [OfficeDev/Open-XML-SDK#34]
This affects the productivity tool. When the option `Ignore XML Namespace` is set, the productivity tool embeds the namespace in lots of tags even if it's already defined. This in turn leads the validator to declare these tags invalid because of the namespace declaration.

``` xml
<styleSheet mc:Ignorable="x14ac" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
 <numFmts count="2">
  <numFmt formatCode="mm/dd/yyyy" numFmtId="164"/>
  <numFmt formatCode="#,##0.00;\-#,##0.00" numFmtId="165"/>


 </numFmts>
 <fonts x14ac:knownFonts="1" count="3">
  <font>
   <sz val="11" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <color rgb="FF000000" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <name val="Calibri" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <family val="2" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <charset val="1" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
  </font>
  <font>
   <b xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <sz val="8" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <color rgb="FF000000" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <name val="Arial" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <family val="2" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <charset val="1" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
  </font>
  <font>
   <sz val="8" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <color rgb="FF000000" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <name val="Arial" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <family val="2" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
   <charset val="1" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"/>
  </font>
 </fonts>
```

This leads to error messages like `The element has unexpected child element 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'`

**Comment by EricWhiteDev** [comment]
I am not even sure what that Ignore XML Namespace option does.  I have never used it.  What is the scenario that this is trying to address?

**Comment by Themanwithoutaplan** [comment]
I suspect the scenario might be related to how the namespaces are declared: at what part in the document, or with a prefix. However, it seems broken at the moment.

**Comment by Themanwithoutaplan** [comment]
![bildschirmfoto 2015-07-24 um 08 11 56](https://cloud.githubusercontent.com/assets/1080058/8868754/0aaac658-31dc-11e5-9cc1-427ef1d0a43c.png)

**Comment by EricWhiteDev** [comment]
I am going to send an email to some of the folks on the original dev team, and see if anyone has any idea of what this option is for, and what it is supposed to do.

**Comment by tomjebo** [comment]
@Themanwithoutaplan Please post this issue to the following forum: 
[https://social.msdn.microsoft.com/Forums/office/en-us/home?forum=oxmlsdk](url)

The PowerTool support is handled there.

**Comment by Themanwithoutaplan** [comment]
I'm sorry, I don't follow. Why has this SDK issue been closed?

**Comment by tomjebo** [comment]
The Productivity Tool is not supported in this repo. Currently the forum I listed, is the way to report issues with it.

**Comment by Themanwithoutaplan** [comment]
But the Productivity Tool is part of the SDK and built with it.

**Comment by tomjebo** [comment]
No, it's not part of this repo. It is built with and dependent on the 2.5 SDK. That's why Eric originally said he would email the folks responsible for developing it. The forum I pointed to is the correct place to ask about the Productivity Tool.
