### ISSUE TITLE
How to signature Excel File with Pfx file?

### ISSUE THREAD

**Issue by vincywindy** [OfficeDev/Open-XML-SDK#378]
I want to signature Excel with No visible digital signature。How can I do?
I found AddDigitalSignatureOriginPart function ,How to use it?

**Comment by twsouthwick** [comment]
@vincywindy This is better asked on stackoverflow (which is also pointed out in the Issue template when you first click "New Issue"). This is the issue tracker for bugs in the SDK. Once you ask the question there, can you put a link here so those interested can answer there? If you find an issue in the SDK with this, please file an issue for that!
