### ISSUE TITLE
Adding common interface/base class for related elements

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-XML-SDK#384]
I know most of the element classes are code generated from XSDs somewhere. Sometimes when I would like to work on shared properties, especially like styles in Word, the classes don't share a common base class or interface to get at the strongly typed properties.

For instance, I've had to come up with this pattern.

```
public interface IOpenXmlElement { } // For future
public interface IParagraphProperties : IOpenXmlElement
{
    Justification Justification { get; }
    SpacingBetweenLines SpacingBetweenLines { get; }
}
public class ParagraphProperties : DocumentFormat.OpenXml.Wordprocessing.ParagraphProperties, IParagraphProperties
{
    public ParagraphProperties(DocumentFormat.OpenXml.Wordprocessing.ParagraphProperties paragraphProperties)
        : base(paragraphProperties.OuterXml)
    { }
}
public class ParagraphPropertiesBaseStyle : DocumentFormat.OpenXml.Wordprocessing.ParagraphPropertiesBaseStyle, IParagraphProperties
{
    public ParagraphProperties(DocumentFormat.OpenXml.Wordprocessing.ParagraphPropertiesBaseStyle baseStyle)
        : base(baseStyle.OuterXml)
    { }
}

```

Is there a way the XSD and/or the code gen develop something similar using either an interface or base class for these related classes and properties?

**Comment by tomjebo** [comment]
@daniel-white thanks for the suggestion.

**Comment by twsouthwick** [comment]
@daniel-white Could you come up with a proposal of which types would be needed? I've been looking at updating the code generation and if we had a list of what kind of types would be helpful, we can incorporate that in.

**Comment by daniel-white** [comment]
Heres a list of what I've done which is far from exhaustive and only from WordprocessingML:

* RunProperties, ParagraphMarkRunProperties (the class is missing the properties despite having the supported child elements, so there that), StyleRunProperties, RunPropertiesBaseStyle
* ParagraphProperties, ParagraphPropertiesBaseStyle, StyleParagraphProperties
* TableProperties, StyleTableProperties
* TableCellProperties, StyleTableCellProperties (missing properties)

**Comment by twsouthwick** [comment]
Thanks. One thing to keep in mind is that once we ship an interface, it cannot change until we do a major version change.

Looks like most of these are for properties, is that right?

**Comment by daniel-white** [comment]
Could it be done with an abstract class then? I used interfaces for simplicity of wrapping.

Yea, I only really used it for properties.

**Comment by twsouthwick** [comment]
The downside of abstract classes are you can only have a single one applied to the types. Can you show the full definition of the abstract classes/interfaces (we can figure out later which one is better here) with the properties they would expose? Do they align with properties that already exist on the types or do they require wrapping of some sort?

**Comment by daniel-white** [comment]
@twsouthwick i would have to look at the xsd to validate things.

**Comment by daniel-white** [comment]
`DocumentFormat.OpenXml.Drawing.Wordprocessing.Anchor` and `DocumentFormat.OpenXml.Drawing.Wordprocessing.Inline` have shared properties too:

* `Extent Extent { get; set; }`
* `EffectExtent EffectExtent { get; set; }`
* `DocProperties DocProperties { get; set; }`
*  `NonVisualGraphicFrameDrawingProperties NonVisualGraphicFrameDrawingProperties { get; set; }`

**Comment by twsouthwick** [comment]
I took a look at the schema generation and it currently flattens items so it doesn't generate code in a hierarchy. Unfortunately, that generator is not open source at the moment. I think it can be modified to not flatten and thus retain  hierarchy of types... this would be a breaking change, but will ensure that base types are applied where needed.

**Comment by daniel-white** [comment]
@twsouthwick i'm fine with this in a 3.0 timeframe.
