### ISSUE TITLE
Changes for 3.x version

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#387]
I've noticed some things we can do when we decide to make a 3.x version which will allow us to have breaking changes. I'll keep this list up-to-date with ideas as we come across them:

- [ ] `OpenXmlSimpleType.TextValue` should be made `private protected`
- [ ] Types derived from `OpenXmlSimpleType` should not have implicit casting operators if they allocate objects
- [ ] Make `EnumStringAttribute` internal
- [ ] Consider making a `DocumentFormat.OpenXml.Validation` library that adds the validation logic. This currently adds a few megabytes to the openxml library
- [ ] Redesign usage of `IFixedContentTypePart`; possibly remove
- [ ] Remove obsolete classes/methods
- [ ] Slim `OpenXmlPackage` (and maybe others) by moving some helper methods to extension classes. An example is the `FlatOPC` methods
- [ ] Make `ValidatorSettings` public and readonly. Add a constructor to `OpenXmlValidator` to handle the settings
- [ ] Consider breaking up library into smaller ones for Word/Powerpoint/Excel. 
- [ ] Add standard unit conversion type. There are different units such as points, emus, etc. that could be understood and convertible from the api.

**Comment by tomjebo** [comment]
@twsouthwick great ideas. shall we use a vNext or 3.x branch to hold these?

**Comment by twsouthwick** [comment]
That's a good idea, although let's keep it lowercase. I'll create a `vnext` branch we can add these to and then we can decide when we want to take the plunge with a 3.0 release

**Comment by daniel-white** [comment]
Another one from me: break up the monolithic library into separate ones for Word, Powerpoint and Excel.

**Comment by twsouthwick** [comment]
@daniel-white I've added this to the list.

**Comment by twsouthwick** [comment]
I think I'll make a GitHub Project plan to track these so we can have discussions about specific ideas

**Comment by daniel-white** [comment]
Another one would be to have a standard unit conversion type. Theres different units such as points, emus, etc. it would be nice if they would be easily understood and convertible from the api.

**Comment by twsouthwick** [comment]
I've added it to the list!

**Comment by jvanriel** [comment]
Do you have a another place for feature request discussions? I want an SaveAsPDF feature.

**Comment by twsouthwick** [comment]
@jvanriel Feel free to create an issue for any request. Saving to PDF, however, is beyond the scope of this project. The SDK this project focuses on it specifically on manipulating the document. To save to a PDF, you'd have to have an engine to render and handle layout...

**Comment by ThomasBarnekow** [comment]
#485 and similar kinds of enhancements could be candidates (unless they don't constitute breaking changes).

**Comment by Alexander-Hauser** [comment]
> Consider breaking up library into smaller ones for Word/Powerpoint/Excel.
I'd welcome this very much. Most of the time only one of those libaries is needed.

> Add standard unit conversion type. There are different units such as points, emus, etc. that could be understood and convertible from the api.
This feature would come in very handy. It would make styling much easier.

**Comment by IrakliLomidze** [comment]
Please Incorporate Open XML Power Tools in the version 3.0

1)Splitting DOCX/PPTX files into multiple files.
2)Combining multiple DOCX/PPTX files into a single file.
3)Comparing two DOCX files, producing a DOCX with revision tracking markup, and enabling retrieving a list of revisions.

4) High-fidelity conversion of DOCX to HTML/CSS.

**Comment by twsouthwick** [comment]
@IrakliLomidze Open XML Power Tools is built on top of the SDK. The SDK is intended for the low level tasks of handling the file format and providing a 1:1 strongly typed SDK.

**Comment by IrakliLomidze** [comment]
@twsouthwick  I'm aware about that Open XML Power tools is build on top of the SDK. but some times it is arguable. what is a base functionality (levels of tasks) and what not.

This is a just suggestion, what DOCX SDK should have.

**Comment by twsouthwick** [comment]
Think of it this way: does it have to do with the file format itself (that is, a direct representation of what is in the package)? If so it belongs in the SDK. Otherwise, probably not. There's definitely room for discussion about some of these, so feel free to open issues for any specific scenario you would like to enable.

Some background: This project is a side project for those of us involved and so we have limited time to invest and we have to pick and choose what we want to maintain. There is a lot of work to be done to clean up the current SDK to a more modern architecture and support new schema elements that that is generally the priority of work.

**Comment by IrakliLomidze** [comment]
@twsouthwick It ok to stabilize code of base SDK.
it is my opinion that goal of "Open XML SDK" is to convince and attract developers to stick with Open XML and not to ODF. 
Open XML Power tools was a great IDEA to make Open XML SDK usable in real business scenarios.
Please make it into consideration, that we developers would like to see more futures in the SDK.

Not only futures from power tools. But also:
1) some rendering capabilities (e.g. Export to PDF).
2) some conversion capabilities from word automation services. 

I fully understand that all this might be out of scope from your current project. But you could initiate to open discussion for that with your program manager.

at least open OpenXMKSDK  on UserVoice.com

**Comment by m-gallesio** [comment]
> Consider breaking up library into smaller ones for Word/Powerpoint/Excel.

Yes, please. Having these separated (along with a base / core module, I assume) would improve clarity, make for a smaller base package (currently ~5.8 MB) and allow more code splitting between dependent assemblies. For reference our product does not currently use Powerpoint at all.

**Comment by softboy99** [comment]
Hi,
@twsouthwick , Does the save to PDF feature will be included in the v3.x?, I see you add it to todo as milestone.

![image](https://github.com/dotnet/Open-XML-SDK/assets/228731/9d4df8a6-41ea-4538-a827-e04b31601cb4)

**Comment by tomjebo** [comment]
@softboy99 We currently have no plans to implement saving to PDF.
