### ISSUE TITLE
Opening read-only document on Mono 4.0.0 throws exception

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#39]
I'm currently trying to use the Open XML SDK on the latest Mono release, i.e., 4.0.0. When creating a read-only instance of `WordprocessingDocument`, using `WordprocessingDocument.Open(fileName, false)`, the following exception is thrown:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Operation not valid when package is read-only
  at System.IO.Packaging.Package.CheckIsReadOnly () [0x00000] in <filename unknown>:0 
  at System.IO.Packaging.PackagePart.CreateRelationship (System.Uri targetUri, TargetMode targetMode, System.String relationshipType, System.String id, Boolean loading) [0x00000] in <filename unknown>:0 
  at System.IO.Packaging.PackagePart.LoadRelationships (System.Collections.Generic.Dictionary`2 relationships, System.IO.Stream stream) [0x00000] in <filename unknown>:0 
  at System.IO.Packaging.PackagePart.get_Relationships () [0x00000] in <filename unknown>:0 
  at System.IO.Packaging.PackagePart.GetRelationships () [0x00000] in <filename unknown>:0 
  at DocumentFormat.OpenXml.Packaging.PackagePartRelationshipPropertyCollection..ctor (System.IO.Packaging.PackagePart packagePart) [0x00000] in <filename unknown>:0 
  at DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load (DocumentFormat.OpenXml.Packaging.OpenXmlPackage openXmlPackage, DocumentFormat.OpenXml.Packaging.OpenXmlPart parent, System.Uri uriTarget, System.String id, System.Collections.Generic.Dictionary`2 loadedParts) [0x00000] in <filename unknown>:0 
  at DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships (DocumentFormat.OpenXml.Packaging.OpenXmlPackage openXmlPackage, DocumentFormat.OpenXml.Packaging.OpenXmlPart sourcePart, DocumentFormat.OpenXml.Packaging.RelationshipCollection relationshipCollection, System.Collections.Generic.Dictionary`2 loadedParts) [0x00000] in <filename unknown>:0 
  at DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load () [0x00000] in <filename unknown>:0 
```

This seems to be a bug in Mono (see http://lists.ximian.com/pipermail/mono-bugs/2011-February/109577.html). However, the question is whether there is a workaround on the level of the Open XML SDK.

**Comment by jhare** [comment]
I encountered the same issue, but through the `SpreadsheetDocument` interface. I gather they rely on the same code.

In my case I didn't explicitly require the file to be read-only so I left it as editable, but my understanding is that changes you make would happen to the document when it's flushed. I imagine this was not possible in your case?

I also wish there was more info on that Mono bug, it was created in Feb 2011. Only 4 years ago!

**Comment by ThomasBarnekow** [comment]
@jhare Right, it is a bit puzzling how long these bugs live.

@EricWhiteDev Would this be fixed by your new implementation of System.IO.Packaging (see also #40)?

**Comment by EricWhiteDev** [comment]
@ThomasBarnekow @jhare I would certainly guess that this same issue will not show up when using the new System.IO.Packaging.  However, I have heard that there are issues with the System.IO.Compression namespace on Mono.  It fails in some circumstances where it should not.  I haven't researched this, though.

**Comment by dmunch** [comment]
The read-only bug looks like it's one of the bugs I fixed on my branch a year ago. I never came to create a pull request since the last commit on my branch breaks quite some unit tests and I had to move forward to other stuff. I still keep an eye on this stuff though.

https://github.com/dmunch/mono/commit/bee81085af07a3ef1f64c024924be63f7b0f344c

I'm not sure if it's still worth to get those fixes in mono upstream, or of the new System.IO.Packaging is going to replace the mono implementation anytime soon? Any plans on this?

**Comment by akoeplinger** [comment]
There's a pending PR on Mono that seems to fix it the same way as @dmunch did: https://github.com/mono/mono/pull/1255. I'll ping them to see if it can get merged.

**Comment by dmunch** [comment]
I remember a long discussion on the mono-dev mailing list about pull requests: http://mono.1490590.n4.nabble.com/Pull-Requests-td4664224.html

> The best approach is to stay engaged in the pull requests and bring the attention to the mailing list for us to discuss.

**Comment by EricWhiteDev** [comment]
@dmunch, @akoeplinger I agree, I apologize for the slow response on this.  At the time, I was working on System.IO.Packaging, and it was taking longer than I planned for, we didn't have XUnit tests for the Open XML SDK, so difficult to validate fixes.  Also feeling pressure to get the SDK for Office 2016 put together.  But we are in a somewhat better shape now, although XUnit tests are not to where I want them.  I will examine that PR in detail later this week and get the fix in vNext branch.

**Comment by Numpsy** [comment]
fwiw, I just fell over this issue when trying to get some Windows document handling code running under Mono 4.2.2 on OSX, with an older version of the SDK.
It seems ok with a local build of Mono 4.3.3, but it would have been nice if the patch linked above could have found its way into a 4.2.x build, given how simple the fix seems to have been.

**Comment by akoeplinger** [comment]
@Numpsy yeah, the release cycle for Mono 4.2 was quite long and for the current service release only high priority fixes went in. We'll be branching for Mono 4.4 in the near future and as you said it'll contain the fix.

**Comment by abelondev** [comment]
So is there workaround?

**Comment by Numpsy** [comment]
It seems to be working in the 4.4.0 alpha, I don't know beyon that.

**Comment by jeongsd** [comment]
I use Mono 5.0.1 and I seem to be getting the same bug. Do you have a solution to this? Or as the above person has said, should I just use 4.4.0 alpha?

**Comment by acabutto** [comment]
Still having the same problem using Xamarin + Mono 5.8.1.0 on MacOs

**Comment by RocheVal** [comment]
Hi,

Same issue here than the one mentioned above by @jeongsd and @acabutto (with Mono 5.16.0.179 on Ubuntu).

Any news on this issue? Or any workaround?

**Comment by downleave** [comment]
Hello, Mono 5.20.1.19 still have the same problem. Have you solve your problem and how? @jeongsd @acabutto @RocheVal
