### ISSUE TITLE
Strict http://purl.oclc.org/ooxml/spreadsheetml/main tables fail validation

### ISSUE THREAD

**Issue by ghost** [OfficeDev/Open-XML-SDK#393]
**Description**

Strict namespace spreadsheetml tables throw an exception in OpenXmlValidator.

**Information**

- .NET Target: whatever the default is in VS
- DocumentFormat.OpenXml Version: 2.5.0, 2.8.1

**Repro**

Trivial spreadsheet that triggers the problem: [test.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/1668722/test.xlsx)

*_rels/worksheet.xml.rels* has `<Relationship Id='rId1' Type='http://purl.oclc.org/ooxml/officeDocu
ment/relationships/table' Target='table.xml' />` which should, I think, enable `StrictTranslation`.

*table.xml* has `<table xmlns='http://purl.oclc.org/ooxml/spreadsheetml/main' id='1' displayName='Data' ref='A1:B3'>`

Both URLs are straight from ECMA-376, Part 1, *12.3.21 Table Definition Part*.

Additionally, both LibreOffice and Office Online are able to load the table definition, which arguably might not signify anything.

```csharp
SpreadsheetDocument document = SpreadsheetDocument.Open("test.xlsx", false);
OpenXmlValidator validator = new OpenXmlValidator(FileFormatVersions.Office2010);
validator.Validate(document);
``` 

**Observed**

```
System.IO.InvalidDataException
  HResult=0x80131501
  Message=Cannot load the root element from the part. The part contains invalid data.
  Source=DocumentFormat.OpenXml
  StackTrace:
   at DocumentFormat.OpenXml.Packaging.OpenXmlPart.LoadDomTree[T]()
   at DocumentFormat.OpenXml.Packaging.TableDefinitionPart.get_PartRootElement()
   at DocumentFormat.OpenXml.Validation.DocumentValidator.ValidatePart(OpenXmlPart part)
   at DocumentFormat.OpenXml.Validation.DocumentValidator.Validate(OpenXmlPackage document)
   at DocumentFormat.OpenXml.Validation.OpenXmlValidator.Validate(OpenXmlPackage openXmlPackage)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\IEUser\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 18

Inner Exception 1:
InvalidDataException: The root XML element "http://purl.oclc.org/ooxml/spreadsheetml/main:table" in the part is incorrect. The expected root XML element is: "http://schemas.openxmlformats.org/spreadsheetml/2006/main:table".
```

**Expected**

No exception should be thrown and no errors returned.

**Comment by pjanouch** [comment]
I've found that the file actually has mixed transitional/strict URLs. Only parts defined by the OPC may use the _schemas.openxmlformats.org_ domain in a purely strict document.

Once united under _purl.oclc.org_ where applicable, the error disappeared, thus closing the issue. I don't know if mixed documents should be valid but the idea seems hardly worth pursuing.

One remaining point is that the function should probably not _throw_ exceptions when it _returns_ errors.
