### ISSUE TITLE
Proposed OpenXmlReader methods

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-XML-SDK#398]
In order to make more succinct calling code, I've extended `OpenXmlReader` in my code with these helpers. I propose that something similar can be added to the library.

```
public T LoadCurrentElement<T>() where T : OpenXmlElement => (T)_reader.LoadCurrentElement();

public bool ElementTypeIs<T>() where T : OpenXmlElement => ElementType == typeof(T);

public bool ElementIs<T>(out T element) where T : OpenXmlElement
{
       element = null;

        if (ElementTypeIs<T>())
        {
            element = LoadCurrentElement<T>();
            return true;
       }

       return false;
}
```

`ElementIs<T>` plays nice with the new `out` semantics introduced in C# 7.0. Instead of this mess, 

```
if (reader.ElementType == typeof(Paragraph))
{
    Paragraph p = (Paragraph)reader.LoadCurrentElement();
    // ...
}
```

the new methods provide a simplification

```
if (reader.ElementIs(out Paragraph p))
{
    // ...
}
```

Thoughts?

**Comment by twsouthwick** [comment]
What about the following:

```csharp
if(reader.LoadCurrentElement() is Paragraph p)
{
...
}
```

Do you see your suggesting having a benefit over this pattern?

**Comment by daniel-white** [comment]
Well what if it isn't a `Paragraph`? Wouldn't it needlessly load the element?

**Comment by twsouthwick** [comment]
Hmmm.. you're right, it would. There isn't a `Current` property, either, which is needed to make that pattern work. We could look at adding that property if there's a need.

Going off what you have in your proposal, I'd suggest the following:

```csharp
public static class OpenXmlReaderExtensions
{
    public static bool TryGetElement<T>(this OpenXmlReader reader, out T element)
        where T : OpenXmlElement
    {
        if (ElementType == typeof(T) && LoadCurrentElement() is T tElement)
        {
            element = tElement;
            return true;
        }

        element = null;
        return false;
    }
}
```

Would this be sufficient of an API for your needs?

**Comment by daniel-white** [comment]
It would, I was looking to simplify other code too, where I dont need to call `LoadCurrentElement`. The `Try...` method pattern would have to swallow most exceptions which might not be desirable.

**Comment by twsouthwick** [comment]
The `Try..catch` pattern should be a way to not swallow exceptions - it should never throw. It's a common pattern when you want to try something, and if it fails, continue on. What exceptions are you relying on that may be missed?

**Comment by daniel-white** [comment]
I was concerned about if theres any malformed XML or some other exceptional behavior, I would st ill want it to throw.

**Comment by twsouthwick** [comment]
That makes sense. The current implementation above doesn't swallow anything, just prevents loading the current element when it's not of the expected type. Do you have an example of where this would swallow an exception?

**Comment by daniel-white** [comment]
I was meaning people may expect that of a `Try...` method like how the `TryParse` methods do, not a `Try...Catch`, hence my different naming.

**Comment by twsouthwick** [comment]
my bad - I meant `Try...` above. Following guidance from https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance#try-parse-pattern, probably want to do the following:

```csharp
 public static bool TryGetElement<T>(this OpenXmlReader reader, out T element)
        where T : OpenXmlElement
{
...
}

 public static T GetElement<T>(this OpenXmlReader reader)
        where T : OpenXmlElement
{
...
}
```

That way, the developer can decide if they want it to handle exceptions or not.

**Comment by daniel-white** [comment]
Yea I had that basically in my proposal. `LoadCurrentElement` is one building block. `ElementIs<T>` just simplifies the call site to a single condition and variable declaration. Plus it reads as a sentence nicely.

**Comment by twsouthwick** [comment]
I see the benefit of it reading nicely, but there is already a standard pattern in the framework for this kind of method using the `Try...` pattern. For discoverability, I'd prefer going with that.

@tomjebo @ThomasBarnekow @igitur There's a request to add some methods to `OpenXmlReader` to help in accessing elements in a strongly-typed way. Have any of you seen needs for this kind of API and have any thoughts to add?

**Comment by ThomasBarnekow** [comment]
@twsouthwick I think I have never used the `OpenXmlReader` in my code, but I might not understand the clear performance advantage over doing something like this with the strongly typed API:
```
MainDocumentPart part = wordDocument.MainDocumentPart;
Document document = part.Document;
IEnumerable<Paragraph> paragraphs = document.Descendants<Paragraph>();
```
Or this (shorter variant of the above):
```
var paragraphs = wordDocument.MainDocumentPart.Document.Descendants<Paragraph>();
```
@daniel-white What is your use case for the `OpenXmlReader`? For example, are you using it to read and somehow transform a document?

**Comment by igitur** [comment]
I'm just a spectator here, but it's definitely something we could use in `ClosedXML`. Here's a snippet of our current code:

```c#
else if (reader.ElementType == typeof(AutoFilter))
    LoadAutoFilter((AutoFilter)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(SheetProtection))
    LoadSheetProtection((SheetProtection)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(DataValidations))
    LoadDataValidations((DataValidations)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(ConditionalFormatting))
    LoadConditionalFormatting((ConditionalFormatting)reader.LoadCurrentElement(), ws, differentialFormats);
else if (reader.ElementType == typeof(Hyperlinks))
    LoadHyperlinks((Hyperlinks)reader.LoadCurrentElement(), wsPart, ws);
else if (reader.ElementType == typeof(PrintOptions))
    LoadPrintOptions((PrintOptions)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(PageMargins))
    LoadPageMargins((PageMargins)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(PageSetup))
    LoadPageSetup((PageSetup)reader.LoadCurrentElement(), ws, pageSetupProperties);
else if (reader.ElementType == typeof(HeaderFooter))
    LoadHeaderFooter((HeaderFooter)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(SheetProperties))
    LoadSheetProperties((SheetProperties)reader.LoadCurrentElement(), ws, out pageSetupProperties);
else if (reader.ElementType == typeof(RowBreaks))
    LoadRowBreaks((RowBreaks)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(ColumnBreaks))
    LoadColumnBreaks((ColumnBreaks)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(WorksheetExtensionList))
    LoadExtensions((WorksheetExtensionList)reader.LoadCurrentElement(), ws);
else if (reader.ElementType == typeof(LegacyDrawing))
    ws.LegacyDrawingId = (reader.LoadCurrentElement() as LegacyDrawing).Id.Value;
```

Looks like it is an ideal candidate for use of the proposed new methods.

**Comment by daniel-white** [comment]
@ThomasBarnekow it allows you to forward-only read the xml positionally without allocating/hydrating the wrapper classes, unless you want it to. Much like a SAX api.

I'm using it to get a full graph of the document to convert it into a certain form of HTML that isn't supported by the power tools using a custom wrapper SAX-like API. The above example I provided just is to show how simplified the code can be, not that I just need to find paragraphs. @igitur's example is more akin to what I'm doing.

**Comment by tomjebo** [comment]
@twsouthwick perhaps this would also be helpful when injecting/parsing custom elements (i.e. non-standard elements per MCE or extensions). In these cases, you wouldn't be using the strong types in the standard defined ML's. Just a guess at this point.

**Comment by daniel-white** [comment]
@twsouthwick i can't implement my own `OpenXmlElement` which is what `OpenXmlReader` provides. There's `IsInVersion`, `Populate`, `WriteContentTo` and `NamespaceId` which are internal abstract.

**Comment by ThomasBarnekow** [comment]
@daniel-white I'd say that the example provided by @igitur would certainly benefit from those additional `OpenXmlReader` methods. Thus, I'm certainly not against adding methods that add value in some use cases.

Having said that, I still don't understand why you would have to use the `OpenXmlReader` in your use case of transforming Open XML to whatever other form of XML (including that "certain form of HTML").

The following is an example pure functional transformation, which turns an `OpenXmlElement` (e.g., a `Document`) into some other form:
```
        private static object Transform(OpenXmlElement element)
        {
            switch (element)
            {
                case Document document:
                    return new XElement("html", document.Elements().Select(Transform));
                case Paragraph paragraph:
                    return new XElement("p", paragraph.Elements().Select(Transform));
                case Text text:
                    return new XElement("span", text.Text);
                default:
                    return element.Select(Transform);
            }
        }
```
You could call this as follows:
```
                Document document = wordDocument.MainDocumentPart.Document;
                var html = Transform(document) as XElement;
```
What would be the benefit of using the `OpenXmlReader`  compared to the above approach?

**Comment by daniel-white** [comment]
@ThomasBarnekow that doesn't scale well if i want to skip certain things. see: https://blogs.msdn.microsoft.com/brian_jones/2010/05/27/parsing-and-reading-large-excel-files-with-the-open-xml-sdk/

**Comment by twsouthwick** [comment]
I think the use case is definitely there for the API. @daniel-white I would prefer the TryGet/Get pattern as that's often employed in the standard libraries and minimizes the APIs added.

**Comment by twsouthwick** [comment]
@daniel-white Would you want to provide a PR with this implementation and some tests? If so, we can get it in the next minor release (2.9.0).

**Comment by daniel-white** [comment]
Sure.

**Comment by twsouthwick** [comment]
We don't have a specific date yet, but probably sometime in May.

**Comment by twsouthwick** [comment]
We're waiting for .NET Core 2.1 release to incorporate a stable build of System.IO.Packaging 4.5.0 which includes a fix for Xamarin platforms, and right now the release is expected in the first half of 2018.

**Comment by twsouthwick** [comment]
Yes, target against master, and then we'll flow it to the office2016/vnext branches
