### ISSUE TITLE
OpenXml Does not fully support .Net 4.5 (TargetFramework)

### ISSUE THREAD

**Issue by kjhano** [OfficeDev/Open-XML-SDK#407]
**Description: OpenXml Does not fully support .Net 4.5 (TargetFramework)**

I will have to inform you that the version of DocumentFormat.OpenXml 2.8.1 does not fully support .Net 4.5.2

VisualStudio:
- .NET Target: 4.5
- DocumentFormat.OpenXml Version: 2.8.1

**Repro**
1. Create a .Net 4.5 Target Console Project. 
2. Test the following code: 
_using (SpreadsheetDocument spreadSheetDocument = SpreadsheetDocument.Open(excelStream, false)_

3. Error: Method not found: 'System.String System.String.Format(System.IFormatProvider, System.String, System.Object, System.Object, System.Object)'.

**My conclusion:**
The Method only exists in mscorlib that comes with .Net 4.6..
Please test, and note me if my assumptions are correct. As pr. now i do not have a workaround for this error since i am not allowed to upgrade the .Net version on the environment...
Please send me a mail if you have fixed this and/or if you know of any workaround.

**Comment by twsouthwick** [comment]
I set up a machine with only .NET 4.5.2 and could not repro this issue. Can you supply a full repro project? Preferably a GitHub link to a project, but a zip would work too. Thanks!

**Comment by twsouthwick** [comment]
For clarification, you are targeting .NET 4.5, but running on a machine with .NET 4.5.2, right? Can you provide the following information:

- What version of Windows? (ie what does WinVer say?)
- The version of .NET as provided by the documentation here: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by twsouthwick** [comment]
I received more details in an email (@kjhano if that wasn't you, then let me know, but the issue was the same). This was occurring because the assemblies for .NET 4.6 were being taken from the nupkg rather than using NuGet to manage the package deployment.
