### ISSUE TITLE
Errors CS0107 when compiling the project..

### ISSUE THREAD

**Issue by MedSaid17** [OfficeDev/Open-XML-SDK#413]
First, Excuse for my poor english. It'ts my first post here.
Because I need a new date for my file DocumentFormat.OpenXml.dll (instead of the initial 01/06/2018),
I tried to compile the project to get a new dll. But I get Compiler Error CS0107 (More than one protection modifier..).
Thanks for your help.

![image](https://user-images.githubusercontent.com/19156977/36789697-baf06b32-1c92-11e8-938e-eabe06fc28f1.png)

**Comment by tomjebo** [comment]
@MedSaid17 "private protected" is valid per [C# 7.2 in this blog](https://blogs.msdn.microsoft.com/mazhou/2017/10/05/c-7-series-part-5-private-protected/). What version of VS are you using?

**Comment by tomjebo** [comment]
@MedSaid17 we state in the [Build Instructions](https://github.com/OfficeDev/Open-XML-SDK#build-instructions) that VS2017 is required and this uses C# 7.2. You can download VS2017 Community for free.

**Comment by twsouthwick** [comment]
Yes, you need VS 2017 with Update 5 to build the project to take advantage of new C# features. Can you try updating and let us know if that works?

**Comment by MedSaid17** [comment]
I use VS2017 with latest updates ( I think..) but I'll check that and return to you.  Thank you.

**Comment by MedSaid17** [comment]
@twsouthwick,  @ tomjebo, I thought wrong.. I was not up to date.. With the new update it works and I have my new dll.Youpiii. 1000 thanks for your help.

**Comment by twsouthwick** [comment]
@MedSaid17 Out of curiosity, what do you mean by a "new dll"?

**Comment by MedSaid17** [comment]
I simply mean that I recompiled DocumentFormat.OpenXml.dll. So now,  I have a new date for it(instead of the initial date 6th january 2018. I needed absolutelty that for my application..

**Comment by twsouthwick** [comment]
What's the need for a different date? Is something in the SDK out of date?

**Comment by MedSaid17** [comment]
No the SDK is fantastically fantastic..
Ok. I'll try to explain ..
In fact, we have an application for which we send updates for our users. Our update procedure is done as we send them only files modified from the date of their last update.
For example, if a user has already been updated on February 20, 2018 and we need to send him a new update today, March 1, we will only send the files modified between these two dates. The 6th january 2018 version of DocumentFormat.OpenXml.dll will unfortunately never be addressed to them...

**Comment by twsouthwick** [comment]
Ah gotcha. I'd recommend not using dates but instead versions - otherwise you'll have problems with any 3rd party library in the future (or even internal builds that you injest into your application that happen to have a timestamp from before the previous update).

**Comment by MedSaid17** [comment]
What you say is the holy truth but unfortunately I have no power to change this..

**Comment by MedSaid17** [comment]
I have a new question if you allow me..

**Comment by MedSaid17** [comment]
the Nuget package creates by default under my VS2017 target only "netstandard1.3".
The only way I found for target "net40" is to edit the following lines in the .csproj. I guess it's not the right method. I am wrong? :

![image](https://user-images.githubusercontent.com/19156977/36872958-55a25536-1da7-11e8-8694-132ae9e7a0fa.png)

**Comment by twsouthwick** [comment]
Yeah, this is a workaround due to the size of the assembly if we try to edit all the targets in a single instance of VS. You have three options:

1. Do what you're doing
2. Start VS with an environment variable ProjectLoadStyle=All
3. Add a ProjectLoadStyle=DevFramework40 (with an analogous update in the test)

If you go with (3), please submit a PR with that as it may come in handy for other people.

**Comment by twsouthwick** [comment]
Also, if you're creating your own build, make sure to check out a released version (ie `git checkout v2.8.1`) so that you are using the same code.
