### ISSUE TITLE
Copy custom xml and SharePoint metadata on merging document

### ISSUE THREAD

**Issue by XzaR90** [OfficeDev/Open-XML-SDK#420]
# Before submitting an issue, please fill this out

**Description**
Copy custom XML and SharePoint metadata on merging document does not work using DocumentBuilder?

**Information**

- .NET Target: NET Framework 4.5.2
- DocumentFormat.OpenXml Version: OpenXMLSDK-MOT 2.6.0.0

**Expected**

When I comment out if (itemList.Contains(propertyPartDoc.Root.Attribute(DS.itemID).Value)) I get the expected result.

```csharp
        private static void CopyCustomXml(WordprocessingDocument sourceDocument, WordprocessingDocument newDocument,
            IEnumerable<XElement> newContent)
        {
            List<string> itemList = new List<string>();
            foreach (string itemId in newContent
                .Descendants(W.dataBinding)
                .Select(e => (string)e.Attribute(W.storeItemID)))
                if (!itemList.Contains(itemId))
                    itemList.Add(itemId);

            foreach (CustomXmlPart customXmlPart in sourceDocument.MainDocumentPart.CustomXmlParts)
            {
                OpenXmlPart propertyPart = customXmlPart
                    .Parts
                    .Select(p => p.OpenXmlPart)
                    .Where(p => p.ContentType == "application/vnd.openxmlformats-officedocument.customXmlProperties+xml")
                    .FirstOrDefault();

                if (propertyPart != null)
                {
                    XDocument propertyPartDoc = propertyPart.GetXDocument();
                    //if (itemList.Contains(propertyPartDoc.Root.Attribute(DS.itemID).Value))
                    //{
                        CustomXmlPart newPart = newDocument.MainDocumentPart.AddCustomXmlPart(customXmlPart.ContentType);
                        newPart.GetXDocument().Add(customXmlPart.GetXDocument().Root);
                        foreach (OpenXmlPart propPart in customXmlPart.Parts.Select(p => p.OpenXmlPart))
                        {
                            CustomXmlPropertiesPart newPropPart = newPart.AddNewPart<CustomXmlPropertiesPart>();
                            newPropPart.GetXDocument().Add(propPart.GetXDocument().Root);
                        }
                    //}
                }
            }
        }
```

**Comment by twsouthwick** [comment]
This is not a working repro. What data are you using? For us to be able to investigate any possible issue, we need to have a working repro so we can debug it.

**Comment by twsouthwick** [comment]
btw DocumentBuilder is not part of the SDK. If this is an issue with that (you mention it in the description, but I see no use of it in the code), then you should file it here: https://github.com/OfficeDev/Open-Xml-PowerTools/issues

**Comment by ThomasBarnekow** [comment]
Even if the `DocumentBuilder` is not used in the repro itself, the usage of the `GetXDocument()` extension method and the `XDocument` class indicate that @XzaR90 is trying to use the Open XML PowerTools. 

Thus, this is not an issue with the SDK.

**Comment by twsouthwick** [comment]
Good catch @ThomasBarnekow . @XzaR90 I'd recommend taking a look at the Open-XML-PowerTools repo and filing and issue there.
