### ISSUE TITLE
Validator ignores elements removed from the spec

### ISSUE THREAD

**Issue by Themanwithoutaplan** [OfficeDev/Open-XML-SDK#44]
I've recently had Excel files that break the spec by including a "mergeCell" attribute in alignment elements. Such files should raise validation errors, certainly against the 2010 and 2013 formats but also against the 2007 as well. However this is currently not the case.

From [MS-OE376]:
2.1.720 Part 4 Section 3.8.1, alignment (Alignment)
a. The standard does not contain a @mergeCell attribute on the alignment element.
Excel allows @mergeCell to be written on the alignment element. @mergeCell is not used by Office and is not necessary for interoperability.
This note applies to the following products: 2007, 2007 SP1, 2007 SP2.

**Comment by EricWhiteDev** [comment]
You are absolutely correct, the Open XML SDK does not properly validate files.  It is close, but there are a number of cases where it complains about the existence of valid elements / attributes, and it does not complain about non existence of required elements and attributes.  It is close, though, and by far the best tool we have.  But it can do more.  I expect to address this, along with sample documents and xUnit tests in the somewhat near future.

I expect to take a systematic approach with this, where I have large sets of documents that are saved by specific versions of Word, and the goal is to make the Validator conform.

I am currently working on Office 2016 support, and improving the validation functionality seems like it would be a natural follow-on project.

**Comment by EricWhiteDev** [comment]
Assigning to myself.

**Comment by EricWhiteDev** [comment]
Further notes on this -

We have contemplated adding an option to validation, which is to either validate as written by Office, or validate per the spec.

In either case, we're not going to address this until the Office 2016 port is completed.

**Comment by twsouthwick** [comment]
@EricWhiteDev What's the current status of this? @Themanwithoutaplan are you still seeing this with the latest changes?

**Comment by twsouthwick** [comment]
Since no clear repro is available, I'm closing this. Feel free to reopen with a repro.
