### ISSUE TITLE
Library generate invalid file if add more than 26 columns

### ISSUE THREAD

**Issue by slgal** [OfficeDev/Open-XML-SDK#440]
Is this a:
- [x] Issue with the OpenXml library
- [ ] Question on library usage

**Description**

Library generate corrupted XLSX file if add more than 26 columns. Looks like the problem with cell order in obtained file.  
```xml
<x:row r="1" xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <x:c r="A1" t="n">
    <x:v>0</x:v>
  </x:c>
  <x:c r="AA1" t="n">
    <x:v>26</x:v>
  </x:c>
  <x:c r="B1" t="n">
    <x:v>1</x:v>
  </x:c>
```
I guess somewhere there is a sort method by R field which cause this issue. 

Thank you!

**Information**

- .NET Framework 4.5.2
- DocumentFormat.OpenXml Version: 2.8.2

**Repro**

```csharp
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Spreadsheet;
using System;

namespace BugDocumentFormatXLSX
{
    class Program
    {
        static void Main(string[] args)
        {
            using (SpreadsheetDocument document = SpreadsheetDocument.Create("test.xlsx", SpreadsheetDocumentType.Workbook))
            {
                WorkbookPart workbookPart = document.AddWorkbookPart();
                workbookPart.Workbook = new Workbook();

                WorksheetPart worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
                worksheetPart.Worksheet = new Worksheet(new SheetData());

                Sheets sheets = workbookPart.Workbook.AppendChild(new Sheets());

                Sheet sheet = new Sheet() { Id = workbookPart.GetIdOfPart(worksheetPart), SheetId = 1, Name = "Test Sheet" };

                sheets.Append(sheet);

                SheetData sheetData = worksheetPart.Worksheet.GetFirstChild<SheetData>();

                var columnsCount = 27; //TO GENERATE VALID XLSX FILE CHANGE THIS VALUE TO 26 or less

                Row row = new Row() { RowIndex = 1u };
                for (int i = 0; i < columnsCount; i++)
                    CreateCell(row, worksheetPart, i, i);

                sheetData.Append(row);

                worksheetPart.Worksheet.Save();
                workbookPart.Workbook.Save();
            }

            Console.ReadKey();
        }


        public static Cell CreateCell(Row row, WorksheetPart worksheetPart, int col, decimal value)
        {
            var columnName = GetStandardExcelColumnName(col);
            //just to make sure that column name is resoulved properly
            Console.WriteLine(string.Format("{0} => {1}", col, columnName));

            var cell = InsertCellInWorksheet(columnName, row, worksheetPart);
            cell.CellValue = new CellValue(value.ToString());
            cell.DataType = new EnumValue<CellValues>(CellValues.Number);
            return cell;
        }

        private static Cell InsertCellInWorksheet(string columnName, Row row, WorksheetPart worksheetPart)
        {
            string cellReference = columnName + row.RowIndex;
            Cell refCell = null;
            foreach (Cell cell in row.Elements<Cell>())
            {
                if (string.Compare(cell.CellReference.Value, cellReference, true) > 0)
                {
                    refCell = cell;
                    break;
                }
            }

            Cell newCell = new Cell() { CellReference = cellReference };
            row.InsertBefore(newCell, refCell);

            return newCell;
        }

        public static string GetStandardExcelColumnName(int columnNumberOneBased)
        {
            int baseValue = Convert.ToInt32('A');
            int columnNumberZeroBased = columnNumberOneBased;

            string ret = "";

            if (columnNumberOneBased > 25)
            {
                ret = GetStandardExcelColumnName((columnNumberZeroBased / 26) - 1);
            }

            return ret + Convert.ToChar(baseValue + (columnNumberZeroBased % 26));
        }
    }
}

``` 

**Observed**
![image](https://user-images.githubusercontent.com/1153279/37310583-072b111e-264d-11e8-975a-7d73df8287c4.png)

Invalid excel file. 
[test.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/1804626/test.xlsx)

![image](https://user-images.githubusercontent.com/1153279/37310616-27c98a2c-264d-11e8-9df4-eba0adb0053f.png)

![image](https://user-images.githubusercontent.com/1153279/37310636-3b4d4458-264d-11e8-9ff1-7746beda1fb7.png)

**Expected**

Valid file with more that 26 columns.

**Comment by mandarBadve** [comment]
Hi,
Open the excel file in Open XML SDK tool and use validate option. It will give you exact error.
[https://www.microsoft.com/en-in/download/details.aspx?id=30425](https://www.microsoft.com/en-in/download/details.aspx?id=30425)

**Comment by ThomasBarnekow** [comment]
@slgal It is not the SDK but your `InsertCellInWorksheet` method that contains a 

> sort method by R field which cause this issue

```
private static Cell InsertCellInWorksheet(string columnName, Row row, WorksheetPart worksheetPart)
{
    string cellReference = columnName + row.RowIndex;
    Cell refCell = null;
    foreach (Cell cell in row.Elements<Cell>())
    {
        // HERE IS THE SORT METHOD
        if (string.Compare(cell.CellReference.Value, cellReference, true) > 0)
        {
            refCell = cell;
            break;
        }
    }

    Cell newCell = new Cell() { CellReference = cellReference };
    row.InsertBefore(newCell, refCell);

    return newCell;
}
```

Thus, while you produce the correct column names for colums "AA", "AB", etc. in your `GetStandardExcelColumnName` method, you incorrectly use a `string.Comare` in `InsertCellInWorksheet` to determine the position of your new cells within a row's list of cells. For example, since "AA1" is obviously less than "B1" in a string comparison, your code inserts the cell before "B1".

**Comment by slgal** [comment]
Hello @ThomasBarnekow, you are totally right. I am happy as it's so easy to fix.
Thank you a lot for your time, that you have been spend looking into my problem.

**Comment by biryazilim** [comment]
> @slgal It is not the SDK but your `InsertCellInWorksheet` method that contains a
> 
> > sort method by R field which cause this issue
> 
> ```
> private static Cell InsertCellInWorksheet(string columnName, Row row, WorksheetPart worksheetPart)
> {
>     string cellReference = columnName + row.RowIndex;
>     Cell refCell = null;
>     foreach (Cell cell in row.Elements<Cell>())
>     {
>         // HERE IS THE SORT METHOD
>         if (string.Compare(cell.CellReference.Value, cellReference, true) > 0)
>         {
>             refCell = cell;
>             break;
>         }
>     }
> 
>     Cell newCell = new Cell() { CellReference = cellReference };
>     row.InsertBefore(newCell, refCell);
> 
>     return newCell;
> }
> ```
> 
> Thus, while you produce the correct column names for colums "AA", "AB", etc. in your `GetStandardExcelColumnName` method, you incorrectly use a `string.Compare` in `InsertCellInWorksheet` to determine the position of your new cells within a row's list of cells. For example, since "AA1" is obviously less than "B1" in a string comparison, your code inserts the cell before "B1".

This is a general issue of OpenXML (26 Columns), correction Sort Line does not correct error here...

**Comment by biryazilim** [comment]
This is a general issue of OpenXML (26 Columns), correction Sort Line does not correct error here...
