### ISSUE TITLE
Add some security/fuzz testing

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#441]
We should add some sort of fuzz testing to test for potential security/reliability issues:

- Zip bombs
- Malicious XML
- Recursive content

These are the items at the top of my head.... there are probably others

**Comment by Metalnem** [comment]
Hi Taylor!

I'm the author of [SharpFuzz](https://github.com/Metalnem/sharpfuzz), which is a tool that enables fuzzing of .NET programs using afl-fuzz. I did a small experiment on **SpreadsheetDocument.Open** method, which discovered that it can throw many unexpected exceptions ([documentation](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.packaging.spreadsheetdocument.open?view=openxml-2.8.1#DocumentFormat_OpenXml_Packaging_SpreadsheetDocument_Open_System_String_System_Boolean_) states that this method should throw only **OpenXmlPackageException**). These are:

- **ArgumentException**
- **FileFormatException**
- **InvalidDataException**
- **InvalidOperationException**
- **XmlException**

I didn't have the time to do a longer fuzzing run, and I think that this only scratches the surface of all the possible problems that could be discovered. If you are interested in exploring this area, here is [my fuzzing playground](https://github.com/Metalnem/sharpfuzz/tree/master/src/SharpFuzz.Samples/DocumentFormat.OpenXml) for Open XML SDK.

If you have any questions, I'll be glad to assist you!

All the best,
Nemanja

**Comment by twsouthwick** [comment]
This is awesome! I had gone through and tried to update some of the exceptions (I had noticed more were thrown than was documented).
