### ISSUE TITLE
ShapeLocks.NoTextEdit attribute is not working in PowerPoint presentation

### ISSUE THREAD

**Issue by Meikandan** [OfficeDev/Open-XML-SDK#444]
**ShapeLocks.NoTextEdit attribute is not working in PowerPoint presentation**

Reference : https://social.msdn.microsoft.com/Forums/office/en-US/c1c61293-72b9-4dc5-ae65-8d5a46144003/shapelocksnotextedit-attribute-is-not-working-in-powerpoint-presentation-2016?forum=oxmlsdk

I am trying to protect a text box in a PowerPoint slide by making it as non-editable. I am editing the XML file as below (Please see the attribute highlighted in bold).

I referred this [documentation](https://technet.microsoft.com/en-us/library/documentformat.openxml.drawing.shapelocks.notextedit?cs-save-lang=1&cs-lang=csharp)

The below XML is valid. I have edited the XML with just an text editor by unzipping the PPTX file.

`<p:spTree>
      <p:nvGrpSpPr>
        <p:cNvPr id="1" name="" />
        <p:cNvGrpSpPr />
        <p:nvPr />
      </p:nvGrpSpPr>
      <p:grpSpPr>
        <a:xfrm/>        
      </p:grpSpPr>
      <p:sp>
        <p:nvSpPr>
          <p:cNvPr id="4" name="TextBox 3"/>
          <p:cNvSpPr txBox="1">
            <a:spLocks noSelect="1" noTextEdit = "1"/>
          </p:cNvSpPr>
          <p:nvPr />
        </p:nvSpPr>
        <p:spPr>
          <a:xfrm>
            <a:off x="3179298" y="1519311" />
            <a:ext cx="4937760" cy="369332" />
          </a:xfrm>
          <a:prstGeom prst="rect">
            <a:avLst />
          </a:prstGeom>
          <a:noFill />
        </p:spPr>
        <p:txBody>
          <a:bodyPr wrap="square" rtlCol="0">
            <a:spAutoFit />
          </a:bodyPr>
          <a:lstStyle />
          <a:p>
            <a:r>
              <a:rPr lang="en-US" />
              <a:t>Safvfmple</a:t>
            </a:r>
            <a:endParaRPr lang="en-US" dirty="0" />
          </a:p>
        </p:txBody>
      </p:sp>
    </p:spTree>`

**Expected**
The 'noTextEdit' attribute should work as expected.
Thanks,
Meikandan

**Comment by twsouthwick** [comment]
Can you please provide a repro using the SDK? From what you describe, I'm not certain what you mean as "not working".

**Comment by Meikandan** [comment]
Hi twsouthwick,

**Not working :** ShapeLocks.NoTextEdit attribute is not working when I edit the slide1.xml file with a text editor.  Attached a pptx file for reproducing the issue. I have explained the issue in the slide  1 of the attached pptx file.
[Non-EditableText.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/1818638/Non-EditableText.pptx)

**Comment by twsouthwick** [comment]
By repro, I mean executable C# code. Please see the guidelines for submitting an issue. I'll take a look at the powerpoint, but please provide a minimal viable repro.

**Comment by twsouthwick** [comment]
I followed the original link you posted and it appears that you are editing the xml by hand. If this is the case, then this is an issue with PowerPoint, and not the SDK. If you are using the SDK and the output is incorrect, then it's an issue we might be able to help you with.

**Comment by Meikandan** [comment]
The original [link ](https://social.msdn.microsoft.com/Forums/office/en-US/c1c61293-72b9-4dc5-ae65-8d5a46144003/shapelocksnotextedit-attribute-is-not-working-in-powerpoint-presentation-2016?forum=oxmlsdk)was now updated with the code snippet needed to reproduce the issue. Can you check this?

**Comment by twsouthwick** [comment]
Can you put a minimum viable repro on this thread? Something that I can put in a unit test and see the issue? Linking to other places make it difficult to ensure we're looking at the same thing as things there may change.

________________________________

**Comment by Meikandan** [comment]
1. ‘Test.pptx’ is a pptx file created manually in PowerPoint application, with only a text box in a slide. 
2. Text in the text box in ‘ABC’.
          
               string path = @"C:\Users\Admin\Desktop\Test.pptx";
               using (PresentationDocument doc = PresentationDocument.Open(path, true))
                {
                Slide slide1 = doc.PresentationPart.SlideParts.First().Slide;
                CommonSlideData commonSlideData1 = slide1.GetFirstChild<CommonSlideData>();

                ShapeTree shapeTree1 = commonSlideData1.GetFirstChild<ShapeTree>();

                Shape shape1 = shapeTree1.GetFirstChild<Shape>();

                NonVisualShapeProperties nonVisualShapeProperties1 = shape1.GetFirstChild<NonVisualShapeProperties>();

                NonVisualShapeDrawingProperties nonVisualShapeDrawingProperties1 = nonVisualShapeProperties1.GetFirstChild<NonVisualShapeDrawingProperties>();

                A.ShapeLocks shapeLocks1 = new A.ShapeLocks();
               shapeLocks1.NoTextEdit = true;
               shapeLocks1.NoSelection = true;
                nonVisualShapeDrawingProperties1.Append(shapeLocks1);
            }
`
Opening it in OpenXML SDK Tools, we could find the **spLocks** changes to

`<a:spLocks noSelect="1" noTextEdit="1" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" />`

Open the file in PowerPoint application, we could not select the text box but could still change the text string in the text box by double clicking it.

**Expected behavior:** The text inside the text box should be non-selectable and non-editable 

Hope the reproduce steps could help you reproduce the issue.

**Comment by twsouthwick** [comment]
This sounds like an issue with PowerPoint not the SDK. Is there a problem with the generated XML or are you reporting an issue in PowerPoint? If it's in powerpoint, we are unfortunately not able to help with that here - this is the repo for the SDK only.

**Comment by Meikandan** [comment]
Can you say where should I report this issue?

**Comment by twsouthwick** [comment]
I'm not exactly sure how they handle bugs. @tomjebo may be able to help there.
