### ISSUE TITLE
Word 2016 : file validation error with value "useWord2013TrackBottomHyphenation"

### ISSUE THREAD

**Issue by christianpokorny** [OfficeDev/Open-XML-SDK#451]
**Description**

Word 2016 : file validation error with value "useWord2013TrackBottomHyphenation"

**Information**

- .NET Framework 4.7
- DocumentFormat.OpenXml Version: (ie 2.8.1)

**Repro**

Here is the OneDrive url from the container where you will find my test word file  :

https://onedrive.live.com/?id=7F7C6DE1B049242F%21105&cid=7F7C6DE1B049242F

and here is the class I need to test this document :

    public class WellFormedDocxRule : ITextValidationRule
    {
        public IResourceManagerService ResourceManagerService { get; set; }

        public ValidationTarget ValidationTarget { get { return ValidationTarget.All; } }

        //We assume the Validate method is thread safe
        OpenXmlValidator validator = new OpenXmlValidator(FileFormatVersions.Office2010);

        public IEnumerable<TextValidationErrorInfo> Validate(Text text, WordprocessingDocument document)
        {
            foreach (ValidationErrorInfo error in validator.Validate(document))
            {
                if (error.Description.Contains("useWord2013TrackBottomHyphenation")) continue;
                string strError = String.Format("(Part={0} ; Path={1}) : {2}", error.Part.Uri, error.Path.XPath, error.Description);
                yield return new TextValidationErrorInfo() { Description = ResourceManagerService.GetString("text_validation_wellformed_docx_rule_description"), Details = strError, Severity = ValidationSeverity.Error, ValidationTarget = ValidationTarget };
            }

        }
    }

**Observed**

After having define my validator in C# with : 
OpenXmlValidator validator = new OpenXmlValidator(FileFormatVersions.Office2010) 
I have this error when I validate my docx document with Word 2016 : 
The attribute http://schemas.openxmlformats.org/wordprocessingml/2006/main:name has invalid value 'useWord2013TrackBottomHyphenation'. The Enumeration constraint failed." 
I'm working with a 2.8.1.15 DocumentFormat.OpenXml.dll file.
Files created by Word 2016 seem to have more compatsetting elements than files created in Word 2010. 
One of them is useWord2013TrackBottomHyphenation.
I note that whether Validate Option provided in OpenXML SDK Tools or FileFormatVersions enumeration provided by Open XML SDK could only support for Office 2007,2010 and 2013. 
So I think that OpenXMLValidator is not updated for Office 2016 at present. 

**Expected**

Update OpenXMLValidator to be compatible with Word 2016

**Comment by twsouthwick** [comment]
Thanks @christianpokorny . We have plans to add Word 2016 support, but it is currently not available.

I did notice, in your comments, that you assume the validator is not thread safe. In currently released builds, that is definitely not the case. Generally, assume that the SDK is *not* threadsafe. I did some work a month ago to remove some of the state that causes the validator to fail in threaded environments, but I haven't performed any exhaustive testing there. #388 is my change for that, but it is only in prerelease versions at the moment. It'll be available in 2.9.0 when released.

**Comment by CaseySchurman** [comment]
Are there any updates on this issue? Or is it known which version will include a fix for this, and when that version will be released? Currently running into the "useWord2013TrackBottomHyphenation" value error with word doc templates that are edited in Word 2016.

**Comment by TazUk** [comment]
Any updates on the validation issue?
We are encountering the value error with useWord2013TrackBottomHyphenation using v2.9.1 validation of Word 2016 template.

**Comment by 06needhamt** [comment]
Is there any ETA for getting a fix for this as I am hitting this quite often. If not I would be willing to contribute a fix if it would be accepted.

**Comment by twsouthwick** [comment]
Please check if 2.10.1 fixes the issue. If not, I'll need something I can reproduce. This is ideally something like an xunit test.

**Comment by Kashishmsft** [comment]
[OpenXML_MS_Word 365_Issue.zip](https://github.com/OfficeDev/Open-XML-SDK/files/4358066/OpenXML_MS_Word.365_Issue.zip)

This issue still occurs when having Open XML SDK 2.10.1 with Office 365 created documents. Is it still under progress for fix ?

**Comment by 06needhamt** [comment]
I will test on Monday morning. I have a document that reproduces this issue 100% of the time. Will upload it here if the issue still occurs with version 2.10.1

**Comment by Kashishmsft** [comment]
> I will test on Monday morning. I have a document that reproduces this issue 100% of the time. Will upload it here if the issue still occurs with version 2.10.1

I have lready uploaded the sample above. Use it to repro the issue with 2.10.1

**Comment by guptavkumar** [comment]
I too having the same exception while validating a file created in O365. It will be really great to know the ETA for this fix. This is actually blocking us to compete something.
