### ISSUE TITLE
Sample Repository Link Missing?

### ISSUE THREAD

**Issue by michael-hawker** [OfficeDev/Open-XML-SDK#457]
**Description**

The Description link in the main repo links to this [Documentation](https://msdn.microsoft.com/en-us/library/office/bb448854.aspx); however its `Samples on GitHub` just dumps you to the `OfficeDev` organization and not an actual samples on how to use the Open XML SDK...

Can a proper link be provided to the repo containing samples?  Especially UWP ones.

Thanks

**Comment by twsouthwick** [comment]
I'm not sure where that's supposed to go - maybe @tomjebo does. As for samples, you can look at the tests to see how to do some of the things. If you encounter any issues with UWP, let us know - we don't currently have test coverage for .NET Native, but have made best efforts to support it.

**Comment by tomjebo** [comment]
@michael-hawker I will inquire about that link (Samples on Github) to find out if it was intended to point somewhere else.

**Comment by tomjebo** [comment]
@michael-hawker just in case you haven't seen it before, there is a lot of code sample and other content on  [openxmldeveloper.org](http://openxmldeveloper.org/).

**Comment by michael-hawker** [comment]
@tomjebo they have a big notice at the top saying it's going away.  Plus it's not really organized to easily find samples.  Searching for 'uwp' for instance brings up nothing.

**Comment by twsouthwick** [comment]
Docs has changed. Not sure if there's a sample repo. Happy to link to one from the README if someone has one.
