### ISSUE TITLE
Add option ToFlatOpcString to exclude whitespace.

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/Open-XML-SDK#478]
**Description**

`OpenXmlDocument.ToFlatOpcString` formulates the document with a lot of whitespace - line breaks and tabs. These aren't needed in XML and creates bloat when transferring.

**Information**

- .NET Target: Any
- DocumentFormat.OpenXml Version: 2.8.1

**Comment by twsouthwick** [comment]
Sounds good to me. What kind of API shape are thinking of? Probably would be good to include some sort of options with settings for serialization.

**Comment by twsouthwick** [comment]
I actually have a branch with a similar idea to yours, but haven't come up with a pattern I'm happy with. I'll open an issue to flesh out some ideas and maybe we can come up with something together.

For now, would something like this work?

```
public abstract partial class OpenXmlPackage
{
  public string ToFlatOpcString(FlatOpcOptions options);
}

public class FlatOpcOptions
{
   bool CondenseWhitespace { get; set; }
}
```

The place to do this would probably be to use `OpenXmlPackage.ToFlatOpcDocument().WriteTo(XmlWriter)` where the `XmlWriter` has appropriate settings.

**Comment by daniel-white** [comment]
Yea. I'm not a fan of the library using Linq to XML right now...

**Comment by daniel-white** [comment]
Just a heads up I was able to chop 30k off in my super simple test.
