### ISSUE TITLE
Error Validating Open XML document with signed version of Open XML SDK

### ISSUE THREAD

**Issue by ron1010** [OfficeDev/Open-XML-SDK#48]
Is it possible to sign the Open XML SDK?

I am having trouble with Validating an Open XML Document with a signed version of the Open XML Sdk. I need to sign my code which in turn requires DLLs it uses to be signed. I added the SNK files to the Open XML SDK projects and added "PublicKey" to ofapi.cs. I can open documents and manipulate them, but when i go the validate them, i get the exception below.

![image](https://cloud.githubusercontent.com/assets/8064198/8772032/d559d518-2efa-11e5-970b-d949467c2786.png)

Has anyone else had issues with this?

Ron.

**Comment by EricWhiteDev** [comment]
Hi Ron,

We don't currently have plans to produce a signed DLL of the Open XML SDK.  Given that the Open XML SDK is simply source code that you can compile into your project, for the purposes of signing your code, can you simply include the Open XML SDK source code, then sign your executable?  There is no technical difference between source code that you write yourself, and the open source Open XML SDK source code that you include in your project.

Eric

**Comment by EricWhiteDev** [comment]
Closing, because this is not a planned feature of the open source Open XML SDK.

**Comment by ron1010** [comment]
Eric,

Thanks for your reply. I did think that I could just sign the code and all would be sweet, and it was until I ran the Validate. What has got me stuck is that the method is the 'DocumentFormat.OpenXml, Version=2.5.5654.1127, Culture=neutral, PublicKeyToken=null' exception. DocumentFormat.OpenXml is the namespace of the Open-XML-SDK, so why is it looking for it in another Version with a Null PublicKey?

My test project is available at http://6377a4303138ef8eab20-ca4532d882fe562d6af8309397556964.r32.cf1.rackcdn.com/WorkbookUpdate.zip

This is just the validation code from an update process i was working on for workbooks. The rest of the code to create an manipulate other parts of the workbooks worked, but i was getting invalid workbooks. Then i ran the validation before i did any changes and came to the conclusion that validation does not work if the Open-XML-SDK is signed. I hope i am wrong :-)

Ron.

**Comment by EricWhiteDev** [comment]
Validation does not rely on being signed.  I don't know why you are getting that specific error.

Here is an experiment:

Build a super-short open xml program that links with the Open XML SDK that you just built, then call the validation functionality, see if your XLSX is valid.

One key point - XLSX is by far the most rigorous about needing all of the elements and attributes in the right order.  Incorrect order will cause the XLSX to not validate and to not load properly in Excel.

Can you open the XLSX in Excel?

**Comment by ThomasBarnekow** [comment]
@ron1010 Which version of the Open-XML-SDK are you using? It seems that you reference the Open-XML-SDK.csproj and System.IO.Packaging.csproj from the SDK. It also seems that you are on the master branch. Can you confirm that?

**Comment by ThomasBarnekow** [comment]
@ron1010 I've checked out the master branch of the Open-XML-SDK and see this as the current commit:
```
commit 45e8bbd787d4a5623efad9d5761ba5639c22b76f
Author: Eric White <eric@ericwhite.com>
Date:   Thu Jul 16 12:21:25 2015 +0530

    Re-add Makefile-Linux-Mono with new .gitattributes so that it will be in the object store as text
```
When putting your solution folder on the same level as the top-level Open-XML-SDK folder, your solution loads all projects. However, there are build errors because the referenced assemblies (DocumentFormat.OpenXml.dll and System.IO.Packaging.dll) are not signed. Thus, I've turned off signing and the solution is built successfully. 

I've then run your project, which produces the following output:
```
Error 1
Description: The attribute 'top' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49.
ErrorType: Schema
Node: DocumentFormat.OpenXml.Spreadsheet.PageMargins
Path: /x:worksheet[1]/x:pageMargins[1]
Part: /xl/worksheets/sheet1.xml
-------------------------------------------
Error 2
Description: The attribute 'bottom' has invalid value '0.75'. The MaxExclusive constraint failed. The value must be less than 49.
ErrorType: Schema
Node: DocumentFormat.OpenXml.Spreadsheet.PageMargins
Path: /x:worksheet[1]/x:pageMargins[1]
Part: /xl/worksheets/sheet1.xml
-------------------------------------------
count=2
```
Does this look like what you would expect?

**Comment by ron1010** [comment]
Eric, Thomas, thanks for your replies.

When Open-XML-SDK is unsigned, the WorkbookUpdate validate works. The sample Workbook with the project is valid, it was created with Excel 2013.

I have created a fork https://github.com/ron1010/Open-XML-SDK.git with one commit of the projects unsigned and working and the other, signed and not working.

The bit I don't understand is to to with the stream in SimpleTypes.cs:306, where the exception is happening, the stream contains the workbook, it was created in Excel, not in the Open-XML-SDK, yet it is looking for a assembly with the same name as one from the SDK. 

Is the SDK relying on a assembly compatible to what Excel used to write the workbook?

**Comment by ThomasBarnekow** [comment]
@ron1010 When you look at the output generated by your code (see my previous post), doesn't that say that the workbook is invalid? The "MaxExclusive" constraint failed for two attributes.

How did you set up your solution, i.e., which Open XML SDK projects did you include and how did you configure signing?

**Comment by ThomasBarnekow** [comment]
@ron1010 Why do you need to sign those assemblies anyhow?

**Comment by ron1010** [comment]
@ThomasBarnekow i don't get the 'MaxExclusive' error you mentioned. I forked the Open XML SDK, then added the WorkbookUpdate project and it validates the workbook.
I then signed the assemblies generating the Open-XML-SDK.snk, System.IO.Packaging.snk and WorkbookUpdate.snk files and adding the PublicKey option to the InternalsVisibleTo attribute in the Open-XML-SDK\src\ofapi\ofapi.cs file.

I am working on a VSTO Excel AddIn and want to move some data from CustomXMLParts to DocumentSettings so the AddIn can work under Office365. The VSTO AddIn requires signing and so does assemblies it references.

**Comment by ThomasBarnekow** [comment]
>  I don't get the 'MaxExclusive' error you mentioned. I forked the Open XML SDK, then added the WorkbookUpdate project and it validates the workbook.

@ron1010 That is indeed interesting. This might be a "feature" in the Open XML SDK, because some of the test cases that pass on AppVeyor and on @EricWhiteDev's machine fail on my machine. This "feature" might be related to localization / internationalization issues.

@EricWhiteDev I will open an issue for this and suggest we look into it.

**Comment by ron1010** [comment]
@ThomasBarnekow, does my fork build for you ? https://github.com/ron1010/Open-XML-SDK.git

**Comment by ThomasBarnekow** [comment]
@ron1010, yes your fork builds on my machine. When I run it, though, an exception is thrown as long as the assemblies are signed.

Another question is whether you'd want to move to vNext. That branch will always have the latest and greatest features before they are finally merged into master. vNext also contains all those test cases.

**Comment by ron1010** [comment]
@ThomasBarnekow , i switched to vNext, and all the tests passed. I then signed DocumentFormat.OpenXml and System.IO.Packaging, they all failed with the same exception is am having with the trunk.

Result Message:	System.Runtime.Serialization.SerializationException : Unable to find assembly 'DocumentFormat.OpenXml, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by ThomasBarnekow** [comment]
@ron1010 and @EricWhiteDev, I think I've found the issue. The exception is thrown in the `SimpleTypeRestrictions.Deserialize(Stream, FileFormatVersions)` method, because it tries to match the full name of the assembly, using `System.Runtime.Serialization.Formatters.FormatterAssemblyStyle.Full`.
```
        /// <summary>
        /// Deserialize the binary data into memory object.
        /// </summary>
        /// <param name="stream">The data stream.</param>
        /// <param name="fileFormat">The target file format version.</param>
        /// <returns></returns>
        internal static SimpleTypeRestrictions Deserialize(Stream stream, FileFormatVersions fileFormat)
        {
            BinaryFormatter binaryFormatter = new BinaryFormatter();
            
            // This is the original line of code that lead to the exception thrown later.
            // binaryFormatter.AssemblyFormat = System.Runtime.Serialization.Formatters.FormatterAssemblyStyle.Full;

            // This is the changed line of code that makes it work with signed assemblies.
            binaryFormatter.AssemblyFormat = FormatterAssemblyStyle.Simple;

            // This is the line of code that originally produced the exception because the assembly that was
            // used originally to serialize the document could not be found.
            var simpleTypeRestrictions = (SimpleTypeRestrictions)(binaryFormatter.Deserialize(stream));

            foreach (var simpleType in simpleTypeRestrictions.SimpleTypes)
            {
                simpleType.FileFormat = fileFormat;
            }
            return simpleTypeRestrictions;
        }
```
By the way, the Serialize method in that same class also uses the same value for `AssemblyFormat`. 
```
        internal void Serialize(Stream stream)
        {
            // simpletypes
            // use BinaryFormatter to serialize 
            BinaryFormatter binaryFormatter = new BinaryFormatter();
            binaryFormatter.AssemblyFormat = System.Runtime.Serialization.Formatters.FormatterAssemblyStyle.Full;
            binaryFormatter.Serialize(stream, this);
        }
```
I'm not sure whether that creates an issue (e.g., because it is used "upstream"). 

@ron1010 and @EricWhiteDev, we should certainly reopen the issue and fix it.
