### ISSUE TITLE
static method AttributeTranslator.DicOfTranslators is not thread safe

### ISSUE THREAD

**Issue by proff** [OfficeDev/Open-XML-SDK#480]
![default](https://user-images.githubusercontent.com/991922/38667774-f6e171e8-3e4a-11e8-929a-48dfa5398f2d.png)
When loading excel files from different threads this method can be executed at same time. On screenshot we got race condition when inserting tblLook in non thread safe class Dictionary

**Comment by twsouthwick** [comment]
The SDK is not guaranteed to be threadsafe. I've been slowly adding better synchronization/reduction of state to help it work better in a threaded environment, but since it was not designed initially to be threadsafe, it's a slow process. Can you provide a test that shows the exact scenario you are doing?

**Comment by twsouthwick** [comment]
I took a quick look and can definitely see a possible cause (lots of unsynchronized read/write). A repro would help ensure it's a full fix, but is probably not necessary if it's hard to create (which a lot of multi-threaded issues tend to be)

**Comment by twsouthwick** [comment]
I've marked this as up-for-grabs - should be a fairly easy fix. The `dicOfTranslators` can be preinitialized. If @proff or anyone else is interested, let me know and I'll assign you to it.

**Comment by twsouthwick** [comment]
@proff I've submitted a fix for this. It turned out to be many kinds of wrong with multiple ways of entering race conditions. I completely redesigned this feature and it should work much more reliably. Thanks for notifying us of this issue!
