### ISSUE TITLE
No support for commentsIds part in master or Office2016 branches

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#484]
**Description**

There is currently no support for the `commentsIds.xml` part and related `w16cid:commentsIds` and `w16cid:commentId` elements.

**Information**

Status as of April 14, 2018:

- master at abbca550c814ead5935862786727ad8ae1328cd1
- feature/office2016 at bf8833877c17b95d6d31f1746b2b0b3de76f0cae

**Repro**

Office 2016 creates a `commentsIds.xml` part next to the `comments.xml` and `commentsExtended.xml` parts. Simplified example (with unnecessary namespace declarations removed):

```xml
<w16cid:commentsIds xmlns:w16cid="http://schemas.microsoft.com/office/word/2016/wordml/cid">
  <w16cid:commentId w16cid:paraId="6C038D6C" w16cid:durableId="1E791E73"/>
  <w16cid:commentId w16cid:paraId="2E0CD699" w16cid:durableId="1E7B8259"/>
  <w16cid:commentId w16cid:paraId="5CE268F4" w16cid:durableId="1E7B8840"/>
</w16cid:commentsIds>
``` 

**Observed**

There is currently no (direct) way of creating the above part with the Open XML SDK.

**Expected**

As part of its Office 2016 support, the Open XML SDK provides a way to create that part and also offers strongly typed classes for the `w16cid:commentsIds` and `w16cid:commentId` elements.

**Comment by twsouthwick** [comment]
I believe work to support 2016 is planned for June/July. @tomjebo Can you comment on this?

**Comment by ThomasBarnekow** [comment]
Is there any update on this?

**Comment by twsouthwick** [comment]
The ball is rolling on it, but it requires coordination among a few times which has been slow. Hopefully we'll have something to share soon.

**Comment by ThomasBarnekow** [comment]
@twsouthwick and @tomjebo Just checking whether there are any news on this.

**Comment by tomjebo** [comment]
@ThomasBarnekow We are currently working on getting the remainder of 2016 support built in the SDK. There were scheduling issues during the summer but we now are starting work on it. No ETA right now but hoping for the next couple months, maybe end of year.

**Comment by ThomasBarnekow** [comment]
@twsouthwick and @tomjebo, just checking whether this has already been done and just not reflected by closing this issue.

**Comment by twsouthwick** [comment]
I don't see the this part in the generated code. @tomjebo Can you check to see if there's schema info we're missing?
