### ISSUE TITLE
OpenXmlSimpleType children do not implement equality

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#485]
**Description**

Classes like `StringValue` and `HexBinaryValue` do not implement equality and you must use their `Value` properties to compare them. This is not handy and can lead to unexpected results.

**Information**

- .NET Target: Any
- DocumentFormat.OpenXml Version: 2.8.1

**Repro**

```csharp
using System.Collections.Generic;
using System.Linq;
using DocumentFormat.OpenXml;
using Xunit;

namespace DocumantFormat.OpenXml.Tests
{
    public class OpenXmlSimpleValueTests
    {
        private const string HexBinary = "12345678";
        private const string Value = "Hello World";

        [Fact]
        public void HexBinaryValue_ValuesAreEqual_HexBinaryValuesAreNotEqual()
        {
            var hexBinaryValue1 = new HexBinaryValue(HexBinary);
            var hexBinaryValue2 = new HexBinaryValue(HexBinary);

            Assert.Equal(hexBinaryValue1.Value, hexBinaryValue2.Value);

            // Those two HexBinaryValue instances should be deemed equal.
            Assert.NotEqual(hexBinaryValue1, hexBinaryValue2);
        }

        [Fact]
        public void HexBinaryValue_ValueIsContainedInList_ListDoesNotContainHexBinaryValue()
        {
            var hexBinaryValues = new List<HexBinaryValue>
            {
                new HexBinaryValue(HexBinary),
                new HexBinaryValue("ABCDEF00")
            };

            var hexBinaryValue = new HexBinaryValue(HexBinary);

            Assert.Contains(hexBinaryValue.Value, hexBinaryValues.Select(hbv => hbv.Value));

            // The HexBinaryValue should be deemed contained in the list.
            // The fact that this wasn't the case was a gotcha.
            Assert.DoesNotContain(hexBinaryValue, hexBinaryValues);
        }

        [Fact]
        public void StringValue_ValuesAreEqual_StringValuesAreNotEqual()
        {
            var stringValue1 = new StringValue(Value);
            var stringValue2 = new StringValue(Value);

            Assert.Equal(stringValue1.Value, stringValue2.Value);

            // The two StringValue instances should be deemed equal.
            Assert.NotEqual(stringValue1, stringValue2);
        }
    }
}
``` 

**Observed**

Two distinct instances of `HexBinaryValue` or `StringValue`, for example, will not be deemed equal even if their values are equal.

**Expected**

Given two distinct instances of `HexBinaryValue`, when the `Value` properties of those instances are equal, then those `HexBinaryValue` instances should be deemed equal as well.

The same should apply to other child classes of `OpenXmlSimpleType` such as `StringValue`.

**Comment by twsouthwick** [comment]
This is a great point. Are you suggesting implementing `Equals(object)` and `GetHashCode()`?

**Comment by ThomasBarnekow** [comment]
@twsouthwick Yes, those two at least. Looking at the `string` and `int` types for inspiration, we should also consider:

- `IComparable`,
- `IComparable<T>`, and
- `IEquatable<T>`.

**Comment by twsouthwick** [comment]
That sounds good to me. Can you prepare a PR for this?

**Comment by ThomasBarnekow** [comment]
Yes, can do.

**Comment by ThomasBarnekow** [comment]
Just to be sure, are you considering to pull into master or 3.x?

This shouldn't be a breaking change, so could create feature branch off of master for PR into master.

**Comment by twsouthwick** [comment]
@ThomasBarnekow thanks for the contribution!
