### ISSUE TITLE
Unit tests failing due to missing CultureInfo.InvariantCulture in ToString()

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#488]
**Description**

The following unit tests fail on machines that do not use the US locale (invariant culture):

- DecimalValueTest
- DoubleValueTest
- SingleValueTest

**Information**

The issue can be observed on machines not configured to use the en-US locale (or similar locales with identical number formats).

**Repro**

Set your locale to de-DE, for example, making sure your local number format is different from the en-US format. For example, "one thousand decimal 5" would be formatted like:

- 1,000.5 in the US (using a comma to separate thousands a point as the decimal separator) and
- 1.000,5 in Germany (using a point to separate thousands and a comma as the decimal separator).

Simply using `number.ToString()` will produce different results for different cultures. To get the same result when comparing numbers in string format on machines with different locale / culture settings, you must use `number.ToString(CultureInfo.InvariantCulture)`.

**Observed**

The above-mentioned unit tests fail on machines using number formats different from those used in the US (invariant culture).

**Expected**

The above-mentioned unit tests pass regardless of the local number formats.

**Comment by twsouthwick** [comment]
Is this a problem with just the unit tests or is there an issue with the parsing of the SDK?

**Comment by ThomasBarnekow** [comment]
It was just a problem with the unit tests. The expected values produced by using `number.ToString()` rather than `number.ToString(CultureInfo.InvariantCulture)` depended on the culture settings of the machine on which those unit tests were run.
