### ISSUE TITLE
Support for isNarration element 

### ISSUE THREAD

**Issue by MihailRomanov** [OfficeDev/Open-XML-SDK#489]
I can't find SDK class for [isNarration element](https://msdn.microsoft.com/en-us/library/dn912522%28v=office.12%29.aspx) 

This element widely used in [OfficeMix](https://mix.office.com) extension.

Can you help me? May be have some workaround (except direct xml reading)?

Thanks

**Comment by ThomasBarnekow** [comment]
If there are no strongly typed classes, you would have to resort to XML, e.g., using Linq to XML as in the PowerTools for Open XML.
