### ISSUE TITLE
Test cases failing under circumstances to be determined

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#49]
Depending on where tests are run (e.g., AppVeyor or certain other machines vs. my machine), either all tests pass or just a few tests fail.

This is the result I'm getting when running the tests in `System.IO.Packaging.Tests.dll`, using the `build.open-xml-sdk.cmd` build script:

```
xUnit.net console test runner (64-bit .NET 4.0.30319.34209)
Copyright (C) 2015 Outercurve Foundation.

Discovering: System.IO.Packaging.Tests
Discovered:  System.IO.Packaging.Tests
Starting:    System.IO.Packaging.Tests
   System.IO.Packaging.Tests.Tests.T170_InvalidRelationshipId [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Xml.XmlException)
      Actual:   typeof(System.ArgumentNullException): Value cannot be null.
      Parameter name: format
      Stack Trace:
            at System.String.Format(String format, Object arg0)
         System.IO.Packaging\InternalRelationshipCollection.cs(188,0): at System.IO.Packaging.InternalRelationshipCollection.ThrowIfInvalidXsdId(String id)
         System.IO.Packaging\Package.cs(618,0): at System.IO.Packaging.Package.DeleteRelationship(String id)
Finished:    System.IO.Packaging.Tests

=== TEST EXECUTION SUMMARY ===
   System.IO.Packaging.Tests  Total: 122, Errors: 0, Failed: 1, Skipped: 0, Time: 2,307s
```

That same build script also runs the tests contained in the `DocumentFormat.OpenXml.Tests.dll`:

```
xUnit.net console test runner (64-bit .NET 4.0.30319.34209)
Copyright (C) 2015 Outercurve Foundation.

Discovering: DocumentFormat.OpenXml.Tests
Discovered:  DocumentFormat.OpenXml.Tests
Starting:    DocumentFormat.OpenXml.Tests
   DocumentFormat.OpenXml.Tests.XlsxTests01.X001_XlsxValidation [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   20
      Stack Trace:
         DocumentFormat.OpenXml.Tests\TestXlsx01.cs(203,0): at DocumentFormat.OpenXml.Tests.XlsxTests01.XlsxValidationHelper(String docName, Int32 expectedErrorCount)
   DocumentFormat.OpenXml.Tests.XlsxTests01.X006_Xlsx_DeleteAdd_CoreExtendedProperties [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   7
      Stack Trace:
         DocumentFormat.OpenXml.Tests\TestXlsx01.cs(82,0): at DocumentFormat.OpenXml.Tests.XlsxTests01.X006_Xlsx_DeleteAdd_CoreExtendedProperties()
   DocumentFormat.OpenXml.Tests.XlsxTests01.X007_SpreadsheetDocument_Open [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   7
      Stack Trace:
         DocumentFormat.OpenXml.Tests\TestXlsx01.cs(53,0): at DocumentFormat.OpenXml.Tests.XlsxTests01.X007_SpreadsheetDocument_Open()
   DocumentFormat.OpenXml.Tests.XlsxTests01.X004_SpreadsheetDocument_Open [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   7
      Stack Trace:
         DocumentFormat.OpenXml.Tests\TestXlsx01.cs(119,0): at DocumentFormat.OpenXml.Tests.XlsxTests01.X004_SpreadsheetDocument_Open()
   DocumentFormat.OpenXml.Tests.XlsxTests01.X008_XlsxCreation_Package_Settings [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   7
      Stack Trace:
         DocumentFormat.OpenXml.Tests\TestXlsx01.cs(35,0): at DocumentFormat.OpenXml.Tests.XlsxTests01.X008_XlsxCreation_Package_Settings()
   DocumentFormat.OpenXml.Tests.XlsxTests01.X005_XlsxCreation_Package_Settings [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   7
      Stack Trace:
         DocumentFormat.OpenXml.Tests\TestXlsx01.cs(101,0): at DocumentFormat.OpenXml.Tests.XlsxTests01.X005_XlsxCreation_Package_Settings()
Finished:    DocumentFormat.OpenXml.Tests

=== TEST EXECUTION SUMMARY ===
   DocumentFormat.OpenXml.Tests  Total: 82, Errors: 0, Failed: 6, Skipped: 0, Time: 23,101s
```

Thus, while all these tests pass on other machines, the above tests consistently fail on my machine.

In another situation that we are currently discussing in #48, validation of a workbook on my machine shows two validation errors while no errors are shown when @ron1010 performs the same validation.

@EricWhiteDev, we should look into this. Not sure whether that is related to differences in localization, for example. If you remember there's one fix I've done to the `HtmlConverter` in OxPt, explicitly using the neutral culture for converting numbers to strings (with decimal points rather than commas customary in certain countries).

**Comment by ron1010** [comment]
@ThomasBarnekow , the System.IO.Packaging tests all pass for me. I am in AU. Please let me know if I can help with getting the tests working. Where are the tests for Open-XML-SDK? I would add the Validation issue I am having to them if I could.

**Comment by EricWhiteDev** [comment]
With regards to the exception thrown in System.IO.Packaging - I believe that in some error circumstance (and only on some platforms), the XmlReader throws an ArgumentNullException instead of an XmlException.  I will go into System.IO.Packaging, see if my theory is correct, and dig down to where the erroneous ArgumentNullException is being thrown, and then throw the right exception.

The Open XML SDK errors are more interesting.  It appears that calling the validation functionality on a specific set of documents is behaving differently.  The theory is that when you validate for a specific document, for a specific version of Office, you will receive an exact set of errors.  One possible theory: we might be seeing symptoms of different exceptions being thrown at a deeper level?  This needs research.

One idea with this - how would it work if we changed the tests to serialize the exceptions into string, and made this the expected value?  Then if the actual value changed, we could see what is different in the test result directly.  But it may not be cool to have a longer string for expected / actual.

I don't think this is related to the changes to HtmlConverter.

**Comment by ThomasBarnekow** [comment]
@EricWhiteDev, I've had a brief look at the System.IO.Packaging related test. The `ArgumentNullException` is thrown by this method:
```
        // If 'id' is not of the xsd type ID, throw an exception.
        internal static void ThrowIfInvalidXsdId(string id)
        {
            Debug.Assert(id != null, "id should not be null");

            try
            {
                // An XSD ID is an NCName that is unique.
                XmlConvert.VerifyNCName(id);
            }
            catch (XmlException exception)
            {
                var r = SR.NotAValidXmlIdString;  // TB: SR.NotAValidXmlIdString returns null
                var s = SR.Format(r, id);  // SR.Format(null, id) throws
                throw new XmlException(s, exception);
            }
        }
```
You should check `SR.NotAValidXmlIdString`. There is an issue with the resources. In the following method of the `SR` class, a `MissingManifestResourceException` is thrown when calling `ResourceManager.GetString`. Therefore, the method returns `null`, which later leads to the `ArgumentNullException`.
```
        internal static string GetResourceString(string resourceKey, string defaultString)
        {
            string resourceString = null;
            try { resourceString = ResourceManager.GetString(resourceKey); }
            catch (MissingManifestResourceException) { }

            if (defaultString != null) // todo ew
            {
                return defaultString;
            }

            return resourceString;
        }
```

This is the exception message:

> Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "FxResources.System.IO.Packaging.SR.resources" was correctly embedded or linked into assembly "System.IO.Packaging" at compile time, or that all the satellite assemblies required are loadable and fully signed.

Like for the `HtmlConverter` (otherwise unrelated to this issue here) there seems to be an issue with the "specified culture" (or the lack of an explicit specification). You have likely done (or not done) something, that does not surface as an issue with your configuration / locale / culture. But it does surface with my regional settings (for Germany). 

It is likely that the 6 failed tests within the `DocumentFormat.OpenXml.Tests` project have the same root cause (because @EricWhiteDev and @ron1010 don't see them on their machines).

@EricWhiteDev, as you have so many test machines, you should really configure them differently, using different regional settings, etc.

**Comment by EricWhiteDev** [comment]
Alternatively, we could write a new set of tests that sequence through all regional settings and cultures within the test module, running the same test while changing the regional settings and culture.  The expectation is that tests should return the same results no matter what regional settings and culture are set.  We can supply it with a reasonable set of test documents (both valid and invalid), doing validation on each one against all settings, results should always be the same.

I believe that I can do this directly in the test, and it is not necessary to set up virtual machines.  True?

This issue is probably only applies to the validation functionality of the SDK.  The other classes that enable creation of the DOM tree don't have much functionality in them.  I don't think their behavior changes with changes in regional settings and culture, but it is easy enough to test.

**Comment by EricWhiteDev** [comment]
Regarding the resources issue, this is good to know.  This should be easy to fix.

**Comment by ThomasBarnekow** [comment]
@EricWhiteDev, I don't know whether you can change regional settings in those unit tests. You would have to make sure this all looks like the tests are run on a German, French, Swedish, Chinese, etc. Windows instance. On CI servers, we'd be talking about a "test matrix", trying out different combinations of OSes, regional settings, 32 vs. 64 bit, etc.

**Comment by akoeplinger** [comment]
FWIW, I see the same T170_InvalidRelationshipId test fail here on de-AT culture, but interestingly the DocumentFormat.OpenXml.Tests all pass.

**Comment by ThomasBarnekow** [comment]
@akoeplinger, can you tell me a bit more about your machine (e.g., OS version, .NET Framework installed)? I'm running Windows 7, .NET Framework 4.5.2, with German regional settings (de-DE).

If the DocumentFormat.OpenXml.Tests all pass on your machine, we are likely talking about a different issue. But it's still strange.

**Comment by akoeplinger** [comment]
@ThomasBarnekow Windows 8.1, .NET Framework 4.6, de-AT regional settings. I agree it's a bit weird :)

**Comment by ThomasBarnekow** [comment]
@EricWhiteDev, how about your configuration? Is it possible that those differences are due to different .NET Frameworks or even OS versions?

**Comment by ThomasBarnekow** [comment]
@EricWhiteDev and @akoeplinger, I found the bug that lead to the six failed tests (on my machine) within DocumentFormat.OpenXml.Tests. And let me say that this is __exactly__ the same issue that I also fixed in `HtmlConverter` in the PowerTools for Open XML.

The bug is in `SemanticConstraint.GetAttrNumVal` and is due to a wrong approach in converting strings to numbers:
```
protected static bool GetAttrNumVal(OpenXmlSimpleType attributeValue, out double value)
{
    HexBinaryValue hexBinaryValue = attributeValue as HexBinaryValue;
    if (hexBinaryValue != null)
    {
        long val = -1;
        bool result;

        result = long.TryParse(hexBinaryValue.Value, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out val);
        value = (double)val;

        return result;
    }
    else
    {
        // This is the original code. It converts a string to a double using the current culture.
        // return double.TryParse(attributeValue.InnerText, out value);

        // This is the fix. It converts the string using the invariant culture. 
        return double.TryParse(attributeValue.InnerText, NumberStyles.AllowDecimalPoint,
            CultureInfo.InvariantCulture, out value);
    }
}
```
With the fix, all six tests pass.

I will create a pull request for this fix...

**Comment by akoeplinger** [comment]
@ThomasBarnekow yep, TryParse() without specifying InvariantCulture is wrong since we deal with a fixed format. Are there other similar TryParse() calls in the codebase?

**Comment by ThomasBarnekow** [comment]
@akoeplinger I've not seen another related to decimal numbers (i.e., double, float, decimal).

**Comment by ThomasBarnekow** [comment]
Hi @EricWhiteDev,

> Regarding the resources issue, this is good to know. This should be easy to fix.

How and when can we fix this? I've played a bit with resource files and found that this issue is due to a missing resource file. Do you have that resource file or would it have to be created?

**Comment by tomjebo** [comment]
@ThomasBarnekow Please resync, build and rerun. We've since removed System.IO.Packaging and the tests should be running. If you still have problems with the tests, please reopen the issue.
