### ISSUE TITLE
Incorrect XML documentation comment for 'OpenXmlBasePart.OpenXmlPackage'

### ISSUE THREAD

**Issue by glenn-slayden** [OfficeDev/Open-XML-SDK#511]
The following source code XML comment (which likely propagates to the developer documentation, though I didn't verify that) is incorrect (and somewhat illogical):

https://github.com/OfficeDev/Open-XML-SDK/blob/601492385e0130f63b39ac1735d58d3a394e3a69/src/DocumentFormat.OpenXml/Packaging/OpenXmlBasePart.cs#L265-L268

This should instead read: **"Gets the OpenXmlPackage which contains the current part."**

The suggested text is taken from the (correct) XML documentation for the `OpenXmlPackage` property in the `OpenXml.Packaging.DataPart` class:

https://github.com/OfficeDev/Open-XML-SDK/blob/601492385e0130f63b39ac1735d58d3a394e3a69/src/DocumentFormat.OpenXml/Packaging/DataPart.cs#L42

**Comment by twsouthwick** [comment]
Can you submit a PR for this? Thanks!

**Comment by glenn-slayden** [comment]
@twsouthwick  I could try, but I'm not yet fully comfortable with my git competency yet and have never gone through a contribution process...

**Comment by twsouthwick** [comment]
That's fine - we can help you through the process. Changes like this are the best to start with since they're small :) For this change, you could do it all online by clicking the 'Edit' button in the file you found has the doc issue. If you need any help, feel free to ask on here
