### ISSUE TITLE
Change in multiple rows in table highlight all table as changed

### ISSUE THREAD

**Issue by ObadMahrous** [OfficeDev/Open-XML-SDK#513]
# Before submitting an issue, please fill this out

Is this a:
- [x] Issue with the OpenXml library
- [x] Question on library usage

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

---------------- Remove this line and above before posting ----------------

**Description**

Please provide a simple description of the issue encountered.

**Information**

- .NET Target: (ie .NET Framework, .NET Core, UWP, Xamarin, etc)
- DocumentFormat.OpenXml Version: (ie 2.7.2)

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
``` 

**Observed**

Please add your observed behavior here

**Expected**

Please add your expected behavior here.

**Comment by ThomasBarnekow** [comment]
@ObadMahrous, you did not provide any details on this issue, so we can’t look into it.

Please have a look at what you are asked to provide, i.e., Description, Information, Repro, Observed, and Expected, and provide that information.

**Comment by ObadMahrous** [comment]
@ThomasBarnekow  When i need to make comparison between two documents and the document content is table consist of multiple rows and columns which this table is split into multiple pages
only i made some changes in some values of cells in specific rows.
after performing the compare then the result is highlighting all rows in the table as changed.
only i need to highlight the specific rows that are changed.

**Comment by ObadMahrous** [comment]
@ThomasBarnekow  so the expected result is highlighting only the changed rows not all rows.

**Comment by ObadMahrous** [comment]
@ThomasBarnekow Could you please tell me if you got what i mean

**Comment by ThomasBarnekow** [comment]
@ObadMahrous, please have a look at #509 for an example on how to provide the required detail. This is basically the form that you submitted when you created this issue, however with the detail we need to look into it.

Also think about whether this is really related to the Open XML SDK rather than the PowerTools or something else (e.g., Microsoft Word). From what you wrote, I don’t understand what exactly the issue is and how to reproduce it.

**Comment by twsouthwick** [comment]
@ObadMahrous you can edit the original post with the repro information

**Comment by ThomasBarnekow** [comment]
@twsouthwick, I think this issue can be closed.
