### ISSUE TITLE
 Could not load assembly 'System.IO.Packaging' during Xamarin startup registration

### ISSUE THREAD

**Issue by jason8232590** [OfficeDev/Open-XML-SDK#517]
-**Description**

I created a new project in Visual Studio 2017 for windows (15.5.4) and import the 'DocumentFormat.OpenXml(2.8.1)' then debug it , but it  could not be debugged in My android phone. And once I remove it , the app can work well in android phone . By the way , it could still work well in iPhone even I had imported 'DocumentFormat.OpenXml(2.8.1)' .

**Information**

- Xamarin.Forms (2.5.0121934)
- DocumentFormat.OpenXml Version: (2.8.1)

**Log**
07-25 11:29:10.266 F/monodroid-assembly(26905): Could not load assembly 'System.IO.Packaging' during startup registration.
07-25 11:29:10.266 F/monodroid-assembly(26905): This might be due to an invalid debug installation.
07-25 11:29:10.266 F/monodroid-assembly(26905): A common cause is to 'adb install' the app directly instead of doing from the IDE.

**Comment by tomjebo** [comment]
@jason8232590 take a look at this: [https://github.com/Microsoft/msbuild/issues/2776#issuecomment-358038589](https://github.com/Microsoft/msbuild/issues/2776#issuecomment-358038589 )
Seems like this might be related to that issue. There are a couple of workarounds that folks have tried there. I can also try reproducing this if the above thread doesn't help. 
@twsouthwick does that sound right? any other ideas?

**Comment by twsouthwick** [comment]
@jason8232590 Can you share what your csproj/vbproj looks like?

**Comment by twsouthwick** [comment]
Also, can you try updating VS? Looks like some of the linked issues have the milestone of 15.7

**Comment by jason8232590** [comment]
@twsouthwick  
Thanks for your reply !
Here is the "csproj" file. 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.8.1" />
    <PackageReference Include="System.IO.Packaging" Version="4.5.0" />
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.121934" />
  </ItemGroup>

  <ItemGroup>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="App.xaml.cs">
      <DependentUpon>*.xaml</DependentUpon>
    </Compile>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="MainPage.xaml.cs">
      <DependentUpon>*.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>

By the way , I don't want to update the visual studio unless it is the only way to solve this problem ,because I find the new version usually can not support the project what build on old version well enough.

**Comment by jason8232590** [comment]
@twsouthwick
Thanks for your reply !
Here is the "csproj" file.
`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.8.1" />
    <PackageReference Include="System.IO.Packaging" Version="4.5.0" />
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.121934" />
  </ItemGroup>

  <ItemGroup>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="App.xaml.cs">
      <DependentUpon>*.xaml</DependentUpon>
    </Compile>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="MainPage.xaml.cs">
      <DependentUpon>*.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>`



By the way , I don't want to update the visual studio unless it is the only way to solve this problem ,because I find the new version usually can not support the project what build on old version well enough.

**Comment by jason8232590** [comment]
@twsouthwick 
Thanks for your reply !
Here is the "csproj" file.
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="2.8.1" />
    <PackageReference Include="System.IO.Packaging" Version="4.5.0" />
    <PackageReference Include="Xamarin.Forms" Version="2.5.0.121934" />
  </ItemGroup>

  <ItemGroup>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="App.xaml.cs">
      <DependentUpon>*.xaml</DependentUpon>
    </Compile>
    <Compile Condition=" '$(EnableDefaultCompileItems)' == 'true' " Update="MainPage.xaml.cs">
      <DependentUpon>*.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>

```
By the way , I don't want to update the visual studio unless it is the only way to solve this problem ,because I find the new version usually can not support the project what build on old version well enough.

**Comment by twsouthwick** [comment]
Well, the fix appears to have been put in a later VS, so I don't know if there's much we can do without you upgrading. You can always stand up a VM in Azure (there are prebuilt machines for this: https://docs.microsoft.com/en-us/visualstudio/install/using-visual-studio-vm).

> I find the new version usually can not support the project what build on old version well enough.

Can you explain what this means? Have you had specific issues in the past?

**Comment by jason8232590** [comment]
@twsouthwick   I have tried updating IDE and now it can run on my android when I only just import "DocumentFOrmat.OpenXML".  By the way , the new version IDE predictably caused some other issues as usual  . It even can not run the project what new from the IDE . Here is  the error log .

```
The "Xamarin.Forms.Build.Tasks.GetTasksAbi" task could not be loaded from the assembly C:\xxxxxx\xamarin.forms\3.0.0.561731\build\netstandard2.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	Text0731.Android	
```
Finally , I downgraded Xamarin.Forms then solved the problem . I think the compatibility of IDE and some libraries(such as Xamarin.Forms) for Xamarin isn't  well enough .  I wonder whether it is a strategy to let developers update their IDE or not . Anyway , thanks for you suggestion .
