### ISSUE TITLE
I have a question, who can help me?

### ISSUE THREAD

**Issue by xiangxingze** [OfficeDev/Open-XML-SDK#518]
Sorry for disturbing you!
Open XML SDK is similar to Microsoft.Office.Interop.Word
How to move the cursor to wrap
Object extend = Word.WdMovementType.wdExtend;
                 Object unit = Word.WdUnits.wdCell;
                 Object count = 1;
                 wApp.Selection.MoveRight(ref unit, ref count, ref extend);

**Comment by twsouthwick** [comment]
As @daniel-white said, this is a question that would be better asked on StackOverflow. This repo is for issues in the SDK. Thanks!
