### ISSUE TITLE
rsid related issue for insert picture to Word with openxml sdk

### ISSUE THREAD

**Issue by guyuming76** [OfficeDev/Open-XML-SDK#523]
https://social.msdn.microsoft.com/Forums/en-US/92a94048-3339-4943-90e0-03fe8d0632a9/cannot-open-docx-after-inserting-picture-with-openxml-problem-with-partworddocumentxml?forum=os_binaryfile#65fb63fb-7ce4-4521-acf2-3b9a7551c302

**Comment by tomjebo** [comment]
@guyuming76 can you please add the description and provide simplified code so that we can reproduce this?

**Comment by tomjebo** [comment]
@guyuming76 I'm closing this for now. If you still need help please post some code that reproduces the issue so we can investigate.
