### ISSUE TITLE
Detect pending track changes in excel using open xml 

### ISSUE THREAD

**Issue by smithapk** [OfficeDev/Open-XML-SDK#524]
# Before submitting an issue, please fill this out

Is this a:

- [x] Question on library usage -Yes

**Description**

Requirement :

                               Read pending track changes from excel which are not yet accepted or rejected

Problem Statement:

                             There is no tag to identify directly whether a track revision is accepted or rejected  in revision log .
                           

Assessment
          
                               Reached in  below assessment after analyzing  revision log  xml files  and revision headers xml files
       
•	There will be revision log corresponding to each revision (eg : revisionLog1.xml,…. revisionLog6.xml)  
         
                                                  This contains revision Id (rId) and cell details(eg: A1) of each revision 
        
•	There is a  revisionheadrs.xml file 
There exists a revision header corresponding to each  revision log 

By correlating these two xml files with “rId” value we will get a unique record 

Last child of this record will have  reviewed tag if it is accepted or rejected

                                    But there are some cases  this logic is failing

                                             I analyzed the xml files of failing excel sheet
                                              
•	If there are more than one values (current value and previous values ) in accept or reject window for a cell .
                                             if it is listing 4 records and I am accepting 2nd one 
                                             After accepting if again I  click this cell to accept or reject it will show a message -    There are no more pending changes to review
                                             In this case maximum revision id comparison for each cell will fail 

                                                     <header guid="{9C3108F2-0497-4372-915B-71E20B8531C3}" dateTime="2018-09-28T18:55:28" maxSheetId="2" userName="Smitha Puzhamkunnu" r:id="rId5" minRId="4"><sheetIdMap count="1"><sheetId val="1"/></sheetIdMap>
                                            <reviewedList count="1"><reviewed rId="4"/></reviewedList></header>                                             
                                           
                                             In this scenario rId="4" is the last node . but the max rev id is  "rId5"  .
                                            So it is showing incorrect result   -    There are pending changes to review
                                         
•	If we select accept all   or if we accept the last text  of a particular cell from accept or reject window the above  logic will work

Implementation details

                                        List<XmlElement> xmlElmnt = new List<XmlElement>();
                    List<string> xmlInnerList = new List<string>();
                    List<int> dicindexlist = new List<int>();
                    dicindexlist.Add(-1);
                    foreach (DocumentFormat.OpenXml.Packaging.WorkbookRevisionLogPart logpart in document.WorkbookPart.WorkbookRevisionHeaderPart.WorkbookRevisionLogParts)
                    {
                        var innerxml = logpart.Revisions.InnerXml;
                        innerxml = "<xmlroot>" + innerxml + "</xmlroot>";
                        xmlInnerList.Add(innerxml);

                    }
                    foreach (string innerelement in xmlInnerList)
                    {
                        XmlDocument xdoc = new XmlDocument();
                        xdoc.LoadXml(innerelement);
                        int ridvalue = 0;
                        for (int k = 0; k < xdoc.ChildNodes.Count; k++)
                        {
                            var node1 = xdoc.ChildNodes[k];
                            for (int cnt = 0; cnt < node1.ChildNodes.Count; cnt++)
                            {
                                var innernode = node1.ChildNodes[cnt];
                                if (innernode.LocalName == "rcc")
                                {
                                    var attributes = innernode.Attributes;
                                    var ridval = attributes.GetNamedItem("rId");
                                    //ridvalue = ridval.LocalName + ridval.InnerText;
                                    ridvalue = Convert.ToInt32(ridval.InnerText);
                                }
                                for (int x = 0; x < innernode.ChildNodes.Count; x++)
                                {
                                    var node2 = innernode.ChildNodes[x];
                                    var node2Attributes = node2.Attributes;
                                    var callidval = node2Attributes.GetNamedItem("r");
                                    if (!DicXmlValues.ContainsKey(ridvalue))
                                    {
                                        DicXmlValues.Add(ridvalue, callidval.InnerText);
                                    }
                                    break;
                                }

                            }

                        }
                    }
                    Dictionary<int, string> dicval = new Dictionary<int, string>();
                    foreach (KeyValuePair<int, string> xmlval in DicXmlValues.OrderBy(key => key.Value))
                    {

                        dicval.Add(xmlval.Key, xmlval.Value);
                    }

                    List<int> indexlist = new List<int>();

                    for (int d = 0; d < dicval.Count - 1; d++)
                    {
                        if (dicval.ElementAt(d).Value != dicval.ElementAt(d + 1).Value)
                        {
                            dicindexlist.Add(d);

                            indexlist.Add(dicval.ElementAt(d).Key);
                        }
                    }
                    dicindexlist.Add(dicval.Count - 1);
                    for (int index1 = 0; index1 < dicindexlist.Count - 1; index1++)
                    {

                        int endindex = dicval.Count - ((dicval.Count - dicindexlist[index1 + 1]));
                        int startindex = endindex - (dicindexlist[index1 + 1] - (dicindexlist[index1] + 1));
                        Dictionary<int, string> resultdicval = new Dictionary<int, string>();
                        Dictionary<int, string> orderedresultdicval = new Dictionary<int, string>();
                        for (int index2 = startindex; index2 <= endindex; index2++)
                        {

                            resultdicval.Add(dicval.ElementAt(index2).Key, dicval.ElementAt(index2).Value);

                        }
                        foreach (KeyValuePair<int, string> indxval in resultdicval.OrderBy(x => x.Key))
                        {

                            orderedresultdicval.Add(indxval.Key, indxval.Value);
                        }
                        int indxmaxvalue = orderedresultdicval.Keys.Max();
                        string rlVal = "rId" + indxmaxvalue;

                        foreach (DocumentFormat.OpenXml.Spreadsheet.Header hdr in document.WorkbookPart.WorkbookRevisionHeaderPart.Headers)
                        {
                            if (rlVal == hdr.Id)
                            {
                                headerrecored = hdr;
                                var rec = headerrecored.LastChild;
                                if (rec.LocalName != "reviewedList")
                                {
                                    pendingchanges = pendingchanges + 1;
                                }
                                break;
                            }
                        }
                    }
                    string msg = "";
                    if (pendingchanges > 0)
                    {
                         msg = "There are pending changes to review";
                    }
                    else
                    {
                         msg = "There are no more pending changes to review";
                    }
                                         https://social.msdn.microsoft.com/Forums/office/en-US/253c2315-f954-4e39-b30b-e10fbddf685c/how-to-get-track-changes-which-are-not-accepted-or-rejected-in-excel?forum=oxmls

                                         https://social.msdn.microsoft.com/Forums/office/en-US/2848801d-a8b2-4dc4-a4ce-39a7c74cabee/open-xml-excel-to-detect-track-changes?forum=oxmlsdk
                                           
                                         https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2010/cc797468(v=office.14)

Open Questions
                              
                    
1.	How can we identify whether a revision is accepted or rejected directly from revision log in excel .
2.	How can we get only the pending track changes which are not accepted or rejected 

**Information**

.NET FRAMEWORK  4.5
DocumentFormat.OpenXml Version  - 2.8.1.15

``` 

**Observed**
There is no way to identify whether a particular track change is accepted ,rejected or pending for  review directly from program

**Expected**

Need to get pending track changes which is not yet accepted or rejected

**Comment by tomjebo** [comment]
@smithapk thanks for detailing this issue and requesting an attribute. I'll take a look. you might also want to check with StackOverflow.

**Comment by smithapk** [comment]
@tomjebo  Thank you for the input.
We are able to progress by considering revision history  and time stamp for each revision.
Currently I used an approach of verifying Time stamp of each header to identify  last change happened in a cell.
DateTime date1 = ((DocumentFormat.OpenXml.Spreadsheet.Header)headercollction[i]).DateTime;
DateTime date2 = ((DocumentFormat.OpenXml.Spreadsheet.Header)headercollction[i + 1]).DateTime;
int result = DateTime.Compare(date1, date2);

Based on the latest header's reviewed status considering it has reviewed
If excel is updated from different time zone, this approach will not work.
What is an alternate solution for identifying the reviewed status

Thanks,
Smitha

**Comment by smithapk** [comment]
@tomjebo    

Hi Tom,
I am getting the expected result using below code
But the issue is that  in addition to  headers and revision log  correlation  I am considering time stamp also to get the last change happened to a cell
This approach will fail if the same excel sheet is updated from different time zones as Time Stamp comparison is there to identify the last change happened to the particular cell .

We can correlate the headers.xml and revisionlog.xml using revision id and are able to find out 
changes which are not accepted/rejected.

But we should get the final change happened to particular cell, for this we used the time stamp in header log 
 
Any alternate solution is there to identify the last change happened to cell without using Time Stamp Comparison  ?

Our exact requirement is below .
 
Consider cell A1

Take an excel sheet and make Track changes On.

Cell : A1
-(1) Enter "Test"   and save changes - a revision log and header log will be created

- (2) Edit with  "Test One" and save changes  -a revision log and header log will be created

- (3) Edit with "Test one two" and save changes -a revision log and header log will be created


-Now take Accept/Reject changes option in excel 
  In Accept/Reject window 
  In this case it will show 3 values 
  "Test"
  "Test one"
  "Test one two"

-(4) We can select a text from this and click accept /reject or we can click accept all or reject all
      I selected "Test One" and click accept 
     Now another  revision log  and header log will be created  with a tag as "Reviewed" in header

After this if click accept/reject ,the output should be 

"There is no more pending changes to review "

In total 

There are 4 revisions for a particular cell " A1" in the above example 
and final state is reviewed

To get the final state now I used the timestamp  comparison

Again as fifth step If I am editing the cell again (Means edit after accept)

- (5).Edit  A1 with "Test one  three"  and save changes -a revision log and header log will be created

Now  the output should be "There is pending changes to review"

This logic should apply for all the cell changes  to identify the pending changes.     
If at least  one  cell has its final header log state is not reviewed , we can decide there exist pending changes.

   class Program
    {
        static void Main(string[] args)
        {
            DirectoryInfo parent = Directory.GetParent(Directory.GetCurrentDirectory()).Parent;
            string filepath = parent.FullName;
            string DocFilePath = Path.Combine(filepath, "Files");
            string excelfile = Path.Combine(DocFilePath, "Book1.xlsx");
            AcceptExcelRevisions(excelfile);
        }
        static int CompareDates(DocumentFormat.OpenXml.OpenXmlElement elmnt1, DocumentFormat.OpenXml.OpenXmlElement elmnt2)
        {
            return DateTime.Compare(((DocumentFormat.OpenXml.Spreadsheet.Header)elmnt1).DateTime, ((DocumentFormat.OpenXml.Spreadsheet.Header)elmnt2).DateTime);
            
        }

        public static void AcceptExcelRevisions(string fileName)
        {

            using (var document = SpreadsheetDocument.Open(fileName, false))
            {
                int pendingchanges = 0;
               
                if (document.WorkbookPart.WorkbookRevisionHeaderPart != null)
                {

                    List<DocumentFormat.OpenXml.OpenXmlElement> HeadersNotReviewed = new List<DocumentFormat.OpenXml.OpenXmlElement>();
                    List<DocumentFormat.OpenXml.OpenXmlElement> HeadersNotReviewedList = new List<DocumentFormat.OpenXml.OpenXmlElement>();
                   
                    foreach (DocumentFormat.OpenXml.Spreadsheet.Header header in document.WorkbookPart.WorkbookRevisionHeaderPart.Headers)
                    {

                        HeadersNotReviewed.Add(header.LastChild);

                    }
                    foreach (DocumentFormat.OpenXml.OpenXmlElement elmnt in HeadersNotReviewed.Where(hd => hd.LocalName != "reviewedList"))
                    {
                        HeadersNotReviewedList.Add(elmnt);
                        string id = ((DocumentFormat.OpenXml.Spreadsheet.Header)elmnt.Parent).Id.ToString();

                        string indx = id.Substring(id.Substring(0, 3).Length);
                        string str = "/xl/revisions/revisionLog";
                        int startIndex = str.Length;
                      
                        var coll = document.WorkbookPart.WorkbookRevisionHeaderPart.WorkbookRevisionLogParts.Where(i => i.Uri.OriginalString.Contains(indx));

                        foreach (DocumentFormat.OpenXml.Packaging.WorkbookRevisionLogPart logpart in coll)
                        {
                            string revstring = logpart.Uri.OriginalString;
                            int charLocation = revstring.IndexOf(".", StringComparison.Ordinal);

                            if (indx == revstring.Substring(startIndex, charLocation - startIndex))
                            {
                                var xmlstring = logpart.Revisions.InnerXml;
                                xmlstring = "<xmlroot>" + xmlstring + "</xmlroot>";
                                XmlDocument xdoc = new XmlDocument();
                                xdoc.LoadXml(xmlstring);
                                for (int k = 0; k < xdoc.ChildNodes.Count; k++)
                                {

                                    var node1 = xdoc.ChildNodes[k];
                                    for (int cnt = 0; cnt < node1.ChildNodes.Count; cnt++)
                                    {
                                        var innernode = node1.ChildNodes[cnt];

                                        for (int x = 0; x < innernode.ChildNodes.Count; x++)
                                        {
                                            var node2 = innernode.ChildNodes[x];
                                            var node2Attributes = node2.Attributes;

                                            var cellid = node2Attributes.GetNamedItem("r");
                                            List<DocumentFormat.OpenXml.OpenXmlElement> headercollction = new List<DocumentFormat.OpenXml.OpenXmlElement>();
                                            List<DocumentFormat.OpenXml.Packaging.WorkbookRevisionLogPart> collction=new List<WorkbookRevisionLogPart>();
                                            if (cellid != null)
                                            {
                                                collction = document.WorkbookPart.WorkbookRevisionHeaderPart.WorkbookRevisionLogParts.Where(i => i.Revisions.InnerXml.Contains(cellid.OuterXml)).ToList();
                                            }
                                             
                                            foreach (DocumentFormat.OpenXml.Packaging.WorkbookRevisionLogPart lgpart in collction)
                                            {
                                                string restring = lgpart.Uri.OriginalString;
                                                int charecterLocation = restring.IndexOf(".", StringComparison.Ordinal);
                                                string rIdIndex = "rId" + restring.Substring(startIndex, charecterLocation - startIndex);
                                                if (document.WorkbookPart.WorkbookRevisionHeaderPart.Headers.Where(hdr => hdr.OuterXml.Contains(rIdIndex)).FirstOrDefault() != null)
                                                {
                                                    headercollction.Add(document.WorkbookPart.WorkbookRevisionHeaderPart.Headers.Where(hdr => hdr.OuterXml.Contains(rIdIndex)).FirstOrDefault());
                                                }
                                            }
                                            if (headercollction.Count != 0)
                                            {
                                                Comparison<DocumentFormat.OpenXml.OpenXmlElement> comparison = new Comparison<DocumentFormat.OpenXml.OpenXmlElement>(CompareDates);
                                                headercollction.Sort(comparison);
                                                var rec = headercollction[headercollction.Count - 1].LastChild;
                                                if(rec.LocalName!= "reviewedList")
                                                {
                                                    pendingchanges = pendingchanges + 1;
                                                }
                                            }
                                            
                                        }
                                    }
                                }

                                break;
                            }

                        }
                    }
                    if (HeadersNotReviewedList.Count == 0)
                    {
                        Console.WriteLine("There are no more pending changes to review");
                        Console.ReadLine();
                    }
                    else
                    {
                       
                        if (pendingchanges > 0)
                        {
                            Console.WriteLine("There are pending changes to review");
                            Console.ReadLine();
                        }
                        else
                        {
                            Console.WriteLine("There are no more pending changes to review");
                            Console.ReadLine();
                        }
                    }
                }
            }
        }
       
    }

**Comment by tomjebo** [comment]
@smithapk after reviewing the latest code you posted, this still won't work. You are still not accounting for the `ua="1"` attribute. Remember that each revision is either: 
1. accepted in which case it will show up by *revision id* in the `<reviewedList>` or
2. rejected in which case there will be another revision that *is* and the `<reviewedList>` *and* which also refers to the rejected revision via `<rcft>` or merge conflict element.
Anything else is "pending".

**Comment by tomjebo** [comment]
@smithapk I've created a simplified example of what I was referring to. This should detect any changes which have not been reviewed (accepted or rejected). 
     
```
            using (SpreadsheetDocument document = SpreadsheetDocument.Open(args[0], false))
            {
                if (document.WorkbookPart.WorkbookRevisionHeaderPart != null)
                {
 
                    List<DocumentFormat.OpenXml.OpenXmlElement> HeadersNotReviewed = new List<DocumentFormat.OpenXml.OpenXmlElement>();
                    List<DocumentFormat.OpenXml.OpenXmlElement> HeadersNotReviewedList = new List<DocumentFormat.OpenXml.OpenXmlElement>();
 
                    List<string> reviewedIds = new List<string>();
                    List<OpenXmlElement> reviewedEls = document.WorkbookPart.WorkbookRevisionHeaderPart.Headers.Descendants<OpenXmlElement>()
                        .Where<OpenXmlElement>(el => el.LocalName == "reviewed")
                        .ToList<OpenXmlElement>();
                    reviewedEls.ForEach(el => reviewedIds.Add(el.GetAttribute("rId", "").Value.ToString()));
 
 
                    var coll = document.WorkbookPart.WorkbookRevisionHeaderPart.WorkbookRevisionLogParts;
                    List<string> rccIds = new List<string>();
                    List<string> rcftIds = new List<string>();
                    foreach (DocumentFormat.OpenXml.Packaging.WorkbookRevisionLogPart logpart in coll)
                    {
                        logpart.Revisions.Descendants()
                            .Where<OpenXmlElement>(el => el.LocalName == "rcc")
                            .ToList<OpenXmlElement>()
                            .ForEach(el => rccIds.Add(el.GetAttribute("rId", "").Value.ToString()));
                        logpart.Revisions.Descendants()
                            .Where<OpenXmlElement>(el => el.LocalName == "rcft")
                            .ToList<OpenXmlElement>()
                            .ForEach(el => rcftIds.Add(el.GetAttribute("rId", "").Value.ToString()));
                    }
 
                    reviewedIds.ForEach(id => rccIds.Remove(id));
                    rcftIds.ForEach(id => rccIds.Remove(id));
 
                    if (rccIds.Count == 0)
                    {
                        Console.WriteLine("There are no more pending changes to review");
                        Console.ReadLine();
                    }
                    else
                    {
                        Console.WriteLine("List of pending change Ids to review:");
                        rccIds.ForEach(id => Console.WriteLine("{0}", id));
                        Console.ReadLine();
                    }
                }
            }
```
Obviously, you may want to add processing in addition but this will find the pending revisions.

**Comment by smithapk** [comment]
@tomjebo 
 Hi Tom,

 Thank you for the solution ! 👍  
 This works fine for me .

Thanks,
Smitha

**Comment by tomjebo** [comment]
@smithapk my pleasure. This could be something to add to the [Open XML PowerTools](https://github.com/tomjebo/Open-Xml-PowerTools.git).
