### ISSUE TITLE
ToFlatOpcDocument and ToFlatOpcString deliver a document that is not useable in MS Word when there is an altChunk-Part

### ISSUE THREAD

**Issue by rominator1983** [OfficeDev/Open-XML-SDK#525]
**Description**
ToFlatOpcDocument and ToFlatOpcString deliver a document that is not useable in MS Word when there is an altChunk-Part.

When a document contains an altChunk-Part with content-Type "application/xhtml+xm" the conversion routine returns a part with a pkg:xmlData-Element.
Such documents cannot be processed in MS Word (tested in 2010 and 2016).

MS Word expects altChunk-Parts always to be in a binary format in a Flat-OPC-document. Otherwise there is an error (Word says the document is corrupted and asks if it should repair the document).
The part information is lost when trying to repair the document in MS Word.

This is controlled in OpenXmlPackage.GetContentsAsXml by checking: part.ContentType.EndsWith("xml")
The standard lists the following content-types for altChunk:
- text/plain
- text/html
- application/vnd.openxmlformats-officedocument.wordprocessingml.document
- application/xhtml+xml

The 3rd entry seems like an error because +xml is missing in the standard. I did not try altChunk with Word-Processing-ML but I suppose Word expects a binary part too.
Considering that, a check for ending of "xml" or "+xml" is not really feasible for the problem.

To be able to tell, if this is an altChunk-Part that should be binary (for MS Word) the Relationship-Type ("http://schemas.openxmlformats.org/officeDocument/2006/relationships/aFChunk" or the purl-Version "http://purl.oclc.org/ooxml/officeDocument/relationships/aFChunk") of the part should be checked and not the content-Type of the part.
The check for "xml" could be done after this check for altChunk but should anyway rather be for "+xml" instead.

**Information**

- .NET Target: 4.6.1
- DocumentFormat.OpenXml Version: 2.7.2 but code in 2.9 seams to have the same issue.

**Repro**
See Unit-Test at:
https://gist.github.com/rominator1983/248dcd826802eeb0a768f18fe709f2b1

An additional file (docx with altchunk) is needed:
https://amforst.ddns.net/s/qd5RELXM6TeMX8t

**Observed**
altChunk-Part is returned as XML-Part instead of binary.

**Expected**
altChunk-Part is returned as binary-Part instead of XML-Part.

---
Copied from https://gist.github.com/rominator1983/248dcd826802eeb0a768f18fe709f2b1 for easier discoverability:

```csharp
using System.IO;
using System.IO.Packaging;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using NUnit.Framework;

namespace ConversionTestNamespace
{
  [TestFixture]
  public class ConvertTest
  {
    [Test]
    public void Convert ()
    {
      // download file from: https://amforst.ddns.net/s/qd5RELXM6TeMX8t
      using (var package = Package.Open (@"c:\\temp\\Doc with altChunk.docx", FileMode.Open))
      {
        using (var wordprocessingDocument = WordprocessingDocument.Create (package, WordprocessingDocumentType.Document))
        {
          var flatOpcDocumentString = wordprocessingDocument.ToFlatOpcString ();

          Assert.That (flatOpcDocumentString, Does.Contain("pkg:binaryData"));
        }
      }
    }
  }
}
```

**Comment by rominator1983** [comment]
@tomjebo: If you need further information just let me know. I will get back at you as soon as I can.

**Comment by rominator1983** [comment]
The issue occurs when creating a document with the OpenXML-SDK (with an altChunk-Part) as well as document that are only opened for conversion and have such a part.

You can easily reproduce the issue when you save the converted Flat-OPC that gets created by my code sample and try to open that in MS Word.

MS Word converts an altChunk-Part during opening to inline Word-Processsing-ML so you do not have this scenario when converting a document from MS Word.

**Comment by twsouthwick** [comment]
Can you provide a simple repro with the SDK creating the altChunk-Part? It helps greatly to have as small as a repro as possible to identify the specific issue.

**Comment by twsouthwick** [comment]
Just saw that you had a sample but it was hidden behind a link... my bad. The file doesn't seem to exist any more.

**Comment by ThomasBarnekow** [comment]
@rominator1983, it seems that

> text/plain
> text/html
> application/vnd.openxmlformats-officedocument.wordprocessingml.document
> application/xhtml+xml

are all MIME types, so the third one is not missing a `+xml` at the end. See the question on the [correct MIME types for Office documents](https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc) on stackoverflow.com and the question on [what mime-type should XHTML be served with](https://www.w3.org/2003/01/xhtml-mimetype/) on www.w3.org.

@twsouthwick, did anybody already fix this, or do you want me to take a stab at this? I originally contributed the `ToFlatOpcDocument()` and `ToFlatOpcString()` methods based on code examples provided by @EricWhiteDev.

**Comment by rominator1983** [comment]
Thank you for getting back at me on this. It has been some time. Fortunately our customers have not yet requested the feature for which this functionality would be great (we did offer a new feature based on the altChunk-functionality when I posted this issue here).

Here is a working link again: https://amforst.ddns.net/s/7qWWpCeRxs2rKgb There has been a security issue in Nextcloud that forced me to regenerate all link-shares and I must have missed that one.
As you can see the file opens perfectly with MS Word since there is no distinction on binary/xml parts for DOCX.

Thank you for your clarification on the mime parts. I was simply listing the content-types for parts that are "allowed" by the Open-XML-standard and not the mime-types for XHTML. I do not know if altchunk-Parts with the correct content-type (... wordprocessingml...) with or without the "+xml" (I believe with +xml is correct since that is used for other parts in MS Word too) could be opened in MS Word when they are xml and not binary. Anyways that is not my issue here since i am trying to use XHTML. I could check that later on for you depending on your proposed solution for my issue.

If you convert it to FlatOpc the file becomes unusable in Word as I mentioned in my original post because the contained altchunk-Part becomes XML which Word does not like at all. I have not retried this with more recent versions of the SDK and MS Word but I do believe that the issue is still present from what I see in the code. If you look at src/DocumentFormat.OpenXml/Packaging/OpenXmlPackage.FlatOpc.cs (was moved since my original post) there is still that line `if (part.ContentType.EndsWith("xml"))` which I believe is responsible for making an XML part out of that altChunk-Part. 

This is OK-ish for most things (since ending with "xml" implies that it can be read as XML via the XmlReader which is done afterwards. My sample has an altChunk-Part with a content-type of `application/xhtml+xml` and a relationship-type of `http://schemas.openxmlformats.org/officeDocument/2006/relationships/aFChunk`.

So there is one real problem and some possible problems that I see:
- The converted document is not processable with MS Word. The content-type is **not** suitable for deciding that a particular part with a content type of xml has to be binary in order to work with MS Word. I believe that there are many possible occurences of parts with "application/xhtml+xml" that **have** to be xml in order to work with many other systems. I would even go so far as to say that this is a bug in MS Word. Anyhow to work around that a part would have to be binary. I do not know how easy it would be to use the relationship-type and starting a list of types that should end up binary or if that is even the corret behavior. Maybe this has to be an opt-in-feature in order not to break things for people relying on such parts being XML.
- Is there a handling of upper-case/lower-case for the content types somewhere? Since the check is for "xml" it could break with "XML".
- If a part has a content type ending with xml than it is treated as XML and there is no fallback to binary if the reading of the XML fails with an exception (which implies that the part is in fact not XML. I do not know if that is a real problem. That is TBD. If you think about acronyms there could be some data format (even in the future) ending with xml that is not really xml at all.

**Comment by ThomasBarnekow** [comment]
@rominator1983 and @twsouthwick, I wanted to look into this and offer a fix. However, as noted in #652, I can't even build the Open XML SDK at the moment.

**Comment by twsouthwick** [comment]
I have not looked into this. Feel free to offer a fix :)

**Comment by ThomasBarnekow** [comment]
@rominator1983 and @twsouthwick, I just created a PR with a fix. Word opens the test document with different kinds of altChunk parts without any issues. I've tested it with the following content types:

- application/xhtml+xml,
- application/xml, and
- application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml.

While the MIME type of Word documents seems to be 

- application/vnd.openxmlformats-officedocument.wordprocessingml.document,

i.e., without ".main+xml" at the end, the content type of the altChunk part produced by the Open XML SDK is the upper one (with ".main+xml" at the end).

**Comment by ThomasBarnekow** [comment]
@rominator1983, I even tried to replace the "xml" with "+xml" in the checks. However, that did not produce the expected results and I left it at "xml". The reason is that _custom XML parts_, for example, have a content type of `application/xml`, meaning those would be treated incorrectly in case we used "+xml".

**Comment by rominator1983** [comment]
I allowed myself to comment on one commit. It looks good to me, even though I do not know why InternalPackageRelationships is neccessary. I do not know the code base too well.

**Comment by ThomasBarnekow** [comment]
I appreciate your feedback. I used `InternalPackageRelationships` to produce the collection of all `PackageRelationship` instances. We need the `RelationshipType` property value of those `PackageRelationship` instances to identify the `AlternativeFormatInputPart`s.

I implemented this class in another context and reused it here. There might be another way to achieve the same, though.
