### ISSUE TITLE
Makefile-Linux-Mono is missing

### ISSUE THREAD

**Issue by wryfi** [OfficeDev/Open-XML-SDK#53]
Makefile-Linux-Mono is missing from the repository. In order to build on mono, I had to find a copy in the revision history, paste it into a text file manually, and then use it to build.

**Comment by akoeplinger** [comment]
It was replaced by the [build.open-xml-sdk.sh](https://github.com/OfficeDev/Open-XML-SDK/blob/vNext/build.open-xml-sdk.sh) file, looks like the docs need to be updated.

**Comment by wryfi** [comment]
Interestingly, if I copy the old Makefile-Linux-Mono and call make 
directly, the build succeeds.

If I call ./build.open-xml-sdk.sh, I get the following build error:

Konsole output
Tests.cs(9,7): error CS0246: The type or namespace name `Xunit' could 
not be found. Are you missing an assembly reference?

Some additional documentation or pointers would be helpful.

**Comment by akoeplinger** [comment]
That looks like restoring the NuGet packages failed, possibly because you don't have nuget installed (it should show you an error related to that though). If you're using the official Mono apt repositories, try `sudo apt-get install nuget`.

**Comment by stever** [comment]
Note that the xunit tests don't work on Linux at the moment anyway. You could just call xbuild and nuget commands instead of using the shell script. Using xbuild rather than the makefile makes the build consistent between platforms, so the makefile which listed files would not be out of date. I for one had more success with xbuild.

**Comment by sonalsatpute** [comment]
@akoeplinger: 
I am trying to build the solution on Ubuntu using *build.open-xml-sdk.sh*. 
I have mono working fine. I am stuck with NuGet package download *nuget restore Open-XML-SDK.sln* when I am trying to execute *sudo apt-get install nuget*  I am getting message -Unable to locate package nuget-

will you help me with installation of NuGet on Ubuntu

**Comment by ant-s** [comment]
The newbuild.open-xml-sdk.sh doesn't seem to create any DLL files. I'm not sure if its still meant to do this. I cant run `mcs WmlComparer01.cs` as I get the following errors:
```
WmlComparer01.cs(6,18): error CS0234: The type or namespace name `Linq' does not exist in the namespace `System.Xml'. Are you missing `System.Xml.Linq' assembly reference?
WmlComparer01.cs(7,7): error CS0246: The type or namespace name `DocumentFormat' could not be found. Are you missing an assembly reference?
Compilation failed: 2 error(s), 0 warnings

```

I'm guessing this is because the DLLs are missing, but I'm unable to generate them.

**Comment by dominoFire** [comment]
I tried to compile the library with the provided script.

```
```

**Comment by dominoFire** [comment]
I found a way to disable the test that have references to libraries that currenty are not available for non-Windows distributions. In the .sln file, you have to remove the references to the projects that have tests:  DocumentFormat.OpenXml.Tests, DocumentFormat.OpenXml.WB.Tests, System.IO.Packaging.Tests. The final .sln file looks like this:

```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 2013
VisualStudioVersion = 12.0.21005.1
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "DocumentFormat.OpenXml", "DocumentFormat.OpenXml\DocumentFormat.OpenXml.csproj", "{E5D39C6A-9067-477E-B0D3-A9419B86E6E5}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "System.IO.Packaging", "System.IO.Packaging\System.IO.Packaging.csproj", "{4C88A3AD-1241-4A04-854B-8372DF29828D}"
EndProject
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = ".nuget", ".nuget", "{E43CE613-45B8-4FFC-AE29-3876ABD68244}"
	ProjectSection(SolutionItems) = preProject
		.nuget\packages.config = .nuget\packages.config
	EndProjectSection
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "DocumentFormat.OpenXml.WB", "DocumentFormat.OpenXml.WB\DocumentFormat.OpenXml.WB.csproj", "{55FB0A8A-B816-4DC9-9BB4-4DB5B5950F5A}"
EndProject
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TestUtil", "TestUtil\TestUtil.csproj", "{B63E969B-F7EC-4B6C-8540-67FC0C0C3E56}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{E5D39C6A-9067-477E-B0D3-A9419B86E6E5}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{E5D39C6A-9067-477E-B0D3-A9419B86E6E5}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{E5D39C6A-9067-477E-B0D3-A9419B86E6E5}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{E5D39C6A-9067-477E-B0D3-A9419B86E6E5}.Release|Any CPU.Build.0 = Release|Any CPU
		{4C88A3AD-1241-4A04-854B-8372DF29828D}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{4C88A3AD-1241-4A04-854B-8372DF29828D}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{4C88A3AD-1241-4A04-854B-8372DF29828D}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{4C88A3AD-1241-4A04-854B-8372DF29828D}.Release|Any CPU.Build.0 = Release|Any CPU
		
		
		{55FB0A8A-B816-4DC9-9BB4-4DB5B5950F5A}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{55FB0A8A-B816-4DC9-9BB4-4DB5B5950F5A}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{55FB0A8A-B816-4DC9-9BB4-4DB5B5950F5A}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{55FB0A8A-B816-4DC9-9BB4-4DB5B5950F5A}.Release|Any CPU.Build.0 = Release|Any CPU
		
		
		{B63E969B-F7EC-4B6C-8540-67FC0C0C3E56}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{B63E969B-F7EC-4B6C-8540-67FC0C0C3E56}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{B63E969B-F7EC-4B6C-8540-67FC0C0C3E56}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{B63E969B-F7EC-4B6C-8540-67FC0C0C3E56}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

I'm not sure to make a pull request for this mod. I think there is a leaner way to do this using flags in xbuild/msbuild/nuget. Also, note that I'm a beginner in .NET issues

**Comment by twsouthwick** [comment]
This project has switched to the new .NET tooling. Please see the README for details.
