### ISSUE TITLE
All strings converted to numbers

### ISSUE THREAD

**Issue by rakewell** [OfficeDev/Open-XML-SDK#530]
**Description**

There is an issue reading data from the spreadsheet. All cells are somehow converted to numbers even if they contain text. For example the word "testing" becomes 11. I have used the same code with other excel files but text is returned where appropriate. 

**Information**

.Net Framework 4.7.2
[OpenXmlReadProblem.zip](https://github.com/OfficeDev/Open-XML-SDK/files/2723115/OpenXmlReadProblem.zip)

**Repro**

Please see the attached windows form application. The Excel file is in the bin path (Deposits.xlsx)

```
            using (SpreadsheetDocument spreadsheetDocument =
            SpreadsheetDocument.Open(Path.Combine(Application.StartupPath, "Deposits.xlsx"), false))
            {

                //open the worksheet
                WorkbookPart workbookPart = spreadsheetDocument.WorkbookPart;
                WorksheetPart worksheetPart = GetWorksheetPart(workbookPart, "Deposits");
                SheetData sheetData = worksheetPart.Worksheet.Elements<SheetData>().First();

                string text;
                foreach (Row r in sheetData.Elements<Row>())
                {
                    if (r.RowIndex != 1) //skip first row
                    {
                        Debug.WriteLine($"Row: {r.RowIndex}");
                        foreach (Cell c in r.Elements<Cell>())
                        {
                            text = c.CellValue.Text;
                            Debug.WriteLine($"Cell {c.CellReference}: {text}");
                        }
                    }
                }
            }

        public WorksheetPart GetWorksheetPart(WorkbookPart workbookPart, string sheetName)
        {
            string relId = workbookPart.Workbook.Descendants<Sheet>().First(s => sheetName.Equals(s.Name)).Id;
            return (WorksheetPart)workbookPart.GetPartById(relId);
        }

```

Data in row 2:
`3562814 | ETH | ETHEREUM | 2.58017 | COMPLETED | testing | testing | 8/09/2017 9:35 | 8/09/2017 9:48`

Code output in row 2:
```
Row: 2
Cell A2: 3562814
Cell B2: 9
Cell C2: 10
Cell D2: 2.5801699999999999
Cell E2: 11
Cell F2: 16
Cell G2: 16
Cell H2: 42986.399305555555
Cell I2: 42986.408333333333

```

**Comment by tomjebo** [comment]
@rakewell You need to check the type of the cell and convert to a string with a look up in the shared string table. The value you see is the index in the shared string table. 
Check out this article to see how to do this: 
[How to: Retrieve the values of cells in a spreadsheet document (Open XML SDK)](https://docs.microsoft.com/en-us/office/open-xml/how-to-retrieve-the-values-of-cells-in-a-spreadsheet)

**Comment by rakewell** [comment]
thank @tomjebo. I'm wondering whether there might be a more intuitive approach for getting the cell value directly using, perhaps, an extension method. The code that looks up the shared string table for example wouldn't have to be replicated client side for deriving strings (something that needs no conversion). Also, it is not helpful for decimals where the original is 2.5817 to be converted to 2.5801699999999999. 

As I am new to this library I understand that there are many holes in my knowledge, I am however looking at it from a fresh perspective and where a developer just needs to gather data from a file, doing a lot of type checking, shared string look ups, serial date conversion and numeric conversion seems like a lot of overhead.

**Comment by tomjebo** [comment]
@rakewell I was thinking this as well. I'll mark this as a proposed feature request. You are welcome to contribute a PR and we'll review for including into the library. I think we do have to be careful of adding a lot of higher level functionality over the encapsulation of OOXML but this might be something we could add.
