### ISSUE TITLE
Not able to open VS 2015 solution (Community/Professional) with GitHub

### ISSUE THREAD

**Issue by Reemamotog1** [OfficeDev/Open-XML-SDK#554]
**Description**

While opening VS2015 (Community/Professional), the VS just scans GitHub repo and automatically closes after 10 secs or so.

**Observed**

On Opening VS2015 it is just keeps scanning GitHub repository and then after 10secs or so VS solution closes automatically.

**Expected**

I was able to open the solution since last 8 month after migration from TFSto GitHub.

**Comment by twsouthwick** [comment]
I'm not sure what you mean by 'GitHub repo' or 'migration from TFSto Github'. If you are referring to a cloned fork of this project, then you're right that VS2015 won't open it. We use the new project system introduced in VS 2017 and require C# 7.2 to compile. Please see the README.md on the front page for details.

**Comment by twsouthwick** [comment]
@Reemamotog1 Since you haven't responded to the question, I'm going to close this issue. Please feel free to reopen with more details.
