### ISSUE TITLE
Office Online created document fails OpenXmlValidator validation

### ISSUE THREAD

**Issue by jchoinski** [OfficeDev/Open-XML-SDK#564]
**Description**

Any document created in Office Online, including blank ones fail OpenXmlValidator validation. 

                var v = new OpenXmlValidator(FileFormatVersions.Office2016);
                var errors = v.Validate(wDoc);

Produces the following 2 errors :

1. 
AttributeQualifiedName: null
Description: The element has unexpected child element 'http://schemas.microsoft.com/office/word/2010/wordml:docId'.
ErrorType: Schema
Id: Sch_UnexpectedElementContentExpectingComplex
Node: {DocumentFormat.OpenXml.Wordprocessing.Settings}
Part: {DocumentFormat.OpenXml.Packaging.DocumentSettingsPart}
Path: XPath="/w:settings[1]"
RelatedNode: {DocumentFormat.OpenXml.Office2010.Word.DocumentId}

2.
AttributeQualifiedName: http://schemas.microsoft.com/office/word/2012/wordml:val
Description: "The attribute 'http://schemas.microsoft.com/office/word/2012/wordml:val' has invalid value '{7297be79-5e23-470a-9fe2-a7ede5c0760f}'. The Pattern constraint failed. The expected pattern is \\{[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}\\}."
ErrorType: Schema
Id: Sch_AttributeValueDataTypeDetailed
Node: {DocumentFormat.OpenXml.Office2013.Word.PersistentDocumentId}
Part: {DocumentFormat.OpenXml.Packaging.DocumentSettingsPart}
Path: XPath="/w:settings[1]/w15:docId[1]"
RelatedNode: null
ValidationErrorCategory: Sch_PatternConstraintFailed
**Information**

- .NET Target: .NET Framework,
- DocumentFormat.OpenXml Version:  feature/office2016

**Repro**
#
        [Theory]
        [InlineData(TestFiles.O365BlankDocument)]
        public void OF16_001_ValidateDocx_2016(string name)
        {
            using (var stream = GetStream(name))
            using (var wDoc = WordprocessingDocument.Open(stream, false))
            {
                var v = new OpenXmlValidator(FileFormatVersions.Office2016);
                var errors = v.Validate(wDoc);

                Assert.Empty(errors);
            }
        }

**Observed**

Validation produces 2 errors

**Expected**

Validation produces 0 errors

**Comment by twsouthwick** [comment]
Thanks for the report. I'm in the middle of some major changes to fix up the validation system (it's very opaque right now so debugging it is incredibly difficult if not impossible). Do you have a sample that we can use?
