### ISSUE TITLE
Unable to build release with .Net native toolchain

### ISSUE THREAD

**Issue by PJBowron** [OfficeDev/Open-XML-SDK#567]
**Description**

A project incorporating the OpenXML package will fail to build in Release config if the build is set to use the .Net native toolchain (required for Store submision).

**Information**

- Target: UWP
- DocumentFormat.OpenXml Version: 2.9.0

**Repro**

- Create/Open a solution & project and add the OpenXML package
- Right-click on project in Solution Explorer and select "Properties"
- With Build selected, choose "Release" for Configuration and "All Platforms" for Platform
- Ensure "Compile with .Net Native tool chain" is ticked
- Build the solution for Release/x86

**Observed**

Build failure:
`Error		MCG0037: MCG0037:InvalidCSharpIdentifierName Struct 'DocumentFormat.OpenXml.Validation.Schema.SdbAttributeConstraint' in assembly 'Assembly(Name=DocumentFormat.OpenXml, Version=2.9.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17)' has a field with name '<AttributeUse>k__BackingField' that is invalid. This could be because the name is obfuscated or the field is auto-implemented by the compiler. Please make sure the field name follows C# identifier conventions.
`

**Expected**

Successful build.

**Comment by twsouthwick** [comment]
Thanks for reporting this! I have a fix that we'll try to get out as quickly as possible (it'll be 2.9.1).

**Comment by twsouthwick** [comment]
btw this seems to be a problem with the .NET Native compiler that has been reported here https://github.com/Microsoft/dotnet/issues/807.

**Comment by PJBowron** [comment]
Thanks for the quick resolution!

**Comment by twsouthwick** [comment]
We'll hopefully have a fix uploaded to NuGet by the end of the week.

**Comment by twsouthwick** [comment]
This has been uploaded to NuGet as v2.9.1: https://www.nuget.org/packages/DocumentFormat.OpenXml/2.9.1

We don't have a good process to vet .NET Native builds, so please file any other issues you find. We have it on the backlog (and I now have a sample app) to add support to run the unit tests on .NET Native....

**Comment by PJBowron** [comment]
Happy to. I'll try out the new package asap. Thanks again!
