### ISSUE TITLE
DocumentBuilder merging styles from MS Word documents created with different language settings.

### ISSUE THREAD

**Issue by LeanderVanEck** [OfficeDev/Open-XML-SDK#57]
When attempted to merge a document created in a Dutch office version with a document created in a English office version the resulting document ends up with default styles from both documents inside styles.xml.

 For example

 <w:style w:styleId="Normal" w:default="1" w:type="paragraph">
 <w:style w:styleId="Standaard" w:default="1" w:type="paragraph">

 This opens perfectly fine in MS Word 2010 and MS Word 2013. It seems only the Word Online Editor doesn't accept it (preview still looks fine)

 This happens because the styleId names are not matching (because Microsoft decided to localize them i guess...)

**Comment by EricWhiteDev** [comment]
@LeanderVanEck This should be an issue in Open-Xml-PowerTools, not Open-Xml-Sdk.  Can you please create the issue there?

When you create the issue there, it is always helpful to include sample documents, so that repro is as easy as possible.
