### ISSUE TITLE
Is there some api to export word/excel/ppt documents to svg or pdf or jpg?

### ISSUE THREAD

**Issue by WeihanLi** [OfficeDev/Open-XML-SDK#578]
Is this a:
- [x] Question on library usage

**Description**

Is there some api we can use to export word/excel/ppt documents to svg or pdf or jpg?

**Comment by twsouthwick** [comment]
Please review the issue template that questions on usage should be posted to Stackoverflow and keep this for actual issues on the SDK.

That being said, no there is no dedicated API to export documents to another format. The purpose of this SDK is to provide low-level access to packages and schema elements. What you do with them (ie exporting, etc) is beyond the scope of this project. There are other projects that build on this to provide such functionality. For instance, you may want to look at https://github.com/EricWhiteDev/Open-Xml-PowerTools for a bunch of higher level examples.

**Comment by WeihanLi** [comment]
Thanks for your reply @twsouthwick

**Comment by IrakliLomidze** [comment]
@twsouthwick Unfortunately Mr. Eric give us promise to support and develop PowerTools but he did not update anything yet.

**Comment by twsouthwick** [comment]
@IrakliLomidze We are not supporting PowerTools for active development and if you find that @EricWhiteDev is not taking it in a direction that works for you, you can try to get involved in his fork or make your own.
