### ISSUE TITLE
Generating objects from outer xml results in missing property values

### ISSUE THREAD

**Issue by t08094a** [OfficeDev/Open-XML-SDK#579]
Is this a:
- [x] Issue with the OpenXml library
- [ ] Question on library usage

**Description**

Generating OpenXmlElements from an XML string results in missing property values of those generated objects. After getting the outer XML of those objects, the attributes with their values are also missing.

**Information**

- .NET Target: .NET Framework (4.7.2)
- DocumentFormat.OpenXml Version: (2.9.0)

**Repro**

```csharp
[Fact]
public void TableLookShouldHaveIdenticalOuterXmlToGivenInputXml()
{
    // arrange
    const string xmlContent = @"
<w:tblPr>
    <w:tblLook w:firstRow=""true"" w:lastRow=""false"" w:firstColumn=""false"" w:lastColumn=""true"" w:noHBand=""false"" w:noVBand=""true"" />
</w:tblPr>";

    // act
    TableProperties p = new TableProperties(xmlContent);
    TableLook tableLook = p.TableLook;

    // assert
    Assert.True(tableLook.FirstRow.Value);
    Assert.False(tableLook.LastRow.Value);
    Assert.False(tableLook.FirstColumn.Value);
    Assert.True(tableLook.LastColumn.Value);
    Assert.False(tableLook.NoHorizontalBand.Value);
    Assert.True(tableLook.NoVerticalBand.Value);

    Assert.Equal(xmlContent, p.OuterXml);
}
``` 

**Observed**
By generating OpenXmlElement objects based on an outer XML the created XmlReader uses `strictTranslation = true` and stores all attribute values in the property defined by `StrictTranslationLocalName`. The other property values of the created object are not updated.

**Expected**

I would have expected that the properties in the test above have the values from the XML attributes.

**Comment by twsouthwick** [comment]
Interesting... doesn't look like an easy way to set that flag as a consumer. Have you been able to do this in previous versions (wondering if there was a regression at some point) or if it is just part of the design. Either way, we can investigate how to adjust this.

**Comment by t08094a** [comment]
In my opinion after parsing the XML content the properties should get updated. There should be no need to modify the `strictTranslation` value.
I think there could be more classes with that behavior. The commit fa9cc48b914b2a20467a407e2a1463ccaeeca5b6 addresses more of them but i haven't verified.

**Comment by twsouthwick** [comment]
I'm not sure I follow. The properties getting updated is due to `strictTranslation` having a default value that causes, so it would need to be able to be set to have the properties updated.

@tomjebo Can you chime in here regarding strict translation and default behavior?

**Comment by twsouthwick** [comment]
@t08094a Sounds like we need some sort of API to allow for opting into transitional behavior. The easiest would be if we added an overload to `OpenXmlElement` that would allow the following:

```csharp
  TableProperties p = new TableProperties();
  p.Parse(xmlContent, new ParseProperties { StrictTranslation = false }); 
  TableLook tableLook = p.TableLook;
```

The transitional attributes should be seen as deprecated (@tomjebo can provide the documentation to back this up), but I can see that it would be nice to be able to create an element from XML outside of the context of a package that is parsed according to transitional names.

**Comment by t08094a** [comment]
To extend the API would be welcome.

**Comment by twsouthwick** [comment]
@t08094a Would you be up for driving this?
