### ISSUE TITLE
.NET Native compilation

### ISSUE THREAD

**Issue by JoelMendoza** [OfficeDev/Open-XML-SDK#595]
**Description**

A UWP project incorporating the following NuGet packages:
- DocumentFormat.OpenXml (version 2.9.1)
- Microsoft.Azure.Management.Fluent (version 1.22.2)
- Microsoft.NETCore.UniversalWindowsPlatform (version 6.2.8)

Fails to build in Release config if the build is set to use the .Net native toolchain (required for Store submission).

**Information**

- UWP
- DocumentFormat.OpenXml Version: 2.9.1

**Repro**

Create a new UWP project, add the Nuget projects noted in the Description section and build in Release config (make sure "Compile with .Net tool chain" is checked)

**Observed**

A UWP project will build in release with only the OpenXml package and will build in release with only the Azure.Management.Fluent package.  **The build fails when both packages are included.**  This solution posted in #168 did not work for this issue.  Since this involves another package (Azure.Management.Fluent), I have opened an issue on the project's page:  [azure-libraries-for-net 697](https://github.com/Azure/azure-libraries-for-net/issues/697)

Output:
```
1>------ Rebuild All started: Project: Intact.UWP.Deployment, Configuration: Release x64 ------
1>  Intact.UWP.Deployment -> C:\Projects\Tests\Intact.UWP.Deployment\Intact.UWP.Deployment\bin\x64\Release\Intact.UWP.Deployment.exe
1>  Processing application code
1>  Computing application closure and generating interop code
1>    Loading 150 modules...
1>    Generating code...
1>    Interop code generated.
1>  Generating serialization code
1>  Compiling interop code
1>  Generating System.Reflection.DispatchProxy proxy code.
1>  Cleaning up unreferenced code
1>  Generating native code
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): error : Internal Compiler Error
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.3\tools\Microsoft.NetNative.targets(801,5): error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x64.microsoft.net.native.compiler\2.2.3\tools\x64\ilc\Tools\nutc_driver.exe @"C:\Projects\Tests\Intact.UWP.Deployment\Intact.UWP.Deployment\obj\x64\Release\ilc\intermediate\MDIL\Intact.UWP.Deployment.rsp"' returned exit code 1
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Expected**

Successful build.

**Comment by laultman** [comment]
This is blocking our company from releasing a product in Azure because we need the Windows client app part as a component of a larger Azure project.

**Comment by twsouthwick** [comment]
Per the linked issue, this appears to be fixed by adding some entries to the `rd.xml` file. Please reopen if it that does not help.
