### ISSUE TITLE
Incorporate Open XML Power Tools in base SDK

### ISSUE THREAD

**Issue by IrakliLomidze** [OfficeDev/Open-XML-SDK#599]
Is this a:
- [ ] Issue with the OpenXml library
- [X] Question on library usage

**Open XML Power tool features in base SDK**

Open XML Power tools had perfect tools that is was very helpful but, Microsoft decided to kill that product. Is it any plan to incorporate that functionality in this SDK ? and support them/

It would be really nice to be.

**Comment by twsouthwick** [comment]
The tooling for it has not been "killed" but no longer invested in from us and moved to a community member. It is OSS and can be used however you would like. Any specific feature that you would like to see? This SDK is focused on the file format management and most of the power tools are scenario specific that isn't a good fit for the SDK.

**Comment by ThomasBarnekow** [comment]
@IrakliLomidze, when @twsouthwick says "moved to a community member", this community member is @EricWhiteDev, the actual author of the Open XML PowerTools. Thus, nothing has changed effectively.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, I would have a totally cool feature that I would love to see. How about (somewhat transparently) supporting documents stored on SharePoint. For example, with documents stored locally at a given `path`, I can do this:
```csharp
using (WordprocessingDocument document = WordprocessingDocument.Open(path, true))
{
    /// Do something with the document
}
```
It would be really nice if `path` could also be a SharePoint URL.

Just saying ...

**Comment by twsouthwick** [comment]
@ThomasBarnekow I honestly have never done any sharepoint programming so not sure what this would entail. Could you create an issue with a description of what currently has to be done?

**Comment by twsouthwick** [comment]
Closing this issue as there are no plans to fold the power tools into this project. Feel free to look at the fork @EricWhiteDev has and help out there!
