### ISSUE TITLE
Error MSB4044 The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion"

### ISSUE THREAD

**Issue by gdalsnes** [OfficeDev/Open-XML-SDK#611]
Downloaded and unpacked v2.10.0-beta1.zip. Opened Open-XML-SDK.sln in VS 2017. 
Build->Build solution. Fail:
Error MSB4044 The "GetAssemblyVersion" task was not given a value for the required parameter "NuGetVersion"

**Comment by twsouthwick** [comment]
Hmmm you may be missing a workload. You need the .NET Core workload. There's a way for a project to declare that so VS will let you know (although it may only be available for VS 2019).  I'll add it though so people can see the required workloads.

**Comment by twsouthwick** [comment]
I've added a .vsconfig in #614. This should prompt you in VS 2019, and in VS 2017 (15.9) you can import the file.
