### ISSUE TITLE
SectionProperties does not expose child elements as properties

### ISSUE THREAD

**Issue by avonwyss** [OfficeDev/Open-XML-SDK#620]
**Description**

In contrast to most other classes in the SDK, the [Wordprocessing SectionProperties](https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.sectionproperties?view=openxml-2.8.1) does not expose the child elements as strongly-typed properties. This makes Wordprocessing sections even more difficult to use than they already are.

Looking at the documentation, the allowed child elements for the last section and the section in the paragraphs do allow exactly the same child elements, so that should not be the reason for not exposing these as properties.

**Information**

- DocumentFormat.OpenXml Version: 2.8.1

**Observed**

There are no strongly-typed properties for the elements bidi, cols, docGrid etc. available.

**Expected**

Having strongly-typed properties for the elements bidi, cols, docGrid etc. available.

**Comment by avonwyss** [comment]
I noticed that there is also a `PreviousSectionProperties` which has the same element name as the `SectionProperties`, but this one does indeed have the strongly typed properties. Apparently it should be used as child of the `sectPrChange` element. I'm tempted to try and use the `PreviousSectionProperties` en lieu of the `SectionProperties` as child in `body`/`pPr` elements...

**Comment by twsouthwick** [comment]
I'm marking this for 2.11  as this has come up a lot. See #627 for some details

**Comment by twsouthwick** [comment]
Closing as duplicate to #492
