### ISSUE TITLE
TableRowProperties does not expose child elements as properties

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#627]
**Description**

The `TableRowProperties` (`w:trPr`) class does not expose child elements such as `Deleted` (`w:del`) or `Inserted` (`w:ins`) as properties. This is in contrast to the `ParagraphMarkRunProperties` (`w:rPr`) class, for example, which exposes those child elements as properties.

This issue is related to #620, which also points out missing properties.

**Information**

- .NET Target: Any
- DocumentFormat.OpenXml Version: 2.9.1

**Repro**

Look at source code.

**Observed**

Inconsistency in API regarding which child elements it exposes.

**Expected**

API should consistently expose child elements.

**Comment by twsouthwick** [comment]
Yeah - I've been looking at this recently. Currently, the way the generator does this is to expose single items; once a sequence is encountered, it stops. I've been cleaning up the generator (hopefully at somepoint we can put it in this repo) to allow for this. I've got a branch somewhere that has changes that should help with this; I'll look to see if I can pull that out and cc you on the design I have to enable this to get your feedback. I'll probably address this after getting 2.10 shipped.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, that sounds good.

I‘d guess the generator also creates the constructors, right? Would it be possible to enhance those as well along the lines of how XElement instances can be constructed? This would be helpful for pure functional transformations. Happy to elaborate more if this is an option at all, e.g., in another specific issue.

**Comment by twsouthwick** [comment]
Yes, updating a constructor would actually be a lot easier. Can you open an issue with a design that you'd find helpful?

**Comment by twsouthwick** [comment]
Closing as duplicate to #492
