### ISSUE TITLE
Incorrect Charactes count

### ISSUE THREAD

**Issue by rajcitystar** [OfficeDev/Open-XML-SDK#63]
Both the below
ExtendedFilePropertiesPart.Properties.Characters.InnerText and 
ExtendedFilePropertiesPart.Properties.Characterswithspace.InnerText and 
returns wrong values

**Comment by EricWhiteDev** [comment]
@rajcitystar Can you provide more info?  The InnerText methods just return the inner text of those XML elements, akin to the InnerText methods of XML DOM APIs.  What value is it returning for you, and what value do you think it should be returning?
