### ISSUE TITLE
Adding NumberingFormats breaks spreadsheet file

### ISSUE THREAD

**Issue by typhon88** [OfficeDev/Open-XML-SDK#633]
I am generating a spreadsheet file with some styles like fonts, borders and fills and they all seem to work but as soon as I add NumberingFormats after the file is generated and I try to open it, it doesn't work it says the file is corrupted.
I tried different format codes, none of them worked, any ideas? Thanks.

This is the code:

        private Stylesheet GenerateStylesheet()
        {
            NumberingFormats numberFormats = new NumberingFormats(
                 new NumberingFormat(),
                 new NumberingFormat() { NumberFormatId = 1U, FormatCode = StringValue.FromString("0.00") }
                 );

            Stylesheet styleSheet = null;
            Fonts fonts = new Fonts(
                new Font( // Index 0 - default
                    new FontSize() { Val = 10 }
                ),
                new Font( // Index 1 - header
                    new FontSize() { Val = 10 },
                    new Bold(),
                    new Color() { Rgb = "FFFFFF" }
                ));

            Fills fills = new Fills(
                    new Fill(new PatternFill() { PatternType = PatternValues.None }), // Index 0 - default
                    new Fill(new PatternFill() { PatternType = PatternValues.Gray125 }), // Index 1 - default
                    new Fill(new PatternFill(new ForegroundColor { Rgb = new HexBinaryValue() { Value = "66666666" } })
                    { PatternType = PatternValues.Solid }) // Index 2 - header
                );

            Borders borders = new Borders(
                    new Border(), // index 0 default
                    new Border( // index 1 black border
                        new LeftBorder(new Color() { Auto = true }) { Style = BorderStyleValues.Thin },
                        new RightBorder(new Color() { Auto = true }) { Style = BorderStyleValues.Thin },
                        new TopBorder(new Color() { Auto = true }) { Style = BorderStyleValues.Thin },
                        new BottomBorder(new Color() { Auto = true }) { Style = BorderStyleValues.Thin },
                        new DiagonalBorder())
                );

            CellFormats cellFormats = new CellFormats(
                    new CellFormat(), // default
                    new CellFormat {
                        FontId = 0,
                        FillId = 0,
                        BorderId = 1,
                        NumberFormatId = 0,
                        ApplyBorder = true }, // body
                    new CellFormat {
                        FontId = 1,
                        FillId = 2,
                        BorderId = 1,
                        NumberFormatId = 0,
                        ApplyFill = true }, // header
                    new CellFormat {
                        FontId = 0,
                        FillId = 0,
                        BorderId = 0,
                        FormatId = 1U,
                        NumberFormatId = 1U,
                        ApplyNumberFormat = true
                    }
                );

            styleSheet = new Stylesheet(fonts, fills, borders, numberFormats, cellFormats);
            return styleSheet;
        }

**Comment by twsouthwick** [comment]
@typhon88 part of the issue template has information we need to correctly identify any issues. Can you please let me know which version you are using? Also, this snippet isn't a functional repro - please provide everything needed for a minimum viable repro.

This sounds like it may have been a regression in 2.10.0 that was fixed in 2.10.1 - can you verify that?
