### ISSUE TITLE
Increase flexibility of constructors, e.g., for pure functional transformations

### ISSUE THREAD

**Issue by ThomasBarnekow** [OfficeDev/Open-XML-SDK#634]
**Description**

In the context of pure functional transformations, it would be beneficial to construct `OpenXmlElement` instances very flexibly. For example, one might want to construct a new element in the following way:
```csharp
return new Paragraph(
    new ParagraphProperties(new ParagraphStyleId { Val = "MyStyleId" }),
    FunctionReturningIEnumerableOfRun(someParams));
```

**Information**

- .NET Target: All
- DocumentFormat.OpenXml Version: Latest

See discussion in #627.

**Observed**

Using the `Paragraph` class as an example, the subclasses of `OpenXmlElement` define the following constructors:
```csharp
public Paragraph()
{
}

public Paragraph(IEnumerable<OpenXmlElement> childElements)
    : base(childElements)
{
}

public Paragraph(params OpenXmlElement[] childElements)
    : base(childElements)
{
}

public Paragraph(string outerXml)
    : base(outerXml)
{
}
```
With those constructors, the example instance can't be created, because we can't combine an `OpenXmlElement`  and an `IEnumerable<OpenXmlElement>`.

**Expected**

We should be able to create instances in the way shown in the description.

**Design Idea**

We could borrow the design from the `System.Xml.Linq.XElement` class, which, owing to how you can construct instances, is instrumental in pure functional transformations.

The two key `XElement` constructors for pure functional transformations are:
```csharp
public XElement(XName name, object content)
    : this(name)
{
    this.AddContentSkipNotify(content);
}

public XElement(XName name, params object[] content)
    : this(name, (object) content)
{
}
```
Note how the second constructor delegates to the first one. Thus, the magic happens in the `AddContentSkipNotify(object)` method, which works with pretty much any meaningful actual parameter you throw at it.

Thus, using the `Paragraph` example, we could replace:
- `Paragraph(IEnumerable<OpenXmlElement>)` with `Paragraph(object)` and
- `Paragraph(params OpenXmlElement[])` with `Paragraph(params object[])`.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, this is based on the discussion we've had in #627. Tell me whether such a change is an option at all.

At the moment, I am dealing with the shortcomings of the constructors by using extension methods. However, more direct support for pure functional transformations would be a pretty appropriate feature of the Open XML SDK from my perspective.

**Comment by twsouthwick** [comment]
This is interesting. I'll create a branch with the generated constructors if you want to prototype what the proposed constructors would look like.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, yes, please do that.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, how about that branch?

**Comment by twsouthwick** [comment]
Here's a branch: https://github.com/twsouthwick/Open-XML-SDK/tree/pure-functional-transformations.

I'm somewhat wary of adding a ton of new constructors, but let's see how this goes. Here's another option to explore:

```csharp
return new Paragraph().With(
    new ParagraphProperties(new ParagraphStyleId { Val = "MyStyleId" }),
    FunctionReturningIEnumerableOfRun(someParams));
```

Where you can define the following:

```csharp
public static class OpenXmlElementFunctionalExtensions
{
  public static T With<T>(object content) where T : OpenXmlElement
  {
    ...
  }

  public static T With<T>(params object[] content) where T : OpenXmlElement
    => With<T>((object)content);
}
```

This simplifies the number of constructors required. Something to explore - not sure how that affects your style of programming, but reduces the public APIs the SDK has to manage.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, let me explore the extension method route. My initial thought is that this would enable the same approach while only requiring a little more code.
