### ISSUE TITLE
Symbols package

### ISSUE THREAD

**Issue by weitzhandler** [OfficeDev/Open-XML-SDK#639]
**Description**

Please include symbols in NuGet package to allow debugging.

**Information**

Please include symbols with the NuGet package so we can debug the `OpenDocument` assemblies.
I'm referring to this:

![image](https://user-images.githubusercontent.com/2716316/69713963-2a976280-110e-11ea-808d-c358ef6ccd5d.png)

**Comment by twsouthwick** [comment]
Good idea. It's been merged and will be available via NuGet with the next release

**Comment by weitzhandler** [comment]
Thank you!

**Comment by andrewmolyneux** [comment]
Hi! I think this has regressed because I can't see any debug symbols on nuget.org for version 2.14.0.
