### ISSUE TITLE
Spreadsheets: Sophisticated references

### ISSUE THREAD

**Issue by weitzhandler** [OfficeDev/Open-XML-SDK#640]
# Feature suggestion

**Description**

Please add alternative coordinates to the hardcoded `CellReference`, or `MergeCell.Reference` etc.

Ideally, there should be few more types like: 
- `ColumnReference { int Index, string ColumnName }` (e.g. `A` as in `A1`).
Should provide easy casting between both `string` and `int`
- `RowReference { int index }` (e.g. `1` as in `A1`)
- `CellReference { ColumnReference Column, RowReference Row }` (e.g. `ABC123`)
- `Range { CellReference Start , CellReference End }` (e.g. A1:A32)
Also need to accommodate for `A:A`.

Would you consider that? I'm willing to contribute.

**Comment by weitzhandler** [comment]
In addition to that, I'd also propose easier ways to work with rows columns and cells, for example, deleting a column or row, so that the affected `Row`s/`Column`s/`Cell`s'/`MergeCell` and styles are all updated accordingly.
I wrote a set of extension methods for that. Would you consider a PR?

**Comment by twsouthwick** [comment]
@weitzhandler For the most part, this SDK maintains a strict goal of enabling support to handle the OpenXML file types. We do not aim to provide an object model on top of it.

However, if you have an API design, please feel free to share what the design would be. Showing the APIs needed and their usage would be a good start.

**Comment by weitzhandler** [comment]
Can I share with you some code privately? Can you please drop me an email (same as my GH handle at gmail)?

**Comment by twsouthwick** [comment]
Sure will do

**Comment by weitzhandler** [comment]
@twsouthwick did u get my email I sent you at the time?

**Comment by twsouthwick** [comment]
I never saw any email regarding this.

**Comment by weitzhandler** [comment]
In March, you sent me an email wish I replied to.
Please search your mail for my last name, I'm sure you'll find it.
