### ISSUE TITLE
How to parse embedded file(OLE obejct) in pptx/docx

### ISSUE THREAD

**Issue by hong1997** [OfficeDev/Open-XML-SDK#644]
# Before submitting an issue, please fill this out

Is this a:
- [ ] Issue with the OpenXml library
- [X] Question on library usage

How to parse embedded files(OLE obejct) in pptx/docx.
They are Ole objects mostly, like object1.bin.
If there're any good ways to parse it?
 Unzip the OLE object, there're several kinds of format:
![image](https://user-images.githubusercontent.com/20583076/70017644-98380880-15be-11ea-95e4-a966e0bb0dba.png)
![image](https://user-images.githubusercontent.com/20583076/70017651-9cfcbc80-15be-11ea-876a-467a3492bce4.png)
![image](https://user-images.githubusercontent.com/20583076/70017658-9ff7ad00-15be-11ea-8f3d-0ce5bb4afb6c.png)
![image](https://user-images.githubusercontent.com/20583076/70017672-a25a0700-15be-11ea-8d83-f29e9d07cb1f.png)

Didn't find out a general good way to achieve that.
I check the source code of Tika parser, they extract it in a rule-based method...
```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
``` 

**Observed**

Please add your observed behavior here

**Expected**

Please add your expected behavior here.

**Comment by adamshakhabov** [comment]
Use follow code example to get OLEObjects from the first slide presentation:

```
public static IEnumerable<DocumentFormat.OpenXml.Presentation.GraphicFrame> GetOleObjects(string pptxFilePath)
{
    using (var doc = PresentationDocument.Open(pptxFilePath, false))
    {
        // Gets first slide
        var sld = doc.PresentationPart.SlideParts.First().Slide;
        // OLEObjects is stored in graphic frame element
        var oleFrames = new List<DocumentFormat.OpenXml.Presentation.GraphicFrame>();
        foreach (var frame in sld.CommonSlideData.ShapeTree.OfType<DocumentFormat.OpenXml.Presentation.GraphicFrame>())
        {
            if (frame.Descendants<DocumentFormat.OpenXml.Presentation.OleObject>().Any())
            {
                oleFrames.Add(frame);
            }
        }

        return oleFrames;
    }
}
```

**Comment by hong1997** [comment]
> Use follow code example to get OLEObjects from the first slide presentation:
> 
> ```
> public static IEnumerable<DocumentFormat.OpenXml.Presentation.GraphicFrame> GetOleObjects(string pptxFilePath)
> {
>     using (var doc = PresentationDocument.Open(pptxFilePath, false))
>     {
>         // Gets first slide
>         var sld = doc.PresentationPart.SlideParts.First().Slide;
>         // OLEObjects is stored in graphic frame element
>         var oleFrames = new List<DocumentFormat.OpenXml.Presentation.GraphicFrame>();
>         foreach (var frame in sld.CommonSlideData.ShapeTree.OfType<DocumentFormat.OpenXml.Presentation.GraphicFrame>())
>         {
>             if (frame.Descendants<DocumentFormat.OpenXml.Presentation.OleObject>().Any())
>             {
>                 oleFrames.Add(frame);
>             }
>         }
> 
>         return oleFrames;
>     }
> }
> ```

Hi adamshakhabov,  thanks for your reply! According to my knowledge, the ole object should be stored in embedded object parts(X.MainDocumentPart.EmbeddedObjectParts), and I am asking for a method to parse the oleobject instead of just getting it.

**Comment by adamshakhabov** [comment]
Hi @hong1997!
 
I think Open XML SDK has not some specific method for OLEObject element reading (parse its properties). Can you say more precise, which one feature of OLEObject you try to parse?

_Also, it would be better if you attach pptx-file with this OLEObject case._

**Comment by ThomasBarnekow** [comment]
@hong1997 and @adamshakhabov, GitHub issues are not the place to ask and discuss questions regarding Open XML SDK library **usage**. You should ask usage-related questions on stackoverflow.com, where you will already find a large number of questions and answers tagged with `openxml` or `openxml-sdk`. 

In this specific case, another user already asked about how he could extract OLE-embedded files from Word documents, and I provided an [accepted answer](https://stackoverflow.com/questions/59106776/how-to-extract-ole-file-from-word-docx-by-openxml-through-c-sharp/59110419#59110419).

**Comment by hong1997** [comment]
@ThomasBarnekow , thanks for your info, I will close the issue. However, the answer you provided only handles 1 kind of OLE structure. You could see from my description that only the last kind of ole object can be handled by the class you provided.

**Comment by lindexi** [comment]
Some of the OLE can show as wmf image

**Comment by twsouthwick** [comment]
Thanks everyone for an interesting discussion. This looks to have been resolved so I'll close the issue.
