### ISSUE TITLE
Breaking changes since v2.5?

### ISSUE THREAD

**Issue by gabisandor** [OfficeDev/Open-XML-SDK#66]
We are currently using the binary release of Open XML SDK v2.5 in our organization and we want to use Open XML Power Tools. However, it seems that the power tools strictly require version 2.6 of the SDK, so we might have to upgrade it.

Are there any breaking changes that we should know of between 2.5 and 2.6? I'm afraid I can't figure out from the repo history where 2.5 ends and 2.6 starts and which are the changes.

**Comment by EricWhiteDev** [comment]
There are no breaking changes between 2.5 and 2.6.  There are tags on the master branch, if you want to find out the specific changes.  The key difference was the new System.IO.Packaging, which fixes a crappy bug in the System.IO.Packaging that comes from WindowsBase.

The latest Open-Xml-PowerTools still works with 2.5.  You just need to compile / link appropriately.
