### ISSUE TITLE
Enable external viewing of CI failures

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#666]
Since we're using an internal DevOps instance, it makes it challenging for the community to see errors (especially since the matrix we build for is larger than the default build in VS). This issue is to track enabling some way to view into the results (potentially GitHub checks, but open to ideas).

**Comment by lindexi** [comment]
@twsouthwick Could we use github action?

**Comment by twsouthwick** [comment]
The challenge is we use devops for signing and unfortunately that process doesn't support running in actions.

**Comment by lindexi** [comment]
@twsouthwick I created an MR but I do not know if I ’m right to do this, could you please review it?

**Comment by twsouthwick** [comment]
After #725 , helpful status is now displayed:

![image](https://user-images.githubusercontent.com/583206/82507030-14170600-9ab6-11ea-99f0-bae37c4b1eb1.png)

For an example, see #727
