### ISSUE TITLE
n open xml exaples

### ISSUE THREAD

**Issue by AceTheWiz** [OfficeDev/Open-XML-SDK#673]
# Before submitting an issue, please fill this out

Is this a:
- [ ] Issue with the OpenXml library
- [ ] Question on library usage

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

---------------- Remove this line and above before posting ----------------

**Description**

Please provide a simple description of the issue encountered.

**Information**

- .NET Target: (ie .NET Framework, .NET Core, UWP, Xamarin, etc)
- DocumentFormat.OpenXml Version: (ie 2.7.2)

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
``` 

**Observed**

Please add your observed behavior here

**Expected**

Please add your expected behavior here.

**Comment by ThomasBarnekow** [comment]
@AceTheWiz, would you mind providing a description of your issue in the structure provided by the template that you are asked to fill in? "n open xml exaples" is not enough to work with ...

**Comment by ThomasBarnekow** [comment]
@twsouthwick, as there's not been any reaction for over a week now, I'd suggest you close this issue (or even delete if possible).

**Comment by twsouthwick** [comment]
No delete option, and in case @AceTheWiz  wants to update their issue, it's good to track.
