### ISSUE TITLE
Objects are not correctly initialized when using constructor with OuterXml

### ISSUE THREAD

**Issue by avonwyss** [OfficeDev/Open-XML-SDK#683]
**Description**

When creating SDK objects with OuterXml string, properties which should be set may be uninitialized (null).

**Information**

- DocumentFormat.OpenXml Version: 1.10.0

The same code works with version 2.9.1

**Repro**

```csharp
var style = new DocumentFormat.OpenXml.Wordprocessing.Style("<w:style w:type=\"paragraph\" w:styleId=\"Heading1\" xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\">\r\n  <w:name w:val=\"heading 1\" />\r\n  <w:basedOn w:val=\"Normal\" />\r\n  <w:next w:val=\"Normal\" />\r\n  <w:link w:val=\"Heading1Char\" />\r\n  <w:qFormat />\r\n  <w:pPr>\r\n    <w:keepNext />\r\n    <w:keepLines />\r\n    <w:numPr>\r\n      <w:numId w:val=\"3\" />\r\n    </w:numPr>\r\n    <w:spacing w:before=\"320\" />\r\n    <w:jc w:val=\"left\" />\r\n    <w:outlineLvl w:val=\"0\" />\r\n  </w:pPr>\r\n  <w:rPr>\r\n    <w:b />\r\n    <w:color w:val=\"187EC9\" />\r\n    <w:spacing w:val=\"4\" />\r\n    <w:kern w:val=\"32\" />\r\n    <w:sz w:val=\"32\" />\r\n  </w:rPr>\r\n</w:style>");
Assert.NotNull(style.StyleId); // StyleId is null here, until some operation is done which actually parses the XML
``` 

**Observed**

Parsing of the supplied XML is not performed when accessing certain properties.

**Expected**

All getters should assert that the provided XML has been parsed.

**Comment by twsouthwick** [comment]
Thanks for the report. I found the issue and have a fix. Apparently, our tests never validate this - good catch!

**Comment by avonwyss** [comment]
Great! It was a bit puzzling because this manifested itself as a Heisenbug; the evaluation of the properties by the debugger would trigger the initialization code...

**Comment by twsouthwick** [comment]
@avonwyss  I've pushed the fix into an updated NuGet package - update to 2.10.1 and it should work now. Thanks for the report!
