### ISSUE TITLE
SDK seems to create corrupted workbooks.

### ISSUE THREAD

**Issue by JordiMola** [OfficeDev/Open-XML-SDK#688]
**Description**

Creating the "sample minimal" Excel spreadsheet with the SDK seems to create a corrupted file (Excel doesn't like it). If I add some row data I still get the issue.

**Information**

- .NET Target: .NET Core (although I could also repro it with .NET Framework)
- DocumentFormat.OpenXml Version: 2.10.0

**Repro**

```csharp
using (SpreadsheetDocument document = SpreadsheetDocument.Create("D:\\Diff\\Sample2\\Foo.xlsx", SpreadsheetDocumentType.Workbook, false))
            {
                // A SpreadsheetDocument must have at least a WorkbookPart and a WorksheetPart
                WorkbookPart workbookPart = document.AddWorkbookPart();
                workbookPart.Workbook = new DocumentFormat.OpenXml.Spreadsheet.Workbook(); // Name ambiguity...
 
                WorksheetPart worksheetPart = workbookPart.AddNewPart<WorksheetPart>();
                worksheetPart.Worksheet = new Worksheet(new SheetData());
 
                Sheets sheets = workbookPart.Workbook.AppendChild(new Sheets());
 
                Sheet sheet = new Sheet() { Id = workbookPart.GetIdOfPart(worksheetPart), SheetId = 1, Name = "Test" };
                sheets.Append(sheet);
 
                SheetData sheetData = worksheetPart.Worksheet.AppendChild(new SheetData());
 
                ////Row row = new Row();
 
                ////row.Append(
                ////    ConstructCell("Id", CellValues.String),
                ////    ConstructCell("Name", CellValues.String),
                ////    ConstructCell("Birth Date", CellValues.String),
                ////    ConstructCell("Salary", CellValues.String));
 
                ////// Insert the header row to the Sheet Data
                ////sheetData.AppendChild(row);
 
                ////uint id = 1;
                ////foreach (Spreadsheet spreadsheet in m_sheets.Values)
                ////{
                ////    Debug.Assert(spreadsheet != null);
 
                ////    spreadsheet.SaveToExcel(workbookPart, sheets, id++);
                ////}
 
                workbookPart.Workbook.Save();
 
                document.Close();
            }
``` 

**Observed**

Excel complains when trying to open the file, message:

We found a problem with some content in 'Foo.xlsx'. Do you want us to try to recover as much as we can? If you trust the source of this workbook, click Yes.

**Expected**

The workbook opens just fine in Excel.

**Comment by ScottHaney** [comment]
It works for me if you remove the line (`SheetData` is already added to `Worksheet` when it was passed in as an argument to the constructor so this extra line causes it to be added twice):

> `SheetData sheetData = worksheetPart.Worksheet.AppendChild(new SheetData());`

and also replace `workbookPart.Workbook.Save()` with `document.Save()`. Where did you get this sample from? If it is in the github repo it should be updated otherwise this should have been a question on stackoverflow.

**Comment by JordiMola** [comment]
That did it, thank you.

I'll contact the owner of the page where I copied this from (after making sure it wasn't my copy/paste) mistake.

Thanks!
