### ISSUE TITLE
Open XML SDK Documentation and Samples

### ISSUE THREAD

**Issue by mojtabakaviani** [OfficeDev/Open-XML-SDK#71]
work with open xml sdk not easy and not enough documentation in internet.
we needs more documentation and samples for new features and advanced capabilities.

**Comment by ThomasBarnekow** [comment]
There is a ton of documentation, e.g., on http://openxmldeveloper.org and https://msdn.microsoft.com/en-US/en-en/library/office/bb448854.aspx

Just google "OpenXML SDK".
