### ISSUE TITLE
The OpenXmlPartContainer.DeletePart will throw exception when the id not found

### ISSUE THREAD

**Issue by lindexi** [OfficeDev/Open-XML-SDK#713]
# Before submitting an issue, please fill this out

Is this a:
- [x] Issue with the OpenXml library
- [ ] Question on library usage

**Description**

As we can see the OpenXmlPartContainer.DeletePart can delete the part, but this API will throw ArgumentOutOfRangeException when the part with the specified id does not exist.

Because the `DeletePart` call the `DeletePartCore` which will call the `GetPartById` to get the part.

https://github.com/OfficeDev/Open-XML-SDK/blob/0f1764a866e36d615e22d247e780fb7675046e9a/src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs#L1762

But the `GetPartById` will throw ArgumentOutOfRangeException when the part with the specified id does not exist.

https://github.com/OfficeDev/Open-XML-SDK/blob/0f1764a866e36d615e22d247e780fb7675046e9a/src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs#L529-L547

Yes, it means that the branch will never enter when the id not found

https://github.com/OfficeDev/Open-XML-SDK/blob/0f1764a866e36d615e22d247e780fb7675046e9a/src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs#L1764-L1768

**Information**

- .NET Target: All 
- DocumentFormat.OpenXml Version: 2.10.1

**Repro**

```csharp
public static void Delete(this string id, OpenXmlPart part)
{
     part.DeletePart(id);
}
``` 

**Observed**

The `part.DeletePart` will throw the exception when the part with the specified id does not exist.

**Expected**

As the other API design, the delete method should not throw exception the element does not exist.

**Comment by twsouthwick** [comment]
Can you point to other APIs in the SDK that do not throw when deleting? I agree we would want consistency, just want to document where else that is occuring.

**Comment by lindexi** [comment]
@twsouthwick Thank you. And my question is 

- We can not sure the OpenXmlPartContainer contain the part with the specified id.
-  The `OpenXmlPackage.DeleteRelationship` do not throw exception when the deleted item not found. But the other API like `OpenXmlPartContainer.DeleteExternalRelationship` will throw exception.

https://github.com/OfficeDev/Open-XML-SDK/blob/c595b4bb4a4733093e2295d7902145b8c82364a5/src/DocumentFormat.OpenXml/Packaging/OpenXmlPart.cs#L753-L758

https://github.com/OfficeDev/Open-XML-SDK/blob/0d0f40da29ac29adb5243189f53f95aa345c8b47/src/DocumentFormat.OpenXml/Packaging/OpenXmlPartContainer.cs#L249-L273

Assuming that the correct way to use it is to throw an exception when deleting a nonexistent element, I think it is necessary to provide a general method to determine whether an element exists

**Comment by lindexi** [comment]
And the other type like `List` and so on in dotnet will not throw exception when the item not found

https://github.com/dotnet/runtime/blob/0ab835c0b27280b87db4385740107bf878f1c491/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L832-L842

**Comment by twsouthwick** [comment]
Thanks for the research. Can you make a list of the APIs that throw and submit a PR to just exit instead of throwing?

**Comment by lindexi** [comment]
@twsouthwick Thank you. And sorry I do not how to solve it. What I'm worried about is that this change will change the behavior of the SDK.

Sorry, I just point the problem and I do not know how to solve it.

**Comment by lindexi** [comment]
@twsouthwick After https://github.com/OfficeDev/Open-XML-SDK/pull/714 merged, we can use this API to check whether the OpenXmlPartContainer contain the part with the specified id. So, there are ways to avoid this problem.

```csharp
if (container.TryGetPartById(id, out _)
{
        part.DeletePart(id);
}
```

**Comment by twsouthwick** [comment]
It's merged so that should be available :)

**Comment by twsouthwick** [comment]
Just making sure, do you want to provide a PR? Your code snippet using `TryGetPartById` would be the pattern to use.

**Comment by lindexi** [comment]
@twsouthwick I do not want to provide a PR because I do not know how to do

**Comment by stoiveyp** [comment]
@twsouthwick I'd be interested in picking this up, seems like a straight forward change to start with
