### ISSUE TITLE
How to refer existing excel sheet in a chart created in ppt like vba

### ISSUE THREAD

**Issue by Amitloh** [OfficeDev/Open-XML-SDK#717]
# Before submitting an issue, please fill this out

Is this a:
- [ ] Issue with the OpenXml library
yes
- [ ] Question on library usage
yes

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

---------------- Remove this line and above before posting ----------------

**Description**

Please provide a simple description of the issue encountered.

**Information**

- .NET Target: (ie .NET Framework, .NET Core, UWP, Xamarin, etc)
- DocumentFormat.OpenXml Version: (ie 2.7.2)

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
``` 

**Observed**

Please add your observed behavior here

**Expected**

Please add your expected behavior here.

**Comment by twsouthwick** [comment]
@Amitloh Doesn't look like you have filled any of the template out. Your title implies this is more a How-To kind of question. Can you please post that to StackOverflow? I'll close this for now, but please link your StackOverflow link here. If this is a bug in the SDK, feel free to re-open with more information.

**Comment by Amitloh** [comment]
ok sure will put it on stackoverflow. Thanks.
