### ISSUE TITLE
Support for .NET Core

### ISSUE THREAD

**Issue by Suriman** [OfficeDev/Open-XML-SDK#72]
It would be very useful that Open XML SDK will be ported to .NET Core.

Thanks!

**Comment by eriawan** [comment]
@Suriman ,

This would not be possible in the near future. There's a dependency on WPF assembly, WindowsBase.dll.

In broader sense, porting to .NET Core will also means to be able to run under other OS, and therefore  making OpenXML SDK to be cross platform.
Unless OpenXML SDK dev team has found solution to provide same functionality to replace this WPF dependency, we could not port to .NET Core easily.

**Comment by eriawan** [comment]
Ah, this issue should be closed, it's already discussed in #65.
I'm glad to know that System.IO.Packaging is ported to be in .NET Core 5 :smile: 

ping @EricWhiteDev

**Comment by twsouthwick** [comment]
Work for this is being tracked by #111

**Comment by igitur** [comment]
@Suriman Please close this issue.
