### ISSUE TITLE
CellValue ctor for DateTime and DateTimeOffset should use proper xml standard format

### ISSUE THREAD

**Issue by jurijr** [OfficeDev/Open-XML-SDK#724]
Issue with the OpenXml library

**Description**

CellValue created via DateTime constructor does not serialize xml string properly.
With the latest version of Excel the document xml has no problems loading, however with Excel 2016 it fails to load the xml value.

Further inspection showed the issue was with "midnight" date cell value "2019-09-25T00:00:00.0000000". 
If you trim down the miliseconds, it works, 
If you add actual miliseconds, it works.

To workaround the issue I have used the string constructor with date formatted via `XmlConvert.ToString`

For example:

```
new DateTime(2019, 9, 25, 0, 0, 0)
    should be
"2019-09-25T00:00:00"
    but was
"2019-09-25T00:00:00.0000000"
```

```
new DateTime(2019, 9, 25, 0, 0, 0).AddMilliseconds(123)
    should be
"2019-09-25T00:00:00.123"
    but was
"2019-09-25T00:00:00.1230000"
```

**Comment by twsouthwick** [comment]
@jurijr Thanks for the issue. Would you be up for submitting a PR to fix this?

@tomjebo Can I get your thoughts on the valid form here?

**Comment by twsouthwick** [comment]
#697 is somewhat related. CellValue could provide a way to validate itself for the different types
