### ISSUE TITLE
[OSX] test failures due to hard coded path separators?

### ISSUE THREAD

**Issue by Numpsy** [OfficeDev/Open-XML-SDK#73]
I just tried to run some document handling code that i'm trying to port from Windows to OS X/Mono using the latest SDK/system.io.packaging, and some some errors that seem to be down to zip handling.
I thought i'd give the units test a go to see what those do, and got rather a lot of failures.

However, looking at the output, a load of those look as though they could be down to hard coded path separators in the tests.

e,g,

   DocumentFormat.OpenXml.Tests.DocumentTraverseTest.TraverseWordDocument [FAIL]
      System.IO.DirectoryNotFoundException : Directory '/Users/rwebb/Documents/gitrepos/Open-XML-SDK/TestDataStorage/v2FxTestFiles/wordprocessing\paragraph' not found.

I'm guessing that the paths in /DocumentFormat.OpenXml.Tests/OpenXmlDomTest/OpenXmlCompositeElementTestClass.cs should be using the system path separator char instead of hardcoding things like @"presentation\smallset" ?

**Comment by EricWhiteDev** [comment]
I'm not surprised.  This definitely needs addressed.  One of the action items coming up is to port the Open-Xml-Sdk to COREFX, which is multi-platform, so this certainly will be addressed in that process.

I think I am a couple of months out from tackling this work.  Of course, pull requests are welcome.  :-)

**Comment by sergey-tihon** [comment]
separators should be fixed in #82

**Comment by Numpsy** [comment]
I think these should all be sorted in vNext now.

**Comment by twsouthwick** [comment]
This issue has been addressed at some point and all tests are passing. Closing issue.
