### ISSUE TITLE
Semantic Error : Attribute 'si' should be present when the value of attribute 't' is 'shared'.

### ISSUE THREAD

**Issue by 06needhamt** [OfficeDev/Open-XML-SDK#735]
Is this a:
- [X] Issue with the OpenXml library
- [ ] Question on library usage

**Description**

Semantic Error : Attribute 'si' should be present when the value of attribute 't' is 'shared'.  On 2 separate valid Office 365 Excel documents.

**Information**

- .NET Target: NET 4.6.2
- DocumentFormat.OpenXml Version: 2.11.0

**Repro**

``` csharp
class Program
    {
        static void Main(string[] args)
        {
            OpenXmlPackage spreadsheetDocument1 = SpreadsheetDocument.Open("DiversenBerekeningen.xlsm", false);
            List<ValidationErrorInfo> errorInfos1 = ValidateDocument(spreadsheetDocument1);

            foreach (ValidationErrorInfo info in errorInfos1)
            {
                Console.WriteLine(string.Format("DiversenBerekeningen.xlsm Error Occurred {0}", info.Description)); 
            }

            OpenXmlPackage spreadsheetDocument2 = SpreadsheetDocument.Open("DiversenGrafiekenPeltier.xlsm", false);
            List<ValidationErrorInfo> errorInfos2 = ValidateDocument(spreadsheetDocument2);

            foreach (ValidationErrorInfo info in errorInfos2)
            {
                Console.WriteLine(string.Format("DiversenGrafiekenPeltier.xlsm Validaton Error Occurred {0}", info.Description));
            }

            Console.ReadKey();
        }

        static List<ValidationErrorInfo> ValidateDocument(OpenXmlPackage package)
        {
            OpenXmlValidator validator = new OpenXmlValidator(FileFormatVersions.Office2019);
            List<ValidationErrorInfo> validationErrors = validator.Validate(package).ToList();

            return validationErrors;
        }
    }
```

**Observed**

The following validation error was reported on both files.

Semantic Error : Attribute 'si' should be present when the value of attribute 't' is 'shared'

**Expected**

Both files should have been validated successfully without errors.

[Invalid Files.zip](https://github.com/OfficeDev/Open-XML-SDK/files/4730346/Invalid.Files.zip)

**Comment by gunnsth** [comment]
We are running into this too.

**Comment by 06needhamt** [comment]
Is there any ETA on a fix for this issue?

**Comment by twsouthwick** [comment]
Can you include a repro? Also, is this present on previous versions or just 2.11?

**Comment by 06needhamt** [comment]
@twsouthwick Thank you for your response. I have added a repro in the initial comment.

**Comment by twsouthwick** [comment]
Thanks @06needhamt. I found the issue - checking if something is false instead of true :) There are still validation issues in the file you sent, but they don't look to be an issue with the validator, but the data. Those issues are:

```
 The attribute 'horizontalDpi' has invalid value '0'. The MinInclusive constraint failed. The value must be greater than or equal to 1.
 The attribute 'verticalDpi' has invalid value '0'. The MinInclusive constraint failed. The value must be greater than or equal to 1.
```

It's a different validation. When you say you expect it to not fail validation, are these not expected as well?

**Comment by 06needhamt** [comment]
@twsouthwick Thanks for the fix. I should have been more clear I was referring to that one specific validation issue the others that you reported were expected.

**Comment by twsouthwick** [comment]
Cool. It's merged in now and will be available via CI. We'll probably cut a 2.11.1 release soon as we've got a few other fixes to get out.
