### ISSUE TITLE
[OSX/MONO] 'The entry is already currently open for writing' errors when running tests

### ISSUE THREAD

**Issue by Numpsy** [OfficeDev/Open-XML-SDK#74]
When trying to run the unit test of OSX/Mono 4.3.3, I get some test failures along the lines of

```
DocumentFormat.OpenXml.Tests.OpenXmlPackageTest.PackageValidateTest [FAIL]
      System.IO.IOException : The entry is already currently open for writing.
      Stack Trace:
           at System.IO.Compression.ZipArchiveEntry.Open () <0x11475a8f0 + 0x00155> in <filename unknown>:0 
           at System.IO.Packaging.ZipStreamManager.Open (System.IO.Compression.ZipArchiveEntry zipArchiveEntry, FileMode streamFileMode, FileAccess streamFileAccess) <0x11475a660 + 0x00113> in <filename unknown>:0 
           at System.IO.Packaging.ZipPackagePart.GetStreamCore (FileMode streamFileMode, FileAccess streamFileAccess) <0x11475a430 + 0x00057> in <filename unknown>:0
```

Which look to be down to calling zipStreamManager.Open twice in ZipPackagePart.GetStreamCore() (https://github.com/OfficeDev/Open-XML-SDK/blob/vNext/System.IO.Packaging/ZipPackagePart.cs#L50).

Not sure if there is a Mono issue here with something not being closed, but besides that, is it actually necessary to open the stream twice here?

**Comment by Numpsy** [comment]
>>> Not sure if there is a Mono issue here with something not being closed

Actually, seems like a more general lssue with ZipArchiveEntry always being 'open' after being opened once (Open() just checks if the existing stream is non-null, and throws even if the stream has been disposed).
The tests have more of these exceptions where OpenXMLPackage.Dispose() tries to write any changes to the archive, and it fails because it thinks they're already open for write.

I guess that the Mono ZipArchiveEntry should do the same as the MS version and pay attention to the stream being disposed, but i'm not sure how all the layers hang together to be sure :-(

**Comment by EricWhiteDev** [comment]
This was an issue that I ran into when doing the new implementation of System.IO.Packaging.  The old System.IO.Packaging (from the WindowsBase assembly) was forgiving if an application opened a stream more than once.  The old System.IO.Packaging was based on a hacked internal implementation of Zip files, and this internal implementation did not complain if an app opened a stream twice.  There are probably some new semantics / limitations on Mono, which need to be sorted.

**Comment by Numpsy** [comment]
At a low level, the code

```
    using (ZipArchive archive = new ZipArchive(input, ZipArchiveMode.Update))
     {
         ZipArchiveEntry selectorEntry = archive.GetEntry("readme.txt");
         using (Stream temp = selectorEntry.Open())
          {
              Console.WriteLine("Open1");
          }

         using (Stream temp = selectorEntry.Open())
          {
               Console.WriteLine("Open2");
          }
     }
```

Works on .NET4.5 (VS 2015), but on Mono throws an 'already open' exception at the second open. Assuming this is supposed to work, it seems like a Mono issue?

**Comment by EricWhiteDev** [comment]
Good information.  This sheds some light on the issue.  This certainly does seem to be a Mono issue.

Question: what happens if you explicitly close the stream inside the using statement?

**Comment by Numpsy** [comment]
That doesn't change anything.

The check in ZipArchiveEntry.Open is just

```
			if (openStream != null && Archive.Mode == ZipArchiveMode.Update)
				throw new IOException("The entry is already currently open for writing.");
```

Changing it to check if the stream is non-null yet disposed (or if CanRead/CanWrite/CanSeek are all false at least) avoids the error, but I'm not sure of there are other issues elsewhere.
I'll mention it on the Mono making list and see.

**Comment by EricWhiteDev** [comment]
Thank you.  Will be curious to see if you get a response.

It probably is not doable to avoid this through the SDK - it relies in many places on opening / closing streams working.

**Comment by Numpsy** [comment]
Ok, a fix for the issue has been made to Mono

https://github.com/mono/mono/pull/2659

hopefully it'll be ok in Mono 4.3 :-)

**Comment by EricWhiteDev** [comment]
Fantastic.  Is there any info on when 4.3 will be available?

**Comment by akoeplinger** [comment]
It's in the branch that will become the next stable Mono (v4.4) and should already be in the current build that is in the alpha channel right now :)

**Comment by sergey-tihon** [comment]
The same error on Mono 4.3.2 from alpha channel https://travis-ci.org/sergey-tihon/Open-XML-SDK/jobs/115731149#L2623
In #82 I have tried to run on `latest`, `alpha` and `beta` versions on Mono https://travis-ci.org/sergey-tihon/Open-XML-SDK/builds/115731147 Tests fails on all of them.

**Comment by Numpsy** [comment]
I also got 23 failures in Packaging.Tests last time I tried them, but that was down to #64 rather than the open streams issue.

**Comment by twsouthwick** [comment]
This issue has been addressed in Mono. Closing issue. Please reopen if issue persists.
