### ISSUE TITLE
Can we use SmartTagClean to replace the abbreviations SmtClean property name

### ISSUE THREAD

**Issue by lindexi** [OfficeDev/Open-XML-SDK#743]
**Description**

I find the property named `SmtClean` in TextCharacterPropertiesType, and the full name of this property should be `SmartTag Clean` 

Can we use `SmartTagClean` to replace the abbreviations `SmtClean` property name in TextCharacterPropertiesType?

Also, I want to replace the property named `SmtId` with the full name "SmartTagId"

**Information**

- .NET Target: (ie .NET Framework, .NET Core, UWP, Xamarin, etc)  All
- DocumentFormat.OpenXml Version: 2.11.0

**Repro**

https://github.com/OfficeDev/Open-XML-SDK/blob/master/src/DocumentFormat.OpenXml/GeneratedCode/schemas_openxmlformats_org_drawingml_2006_main.g.cs

Line: 27709

**Observed**

The property named `SmtClean` in TextCharacterPropertiesType is an abbreviation

**Expected**

We can change the property name to full name

Suitable?

**Comment by twsouthwick** [comment]
I'm fine with that. There's a lot of historical choices here that aren't as common (such as abbreviations... I mean, we don't have the same file limitations as 2 decades ago!).

@tomjebo any thoughts on this renaming?

**Comment by twsouthwick** [comment]
btw this will have to be in the schema generation side which is still closed source (no timeframe on open sourcing that). It's a simple change, but FYI
