### ISSUE TITLE
Not able to add chart in spreadsheet

### ISSUE THREAD

**Issue by RAVIDHOBLE** [OfficeDev/Open-XML-SDK#755]
Am new to C# and OpenXML. As per the example shown in this link [https://docs.microsoft.com/en-us/office/open-xml/how-to-insert-a-chart-into-a-spreadsheet](url) I can't see the chart added to the generated spreadsheet.
In this below code snipet the Uri link is not working. 
graphicFrame.Append(New Graphic(New GraphicData(New ChartReference() With _
                {.Id = drawingsPart.GetIdOfPart(chartPart)}) With {.Uri = _
                "http://schemas.openxmlformats.org/drawingml/2006/chart"}))
I also tried to use other .Uri http link. but not able to see the expected chart in the output spreadsheet. Looking for a solution to this.

**Comment by twsouthwick** [comment]
Can you include a snippet of code that we can review to see what the issue is? FYI, this is most likely not an issue with SDK, and could be asked on Stackoverflow
