### ISSUE TITLE
AttributeCollection's IsEmpty will alway be false

### ISSUE THREAD

**Issue by lindexi** [OfficeDev/Open-XML-SDK#759]
**Description**

The IsEmpty property in AttributeCollection will always be false, because the `_data` is never been null

As the Constructor code says, we will set the `_data` field a not null value

https://github.com/OfficeDev/Open-XML-SDK/blob/0977a9430407115ff9ed149f60496fbb2688b5e5/src/DocumentFormat.OpenXml/Framework/Metadata/AttributeCollection.cs#L15-L27

And the `IsEmpty` property will be false only when the `_data` is null

https://github.com/OfficeDev/Open-XML-SDK/blob/0977a9430407115ff9ed149f60496fbb2688b5e5/src/DocumentFormat.OpenXml/Framework/Metadata/AttributeCollection.cs#L29

**Comment by twsouthwick** [comment]
Good catch! Is that used any where? Maybe can delete it or update to check for `.Length == 0`

**Comment by lindexi** [comment]
@twsouthwick I can not find any code use it and I think we can delete it

**Comment by twsouthwick** [comment]
You can add that into the PR you're doing to remove the `Contains` method.

I've been revamping the infrastructure to consolidate concepts and help reason about metadata. Some of these methods were used at different points. Thanks for exploring in here!

**Comment by lindexi** [comment]
> 
> 
> @twsouthwick I can not find any code use it and I think we can delete it



@twsouthwick I find the `ElementState` will use the `AttributeCollection.IsEmpty` property. And I can not delete it.

**Comment by lindexi** [comment]
@twsouthwick  I seem to have found an null reference exception, could you help me?

The `ElementMetadata.Builder.BuildAttributes` will return null when the `_attributes` is null.

```csharp
            private AttributeMetadata[] BuildAttributes()
            {
                if (_attributes is null)
                {
                    return default;
                }
                // Ignore code
            }
```

And it will make the ElementMetadata receive the null argument, and that means the `ElementMetadata.Attributes` may be null.

```csharp
        internal ElementMetadata(
            ReadOnlyArray<AttributeMetadata> attributes,
            ReadOnlyArray<IValidator> validators,
            ReadOnlyArray<IValidator> constraints,
            FileFormatVersions version,
            SchemaAttrAttribute schema,
            CompiledParticle particle,
            Lazy<ElementLookup> lookup)
        {
            Attributes = attributes; // may be null, when the ElementMetadata.Builder.BuildAttributes return null
            Validators = validators;
            Constraints = constraints;
            Availability = version;
            Schema = schema;
            Particle = particle;
            _children = lookup;
        }
```

And we will use the `ElementMetadata.Attributes` to create the AttributeCollection object in ElementState

```csharp
        public ElementState(ElementMetadata metadata)
        {
            // The metadata.Attributes may be null
            Attributes = new AttributeCollection(metadata.Attributes);
            Metadata = metadata;
        }
```

And the AttributeCollection will throw null reference exception when the metadata.Attributes is null.

```csharp
        public AttributeCollection(ReadOnlyArray<AttributeMetadata> tags)
        {
            _attributes = tags;

            // The tags may be null
            if (tags.Length == 0)
            {
                _data = Cached.Array<OpenXmlSimpleType>();
            }
            else
            {
                _data = new OpenXmlSimpleType[tags.Length];
            }
        }
```

**Comment by twsouthwick** [comment]
Do you have a repro of a null red? The readonly array is a custom type that gracefully handles null. If you have a repro, that would be very helpful.

**Comment by lindexi** [comment]
@twsouthwick  Thank you. It is not null.

Why it is not null? Because we use the `DocumentFormat.OpenXml.Framework.ReadOnlyArray` to cast the null array to ReadOnlyArray object.

        public static implicit operator ReadOnlyArray<T>(T[] array) => new ReadOnlyArray<T>(array);

That means the ElementMetadata will never receive the null `attributes` argument
