### ISSUE TITLE
Validator reports error for valid "0" values in pageSetup attributes

### ISSUE THREAD

**Issue by gabisandor** [OfficeDev/Open-XML-SDK#77]
I identified the following attributes in pageSetup that trigger a "Sem_AttributeValueDataTypeDetailed" error when they have value 0:

"copies",
"firstPageNumber",
"fitToHeight",
"fitToWidth",
"paperSize",
"scale",
"verticalDpi",
"horizontalDpi"

The value 0 is acceptable in the specification: [https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.pagesetup(v=office.14).aspx](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.pagesetup%28v=office.14%29.aspx).

There might be more unsigned attribute values in this tag or others which cause such false validation errors.

**Comment by EricWhiteDev** [comment]
@gabisandor Noted.  I am addressing some validation errors for v3.0.  Not sure if this fix will make it in, but in any case, we will leave the issue open.

**Comment by gabisandor** [comment]
@EricWhiteDev I see, thanks. I'm wondering if the validation fixes will include something related to this: http://openxmldeveloper.org/discussions/formats/f/14/p/8638/164860.aspx.

**Comment by EricWhiteDev** [comment]
@gabisandor Yes, I have already addressed w:smtClean in v3.0.

**Comment by twsouthwick** [comment]
As this will be available when the Office2016 branch is merged, I'm closing this issue.
