### ISSUE TITLE
Poll: What target are you running on?

### ISSUE THREAD

**Issue by twsouthwick** [OfficeDev/Open-XML-SDK#772]
As we move forward, it would be nice to drop some old platforms that add a bunch of extra technical work (ie .NET 3.5, .NET Standard 1.3). So, I'm interested in what everyone is running on?

[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%203.5)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%203.5/vote)
[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%204.0)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%204.0/vote)
[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%204.6%2B)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%204.6%2B/vote)
[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%20Core%201.x)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%20Core%201.x/vote)
[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%20Core%202.x)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%20Core%202.x/vote)
[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%20Core%203.x)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/.NET%20Core%203.x/vote)
[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/Xamarin)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/Xamarin/vote)
[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/UWP)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/UWP/vote)
[![](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/Mono)](https://api.gh-polls.com/poll/01EDEZQY609NYXTRGVE4P67Y67/Mono/vote)

**Comment by twsouthwick** [comment]
Note: You can only select one :( Limitation of the polling system it seems

**Comment by Trysor** [comment]
Attempting to upgrade from .NET Framework 4.8 to Core but I've run into issues discussed across several issues in .NET (but perhaps most notably in https://github.com/dotnet/runtime/issues/23750), which leaves me unable to do this upgrade. Whether or not such things is considered bias in this poll or not is up to you, but here's a vote for Framework that would otherwise have been Core (3.x).

**Comment by twsouthwick** [comment]
@Trysor that's really helpful as well! Thanks for the feedback

**Comment by ThomasBarnekow** [comment]
For VSTO add-ins, I‘m targeting net472 to be fully netstandard2.0 compatible. For server-side stuff, I‘m on Net Core 3.x.

I would be interested to know for which use cases you would need anything older than net461. Just thinking that no longer supporting older .Net Frameworks might give developers an argument to finally deal with that technical debt.

**Comment by twsouthwick** [comment]
That's a good question, but I want to point out that running an application *targeting* 4.0, but running on .NET 4.8 is fully supported, hence why I'll probably continue to support a .NET 4.0 target. It is still technical debt, ie you're opting into quirks to mimic behavior for an older runtime that may cause issues if you move to targeting .NET 4.8 or .NET Core (for example, one that comes to mind for this project is https://github.com/OfficeDev/Open-XML-SDK/issues/715).

**Comment by Pitterling** [comment]
NET5 is not selectable :)

**Comment by twsouthwick** [comment]
Thanks all! Closing for now as we got the data we needed (people still use .NET 3.5 and .NET 4.0)
