### ISSUE TITLE
Looking for consultant/vendor with Open Office XML/Open XML SDK  Expertise

### ISSUE THREAD

**Issue by Corpac46** [OfficeDev/Open-XML-SDK#797]
Dear Open-XML-SDK Community,

My company is working on a large project where we are levering Open Office XML/Open XML SDK to manipulate/transform patent submission documents (Word format) as they are submitted online.  We are looking for somebody (or a vendor) with deep expertise with Open Office XML/Open XML SDK to provide technical consultation for the project.  We can accommodate a full-time resource for this role.   

Please let me know if you might know somebody who can help with this requirement.

Thanks!

**Comment by twsouthwick** [comment]
I'm going to close this comment as it is not the purpose of this issue tracker. Good luck!
