### ISSUE TITLE
Reader depth or how to get current node's real depth.

### ISSUE THREAD

**Issue by amanbolat** [OfficeDev/Open-XML-SDK#803]
Is there any approach to get `depth`, `lineNumber` or `position` of current node in a real XML file?
As it's done using native `XmlTextReader`: https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmltextreader.lineposition?view=netcore-3.1
```csharp
while (reader.Read()){
       switch (reader.NodeType){
         case XmlNodeType.Element:
           Console.Write("{0} {1},{2}  ", reader.Depth, reader.LineNumber, reader.LinePosition);
           Console.WriteLine("<{0}>", reader.Name);
           break;
       }
    }
```

I have tried to get `Depth` of OpenXMLReader, but it seems that it is returning depth of element in some stack which is not real depth of current xml node.

It would be nice to have such functionality.

**Comment by twsouthwick** [comment]
Can you show what you are doing and what you would expect?

**Comment by amanbolat** [comment]
@twsouthwick Thanks for response!
I can't show any code right now, but please look at my explanation below:

### Why
I'm working on library which converts different types of files into my own structured document. After that the structured document would be translated and should be reinserted into the original document. 
Whenever my library parses any kind of xml document, it relies on configurations with names of elements/nodes which should be parsed or not parsed during the process of converting into structured document. In order to know where those parsed texts should be reinserted, i need reliable mechanism of creating immutable unique IDs for every node.
For instance, my library would mark every node with id like that: 
```
<w:p>                                 // id:1
    <w:r>                             // id:2
        <w:rPr>                       // id:3
        <w:sz w:val="24"/>            // id:4
        <w:szCs w:val="24"/>          // etc...
        <w:rPr>
        <w:t>This is the text.</w:t>
    </w:r>
</w:p>
```

### My expectations
It would be nice to have an attribute or a function to get: 
- position of node in the text. It can be number of row or column in a real XML file.
OR
- depth of the node, including the position within siblings in one parent node.


In addition, this kind of unique and immutable id is very useful if we read and rewrite the same documents many times. So we wouldn't need parse the whole file to change just one small part of it. 

### What i'm doing currently to achieve that
I create a dictionary with a key as the name of element and value as its iteration. 
Found paragraph, `dict[p]+1`, found paragraph two `dict[p]+1`, found run one `dict[r]+1`

I don't know if that function useful for other people, but I would appreciate to have a such feature.

**Comment by twsouthwick** [comment]
Seems like a reasonable feature to include. It may be as simple as ensuring IXmlLineInfo is implemented on an internal XmlReader. If you can provide a scenario where you need this we can ensure it's surfacing the information correctly.

**Comment by amanbolat** [comment]
@twsouthwick Good evening or morning. 
There is the code I have written today. I've omitted some parts in order to show where exactly this functionality is used in my library. 
How i see it:

```csharp
_docBuilder = new DocumentBuilder();
using var doc = WordprocessingDocument.Open(source, false);
_bodyReader = OpenXmlReader.Create(doc.MainDocumentPart.Document.Body);

while (_bodyReader.Read()) {
        switch (_bodyReader.ElementType) {
        case Type parType when parType == typeof(Paragraph):
          var paragraph = (Paragraph) _bodyReader.LoadCurrentElement();
          ProcessParagraph(paragraph);

          break;
        }
}


private void ProcessParagraph(Paragraph paragraph) {
    // Depth method of OpenXMLElement returns this unique id/position/line number in 
    // actual document.xml or other xml files contained in zip file (.docx file).
    var paragraphID = paragraph.Depth();
    // this method of my library uses given unique id and creates a sentence 
    // which will be added into my custom structured document class
    _docBuilder.StartUnit(paragraphID); 


    // Then i continue parse child elements to get the text
    foreach (var element in paragraph.Elements()) {
        switch (element) {
        case Run run:
          ProcessRun(run);
          break;
    }
}

...
...
...

// This function will be used to reinsert paragraph text into the document
// Text unit is just a structure to store that paragraph in my own way
private void WriteParagraph(TextUnit unit) {
    var paragraphID = unit.ID();
    
    _wordDocument = WordprocessingDocument.Create(_mStream, WordprocessingDocumentType.Document);
    var elements = _wordDocument.MainDocumentPart.Document.Body.Elements();

     foreach (var element in elements) {
          if (element.Depth() == paragraphID) {
              // do some manipulations and insert translated text into new copy of the document
          }
     }
}

```

**Comment by twsouthwick** [comment]
I've pushed some code that will surface that information if available. Not all implementations of OpenXmlReader will have this info (such as one created from OpenXmlElement instances)

**Comment by twsouthwick** [comment]
As for the depth, there is already a property for that. Can you give an example as to what you expect and why the value right now isn't valid?

**Comment by amanbolat** [comment]
First of all, i see that i was not clear enough talking about depth.
There is an example of code with simple iteration trough the body of document.
Link: https://github.com/amanbolat/openxml_depth_example

Code: 
```csharp
class Program {
  private static void Main(string[] args) {
    using var doc = WordprocessingDocument.Open("./testdoc.docx", false);
    var reader = OpenXmlReader.Create(doc.MainDocumentPart.Document.Body);

    while (reader.Read()) {
      if (reader.IsEndElement) {
        continue;
      }
      switch (reader.ElementType) {
        case { } typ when typ == typeof(Paragraph) || typ == typeof(Body):
          Console.WriteLine("Name: {0}. Depth: {1}", reader.LocalName, reader.Depth);
          break;
      }
    }
  }
}
```
Simple structure of main xml file (i also added it to an example repo):
```xml
  <w:body>
    <w:p>
        ...Paragraph 1
    </w:p>
    <w:p>
        ...Paragraph 2 
    </w:p>
    <w:p>
        ...Paragraph 3
    </w:p>
  </w:body>
```

If we execute the program the result will be:
```
Name: body. Depth: 0
Name: p. Depth: 1
Name: p. Depth: 1
Name: p. Depth: 1
```

And I want it to be is:
```
Name: body. Depth: 0
Name: p. Depth: 0.0
Name: p. Depth: 0.1
Name: p. Depth: 0.2
```
Where the depth is: `{sequence number of parent}.{sequence number of current node}`:

```
body: 0 
    paragraph: 0.0
    paragraph: 0.1
    paragraph: 0.2
        run: 0.2.0
            text: 0.2.0.0 
            text: 0.2.0.1
    paragraph: 0.3
        run: 0.3.0
            text: 0.3.0.0 
... etc
```

As you see, every node will get unique id just relying on its and parents' depth + sequence number. 
Does it make sense to you? I hope you got the idea. 

I suppose, my suggestion might be more useful than current implementation of `Depth`. It's just my opinion.
