### ISSUE TITLE
Add support for SVG files

### ISSUE THREAD

**Issue by mattiamerzi** [OfficeDev/Open-XML-SDK#805]
Office 2016 natively supports svg as a vector image format, but OpenXml SDK does not have support for this yet.
Issue #204 has been opened back in 2017, but closed for inactivity.
I've written basic support for SVGs, and created pull request #802 , but that has been refused because modifies generated files, and the code generation process is not publicly available (sic.)

**Comment by zeroskyx** [comment]
Any news on the topic? Would be really great to utilize SVG within PresentationML documents.

**Comment by lcregencia** [comment]
any updates on SVG in OpenXML?

**Comment by AlfredHellstern** [comment]
Please update to 2.13.0 which introduces SVG support. Please let us know if you find any issues.
