### ISSUE TITLE
System.FormatException on Row.RowIndex.Value once row index hits one million

### ISSUE THREAD

**Issue by abalaci** [OfficeDev/Open-XML-SDK#806]
**Description**

I need to import data from an exceptionally large Excel worksheet (~ 1 million rows),
and I'm using the `OpenXmlReader` class to read the sheet row by row.
However, when calling the `Row.RowIndex.Value` method for the row with index 1 million,
I'm getting a `System.FormatException`.

**Information**

- .NET Target:  .NET Core 3.1
- DocumentFormat.OpenXml Version: 2.11.3
- Partial stack trace:

_System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseUInt32(ReadOnlySpan\`1 value, NumberStyles styles, NumberFormatInfo info)
   at DocumentFormat.OpenXml.UInt32Value.Parse(String input)
   at DocumentFormat.OpenXml.OpenXmlSimpleValue`1.get_Value()_

**Repro**

```csharp
using var reader = OpenXmlReader.Create(worksheetPart);
while (reader.Read())
{
    if (reader.ElementType == typeof(Row))
    {
        var row = (Row)reader.LoadCurrentElement();
        uint rowIndex = row.RowIndex.Value;
    }
}
``` 

```xml
<row r="999999" s="1" customFormat="1" ht="19.7321" customHeight="1">
    <c r="A999999" s="3" t="s">
        <v>3231031</v>
    </c>
    <c r="B999999" s="3" t="s">
        <v>18938</v>
    </c>
</row>
<row r="1e6" s="1" customFormat="1" ht="19.7321" customHeight="1">
    <c r="A1000000" s="3" t="s">
        <v>3231032</v>
    </c>
    <c r="B1000000" s="3" t="s">
        <v>440271</v>
    </c>
</row>
<row r="1.000001e6" s="1" customFormat="1" ht="19.7321" customHeight="1">
    <c r="A1000001" s="3" t="s">
        <v>3231033</v>
    </c>
    <c r="B1000001" s="3" t="s">
        <v>3231034</v>
    </c>
</row>
```

**Observed**

The value that's causing the exception is **1e6**.
What's interesting is that once the row index reaches 1,000,000, the number format of the indexes changes from base 10 to exponential notation.
What's even more curious is that this only happens for rows, because—as you can notice from the example—the values of the cell references are still base 10, even for values larger than 1,000,000.

**Expected**

I have absolutely no idea why the row indexes change format at the 1,000,000 mark, but I would expect the SDK to be able to work with them, nevertheless.

**Comment by twsouthwick** [comment]
@abalaci We've checked with the Office team and it looks like this wouldn't be supported by excel. How are you getting your input?

**Comment by twsouthwick** [comment]
@abalaci Any response? I'd like to finish verifying this before getting v2.12.0 released

**Comment by abalaci** [comment]
One thing I've noticed is that Excel turns any rows indexes in exponential format into decimal upon saving the file. However, it can definitely open and read the file either way.

**Comment by twsouthwick** [comment]
Thanks - not sure I need the actual file. I'm just trying to figure out the process here. What automated BI process?

**Comment by twsouthwick** [comment]
Actually, @abalaci can you send a copy to me directly?

**Comment by abalaci** [comment]
Sure, how does https://www.file.io/# sound?

**Comment by twsouthwick** [comment]
That works

**Comment by abalaci** [comment]
@twsouthwick, you should be able to download the file from here: https://file.io/02v5gcKJS8s0

**Comment by twsouthwick** [comment]
Sorry - just got around to trying to download it, but it's failing. Also, what's the BI process?

**Comment by twsouthwick** [comment]
You should also be able to drag and drop it into the comment here
