### ISSUE TITLE
Move to Automatic Package Restore process for nuget

### ISSUE THREAD

**Issue by george-polevoy** [OfficeDev/Open-XML-SDK#81]
Consider moving from outdated MSBuild-Integrated package restore to Automatic Package Restore, which is a recommended way for nuget.

Basically this means that the .csproj files do not contain nuget related build targets, and there is no nuget.exe in the source code repository.

Visual Studio handles the new scenario automatically, and many CI servers also have this feature: [Building a C#, F#, or Visual Basic Project](https://docs.travis-ci.com/user/languages/csharp/)

See also:
[The right way to restore NuGet packages](http://blog.davidebbo.com/2014/01/the-right-way-to-restore-nuget-packages.html)

[MSBuild-Integrated package restore vs. Automatic Package Restore](http://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore)

**Comment by avishnyakov** [comment]
+1

**Comment by tomjebo** [comment]
@george-polevoy @avishnyakov I think this is covered now in our current build. Do you agree?

**Comment by george-polevoy** [comment]
@tomjebo I think so, as long as .nuget folder is gone.
