### ISSUE TITLE
ToFlatOpcDocument() or ToFlatOpcString() throws "System.Xml.XmlException: 'For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.'"

### ISSUE THREAD

**Issue by robertmuehsig** [OfficeDev/Open-XML-SDK#815]
# Before submitting an issue, please fill this out

Is this a:
- [x] Issue with the OpenXml library
- [ ] Question on library usage

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

---------------- Remove this line and above before posting ----------------

We generate PowerPoint slides via the OpenXML SDK and it seems we are doing "something" wrong. PowerPoint opens the file just fine, but I noticed that when I invoke the `ToFlatOpcDocument` or `ToFlatOpcString` the following exception is thrown:

```
    System.Xml.XmlException: 'For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.'
```

**Information**

- .NET Target: .NET Core 3.1
- DocumentFormat.OpenXml Version: (ie 2.11.3)

**Repro**

[dtd.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/5474212/dtd.pptx)

```csharp
            byte[] content =System.IO.File.ReadAllBytes("dtd.pptx");

            MemoryStream validationStream = new MemoryStream();
            await validationStream.WriteAsync(content, 0, content.Length).ConfigureAwait(false);
            validationStream.Position = 0;

            string xDocString;
            using (PresentationDocument resultDoc = PresentationDocument.Open(validationStream, false))
            {
                var r = resultDoc.ToFlatOpcString(); // boom
            }
``` 

**Observed**

The exception is thrown. 

**Expected**

Even if we do something "strange", I would expect that this method doesn't throw this exception. As a workaround I need to implement the "ToFlatOpc" method myself and inject the "Dtdprocessing" stuff. 

It would be nice if there would be an overload to inject this setting in your method.

**Comment by twsouthwick** [comment]
Yes, we disable it due to security. Can you provide a file so we can repro it? We definitely should just ignore it, but I'm interested why there is a DTD element in there.

**Comment by robertmuehsig** [comment]
We are processing Open XML documents and maybe it has something to do how we bind "svg" images? At least PowerPoint itself is capable of opening the file, so it seems "fine".

Check the attached file:
[dtdprocessing.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/5536041/dtdprocessing.pptx)

**Comment by twsouthwick** [comment]
@robertmuehsig I'm not really sure what the FlatOpc behavior should be here. If you check `DtdProcessing.Ignore` or event `.Parse`, it strips out the DOCTYPEs and the content of the svg is therefore changed. In order to identify what should happen, I need to identify the following:

- Is the FlatOpc a doc that Office will open and write? We'll want to conform to it if so
- Do all SVG docs have the same doctype (ie `<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">`? If so, we can manually add that back in, but the above point may come into play

**Comment by robertmuehsig** [comment]
We are able to generate such documents and Office has not problems to open and edit them.
The issue came up, because  we use "ToFlatOpcDocument" in our unit tests and it failed. I'm not really sure if we are doing the svg stuff 100% correct, but it "works" (as you can see in the document). Does that help?

**Comment by twsouthwick** [comment]
So, it looks like office does not save the preamble or doctype. That makes it easier to work around.
