### ISSUE TITLE
Porting Open XML SDK Library to Modern C++

### ISSUE THREAD

**Issue by IrakliLomidze** [OfficeDev/Open-XML-SDK#817]
Is this a:
- [x] Question on library usage

**Description**
Is it any plan to port Open XML SDK Library to Modern C++?
Now C++ supports reflection and technically it is possible to port the library to the modern C++.

That will have significantly better performance and better portability.

**Comment by jdehaan** [comment]
C++ portability is at source code level... .NET is more portable (at assembly level) I do not see any good reason to do that... I doubt about your better performance argument as well...

**Comment by IrakliLomidze** [comment]
.NET core has a 3-year support lifecycle. A C++ code is more stable and you could rely on it for a long time.

About Performance: Abstraction in C++ has zero overhead. I'm sure that C++ implementation will have significantly better performance.

**Comment by lindexi** [comment]
@IrakliLomidze You can call the dotnet library in C++ project, see [Write a custom .NET Core runtime host](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting?WT.mc_id=DX-MVP-5003606 )

**Comment by ThomasBarnekow** [comment]
@twsouthwick and @tomjebo, I think this issue should be closed.
