### ISSUE TITLE
Bug report from PVS-Studio

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [OfficeDev/Open-XML-SDK#820]
Hello all.

We have found bugs using [PVS-Studio](https://www.viva64.com/en/pvs-studio/) tool (static code analyzer for C, C++, C#, and Java).

Here is the report: [Analyzing the Code Quality of Microsoft's Open XML SDK](https://www.viva64.com/en/b/0777/).

**Comment by twsouthwick** [comment]
Very interesting! Looks like some stuff we should look into. I am not familiar with that tool, but would love to see issues created for what they found. Looking over some of them are definitely latent bugs, while others I'm not so sure I trust the analysis. Happy to take issues and even happier for PRs 👍 

This project was started long before my time and I've been working hard to clean some of the old patterns up that were blatant issues and it definitely has a long tail of other issues.
