### ISSUE TITLE
No more (public) way of retrieving schema metadata

### ISSUE THREAD

**Issue by arcusmaximus** [OfficeDev/Open-XML-SDK#821]
Pull request #532 saw the removal of the "unused" SchemaAttrAttribute. However, we have software at our company that very much depends on this attribute to determine XML namespaces and attribute names based on .NET properties. (An example would be finding the "anchorx" XML attribute name for the TextWrap.AnchorX .NET property.)

I looked around for alternative ways of retrieving this information in the current version of the library, but came up empty.
* The pull request refers to OpenXmlElement.RawAttributes, but this property appears to no longer exist. There is a RawState property, but along with the Metadata property, it's not accessible from outside the library.
* Similarly, the ElementMetadata and AttributeMetadata classes are internal, making it impossible to (say) call ElementMetadata.Create\<TextWrap\>() and read the results without resorting to reflection.
* While OpenXmlElement does have a public way of retrieving OpenXmlAttributes, the OpenXmlAttribute struct doesn't contain the .NET property name.

Please add back a public way of retrieving schema metadata.

**Comment by twsouthwick** [comment]
Thanks for the feedback! I plan on opening up the DocumentFormat.OpenXml.Framework namespace as public once I'm happy with the usage. I would be happy to expose it as public with a warning for now to mark it as preview if that would be helpful so you can use it and let me know what you think about it.

**Comment by arcusmaximus** [comment]
That would be great, thank you. The Framework classes look straightforward to use, so just making them (or even just the Framework.Metadata classes) public would be plenty for us.

On a small side note, I noticed that ActivatorElementChild.GetSchema() still calls GetCustomAttribute\<SchemaAttrAttribute\>(). Presumably this always returns null now. Similarly, the XML documentation on ElementLookup still mentions the "SchemaAttrAttribute on the property type", which also no longer applies.

**Comment by twsouthwick** [comment]
Ok. Looking at what would be required, I'm going to add back the attributes so we can get a 2.12.0 release out with that. Then, I'll look at making them public for 2.13.0 and solicit your feedback on how it works.

Sorry again for not realizing that was part of the public surface that users may be relying on.

**Comment by twsouthwick** [comment]
This has been added back and will be in the 2.12.0 release
