### ISSUE TITLE
Issue after upgrade from 2.11.3 to v2.12.0 - generated excel is not valid

### ISSUE THREAD

**Issue by Pitterling** [OfficeDev/Open-XML-SDK#829]
**Description**

I'm using ClosedXML to generate some large Excel files. I just replaced OpenXML to 2.12 and the generated file is broken.
Reverting back to 2.11.3 is fixing it again. Opening the Excel shows this error message

"We found a problem with some content ... Do you want us to try to recover .."

**Information**

- .NET Target: 5.0
- DocumentFormat.OpenXml Version: 2.12.0

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
``` 

**Observed**

```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<logFileName>error140160_01.xml</logFileName>
<summary>Errors were detected in file 'C:\file_broken.xlsx'</summary>
<removedRecords>
<removedRecord>Removed Records: Cell information from /xl/worksheets/sheet5.xml part</removedRecord>
</removedRecords>
<repairedRecords>
<repairedRecord>Repaired Records: Cell information from /xl/worksheets/sheet5.xml part</repairedRecord>
</repairedRecords>
</recoveryLog>
```

I compared the worksheet within Excel from a valid workbook generated with 2.11.3 with the repaired worksheet generated by 2.12.0 and could not find any difference so far ..

Comparing the sheet5.xml files might unveil this is related to `<x:v>xxx</x:v>` following formulars 

the broken version has additional properties similiar like:
`<x:f>Param.DateRange</x:f><x:v>23-Jun-2011  06:00 - 06:00 (0:00 h)</x:v></x:c>`
`<x:f>SUBTOTAL($D3,IOSTAT[busy '[%']])</x:f><x:v>0</x:v></x:c>`

while the valid version does not have them
`<x:f>Param.DateRange</x:f></x:c>`
`<x:f>SUBTOTAL($D3,IOSTAT[busy '[%']])</x:f></x:c>`

**Expected**

Please add your expected behavior here.

**Comment by Pitterling** [comment]
opened issue at ClosedXML .. provided repro code and template
[https://github.com/ClosedXML/ClosedXML/issues/1583](https://github.com/ClosedXML/ClosedXML/issues/1583)

**Comment by twsouthwick** [comment]
Please provide the SDK code that is used to generate this.

**Comment by igitur** [comment]
As mentioned in https://github.com/OfficeDev/Open-XML-SDK/pull/774#issuecomment-757482273 : 

Hi,

This PR is a breaking change, specifically the https://github.com/OfficeDev/Open-XML-SDK/pull/774/files#diff-bfc8b437c919c6cfa4a52da72a36b29ac087ebdd0d7c2789043b6ce6bd396ff5R53 block.

Repro:
```c#
private static void Main(string[] args)
{
    using var ssd = SpreadsheetDocument.Open(@"c:\temp\template.xlsx", false);
    var wsp = ssd.WorkbookPart.WorksheetParts.First(w => w.Uri.ToString().EndsWith("sheet1.xml"));
    var sheetdata = wsp.Worksheet.Elements<SheetData>().First();
    var row = sheetdata.Elements<Row>().First(r => r.RowIndex == 8);
    var cell = row.Elements<Cell>().First(C => C.CellReference == "C8");
    System.Console.WriteLine(cell.CellValue.Text);

    cell.CellValue = null;

    ssd.SaveAs(@"c:\temp\template2.xlsx");
}
```

The `cell.CellValue = null` statement has no effect since v2.12.0. It still worked in v2.11.3. Until v2.11.3 setting and element to `null` would remove it completely from the generated XML.

@Pitterling Upload your `template.xlsx`, please.

**Comment by Pitterling** [comment]
@igitur @twsouthwick Template file uploaded
[template.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/5794553/template.xlsx)

**Comment by twsouthwick** [comment]
Thanks @igitur for looking into this.

**Comment by twsouthwick** [comment]
Fixed in v2.12.1 available on NuGet

**Comment by igitur** [comment]
Thanks @twsouthwick for the quick fix.

**Comment by Pitterling** [comment]
thx @twsouthwick , @igitur .. confirm it's fixed
