### ISSUE TITLE
Export Excel - number cells with 2 decimals

### ISSUE THREAD

**Issue by GiuliaMarradi** [OfficeDev/Open-XML-SDK#831]
# Export Excel - number cells with 2 decimals

Is this a:
[x] Issue with the OpenXml library
[ ] Question on library usage

**Description**
I have a problem with excel export where I have numeric cells with 2 decimals.

**Information**

- .NET Target: .NET Core 3.1.1
- DocumentFormat.OpenXml Version: 2.12

**Repro**
Here you can find a sample reproducing the issue.
[https://github.com/GiuliaMarradi/CreateExcel](url)
Just start the program and you can see excel produced C:\temp\output1.xlsx 

**Observed**
Cells with 1 decimal where a 0 should be added are not true numeric cells:
![image](https://user-images.githubusercontent.com/27773947/103620119-3a998c80-4f33-11eb-88ca-e3a990ba74ba.png)

Also when opening the excel I have this error, caused by those numeric but not numeric cells
![image](https://user-images.githubusercontent.com/27773947/103620330-8fd59e00-4f33-11eb-98ba-d9bfaa6d3eda.png)

**Expected**
I found an example whose behavior should be: 
![image](https://user-images.githubusercontent.com/27773947/103619767-9879a480-4f32-11eb-807b-e1de384f1cab.png)
In column B there are numeric cells with data where you can make sums and other operations.

I was inspired by this article from Codeproject (based on an older version of openxml library), but I wasn't able to get it work
https://www.codeproject.com/Articles/97307/Using-C-and-Open-XML-SDK-2-0-for-Microsoft-Office

**Comment by twsouthwick** [comment]
This appears to be a problem with using the SDK. I've pushed a PR for you to see how to fixe up some of it.

**Comment by GiuliaMarradi** [comment]
Hi, thank you very much for your help.
I tried your changes, but still something is wrong.

![image](https://user-images.githubusercontent.com/27773947/104324361-9fcb2000-54e7-11eb-90cc-aee146261383.png)
![image](https://user-images.githubusercontent.com/27773947/104324445-be311b80-54e7-11eb-94a8-df8e92b844b0.png)


Cells in column B are considered numeric, but some don't have the right formatting applied and can't be used to apply formulas.
