### ISSUE TITLE
FieldCode (w:instrText) does not preserve whitespace

### ISSUE THREAD

**Issue by avonwyss** [OfficeDev/Open-XML-SDK#833]
**Description**

When using field codes with leading or trailing whitespace, the whitespace is lost.

This is a problem because it can cause problems with nested fields in Word, e.g. `{ IF { DATE }=...`

**Information**

- .NET Target: .NET Framework
- DocumentFormat.OpenXml Version: 2.12.0

**Repro**

```csharp
var code = new FieldCode("IF ");
Trace.WriteLine(code.OuterXml);
``` 

**Observed**

```xml
<w:instrText xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">IF </w:instrText>
```

**Expected**

```xml
<w:instrText xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xml:space="preserve">IF </w:instrText>
```

**Comment by akindle** [comment]
I believe the `Space` property will add this:
`new FieldCode("IF ") {Space = SpaceProcessingModeValues.Preserve };`

**Comment by avonwyss** [comment]
Thanks @akindle , that indeed works. Nevertheless using `Preserve` as default for this element may be a good idea?

**Comment by twsouthwick** [comment]
Unfortunately, that would be a breaking change in behavior. I'll leave this open for now to see what others think, but I'd be very hesitant to change the default value.

**Comment by DawidIzydor** [comment]
I think changing the default value would cause problem for every user that expects current default behavior.
Also there is a easy solution to get the code to work as expected so I don't really think this is a bug.

**Comment by mikeebowen** [comment]
Hi @avonwyss We looked into this and it is not a bug because the SDK is mimicking the behavior of Word and Word requires the xml:space=”preserve” attribute to be set explicitly. I.e. Word only adds the code as needed, so a element with no space to preserve would not have an xml:space=”preserve” attribute. For rendering if Word receives a instText with extra space, but no xml:space=”preserve” then the space will be removed.

**Comment by avonwyss** [comment]
Thank you @mikeebowen for the feedback.

The behavior of Word you're describing is indeed like that: as soon as there is content whitespace (in any element, not just w:instrText) which would be trimmed by XML whitespace rules, Word will automatically add the xml:space=”preserve” attribute in order to prevent that whitespace from being trimmed. And this is what I expected to see as behavior.

The SDK does *not* do that. If I set a string in a FieldCode with significant space (as shown in the initial post), it does *not* automatically add the xml:space=”preserve” in order to preserve that space. If you say that it should mimic what Word is doing, then this would be a bug, even though one can easily work around as shown by @akindle .

**Comment by mikeebowen** [comment]
Hi @avonwyss thanks for the explanation, it gave me a better understanding and I think you're probably right. Unfortunately, it's a breaking change, so for now you'll have to use the work around and we will try and get it into the next major release.
