### ISSUE TITLE
SaveAs WordprocessingDocumentType.Template loses image references

### ISSUE THREAD

**Issue by timcodesdotnet** [OfficeDev/Open-XML-SDK#836]
**Description**

When converting from a .docx format to a .dotx format, the images contained in the document show "The linked image cannot be displayed. The file may have been moved, renamed, or deleted. Verify that the link points to the correct file and location".

When inspecting the generated XML and comparing to a manually saved .dotx, it appears the image loses an r:href attribute.

**Information**

- .NET Target: .NET Framework & .NET Core...untested in others
- DocumentFormat.OpenXml Version: 2.12.0

**Repro**

Create a console application, and add a folder named "files". Create a .docx file in this folder named "Doc1.docx", the document should contain an image. Change the Build Action on the file to Content and Copy Always. Run the application. Open the .dotx that is created in the executing bin\files folder. The image is missing.

```csharp
using DocumentFormat.OpenXml.Packaging;
using System.IO;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var root = Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "files");

            File.Copy(@$"{root}\Doc1.docx", @$"{root}\Doc2.docx");
            using (var doc = WordprocessingDocument.Open(@$"{root}\Doc2.docx", true))
            {
                doc.ChangeDocumentType(DocumentFormat.OpenXml.WordprocessingDocumentType.Template);

                doc.SaveAs(@$"{root}\Doc1.dotx").Close();
                doc.Close();
            }
            File.Delete(@$"{root}\Doc2.docx");
        }
    }
}

``` 

**Observed**

Images are not displayed correctly in the .dotx

**Expected**

Images should be displayed in the .dotx

**Comment by Muppets** [comment]
I tried to reproduce this here and I wasn't able to. Are you able to provide a working sample including a word document with the issue?

**Comment by timcodesdotnet** [comment]
I can't seem to reproduce it anymore either.
