### ISSUE TITLE
'Invalid Hyperlink' exception when opening the document

### ISSUE THREAD

**Issue by SergeyKn** [OfficeDev/Open-XML-SDK#85]
OpenXML version: 2.5.5631.0

When I worked with one of the documents I found out that 
`WordprocessingDocument::Open(gcnew String(documentName), true)` throws an exception 
_Invalid Hyperlink: Malformed URI is embedded as a hyperlink in the document._

There is no other way to continue working with the document except of removing that hyperlink.
Attached problematic document.
[APPSERVER.docx](https://github.com/OfficeDev/Open-XML-SDK/files/179029/APPSERVER.docx)

Same happens if i try to open the document with Open XML SDK 2.5 Productivity Tool. See screenshot.
![capture](https://cloud.githubusercontent.com/assets/1464865/13867561/41c41aa6-ed14-11e5-9550-6c93f94b4347.PNG)

**Comment by tarunchopra** [comment]
Hello SergeyKn: 

I'll have a look and get back !!

Thanks

**Comment by tarunchopra** [comment]
Hello Sergey:

I debugged the issue and observed that .net API for creating a URI (https://msdn.microsoft.com/en-us/library/ceyeze4f(v=vs.110).aspx ) is not happy with the reserved character ('$') present  in document.xml.rels :

    Target="file:///\\$APPSERVER_HOST_1$\renditiontemp" 

If we remove '$' from target and replace it with the following, then validation works fine:
  
     Target="file:///\\APPSERVER_HOST_1\renditiontemp" 

Based on this above observation, I believe that the reason for this error is invalid URI format. 

Thanks.
PS : RFC for URI is : https://tools.ietf.org/html/rfc3986

**Comment by SergeyKn** [comment]
Hi Tarun,
In my opinion, if I can create a document with a bad format Hyperlink in MS Word, then the SDK should be able to open this document (probably simply ignore it instead of failing to load the document). The document is still valid.
I keep receiving problem reports, because users keep creating documents with this type of hyperlinks. If a user puts any link with a bad format - SDK won't be able to parse it ((

Anyway appreciate that you had a look at the issue. Hope it'll be resolved in the future.

Regards
Sergey

**Comment by tarunchopra** [comment]
Hello @SergeyKn :

Can you please tell us as to how are you creating bad format hyperlink document in word? Reason I'm asking, I took your document and re-saved it using 'save as' option in Word. Word removed the existing relationship in document.xml.rels

<Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="file:///\\$APPSERVER_HOST_1$\renditiontemp" TargetMode="External"/>

And added fields in document.xml for that hyperlink.

<w:r>
     <w:fldChar w:fldCharType="begin"/>
     </w:r>
      <w:r>
      <w:instrText xml:space="preserve"> HYPERLINK "file:///\\\\$APPSERVER_HOST_1$\\renditiontemp" </w:instrText>
       </w:r>
       <w:r>
       <w:fldChar w:fldCharType="separate"/>
        </w:r>

Hence we can see that Word uses fields instead of hyperlink attribute for hyperlink, at least in this case. 

Thanks.

**Comment by SergeyKn** [comment]
Thanks for a quick response.
The steps are pretty straight forward.
1) Add a link
![image](https://user-images.githubusercontent.com/1464865/28054919-30acd15c-665a-11e7-91c1-d863cc2764d8.png)
2) Put bad formatted address 
![image](https://user-images.githubusercontent.com/1464865/28054958-551bde34-665a-11e7-954e-aafadb8506ad.png)
3) 'Save as' document to a desktop
4) Open the document with the Productivity Tool
![image](https://user-images.githubusercontent.com/1464865/28055096-d4e06a0e-665a-11e7-85e7-e172c1519b2e.png)

P.S. You are right. If I open the document and save it again as another document, I no longer can experience the issue.

Cheers
