### ISSUE TITLE
数据包中不存在指定部件

### ISSUE THREAD

**Issue by wtujvk** [OfficeDev/Open-XML-SDK#858]
**Description**
数据包中不存在指定部件

Translation: The specified part does not exist in the packet

 File.Stream -> MemoryStream
调用  WordprocessingDocument.Open(memoryStream, true)

**Information**

- .NET Target: (NET Frameworknet461)
- DocumentFormat.OpenXml Version: (2.11.3)

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
``` 

**Observed**

在 System.IO.Packaging.Package.GetPart(Uri partUri)
   在 DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   在 DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   在 DocumentFormat.OpenXml.Packaging.OpenXmlPart.Load(OpenXmlPackage openXmlPackage, OpenXmlPart parent, Uri uriTarget, String id, Dictionary`2 loadedParts)
   在 DocumentFormat.OpenXml.Packaging.OpenXmlPartContainer.LoadReferencedPartsAndRelationships(OpenXmlPackage openXmlPackage, OpenXmlPart sourcePart, RelationshipCollection relationshipCollection, Dictionary`2 loadedParts)
   在 DocumentFormat.OpenXml.Packaging.OpenXmlPackage.Load()
   在 DocumentFormat.OpenXml.Packaging.OpenXmlPackage.OpenCore(Stream stream, Boolean readWriteMode)
   在 DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(Stream stream, Boolean isEditable, OpenSettings openSettings)
   在 DocumentFormat.OpenXml.Packaging.WordprocessingDocument.Open(Stream stream, Boolean isEditable)

**Expected**

Please add your expected behavior here.

**Comment by wtujvk** [comment]
use Spire.Doc 9.1.0 is ok

**Comment by twsouthwick** [comment]
@wtujvk I've translated the issue you're reporting, but I don't see what the expected behavior is. In order to identify an SDK issue here, we'll need a repro.

**Comment by wtujvk** [comment]
//1-  error here  at, Open
using (WordprocessingDocument wordDoc = WordprocessingDocument.Open(memoryStream, true))

// throw exception here。
wordprocessingDocument.OpenCore(stream, isEditable);
![image](https://user-images.githubusercontent.com/17868266/105576622-02a59c80-5daf-11eb-8dc3-604f0cbdd60a.png)


----------------------------------------------------------------
This should be ignored。
![image](https://user-images.githubusercontent.com/17868266/105576462-dccbc800-5dad-11eb-85b4-c22f3948c649.png)

I upload a docx file。
[Demo1.docx](https://github.com/OfficeDev/Open-XML-SDK/files/5860060/Demo1.docx)

**Comment by wtujvk** [comment]
Another situation is that  partUri = /NULL
![image](https://user-images.githubusercontent.com/17868266/105578698-f3c5e680-5dbc-11eb-820a-16a8ba5eb5ae.png)

**Comment by twsouthwick** [comment]
This document is missing a relationship it says should be there `image1.jpeg`. Looks like however it was generated caused a problem. Feel free to reopen if it's tracked down to an issue in the SDK (or if there is a proposal for alternate behavior here).
