### ISSUE TITLE
Productivity Tool validation vs OpenXmlValidator

### ISSUE THREAD

**Issue by kfertitta** [OfficeDev/Open-XML-SDK#87]
I'm seeing the OpenXmlValidator v2.6.0 report some errors not being reported by the 2.5 SDK Productivity Tool.  Is this to be expected?

**Comment by EricWhiteDev** [comment]
I'm not certain.  Exactly what differences in errors are you seeing?

**Comment by tarunchopra** [comment]
@kfertitta : Please share specific details so that we can confirm if the behavior is expected or not?

**Comment by twsouthwick** [comment]
@kfertitta There is nothing we can do with this issue. If you feel like this is still persisting in new builds, please provide a repro and we can take a look.
