### ISSUE TITLE
Incorrect path in Target attribute of <Relationship> tag

### ISSUE THREAD

**Issue by ghost** [OfficeDev/Open-XML-SDK#88]
Relationship tag in /_rels/.rels after creation by SDK:
`<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="/word/document.xml" Id="Rc15b273bb4a243cd" />`
Can open document with MS Word: **yes**
Can open document with OpenOffice: **no**

Relationship tag in /_rels/.rels after creation by SDK **and resaving by MS Word**:
`<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml" Id="Rc15b273bb4a243cd" />`
_Note leading slash!_
Can open document with MS Word: **yes**
Can open document with OpenOffice: **yes**

Relationship tag in /word/_rels/document.xml.rels after creation by SDK:
`<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="/word/styles.xml" Id="R1573c7d6e53e43aa" />`
Can open document with MS Word: **yes**
Can open document with OpenOffice: **no**

Relationship tag in /word/_rels/document.xml.rels after creation by SDK **and resaving by MS Word**:
`<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml" Id="R1573c7d6e53e43aa" />`
Can open document with MS Word: **yes**
Can open document with OpenOffice: **yes**

**Comment by Numpsy** [comment]
Sounds like the same issue as #59 and #86? (affecting all the office apps with various problems occuring as a result).

**Comment by mif007** [comment]
Yes, you are right.

**Comment by tomjebo** [comment]
See the comments on [#86](https://github.com/OfficeDev/Open-XML-SDK/issues/86). I did some testing and verified against the standard (ISO 29500-2 9.1.1 and 9.3.2.2) and: 

1) absolute URI and relative path should both be correct for the <Relationship> Target attribute.
2) OpenOffice 4.1.2 (at least Calc) seems to handle absolute paths just fine, as does Microsoft Excel.

I haven't tested OpenOffice Write but if you provide a sample document or code to generate one, I can try it out.

**Comment by tomjebo** [comment]
closing as this is being discussed on #88
