### ISSUE TITLE
How to I clear cached excel chart underlying all charts values without user clicking on each chart refresh

### ISSUE THREAD

**Issue by swiftinitdotcom** [OfficeDev/Open-XML-SDK#886]
# Before submitting an issue, please fill this out

Is this a:
- [ ] Issue with the OpenXml library
- [x] Question on library usage- its a question

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

---------------- Remove this line and above before posting ----------------

**Description**

Please provide a simple description of the issue encountered.

I need to update all charts in embedded open xml based charts without user clicking on refresh

- .NET Target: (ie .NET Framework, .NET Core, UWP, Xamarin, etc)
- DocumentFormat.OpenXml Version: (ie 2.7.2)

**Repro**

```csharp
// Please add a self-contained, minimum viable repro of the issue.
// If you require external resources, please provide a gist or GitHub repro
// An Xunit style test is preferred, but a console application would work too.
``` 

**Observed**

Please add your observed behavior here

**Expected**

Please add your expected behavior here.

**Comment by twsouthwick** [comment]
Please fill in the issue template. There is no user buttons this SDK provides so I am not sure what you are referring to. As it appears to not be an SDK issue, I'm closing for now. Feel free to reopen with a repro that we can work with.
