### ISSUE TITLE
SpreadSheet custom map add x: to defaultNamespace

### ISSUE THREAD

**Issue by broegger111** [OfficeDev/Open-XML-SDK#90]
Changing an OpenEmlElement in a CustomXmlMapping adds the prefix x to the default namespace.
This results in the new xlsx file cant map to the schemas in excel.

**Comment by webartoli** [comment]
+1
I've the same problem using `DocumentFormat.OpenXml.Spreadsheet.MapInfo` that's write `xl\xmlMaps.xml` file inside xlsx package.

With prefix `x:` for default namespace `http://schemas.openxmlformats.org/spreadsheetml/2006/main` excel do not recognise properly xml maps.

Removing manually the `x:` prefix it works like a charm.

**Comment by broegger111** [comment]
This is how I solved it
`                    //add the default namespace without prefix -> this is a hack
                    var mapOuterXml = spreadsheetDocument.WorkbookPart.CustomXmlMappingsPart.MapInfo.OuterXml;
                    var xml = new XmlDocument();
                    xml.LoadXml(mapOuterXml);
                    if (xml.DocumentElement != null) xml.DocumentElement.SetAttribute("xmlns", "http://schemas.openxmlformats.org/spreadsheetml/2006/main");
                    spreadsheetDocument.WorkbookPart.CustomXmlMappingsPart.MapInfo = new MapInfo(xml.OuterXml);
                    //hack ended`
But I dont like the solution...

**Comment by webartoli** [comment]
your last comment is self describing: it is an hack! ;-)

Saving an xlsx file using ms excel the default namespace (without prefix) is `http://schemas.openxmlformats.org/spreadsheetml/2006/main`. But in the library in the file `DocumentFormat.OpenXml.NamespaceIdMap.cs` each namespace has a prefix.

Defining a xml default namespace for each output file seems an elegant solution like:

- xlsx - `http://schemas.openxmlformats.org/spreadsheetml/2006/main`
- docx- `http://schemas.openxmlformats.org/wordprocessingml/2006/main`
- ...

I've tried to remove the "x" value with "" from the _namespacePrefixList string array in `NamespaceIdMap` class and it works on excel.

This behaviour could be related to #34

**Comment by Josh-Curry** [comment]
Hi broegger111, there have been significant changes to the SDK in the past few months. Can you please verify whether or not this is still a problem that is occurring? If this is still a problem, could you please post some sample code that reproduces the issue?

Thank you.

**Comment by twsouthwick** [comment]
@broegger111  @webartoli This seems like something we may want to integrate. Do you have a repro of what is the current behavior and what you are expecting?

**Comment by webartoli** [comment]
Actually i found on Open-XML-SDK a working spreadsheet file with XmlMaps
`DocumentFormat.OpenXml.Tests\assets\TestDataStorage\v2FxTestFiles\spreadsheet\XMLMap.xlsx` but the file is not referenced by `TestAssets.TestFiles` or in general in any path.

So, I'll extract a repro with actual and expected files and I'll give you a reference shortly.

Talking about the bug: basically the file `xl\xmlMaps.xml` must be have as a default namespace this uri `http://schemas.openxmlformats.org/spreadsheetml/2006/main`.

Excel cannot handle that namespace with the `x:` prefix.

**Comment by webartoli** [comment]
You can find a repro in this repo [webartoli/Open-XML-SDK-issues-90-repro](https://github.com/webartoli/Open-XML-SDK-issues-90-repro)

Hope it helps.

**Comment by twsouthwick** [comment]
It appears that a simpler repro would be this:

```csharp
[Fact]
public void MapInfoTest()
{
    Assert.StartsWith("<MapInfo>", new MapInfo().OuterXml);
}
```

@webartoli  Is the `MapInfo` the only item you're noticing this issue on?

**Comment by twsouthwick** [comment]
@tomjebo @Josh-Curry Do either of you have input as to what should be done? I doubt we just want to remove the `x` from the `_namespacePrefixList`, but I'll defer to what you guys think

**Comment by webartoli** [comment]
@twsouthwick yes: `MapInfo` is the only item that case me some problems but opening files generated by Excel i notice that the `http://schemas.openxmlformats.org/spreadsheetml/2006/main` namespace is always a default for excel generated file.

After some searches i notice that each office programs has its own default namespace.

**Comment by ThomasBarnekow** [comment]
All, is this a bug in Excel or the SDK? In my mind, the prefix should not make a difference. Any client that reads the XML, with or without prefix but obviously with the corresponding and correct namespace definition, should be able to determine the namespace and see it is the one expected.

Other than Word and PowerPoint, Excel does not write XML with prefixes, probably to reduce the size of what gets written. Not sure whether the assumption is that no prefixes are used and whatever check is performed can‘t deal with prefixes.

**Comment by webartoli** [comment]
Excel has a bug that any Date between 1st jan 1900 and 10th jan 1900 are affected by an offset so writing the 2nd jan 1900 with the SDK, the result on excel is different.
In that case it's an Excel bug and probably should not have impact on the SDK.

In the case of the issue, it is also definitely an Excel bug and generally I agree with you but in that specific case the SDK doesn't give a way to get the expected results.
In my opinion the SDK should manage a correct parsing by Excel (the goal of an SDK): in that case any usages of the `MapInfo` SDK has no effect on Excel.

**Comment by ThomasBarnekow** [comment]
@webartoli Microsoft would have to chime in at this point and say what level of compliance with the relevant standard both Excel and the Open XML SDK should achieve. In my view, both should be able to read, process, and write compliant Open XML. If compliance is a requirement, it seems Excel has a bug, which should be fixed.

There would be two ways to work around this Excel bug. Firstly, when using the strongly typed classes, the SDK could consistently produce Open XML without prefixes for all Excel-related parts.

Secondly, you don‘t have to use the strongly typed classes to produce Open XML. You can use the Linq to XML classes (e.g., XElement) as used in the Open XML PowerTools to produce Open XML as you see fit. This way, no change to the strongly typed classes would be required.

**Comment by databird** [comment]
Very old post... but same problem in 2026 ! The "x:" namespace is still added and can cause problem on some other software that import XLSX.

Here's our hack :

When creating the speadsheet, just before disposing, we call 2 customs functions :

```csharp
SpreadsheetDocument spreadsheetDoc = DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Open(this._spreadsheetDocumentStream, true)

// your code that generate the XLSX

// Fixing problem :
FixAllWorksheetDimensions(spreadsheetDoc); //only needed if software report wrong number of lines
RemovePrefixesEverywhere(spreadsheetDoc); //remove bad namespace

spreadsheetDoc.Dispose();
```

And here's the customs functions :

```csharp
private void RemovePrefixesEverywhere(SpreadsheetDocument doc)
{
    foreach (var part in doc.GetAllParts())
    {
        try
        {
            string xml;
            using (var reader = new StreamReader(part.GetStream(FileMode.Open, FileAccess.Read)))
            {
                xml = reader.ReadToEnd();
            }
            if (xml.StartsWith("<?xml"))
            {
                // remove all "x:" prefixes and xmlns:x declaration
                xml = xml.Replace("<x:", "<").Replace("</x:", "</").Replace("xmlns:x=", "xmlns=");
                using (var writer = new StreamWriter(part.GetStream(FileMode.Create, FileAccess.Write)))
                {
                    writer.Write(xml);
                }
            }

        } catch { /* ignore parts that are not XML (e.g. images) */ }
    }
}
private void FixAllWorksheetDimensions(SpreadsheetDocument doc)
{
    foreach (var wsPart in doc.WorkbookPart.WorksheetParts)
    {
        var sheetData = wsPart.Worksheet.GetFirstChild<SheetData>();
        if (sheetData == null || !sheetData.Elements<Row>().Any())
            continue;

        uint minRow = sheetData.Elements<Row>().Min(r => r.RowIndex.Value);
        uint maxRow = sheetData.Elements<Row>().Max(r => r.RowIndex.Value);

        // max length = number of columns of the longest row
        int maxColIndex = sheetData.Elements<Row>()
                                   .Max(r => r.Elements<Cell>().Count());
        string maxCol = GetExcelColumnReference(maxColIndex);

        string dimensionRef = $"A{minRow}:{maxCol}{maxRow}";
        var dim = wsPart.Worksheet.GetFirstChild<SheetDimension>();
        if (dim == null)
        {
            dim = new SheetDimension();
            wsPart.Worksheet.InsertAt(dim, 0);
        }

        dim.Reference = new DocumentFormat.OpenXml.StringValue(dimensionRef);
        wsPart.Worksheet.Save();
    }
}
```

Enjoy it :-)

**Comment by Gaburiere-Remira** [comment]
i don't think this issue should be marked as closed, because @databird working solution is a workaround.
