### ISSUE TITLE
Validation fails for different culture

### ISSUE THREAD

**Issue by huanacaraz** [OfficeDev/Open-XML-SDK#91]
Hello, didnt found this in list of bugs so reporting it here.
When I run the tests, this three OpenXmlSimpleValueTest tests fails for me:
DecimalValueTest
DoubleValueTest
SingleValueTest
and one OpenXmlSimpleValueTest2:
SingleValueTest
(in this case the tests pass for double and decimal because they are missing real decimal number test - the value 765.43211234E11 is actually without decimal point, but with float is converted to number with decimal point because of precision..)

The reasons are like this: (problem with decimal separator)
Property InnerText 123.456 does NOT equal to expected 123,456. [Actual: 123.456, Expected: 123,456]

My locale is Slovak.

**Comment by niwrA** [comment]
I also noticed this. You can easily fix these tests (I tried) by adding CultureInfo.InvariantCulture to the ToString() method as follows:

            Assert.Equal(((float)765.43211234E11).ToString(CultureInfo.InvariantCulture), target.InnerText);
