### ISSUE TITLE
New NuGet prerelease 2.13.0-beta0002 with Office 2019 support

### ISSUE THREAD

**Issue by AndrewDavidoff** [OfficeDev/Open-XML-SDK#922]
This is a note that on April 20th we released Beta 2 version of SDK with support for Office 2019: namespaces and generated classes. Please give it a try and report issues, specifying NuGet package version number.

You need to check “Include prerelease” in VS NuGet Package Manager to see 2.13.0-beta0002 version.

**Comment by AlfredHellstern** [comment]
Closing issue. Shipping 2.13.0 release today.
