### ISSUE TITLE
using memory stream doesn't work when adding chunked content

### ISSUE THREAD

**Issue by foxjazz** [OfficeDev/Open-XML-SDK#927]
This is using openxml worddocument processing.

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

When opening the document from a file, the functions for adding content behave differently than when using memorystream to open the document.

**Comment by twsouthwick** [comment]
@foxjazz Do you have a repro? What are your observations vs expectations? We can't do much without some details as to how to repro it.
