### ISSUE TITLE
Office 365 Word starts extremly slow with a template that has "AltChunks" in it

### ISSUE THREAD

**Issue by robertmuehsig** [OfficeDev/Open-XML-SDK#929]
Office 365 Word starts extremly slow with a template that has "AltChunks" in it

We have a tool, that produces "dotx" files. The tool can automatically add content based on some variables. The added content is inserted via the OpenXML "AltChunk" mechanic. 

This worked absolutely fine in Office 2013/2016/2019, but with Office 365 we are seeing performance issues. 

We even could reproduce it with a very simple dotx template: We just inserted 200 "AltChunks" with the content "ABC".

Office 365 Word needs more than 4 minutes to open this file. On a machine with Office 2019 this takes 5 seconds. 

It seems that the performance is getting worse when a user has multiple languages installed. Attached is the "simple dotx" file. 

Be aware that I posted the same stuff in the MS Office Support forum, but the official MS Support sees "AltChunk" and told me, that this is development related. Maybe someone could clarify if this is an official "bug" or if we are doing something strange inside the generated template.

The MS support forum issue: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_win10-mso_o365b/office-365-word-starts-extremly-slow-with-a/ff762f54-4044-4076-a6da-79aee6f10df1?auth=1

**Information**

- .NET Target: .NET Framework
- DocumentFormat.OpenXml Version: 2.9.1

**Repro**

* Create a template with multiple AltChunks
* Open the generated template on a Office 365 Click to Run installation (Current Channel) 
* To make it even worse: Install addional language packs (I have 10 installed)

**Observed**

Word loading phase is extremly long even on simple documents

**Expected**

"As fast as a Office 2019" installation. 

I'm not sure if this is the correct spot, but our customers are not very amused about this issue and I try to find someone at Microsoft who might at least point us in the "right" direction.

Sample file (zipped)
[03_200_simple_snippets_as_alt_chunks.zip](https://github.com/OfficeDev/Open-XML-SDK/files/6455291/03_200_simple_snippets_as_alt_chunks.zip)

**Comment by twsouthwick** [comment]
@robertmuehsig Interesting find! It's been routed to the appropriate team to investigate. We'll update with news as it becomes available.

**Comment by robertmuehsig** [comment]
Seems to be fixed (at least with Version Microsoft® Word für Microsoft 365 MSO (Version 2109 Build 16.0.14430.20292) 64 Bit ).
