### ISSUE TITLE
OpenXML integration with Windows RMS (Right Management Services)

### ISSUE THREAD

**Issue by nickgsoft** [OfficeDev/Open-XML-SDK#93]
I got requirement to Export Excel with integrating the Windows AD RMS ( Active Directory Right management Service) integration.  I mean is there any way we can use ClosedXML or OpenXML SDK and create some security that Excel can be accessed by Users defined in AD RMS Security configuration??

I know it is complex requirement, and i did search but looks like there is no way at this moment.

Can any one did this before or is it possible at all  or  can any one provide any assistance on this?? 

thanks in advance.

**Comment by jurjen74** [comment]
+1. I have problems with RMS/Open XML too. Cannot open RMS protected files with open XML even thought programmatic access is allowed according to the RMS template.

**Comment by tomjebo** [comment]
@nickgsoft @jurjen74  Thanks for the suggestion to add RMS support. At this time we have no plans to take this on but you or anyone in the community is welcome to implement this in a fork/clone and we will evaluate PR contributions for inclusion in this repository.

**Comment by twsouthwick** [comment]
@nickgsoft @jurjen74 Are you still looking at how to do this?

**Comment by twsouthwick** [comment]
This doesn't look like something the SDK should support as it's not directly related to the actual file format. Feel free to reopen if you disagree, but it looks like this would be something an application would need to handle. We'd be open to including a sample in the repo as to how to solve it.
