### ISSUE TITLE
Media References are removed

### ISSUE THREAD

**Issue by lklein53** [OfficeDev/Open-XML-SDK#931]
Hi I encountered the following issue while using the OpenXML SDK:

**Description**
I opened the attached file with the OpenXML SDK and saved it using a different name.
If I try to open the saved file Power Point reports that the file is broken and that it can try to repair it.
After repairing the document does not contain the video which was originally in the presentation.

**Information**

- .NET Target:  .NET Core
- DocumentFormat.OpenXml Version: 2.13.0-beta2

**Repro**

Use the following code with the attached file and try to open the saved pptx file.

```csharp
    var ppt = PresentationDocument.Open("source.pptx", false);
    ppt.SaveAs("saved.pptx");
``` 
[source.pptx](https://github.com/OfficeDev/Open-XML-SDK/files/6467546/source.pptx)

**Observed**

The saved file is broken and has to be repaired. The repaired file does not contain the video anymore. 
Somehow the OpenXML SDK removes all the media references contained in the pptx file.

**Expected**

A valid pptx file that is identical to the original document.

I would also be willing to help working on a fix if someone could provide me a starting point why/where the references are removed.

Thanks and kind regards,
Lars

**Comment by twsouthwick** [comment]
@lklein53 Can you try the latest beta? 2.7.1 is quite old at this point.

**Comment by lklein53** [comment]
@twsouthwick thanks for your quick reply. Sorry messed up the bug report. I already tried using version v2.13.0-beta2

**Comment by twsouthwick** [comment]
Thanks! So to be clear, it removes them in both?  Trying to understand if it is a regression from an earlier version that may have been working as expected.

**Comment by lklein53** [comment]
Yes, both versions produce a broken pptx without the video in it.

**Comment by twsouthwick** [comment]
Thanks! At least it's not a regression, but we'll take a look

**Comment by lklein53** [comment]
Hi,
I had some time to look into this today.
In line 1731 of the OpenXmlPartContainer is the following code:

```csharp
ReferenceRelationshipList.AddLast(newDataPartReference);
```
I think this has to be replaced by 

```csharp
 child.AddDataPartReferenceRelationship(DataPartReferenceRelationship.Create(child, newDataPart, dataPartReferenceRelationship.RelationshipType, dataPartReferenceRelationship.Id));
```

At least my example works with this change. If you agree I will create a PR for it. Including a test case

**Comment by twsouthwick** [comment]
Awesome! Go ahead and make a PR and we can explore it further

**Comment by lklein53** [comment]
https://github.com/OfficeDev/Open-XML-SDK/pull/934 contains the change and a simple regression test

**Comment by twsouthwick** [comment]
@tomjebo Can you take a look to verify this change makes sense?

**Comment by lklein53** [comment]
@twsouthwick can this issue be closed? Somehow my changes have been merged in June last year already (https://github.com/OfficeDev/Open-XML-SDK/pull/934)
