### ISSUE TITLE
Incorrect nullability annotations for OpenXmlComparableSimpleReference operator ==/!=

### ISSUE THREAD

**Issue by MaceWindu** [OfficeDev/Open-XML-SDK#933]
**Description**

https://github.com/OfficeDev/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml/SimpleTypes/OpenXmlComparableSimpleReference.cs#L131
https://github.com/OfficeDev/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml/SimpleTypes/OpenXmlComparableSimpleReference.cs#L147

Operators parameters not marked as nullable which leads to following error when checking derived instances (e.g. StringValue) for null.

Also other operators seems to accept nulls, but I don't use them, so there is no breaking scenario for them from me.

**Information**

- .NET Target: net48, net5.0
- DocumentFormat.OpenXml Version: 2.13.0

**Repro**

```cs
// CS8604	Possible null reference argument for parameter 'left' in 'bool OpenXmlComparableSimpleReference<string>.operator !=(OpenXmlComparableSimpleReference<string> left, OpenXmlComparableSimpleReference<string> right)'.
if (cell.CellReference != null)
```

**Observed**

error generated

**Expected**

no error generated

**Comment by twsouthwick** [comment]
Thanks for the catch! Happy to accept a PR for this!

**Comment by ThomasBarnekow** [comment]
@twsouthwick, please have a look at PR #953.
