### ISSUE TITLE
Check excel content vaild like office excel open

### ISSUE THREAD

**Issue by shps951023** [OfficeDev/Open-XML-SDK#936]
# Before submitting an issue, please fill this out

Is this a:
- [ ] Issue with the OpenXml library
- [X] Question on library usage

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

---------------- Remove this line and above before posting ----------------

**Description**

Sometimes OpenXml.SDK  generate excel working success, but open it by office will show message like :  

![](https://i.imgur.com/5DVY8Yw.png)

How to openxml.sdk check excel content vaild like office excel open?

**Comment by ThomasBarnekow** [comment]
@shps951023, did you ask that question on StackOverflow as suggested in the issue template that you filled in?

> If you have answered that this is a question, please ask it on StackOverflow instead of here.
> This issue tracker is meant to track product issues while StackOverflow excels at answering questions

@twsouthwick, as this is clearly a how-to question, I think we can close this issue.

**Comment by shps951023** [comment]
@ThomasBarnekow 
Thanks, I've read document and found no way to do it, maybe it can be a feature? 
Thanks again.
