### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by ArunGust** [OfficeDev/Open-XML-SDK#938]
# Before submitting an issue, please fill this out

Is this a:
- [ ] Issue with the OpenXml library
- [x] Question on library usage

If you have answered that this is a question, please ask it on StackOverflow instead of here.
This issue tracker is meant to track product issues while StackOverflow excels at answering questions

---------------- Remove this line and above before posting ----------------

**Description**

Please provide a simple description of the issue encountered.

**Information**

- RUST/Linux
- DocumentFormat.OpenXml Version: (ie 2.7.2)

**Repro**

```
Any plan to provide rust library ?
``` 

**Observed**

Please add your observed behavior here

**Expected**

Please add your expected behavior here.

**Comment by twsouthwick** [comment]
Not at this time.
