### ISSUE TITLE
Incorrect font names when chart added from Excel to PowerPoint

### ISSUE THREAD

**Issue by okravchuk** [OfficeDev/Open-XML-SDK#94]
Dear all,

Chart in Excel has Calibri fonts. 
If it's added to PowerPoint from Excel with OpenXML it gets Arial fonts.

I created a test solution to show this issue. You can find it in my repository: https://github.com/okravchuk/public/
Filename: TestOpenXmlFont.7z

Thanks, Oleksiy

**Comment by tarunchopra** [comment]
Hello Oleksiy: I'll have a look as I get bandwidth and will get back !!

**Comment by tarunchopra** [comment]
Hello Oleksiy

I'll have a look.

Thanks.

**Comment by tarunchopra** [comment]
Hello Oleksiy

I manually copied over the chart from Excel to PowerPoint and observed the exactly same behavior as produced by SDK. Hence I don't think there is any issue with SDK. 

Thanks.
