### ISSUE TITLE
The error is occurring while merging the two OpenXML word documents having the chart into one of the document.

### ISSUE THREAD

**Issue by Munavvar-Husein** [OfficeDev/Open-XML-SDK#941]
**Description**

The error is occurring while merging the two OpenXML word documents having the Chart inside one of the document.

Below is the error.
"Unable to cast object of type 'DocumentFormat.OpenXml.Packaging.ExtendedPart' to type 'DocumentFormat.OpenXml.Packaging.EmbeddedPackagePart'."

Below is the Stack track. The error is occurring from "OpenXmlPowerTools.DocumentBuilder.CopyChartObjects"
   at OpenXmlPowerTools.DocumentBuilder.CopyChartObjects(ChartPart oldChart, ChartPart newChart)
   at OpenXmlPowerTools.DocumentBuilder.CopyRelatedPartsForContentParts(OpenXmlPart oldContentPart, OpenXmlPart newContentPart, IEnumerable`1 newContent, List`1 images)
   at OpenXmlPowerTools.DocumentBuilder.AppendDocument(WordprocessingDocument sourceDocument, WordprocessingDocument newDocument, List`1 newContent, Boolean keepSection, String insertId, List`1 images)
   at OpenXmlPowerTools.DocumentBuilder.BuildDocument(List`1 sources, WordprocessingDocument output)
   at OpenXmlPowerTools.DocumentBuilder.BuildDocument(List`1 sources)

**Information**

- .NET Target: (.NET Framework 4.6.1)
- DocumentFormat.OpenXml Version: (2.11.3.0 as well as 2.13.0.0)

**Comment by tomjebo** [comment]
@Munavvar-Husein did you see previous to 2.11.3.0? It looks like it may go back further as I found a closed issue in the Microsoft PowerTools repro: [https://github.com/OfficeDev/Open-Xml-PowerTools/issues/149](https://github.com/OfficeDev/Open-Xml-PowerTools/issues/149)

**Comment by tomjebo** [comment]
@twsouthwick could this be due to the #nullable enable we added in Feb? It looks like that was removed for ExtendedPart.

**Comment by tomjebo** [comment]
I think this is the line in CopyChartObjects: 

                        var newPart = newChart.AddExtendedPart(relType, conType, ".bin", id);

**Comment by Munavvar-Husein** [comment]
@tomjebo , @twsouthwick, can you please tell me when this will be resolved?

**Comment by sorensenmatias** [comment]
This is using OpenXmlPowerTools - I think you should direct your attention to that library and not this one? Am I missing something?

**Comment by Munavvar-Husein** [comment]
@sorensenmatias, @tomjebo, @twsouthwick is the above comment for me? If it is, can you tell me which libraries are you referring to when you say "that library and not this one"?

**Comment by ThomasBarnekow** [comment]
If you look at the stack trace, you see OpenXmlPowerTools, which is another namespace and library, which uses the Open XML SDK but is different from the Open XML SDK. If you see DocumentFornat.OpenXml, that‘s the namespace and library name used by the Open XML SDK. 

You would have to open an issue in the Open XML PowerTools repo and not in this one.

**Comment by Munavvar-Husein** [comment]
@ThomasBarnekow, the repo for Open XML PowerTools at https://github.com/OfficeDev/Open-Xml-PowerTools/ is readonly. I cant add any new issues. According to the readme there, the newer version is at https://github.com/EricWhiteDev/Open-Xml-PowerTools. This is not archived but I cant add issue there either. 
Can you please guide me what to do next?

**Comment by adamshakhabov** [comment]
Unfortunately, this repository is rarely updated and opened PRs are not been reviewed 😞 Not sure about Word, but sometimes I open an issue in [Clippit](https://github.com/sergey-tihon/Clippit) (Open-XML-PowerTools fork) repo when the issue related to PowerPoint.  You can take your chance there :)

**Comment by ThomasBarnekow** [comment]
@Munavvar-Husein, the beauty of Open Source projects hosted on GitHub is that you can create your own forks and fix issues yourself. You do not have to wait for the maintainer or other contributors to do that for you, e.g., if fixing your specific issue is not high up on the priority list. Once you created the fix, you can open a pull request to contribute something back.

In the case of the Open XML PowerTools, @EricWhiteDev seemingly disabled the issues feature, which is why you can't open new issues. Further, @adamshakhabov is unfortunately right about the PRs not being reviewed. Thus, coming back to my first point, you should consider fixing the issue yourself.

**Comment by twsouthwick** [comment]
Since this is not directly related to the SDK, I'm going to close this. Please re-open if I have misunderstood.
