### ISSUE TITLE
"Requested registry access is not allowed" error is create spreadsheet from restricted account (IIS etc.).

### ISSUE THREAD

**Issue by AlexanderMagdysyuk** [OfficeDev/Open-XML-SDK#942]
**Description**

Exception from the library under restricted account:

System.TypeInitializationException: The type initializer for 'MS.Utility.EventTrace' threw an exception. --->
System.Security.SecurityException: Requested registry access is not allowed.
System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
Microsoft.Win32.RegistryKey.OpenSubKey(String name)
Microsoft.Win32.Registry.GetValue(String keyName, String valueName, Object defaultValue)
MS.Utility.EventTrace.IsClassicETWRegistryEnabled()
MS.Utility.EventTrace..cctor()
--- End of inner exception stack trace ---
MS.Utility.EventTrace.EasyTraceEvent(Keyword keywords, Event eventID)
System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare)
DocumentFormat.OpenXml.Packaging.OpenXmlPackage.CreateCore(String path)
DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Create(String path, SpreadsheetDocumentType type, Boolean autoSave)
DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Create(String path, SpreadsheetDocumentType type)
...

Steps are something like next:
- Create a new window user with the following detail with that password (set it to never expire)
- UserName="TestUser" password="TestPassword" 
- Add the above user to "IIS_IUSRS" group
- Create a new web application in C:\WebApp\ path with next code "SpreadsheetDocument.Create("C:\WebApp\test.xlsx", SpreadsheetDocumentType.Workbook);"
- Give the Full right to "TestUser" on "C:\WebApp\" folder
- Build and publish the web app.
- Run the web app.

- .NET Target: 4.6.2
- DocumentFormat.OpenXml Version: 2.12.1 (reproduced with 2.13.0 too).

**Comment by ThomasBarnekow** [comment]
This somehow does not sound like it is due to the Open XML SDK specifically. 

Could you try the following?

- Open any other type of file, e.g., a text or PDF, stored in the same location. Does that work?
- Open the Package (from System.IO.Packaging namespace) directly. Does that work?

If any of those don't work, it's not due to the SDK. If both work, it's the SDK.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, I think we can close this issue.

**Comment by quager** [comment]
Hello @ThomasBarnekow, this error occurs when the Web.config file contains `<identity impersonate="true" userName="TestUser" password="TestPassword" />`.

> Open any other type of file, e.g., a text or PDF, stored in the same location.

It works.

> Open the Package (from System.IO.Packaging namespace) directly.

This throws the same exception:
```
System.TypeInitializationException: The type initializer for 'MS.Utility.EventTrace' threw an exception. --->
System.Security.SecurityException: Requested registry access is not allowed.

MS.Utility.EventTrace.EasyTraceEvent(Keyword keywords, Event eventID)
System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
System.IO.Packaging.Package.Open(String path)
...
```

**Comment by twsouthwick** [comment]
This is a permissions issue with the application you're running under. This would be better served on stackoverflow.
