### ISSUE TITLE
Open XML SDK Productivity Tool has been removed from download

### ISSUE THREAD

**Issue by georearl** [OfficeDev/Open-XML-SDK#943]
**Open XML SDK Productivity Tool has been removed from download**

We were using the open xml sdk productivity tool to compare a before and after version of a slide in PowerPoint and then to generate the code to make the change. This saved us so much time and ramp up on the sdk. The scenario is we were generating a daily PowerPoint briefing as part of a daily process. we are creating highlight event slides and summary slides, and therefore adding images and text, changing formats, removing and adding shapes etc. Beyond us just doing this once and build time, we see the users of this solution making their own configuration changes to this briefing deck. As such they would get huger value from a code generator. IF there is any way to get access to the tool, or even better an updated one, it would be very useful to the users of this system.

**Comment by adamshakhabov** [comment]
I also still use Open XML SDK 2.5 Productivity Tool and have plan check [DocxToSource](URL). Did you use it? It is not yet a good alternative for PowerPoint document investigation?

**Comment by rmboggs** [comment]
Hi,

[DocxToSource](https://github.com/rmboggs/DocxToSource) is good for spreadsheets right now and it can do presentations and wordprocessing documents too but the latter 2 document formats are pretty complex and there may still be bugs present for those situations.

Also, as an FYI, the main dependency of [DocxToSource](https://github.com/rmboggs/DocxToSource)  is [Serialize.OpenXml.CodeGen](https://github.com/rmboggs/Serialize.OpenXml.CodeGen) which is where the code generation for the document actually occurs.  In theory, you could use this library to generate your own source code for your documents as needed.  But please keep in mind that any code generation issues you are seeing in [DocxToSource](https://github.com/rmboggs/DocxToSource), you will likely see in [Serialize.OpenXml.CodeGen](https://github.com/rmboggs/Serialize.OpenXml.CodeGen) as well.

Thanks,
Ryan

**Comment by ThomasBarnekow** [comment]
On the Microsoft DevDays Redmond 2021 Online, @AlfredHellstern explained that the Productivity Tools were removed after a security review. They might become available for download again, if there is enough interest. In the same session, @mikeebowen demoed a very cool Visual Studio Code extension that might be a replacement, unless you need the C# code generation feature.

**Comment by patrickryan79** [comment]
This is a bummer. Setup a new PC and can't find the download anywhere. I heavily relied on this. Still have old computer to use though but where can I cast my vote?

**Comment by AlfredHellstern** [comment]
The Open XML 2.5 Productivity Tool was recently removed from the Microsoft Download Center because of concerns with SHA-1 signatures. There have been many requests for it in the meantime, so we’re making it available again with a SHA-256 signature for the MSI container (while the files inside the MSI are still signed with SHA-1). You can find it [here](https://github.com/OfficeDev/Open-XML-SDK/releases/tag/v2.5) on GitHub.
This MSI is provided **AS IS**, to address the needs of developers wanting to use the Productivity Tool to get a quick start on generating Open XML 2.5 source code. It has not been updated to the latest version of the SDK.
