### ISSUE TITLE
How to add slicer to excel?

### ISSUE THREAD

**Issue by TimonYang** [OfficeDev/Open-XML-SDK#948]
**Description**

I want to add a slicer to a table in excel, which is easy to implement in other packages, but now for some reasons I want to use Openxml to do it.

But I can't find relevant code examples on the Internet. My intuition tells me that this shouldn't be very complicated, but I don't know how to proceed.

**Information**

- .NET Target:  .NET Framework 4.7.2

             using (SpreadsheetDocument document = SpreadsheetDocument.Open(@"C:\Users\timony\Desktop\1.xlsx",true))
            {
                WorkbookPart wbp = document.WorkbookPart;
                wbp.SlicerCacheParts.
                ......
            }
Thanks in advance.

**Comment by ThomasBarnekow** [comment]
As this is a question on library usage, please post it on stackoverflow.com.

**Comment by ThomasBarnekow** [comment]
@twsouthwick, please close this issue.
