### ISSUE TITLE
AddMediaReferenceRelationship and AddVideoReferenceRelationship Methods in Open XML Version 2.13.0 and Open XML Version 2.12.3

### ISSUE THREAD

**Issue by Iansamaaa** [OfficeDev/Open-XML-SDK#949]
The code is run, both in version 2.13.0 and 2.12.3

**Sample Code:**

MediaDataPart mediaDataPart1 = document.CreateMediaDataPart("video/mp4", ".mp4");
System.IO.Stream mediaDataPart1Stream = System.IO.File.Open(@"D:\samplevideo.mp4", System.IO.FileMode.Open);
mediaDataPart1.FeedData(mediaDataPart1Stream);
mediaDataPart1Stream.Close();

slidePart1.AddMediaReferenceRelationship(mediaDataPart1, "rId2");
slidePart1.AddVideoReferenceRelationship(mediaDataPart1, "rId1");

after checking the raw XML of the Power point file 

**Sample Result:**

In slide1.xml.rels in version 2.12.3

<Relationship Type="http://schemas.microsoft.com/office/2007/relationships/media" Target="/media/mediadata.mp4" Id=**"rId2"** />
<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/video" Target="/media/mediadata.mp4" Id=**"rId1"** />

video inside power point presentation is playable

In slide1.xml.rels in version 2.13.0

<Relationship Type="http://schemas.microsoft.com/office/2007/relationships/media" Target="/media/mediadata.mp4" Id=**"Rc3519f9b3fa04f59"** />
<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/video" Target="/media/mediadata.mp4" Id=**"R365391439af74425"** />

video inside Power point presentation isn't playable anymore

what happen to relationship id reference in version 2.13.0(e.g. Id=**"Rc3519f9b3fa04f59"** and not Id=**"rId1"**) ?
Is this a bug or another feature? Thank you.

![1](https://user-images.githubusercontent.com/31118570/122875175-7f40a500-d366-11eb-8b4a-71c626be398a.png)

**Comment by tomjebo** [comment]
@Iansamaaa thanks for reporting this. I assume you start with a blank presentation and add using the code above? I'll test it out and try to understand why the relationship ids changed.

**Comment by tomjebo** [comment]
@Iansamaaa can you provide the full sample code for the repro including adding the video blip to the slide?

**Comment by tomjebo** [comment]
@Iansamaaa more on my testing: I used a PowerPoint generated deck with a video inserted already. Then replaced the id's with longer ones like "Raf78128d2b5b4f28". The video still plays just fine. So I think there's something else missing after your code adds the media and video parts. I'll need the full repro sample code to check it out.

**Comment by Iansamaaa** [comment]
@tomjebo thank you for answering my question, so the code I am using is the generated code by the Open Xml Sdk tool 2.5, so is it okay if I send here the class ? 

[RecreateVideoPowerpoint.txt](https://github.com/OfficeDev/Open-XML-SDK/files/6698249/RecreateVideoPowerpoint.txt)

Sample Code of creation slide 1 content:
private void GenerateSlidePart1Content(SlidePart slidePart1)
        {
            Slide slide1 = new Slide();
            slide1.AddNamespaceDeclaration("a", "http://schemas.openxmlformats.org/drawingml/2006/main");
            slide1.AddNamespaceDeclaration("r", "http://schemas.openxmlformats.org/officeDocument/2006/relationships");
            slide1.AddNamespaceDeclaration("p", "http://schemas.openxmlformats.org/presentationml/2006/main");

            CommonSlideData commonSlideData1 = new CommonSlideData();

            ShapeTree shapeTree1 = new ShapeTree();

            NonVisualGroupShapeProperties nonVisualGroupShapeProperties1 = new NonVisualGroupShapeProperties();
            NonVisualDrawingProperties nonVisualDrawingProperties1 = new NonVisualDrawingProperties() { Id = (UInt32Value)1U, Name = "" };
            NonVisualGroupShapeDrawingProperties nonVisualGroupShapeDrawingProperties1 = new NonVisualGroupShapeDrawingProperties();
            ApplicationNonVisualDrawingProperties applicationNonVisualDrawingProperties1 = new ApplicationNonVisualDrawingProperties();

            nonVisualGroupShapeProperties1.Append(nonVisualDrawingProperties1);
            nonVisualGroupShapeProperties1.Append(nonVisualGroupShapeDrawingProperties1);
            nonVisualGroupShapeProperties1.Append(applicationNonVisualDrawingProperties1);

            GroupShapeProperties groupShapeProperties1 = new GroupShapeProperties();

            A.TransformGroup transformGroup1 = new A.TransformGroup();
            A.Offset offset1 = new A.Offset() { X = 0L, Y = 0L };
            A.Extents extents1 = new A.Extents() { Cx = 0L, Cy = 0L };
            A.ChildOffset childOffset1 = new A.ChildOffset() { X = 0L, Y = 0L };
            A.ChildExtents childExtents1 = new A.ChildExtents() { Cx = 0L, Cy = 0L };

            transformGroup1.Append(offset1);
            transformGroup1.Append(extents1);
            transformGroup1.Append(childOffset1);
            transformGroup1.Append(childExtents1);

            groupShapeProperties1.Append(transformGroup1);

            Shape shape1 = new Shape();

            NonVisualShapeProperties nonVisualShapeProperties1 = new NonVisualShapeProperties();
            NonVisualDrawingProperties nonVisualDrawingProperties2 = new NonVisualDrawingProperties() { Id = (UInt32Value)2U, Name = "Title 1" };

            NonVisualShapeDrawingProperties nonVisualShapeDrawingProperties1 = new NonVisualShapeDrawingProperties();
            A.ShapeLocks shapeLocks1 = new A.ShapeLocks() { NoGrouping = true };

            nonVisualShapeDrawingProperties1.Append(shapeLocks1);

            ApplicationNonVisualDrawingProperties applicationNonVisualDrawingProperties2 = new ApplicationNonVisualDrawingProperties();
            PlaceholderShape placeholderShape1 = new PlaceholderShape() { Type = PlaceholderValues.CenteredTitle };

            applicationNonVisualDrawingProperties2.Append(placeholderShape1);

            nonVisualShapeProperties1.Append(nonVisualDrawingProperties2);
            nonVisualShapeProperties1.Append(nonVisualShapeDrawingProperties1);
            nonVisualShapeProperties1.Append(applicationNonVisualDrawingProperties2);
            ShapeProperties shapeProperties1 = new ShapeProperties();

            TextBody textBody1 = new TextBody();
            A.BodyProperties bodyProperties1 = new A.BodyProperties();
            A.ListStyle listStyle1 = new A.ListStyle();

            A.Paragraph paragraph1 = new A.Paragraph();
            A.EndParagraphRunProperties endParagraphRunProperties1 = new A.EndParagraphRunProperties() { Language = "en-US", Dirty = false };

            paragraph1.Append(endParagraphRunProperties1);

            textBody1.Append(bodyProperties1);
            textBody1.Append(listStyle1);
            textBody1.Append(paragraph1);

            shape1.Append(nonVisualShapeProperties1);
            shape1.Append(shapeProperties1);
            shape1.Append(textBody1);

            Shape shape2 = new Shape();

            NonVisualShapeProperties nonVisualShapeProperties2 = new NonVisualShapeProperties();
            NonVisualDrawingProperties nonVisualDrawingProperties3 = new NonVisualDrawingProperties() { Id = (UInt32Value)3U, Name = "Subtitle 2" };

            NonVisualShapeDrawingProperties nonVisualShapeDrawingProperties2 = new NonVisualShapeDrawingProperties();
            A.ShapeLocks shapeLocks2 = new A.ShapeLocks() { NoGrouping = true };

            nonVisualShapeDrawingProperties2.Append(shapeLocks2);

            ApplicationNonVisualDrawingProperties applicationNonVisualDrawingProperties3 = new ApplicationNonVisualDrawingProperties();
            PlaceholderShape placeholderShape2 = new PlaceholderShape() { Type = PlaceholderValues.SubTitle, Index = (UInt32Value)1U };

            applicationNonVisualDrawingProperties3.Append(placeholderShape2);

            nonVisualShapeProperties2.Append(nonVisualDrawingProperties3);
            nonVisualShapeProperties2.Append(nonVisualShapeDrawingProperties2);
            nonVisualShapeProperties2.Append(applicationNonVisualDrawingProperties3);
            ShapeProperties shapeProperties2 = new ShapeProperties();

            TextBody textBody2 = new TextBody();
            A.BodyProperties bodyProperties2 = new A.BodyProperties();
            A.ListStyle listStyle2 = new A.ListStyle();

            A.Paragraph paragraph2 = new A.Paragraph();
            A.EndParagraphRunProperties endParagraphRunProperties2 = new A.EndParagraphRunProperties() { Language = "en-US" };

            paragraph2.Append(endParagraphRunProperties2);

            textBody2.Append(bodyProperties2);
            textBody2.Append(listStyle2);
            textBody2.Append(paragraph2);

            shape2.Append(nonVisualShapeProperties2);
            shape2.Append(shapeProperties2);
            shape2.Append(textBody2);

            Picture picture1 = new Picture();

            NonVisualPictureProperties nonVisualPictureProperties1 = new NonVisualPictureProperties();

            NonVisualDrawingProperties nonVisualDrawingProperties4 = new NonVisualDrawingProperties() { Id = (UInt32Value)4U, Name = "samplevideo.mp4" };
            A.HyperlinkOnClick hyperlinkOnClick1 = new A.HyperlinkOnClick() { Id = "rId1", Action = "ppaction://media" };

            nonVisualDrawingProperties4.Append(hyperlinkOnClick1);
            NonVisualPictureDrawingProperties nonVisualPictureDrawingProperties1 = new NonVisualPictureDrawingProperties();

            ApplicationNonVisualDrawingProperties applicationNonVisualDrawingProperties4 = new ApplicationNonVisualDrawingProperties();
            A.VideoFromFile videoFromFile1 = new A.VideoFromFile() { Link = "rId1" };

            ApplicationNonVisualDrawingPropertiesExtensionList applicationNonVisualDrawingPropertiesExtensionList1 = new ApplicationNonVisualDrawingPropertiesExtensionList();

            ApplicationNonVisualDrawingPropertiesExtension applicationNonVisualDrawingPropertiesExtension1 = new ApplicationNonVisualDrawingPropertiesExtension() { Uri = "{DAA4B4D4-6D71-4841-9C94-3DE7FCFB9230}" };

            P14.Media media1 = new P14.Media() { Embed = "rId2" };
            media1.AddNamespaceDeclaration("p14", "http://schemas.microsoft.com/office/powerpoint/2010/main");

            applicationNonVisualDrawingPropertiesExtension1.Append(media1);

            applicationNonVisualDrawingPropertiesExtensionList1.Append(applicationNonVisualDrawingPropertiesExtension1);

            CustomerDataList customerDataList1 = new CustomerDataList();
            CustomerDataTags customerDataTags1 = new CustomerDataTags() { Id = "rId3" };

            customerDataList1.Append(customerDataTags1);

            applicationNonVisualDrawingProperties4.Append(videoFromFile1);
            applicationNonVisualDrawingProperties4.Append(applicationNonVisualDrawingPropertiesExtensionList1);
            applicationNonVisualDrawingProperties4.Append(customerDataList1);

            nonVisualPictureProperties1.Append(nonVisualDrawingProperties4);
            nonVisualPictureProperties1.Append(nonVisualPictureDrawingProperties1);
            nonVisualPictureProperties1.Append(applicationNonVisualDrawingProperties4);

            BlipFill blipFill1 = new BlipFill();
            A.Blip blip1 = new A.Blip() { Embed = "rId4" };

            A.Stretch stretch1 = new A.Stretch();
            A.FillRectangle fillRectangle1 = new A.FillRectangle();

            stretch1.Append(fillRectangle1);

            blipFill1.Append(blip1);
            blipFill1.Append(stretch1);

            ShapeProperties shapeProperties3 = new ShapeProperties();

            A.Transform2D transform2D1 = new A.Transform2D();
            A.Offset offset2 = new A.Offset() { X = 3810000L, Y = 2143125L };
            A.Extents extents2 = new A.Extents() { Cx = 4572000L, Cy = 2571750L };

            transform2D1.Append(offset2);
            transform2D1.Append(extents2);

            A.PresetGeometry presetGeometry1 = new A.PresetGeometry() { Preset = A.ShapeTypeValues.Rectangle };
            A.AdjustValueList adjustValueList1 = new A.AdjustValueList();

            presetGeometry1.Append(adjustValueList1);

            shapeProperties3.Append(transform2D1);
            shapeProperties3.Append(presetGeometry1);

            picture1.Append(nonVisualPictureProperties1);
            picture1.Append(blipFill1);
            picture1.Append(shapeProperties3);

            shapeTree1.Append(nonVisualGroupShapeProperties1);
            shapeTree1.Append(groupShapeProperties1);
            shapeTree1.Append(shape1);
            shapeTree1.Append(shape2);
            shapeTree1.Append(picture1);

            commonSlideData1.Append(shapeTree1);

            ColorMapOverride colorMapOverride1 = new ColorMapOverride();
            A.MasterColorMapping masterColorMapping1 = new A.MasterColorMapping();

            colorMapOverride1.Append(masterColorMapping1);

            Timing timing1 = new Timing();

            TimeNodeList timeNodeList1 = new TimeNodeList();

            ParallelTimeNode parallelTimeNode1 = new ParallelTimeNode();

            CommonTimeNode commonTimeNode1 = new CommonTimeNode() { Id = (UInt32Value)1U, Duration = "indefinite", Restart = TimeNodeRestartValues.Never, NodeType = TimeNodeValues.TmingRoot };

            ChildTimeNodeList childTimeNodeList1 = new ChildTimeNodeList();

            Video video1 = new Video() { FullScreen = false };

            CommonMediaNode commonMediaNode1 = new CommonMediaNode();

            CommonTimeNode commonTimeNode2 = new CommonTimeNode() { Id = (UInt32Value)2U, Fill = TimeNodeFillValues.Hold, Display = true };

            StartConditionList startConditionList1 = new StartConditionList();
            Condition condition1 = new Condition() { Delay = "indefinite" };

            startConditionList1.Append(condition1);

            EndConditionList endConditionList1 = new EndConditionList();

            Condition condition2 = new Condition() { Event = TriggerEventValues.OnNext };

            TargetElement targetElement1 = new TargetElement();
            SlideTarget slideTarget1 = new SlideTarget();

            targetElement1.Append(slideTarget1);

            condition2.Append(targetElement1);

            Condition condition3 = new Condition() { Event = TriggerEventValues.OnPrevious };

            TargetElement targetElement2 = new TargetElement();
            SlideTarget slideTarget2 = new SlideTarget();

            targetElement2.Append(slideTarget2);

            condition3.Append(targetElement2);

            endConditionList1.Append(condition2);
            endConditionList1.Append(condition3);

            commonTimeNode2.Append(startConditionList1);
            commonTimeNode2.Append(endConditionList1);

            TargetElement targetElement3 = new TargetElement();
            ShapeTarget shapeTarget1 = new ShapeTarget() { ShapeId = "4" };

            targetElement3.Append(shapeTarget1);

            commonMediaNode1.Append(commonTimeNode2);
            commonMediaNode1.Append(targetElement3);

            video1.Append(commonMediaNode1);

            SequenceTimeNode sequenceTimeNode1 = new SequenceTimeNode() { Concurrent = true, NextAction = NextActionValues.Seek };

            CommonTimeNode commonTimeNode3 = new CommonTimeNode() { Id = (UInt32Value)3U, Restart = TimeNodeRestartValues.WhenNotActive, Fill = TimeNodeFillValues.Hold, EventFilter = "cancelBubble", NodeType = TimeNodeValues.InteractiveSequence };

            StartConditionList startConditionList2 = new StartConditionList();

            Condition condition4 = new Condition() { Event = TriggerEventValues.OnClick, Delay = "0" };

            TargetElement targetElement4 = new TargetElement();
            ShapeTarget shapeTarget2 = new ShapeTarget() { ShapeId = "4" };

            targetElement4.Append(shapeTarget2);

            condition4.Append(targetElement4);

            startConditionList2.Append(condition4);

            EndSync endSync1 = new EndSync() { Event = TriggerEventValues.End, Delay = "0" };
            RuntimeNodeTrigger runtimeNodeTrigger1 = new RuntimeNodeTrigger() { Val = TriggerRuntimeNodeValues.All };

            endSync1.Append(runtimeNodeTrigger1);

            ChildTimeNodeList childTimeNodeList2 = new ChildTimeNodeList();

            ParallelTimeNode parallelTimeNode2 = new ParallelTimeNode();

            CommonTimeNode commonTimeNode4 = new CommonTimeNode() { Id = (UInt32Value)4U, Fill = TimeNodeFillValues.Hold };

            StartConditionList startConditionList3 = new StartConditionList();
            Condition condition5 = new Condition() { Delay = "0" };

            startConditionList3.Append(condition5);

            ChildTimeNodeList childTimeNodeList3 = new ChildTimeNodeList();

            ParallelTimeNode parallelTimeNode3 = new ParallelTimeNode();

            CommonTimeNode commonTimeNode5 = new CommonTimeNode() { Id = (UInt32Value)5U, Fill = TimeNodeFillValues.Hold };

            StartConditionList startConditionList4 = new StartConditionList();
            Condition condition6 = new Condition() { Delay = "0" };

            startConditionList4.Append(condition6);

            ChildTimeNodeList childTimeNodeList4 = new ChildTimeNodeList();

            ParallelTimeNode parallelTimeNode4 = new ParallelTimeNode();

            CommonTimeNode commonTimeNode6 = new CommonTimeNode() { Id = (UInt32Value)6U, PresetId = 2, PresetClass = TimeNodePresetClassValues.MediaCall, PresetSubtype = 0, Fill = TimeNodeFillValues.Hold, NodeType = TimeNodeValues.ClickEffect };

            StartConditionList startConditionList5 = new StartConditionList();
            Condition condition7 = new Condition() { Delay = "0" };

            startConditionList5.Append(condition7);

            ChildTimeNodeList childTimeNodeList5 = new ChildTimeNodeList();

            Command command1 = new Command() { Type = CommandValues.Call, CommandName = "togglePause" };

            CommonBehavior commonBehavior1 = new CommonBehavior() { Additive = BehaviorAdditiveValues.Base };
            CommonTimeNode commonTimeNode7 = new CommonTimeNode() { Id = (UInt32Value)7U, Duration = "1", Fill = TimeNodeFillValues.Hold };

            TargetElement targetElement5 = new TargetElement();
            ShapeTarget shapeTarget3 = new ShapeTarget() { ShapeId = "4" };

            targetElement5.Append(shapeTarget3);

            commonBehavior1.Append(commonTimeNode7);
            commonBehavior1.Append(targetElement5);

            command1.Append(commonBehavior1);

            childTimeNodeList5.Append(command1);

            commonTimeNode6.Append(startConditionList5);
            commonTimeNode6.Append(childTimeNodeList5);

            parallelTimeNode4.Append(commonTimeNode6);

            childTimeNodeList4.Append(parallelTimeNode4);

            commonTimeNode5.Append(startConditionList4);
            commonTimeNode5.Append(childTimeNodeList4);

            parallelTimeNode3.Append(commonTimeNode5);

            childTimeNodeList3.Append(parallelTimeNode3);

            commonTimeNode4.Append(startConditionList3);
            commonTimeNode4.Append(childTimeNodeList3);

            parallelTimeNode2.Append(commonTimeNode4);

            childTimeNodeList2.Append(parallelTimeNode2);

            commonTimeNode3.Append(startConditionList2);
            commonTimeNode3.Append(endSync1);
            commonTimeNode3.Append(childTimeNodeList2);

            NextConditionList nextConditionList1 = new NextConditionList();

            Condition condition8 = new Condition() { Event = TriggerEventValues.OnClick, Delay = "0" };

            TargetElement targetElement6 = new TargetElement();
            ShapeTarget shapeTarget4 = new ShapeTarget() { ShapeId = "4" };

            targetElement6.Append(shapeTarget4);

            condition8.Append(targetElement6);

            nextConditionList1.Append(condition8);

            sequenceTimeNode1.Append(commonTimeNode3);
            sequenceTimeNode1.Append(nextConditionList1);

            childTimeNodeList1.Append(video1);
            childTimeNodeList1.Append(sequenceTimeNode1);

            commonTimeNode1.Append(childTimeNodeList1);

            parallelTimeNode1.Append(commonTimeNode1);

            timeNodeList1.Append(parallelTimeNode1);

            timing1.Append(timeNodeList1);

            slide1.Append(commonSlideData1);
            slide1.Append(colorMapOverride1);
            slide1.Append(timing1);

            slidePart1.Slide = slide1;
}

thank you.

**Comment by tomjebo** [comment]
@Iansamaaa thank you. Looks like SDK Productivity Tool reflection code. I can also try that if the code doesn't work directly for me. But this helps.

**Comment by Iansamaaa** [comment]
@tomjebo Thank you so much

**Comment by tomjebo** [comment]
@Iansamaaa I found the issue. We made a change recently that removed the id parameter to System.IO.Packaging's CreateRelationship function. That cause it to generate a new id which you found. I will submit a PR shortly with a small fix that will resolve this and you can test.

**Comment by tomjebo** [comment]
@Iansamaaa I submitted PR #954. Can you test with this to make sure it works for you? I tested with my repro and it does successfully add the video which plays.

**Comment by Iansamaaa** [comment]
hi @tomjebo thank you so much for this, for the testing, by the way, sorry I am new to this, does the fix automatically reflected on nuget package?

**Comment by tomjebo** [comment]
@lansamaaa we haven't merged #954 yet. I was pulled off on some other work and I've also been requested to add unit testing for this scenario. I intend to do that soon. It will go out with a minor build due to the fact that this changes the API surface area (not a breaking change).
