### ISSUE TITLE
sorting table per date column in word document

### ISSUE THREAD

**Issue by gogi100** [OfficeDev/Open-XML-SDK#961]
**Description**

sorting table per date column in word document

**Information**

- .NET Target: .NET Framework 3.5
- DocumentFormat.OpenXml Version: 2.0

**Observed**

i have project in visiual studio 2010 where from the sharepoint 2010 list item is adding in word document table. the list items i adding from three list. i have to after adding to make sorting per column that contains date. my code is
using (WordprocessingDocument doc = WordprocessingDocument.Open(memStr5, true))
                {

                    MainDocumentPart main = doc.MainDocumentPart;

                    Table TabelaEvidencijaPutnihNaloga = main.Document.Body.Descendants<Table>().First();
                    int brojredova = TabelaEvidencijaPutnihNaloga.Elements<TableRow>().Count();
                    TableRow Red = TabelaEvidencijaPutnihNaloga.Elements<TableRow>().Last();
                  //  TableRow prazanred = new TableRow();
            //        IEnumerable<TableRow> rows = TabelaEvidencijaPutnihNaloga.Elements<TableRow>(); //svi redovi u tabeli
                   
                  //   TableCell cell = rows.Elements<TableCell>().ElementAt(2);
                    TableRow rowCopy = (TableRow)Red.CloneNode(true);

                    brojredova = brojredova - 1;

                    rowCopy.Descendants<TableCell>().ElementAt(0).RemoveAllChildren<Paragraph>();
                    rowCopy.Descendants<TableCell>().ElementAt(0).Append(new Paragraph(new Run(new RunFonts() { Ascii = "Times New Roman" }, new Text(Convert.ToString(brojredova)))));
                    rowCopy.Descendants<TableCell>().ElementAt(1).RemoveAllChildren<Paragraph>();
                    rowCopy.Descendants<TableCell>().ElementAt(1).Append(new Paragraph(new Run(new RunFonts() { Ascii = "Times New Roman" }, new Text(dn.ToString()))));
                    rowCopy.Descendants<TableCell>().ElementAt(2).RemoveAllChildren<Paragraph>();
                    rowCopy.Descendants<TableCell>().ElementAt(2).Append(new Paragraph(new Run(new RunFonts() { Ascii = "Times New Roman" }, new Text(imeiprezime.ToString()))));
                    rowCopy.Descendants<TableCell>().ElementAt(3).RemoveAllChildren<Paragraph>();
                    rowCopy.Descendants<TableCell>().ElementAt(3).Append(new Paragraph(new Run(new RunFonts() { Ascii = "Times New Roman" }, new Text(lokacija.ToString() + "," + brojdananaputu.ToString() + " дан"))));
                    rowCopy.Descendants<TableCell>().ElementAt(4).RemoveAllChildren<Paragraph>();
                    rowCopy.Descendants<TableCell>().ElementAt(4).Append(new Paragraph(new Run(new RunFonts() { Ascii = "Times New Roman" }, new Text(razlogputovanja.ToString()))));
                    rowCopy.Descendants<TableCell>().ElementAt(5).RemoveAllChildren<Paragraph>();
                    rowCopy.Descendants<TableCell>().ElementAt(5).Append(new Paragraph(new Run(new RunFonts() { Ascii = "Times New Roman" }, new Text(vozilo.ToString()))));
                    rowCopy.Descendants<TableCell>().ElementAt(9).RemoveAllChildren<Paragraph>();
                    rowCopy.Descendants<TableCell>().ElementAt(9).Append(new Paragraph(new Run(new RunFonts() { Ascii = "Times New Roman" }, new Text(napomena.ToString()))));

                    TabelaEvidencijaPutnihNaloga.AppendChild(rowCopy);
                  //  TabelaEvidencijaPutnihNaloga.OrderBy(rows.OrderBy(.Descendants<TableCell>().ElementAt(1));
                 var orderByAscendingResult = from s in TabelaEvidencijaPutnihNaloga
                                            orderby s.Elements<TableCell>().ElementAt(1) ascending
                                            select s;
                    TabelaEvidencijaPutnihNaloga.OrderBy(s => s.Elements<TableCell>().ElementAt(1));
                    foreach (var std in orderByAscendingResult)
                        Console.WriteLine(std.Elements<TableCell>().ElementAt(1));
                    // Get the last row in the table.
                   
                    // Remove the empty placeholder row from the table.
                    //   TabelaZapisnik.RemoveChild(Red);

                    //closing WordprocessingDocument automatically saves the document
                }

do you have solution form my problem

**Expected**

Please add your expected behavior here.

**Comment by ThomasBarnekow** [comment]
@gogi100, please ask this question on stackoverflow.com. This how-to question is not an issue.

A hint on asking the questions on stackoverflow.com, though: You should demonstrate that you have done your own research on solutions and tried things that might have failed. In other words, don't expect others to do your homework.

@twsouthwick, please close this issue.
