### ISSUE TITLE
OpenXML doesn't retrieve correct display formatted data

### ISSUE THREAD

**Issue by thanhvyit** [OfficeDev/Open-XML-SDK#99]
In excel file, the data is displaying these values:
232.2342
343454
3.343
43.4343
43.343
345.545
54.454

But when I use OpenXML for retrieve data, it show me different with more than decimal point:
232.234200002
343454
3.3429999
43.43430345234
43.3429999
345.545
54.454

This is my testing code:
`string value = null;

```
        // If the cell does not exist, return an empty string.
        if (theCell != null)
        {
            value = theCell.InnerText;

            // If the cell represents an integer number, you are done. 
            // For dates, this code returns the serialized value that 
            // represents the date. The code handles strings and 
            // Booleans individually. For shared strings, the code 
            // looks up the corresponding value in the shared string 
            // table. For Booleans, the code converts the value into 
            // the words TRUE or FALSE.
            if (theCell.DataType != null)
            {
                switch (theCell.DataType.Value)
                {
                    case CellValues.SharedString:

                        // For shared strings, look up the value in the
                        // shared strings table.
                        var stringTable =
                            wbPart.GetPartsOfType<SharedStringTablePart>()
                            .FirstOrDefault();

                        // If the shared string table is missing, something 
                        // is wrong. Return the index that is in
                        // the cell. Otherwise, look up the correct text in 
                        // the table.
                        if (stringTable != null)
                        {
                            value =
                                stringTable.SharedStringTable
                                .ElementAt(int.Parse(value)).InnerText;
                        }
                        break;

                    case CellValues.Boolean:
                        switch (value)
                        {
                            case "0":
                                value = "FALSE";
                                break;
                            default:
                                value = "TRUE";
                                break;
                        }
                        break;
                }
            }
            else if (theCell.StyleIndex != null && theCell.StyleIndex.HasValue && numberingFormats != null)
            {
                // look up the style used for the cell
                int formatStyleIndex = Convert.ToInt32(theCell.StyleIndex.Value);
                var cf = (CellFormat)cellFormats.ElementAt(formatStyleIndex);

                if (cf.NumberFormatId != null)
                {
                    var numberFormatId = cf.NumberFormatId.Value;
                    var numberingFormat = numberingFormats.Cast<NumberingFormat>().Single(f => f.NumberFormatId.Value == numberFormatId);

                    // Here's yer string! Example: $#,##0.00_);[Red]($#,##0.00)
                    return numberingFormat.FormatCode.Value;
                }
                else
                {
                    value = theCell.InnerText;
                }
            }
        }
        return value;`
```

**Comment by tarunchopra** [comment]
Hello thanhvyit: Can you please attach your test file so that I can try to repro the issue and have a look?

**Comment by thanhvyit** [comment]
Thanks for your response!
Please get the test file in attachment.
[testdecimals.xlsx](https://github.com/OfficeDev/Open-XML-SDK/files/507677/testdecimals.xlsx)

**Comment by tarunchopra** [comment]
Sorry for not being clear, please share the file that has testing code (.cs file)

**Comment by tarunchopra** [comment]
@thanhvyit : Gentle reminder, would you like to share the requested .cs file or solution so that we can have a look ?

**Comment by thanhvyit** [comment]
Sorry for late response, I actually found solution for it. Just return Double.Parse(cell.CellValue.Text, CultureInfo.InvariantCulture).ToString() if datatype null.
Thank you very much!

**Comment by apetrut** [comment]
@thanhvyit This seems like a workaround rather than an actual solution. Why should the DataType be null if the value is decimal? Shouldn't OpenXML identify correctly the datatype automatically?
@tarunchopra Can you confirm why the values: 3.343 gets translated into: 3.3429999?

I ran into the same issue when reading values from excel using OpenXML but this seems to be an issue that has to be fixed by the team behing the OpenXML project.

**Comment by kev-ops** [comment]
same case with me, we need to re open this issue @tarunchopra , values like "4.9" in excel gets translated to. Given that it is in General format. WE should be able to fetch the value of the cell as it was inputted
![image](https://user-images.githubusercontent.com/15882382/233114188-0b4a73cc-7e53-446e-a6da-1f3fbc77f236.png)

@apetrut @tarunchopra

**Comment by SeerGiuS96** [comment]
Thanks @thanhvyit CultureInfo.InvariantCulture saved me, thanks for posting the solution to fix that problem.
